### ISSUE TITLE
Coverage Map uploads not working

### ISSUE THREAD

**Issue by dalonso22893** [jacobalberty/unifi-docker#10]
When attempting to upload custom image for the coverage maps, it yields an error message and nothing displays. The sample image also disappears after attempting to upload the first custom image.

**Comment by Hinni** [comment]
What was the error message? Please provide more details. In my configuration image uploads works without problems.

**Comment by dalonso22893** [comment]
I am able to select the image and then upload it, but then the screen shows up blank. If I log off and then log back and go to maps, the image shows up but as I attempt to work with it, in the most recent case something as simple as zoom in, the browser throws an error: "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."

The Javascript console has this:
maps.googleapis.com/maps-api-v3/api/js/24/12/util.js:222 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
maps.googleapis.com/maps-api-v3/api/js/24/12/util.js:222 Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
maps.googleapis.com/maps/api/js?v=3&key=&callback=__atlasInit&libraries=places:35 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

**Comment by Hinni** [comment]
Does the error still exists with the latest version 5.2.9?

**Comment by dalonso22893** [comment]
I'm on 5.2.7, has the package been updated to 5.2.9?

**Comment by dalonso22893** [comment]
My fault for not updating this sooner but the issue has been resolved and is not visible since 5.2.9 on.
