### ISSUE TITLE
Upgrading Unifi on Qnap

### ISSUE THREAD

**Issue by venancio7** [jacobalberty/unifi-docker#100]
Hello,

How can i update the Unifi version on Qnap NAS.

Best regards

**Comment by ning42** [comment]
Remove the container, and create a new with the desired version

Since you have the data in /unifi/data, there should be no problem, but just-in-case I personally like to have the backup made manually in the Unifi webinterface.
:)

**Comment by feutl** [comment]
Tried that, but it is not referencing to the same /unifi/ share as the first one.
Any ideas how to change this? I couldn't figure it out.

thanks

**Comment by feutl** [comment]
All I did was pulling the latest docker and using it.
After seeing that the latest docker was upgraded to a new unifi version, I pulled the new "latest" version, but I never created a unifi volume manually.
Which I see not needs / can be done at the very beginning of creating that docker image.

thanks - wasn't clear for me

**Comment by jacobalberty** [comment]
I don't personally use QNAP so I can't provide screenshots but after some googling it looks like qnap may call it shared folders, you would need to create a shared folder where the mount point is /unifi then for the volume on host set it to wherever you would want to store the data, You can copy an existing data folder out from a running container by using the command  (ssh into the qnap machine) and running 
`docker cp -a <unifi container name>:/unifi /<path to where you want to save it for the future>`

**Comment by ning42** [comment]
@feutl I own a Qnap - can you provide info on how you create the container?
Via gui or command - if command please provide the command you execute

**Comment by feutl** [comment]
@ning42 
I used the GUI "ContainerStation" shipped with QNAP
It was quite straight forward, search for the docker image within the "Create" optione and deploy it.
Import is to mount a Shared Folder /unifi somewhere on your NAS so the the configuration is permanent and can be reused if you upgrade.

I also bound the ContainerStation to one of the 2 NICs I have with a spatic IP. Otherwise you conflict with the ports used by QNAP WebUI.

But at the end it was easier than expected, the magic is to get the /unifi share mounted from a local directory for keeping data after a upgrade.

**Comment by ning42** [comment]
:) 
@venancio7 do you still have the problem or can we close the issue?

**Comment by joffer77** [comment]
He probably never created a folder in QNap, and thus never mounted the /unifi folder to that folder (outside the container), so the data was stored inside the container:
"All I did was pulling the latest docker and using it."
So if he didn't export the configuration, and have deleted the container the config is gone

**Comment by csfshore** [comment]
First, thanks for this. Felt like I had discovered fire when I got this to work!

I don't have an issue, but a question, regarding upgrading.

Have read and understand the suggested approach, BUT as I
have created a "persistent volume" (whatever) can't I just upgrade
in place via the Ubiquiti command?

Thanks for any help

**Comment by joffer77** [comment]
> I don't have an issue, but a question, regarding upgrading.
> 
> Have read and understand the suggested approach, BUT as I
> have created a "persistent volume" (whatever) can't I just upgrade
> in place via the Ubiquiti command?

I'm no docker expert, but I would thinks so. And if it doesn't work, just remove the failed docker instance and recreate a new one pointing on the persistent datafolder.
I tend to just stop the old, create a new, verify it works (pointed at the persistent data folder), and delete the old..

**Comment by csfshore** [comment]
Thank you. Appreciate the response.
Regards,
CSF

**Comment by simonz21** [comment]
Can I just clarify something here. I'm a little out of my depth, and trying to learn fast. I have unifi up and working fine, but am also curious about up to upgrade. 

1. So I'm a little confused on where and when to create the dedicated Unifi shared volume on the QNAP.  When you create the container, there are several places I could reference a dedicated Unifi folder. On the initial create-page there's something called **Entrypoint** . 

![image](https://user-images.githubusercontent.com/26865660/58704264-ac9b0e80-83ab-11e9-8a3a-b6db787d3ffc.png)

In the advanced settings under Shared Folders there are three options: 
New volume - I could specify the name of the dedicated folder i've created here
Volume from host - i can pick my newly-made folder from the folder list here
Volume from container - here I could specify the volume from my current Unifi container, so does that mean it will use the existing data - that would be perfect!
![image](https://user-images.githubusercontent.com/26865660/58704294-c5a3bf80-83ab-11e9-89f3-ee234966345c.png)

2. And where best to keep it this new folder? In the container folder would be ideal (would make sense to store it here, keeping all the container materials together) or does it need to be a totally seperate folder (shared?) in the same volume? The documentation mentions a series of folders, /unifi , /unifi/data,  /unifi/log  etc but are these created automatically (if so, where?) or am I supposed to create them and reference them during the container creation process somehow/somewhere?

3. Finally,[ the documentation](https://github.com/jacobalberty/unifi-docker/blob/master/README.md#volumes) recommends setting RUNAS_UID0=false. I assume this is a security issue of some kind? I'm guessing I do this during the container creation process?

Sorry if this all sounds a bit green, but I'm learning as fas as I can!

**Comment by ning42** [comment]
when you setup "container station" on QNAP you either created a shared folder or reuse a new.
Personally i create a new folder called "Container".
In that folder i store all my container foldres.

So I have created a folder called "unifi-jacob" in that shared folder "Container".

When you create the unify container, you would under the "Volume from host" mount that folder, and chose the mount point "unifi", as that is needed for this contianer. The rest as you mentioned would be automatically created in the "unifi" folder, and on my qnap you would see the foder under "Container/unifi-jacob"

![Screenshot 2019-06-01 at 16 13 26](https://user-images.githubusercontent.com/13636254/58749601-4637ee00-8488-11e9-9dc0-d807a069f918.png)

**Comment by barbatrukko** [comment]
> when you setup "container station" on QNAP you either created a shared folder or reuse a new.
> Personally i create a new folder called "Container".
> In that folder i store all my container foldres.
> 
> So I have created a folder called "unifi-jacob" in that shared folder "Container".
> 
> When you create the unify container, you would under the "Volume from host" mount that folder, and chose the mount point "unifi", as that is needed for this contianer. The rest as you mentioned would be automatically created in the "unifi" folder, and on my qnap you would see the foder under "Container/unifi-jacob"
> 
> ![Screenshot 2019-06-01 at 16 13 26](https://user-images.githubusercontent.com/13636254/58749601-4637ee00-8488-11e9-9dc0-d807a069f918.png)

ah! ok.
So next time that I recreate image I use "Volume from host" for store data and then I can use again when pull new version.
I will try.
Thanx|

**Comment by Th3S4mur41** [comment]
I personally prefer to create an "App"...
That way you set everything up in a docker compose file that you can save locally, so no more manual steps when you need to recreate the container. Just copy/paste your docker compose file and you're done.

And for the update I use [watchtower](https://containrrr.dev/watchtower/).
Same here, I created the container with a docker compose since QNAP UI doesn't let me mount `/var/run/docker.sock`
Works like a charm and automatically updates my containers (or notifies me about available updates based on configuration)
