### ISSUE TITLE
Unifi-Beta Not Starting 5.7.18

### ISSUE THREAD

**Issue by iwoloschin** [jacobalberty/unifi-docker#101]
### Host operating system

Funtoo

### What tag are you using

Beta

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/New_York' -e RUNAS_UID0=false -v ~/:/unifi --restart always -d --net=host --name unifi unifi-beta

### What do you expect to happen?

Unifi services to start

### What actually happens?

Nothing, presumably because of this line:
2018-02-10T12:42:25.063+0000 [initandlisten] options: { net: { bindIp: "127.0.0.1", http: { enabled: false }, port: 27117, unixDomainSocket: { pathPrefix: "/usr/lib/unifi/run" } }, storage: { dbPath: "/usr/lib/unifi/data/db" }, systemLog: { destination: "file", logAppend: true, path: "/usr/lib/unifi/logs/mongod.log" } }
2018-02-10T12:42:25.063+0000 [initandlisten] exception in initAndListen: 28574 Cannot start server. Detected data files in /usr/lib/unifi/data/db created by storage engine 'wiredTiger'. The configured storage engine is 'mmapv1'., terminating

Do we need to make sure to pull in a newer version of mongdb than provided by Ubuntu?

**Comment by iwoloschin** [comment]
Almost forgot, here's the instructions for installing mongodb-org:
https://docs.mongodb.com/master/tutorial/install-mongodb-on-ubuntu/

I might try to take a shot at this myself this weekend if I have some time.

**Comment by jacobalberty** [comment]
That's weird that I didn't run into this myself when I moved from the debian base for beta to ubuntu base.

I have a fix checked in and it is building on the hub now.

**Comment by jacobalberty** [comment]
Upgrading will require a full rebuild of the database though make sure you have backups before applying

**Comment by jacobalberty** [comment]
Actually if you hold off im gonna change the mongodb version to one that will cleanly update from one of the stables

**Comment by jacobalberty** [comment]
Ok there, I put it on 3.2 so its in sync with the stable, later I'll move beta up to 3.4 once enough people have had time to run this to avoid jumping versions too high to auto upgrade.

**Comment by iwoloschin** [comment]
Great, that looks like it's working fine now.  Glad it was an easy fix!
