### ISSUE TITLE
Cannot start unifi docker; docker-entrypoint.sh: Exec format error

### ISSUE THREAD

**Issue by symetryczny** [jacobalberty/unifi-docker#105]
### Host operating system

Raspbian 4.9, Raspberry Pi 3, fresh install

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Zurich' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:stable

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

Unifi controller started

### What actually happens?

Error [FATAL tini (7)] exec /usr/local/bin/docker-entrypoint.sh: Exec format error

**Comment by symetryczny** [comment]
Fresh install of Raspbian and fresh docker install (via curl -sSL https://get.docker.com | sh). I'm quite new to Docker but I've managed to run Pi-Hole with no issues so I have probably missed a step.

**Comment by jacobalberty** [comment]
Alas the docker hub doesn't support building arm images. I am working on getting a CI setup to build arm images on my own local raspberry pi and push them to the hub under the same tags as the x86 images, until that time you would need to use the jacobalberty/unifi:arm32v7-beta tag. It's currently on 5.6.29,  I just updated it to 5.6.30 and it's building on the hub now

**Comment by symetryczny** [comment]
Much appreciated, thank you and keep up the good work, cheers!On 19 Feb 2018 7:51 p.m., Jacob Alberty <notifications@github.com> wrote:Closed #105.

**Comment by kanecharles92** [comment]
Hi @jacobalberty, is this still an issue? I am running my container with: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e Z='Australia/Canberra' -v ~/docker_vols/unifi:/unifi --name unifi jacobalberty/unifi:stable` and receiving the following error (on a raspberry pi): `[FATAL tini (8)] exec /usr/local/bin/docker-entrypoint.sh failed: Exec format error`

**Comment by jacobalberty** [comment]
yes, most of the tags are built for x86_64, the arm branch is jacobalberty/unifi:arm32v7-beta

**Comment by jam313** [comment]
This is a fairly old thread but where can i see what the current controller version of the arm32v7-beta branch? @jacobalberty
