### ISSUE TITLE
error on guest login page with docker running on Pplesk on Centos 7

### ISSUE THREAD

**Issue by timlitw** [jacobalberty/unifi-docker#106]
### Centos 7.2.1511 running plesk

tag = latest

running on plesk requires that several ports get changed - but this isn't happening correctly.

![unifi-plesk](https://user-images.githubusercontent.com/11441935/36386400-40b65cde-155b-11e8-8859-cb7df3479213.gif)

### What do you expect to happen?
I was trying to setup a guest portal with simple password when the guest connects to the wifi they should get sent to a page that asks for password

### What actually happens?
they get sent to a 404 error page.

I believe it is because the 8880 port on the plesk install gets set to 8881 but even tho that is in the settings show above the system still sends 8880 in the url so they get send to a place that doesn't exist.

**Comment by phroggster** [comment]
Edit the system.properties file in your containers data volume/mapping (/unifi/data/system.properties). The directive by default shows up as:
```
## portal redirect port for HTTP
# portal.http.port=8880
```
So change that to (or add in at the bottom of the file) `portal.http.port=8883`. Note that's 8883, not 8881 nor 8882 as those ports are used elsewhere but not exposed by default. Another port could be used as desired, but check that system.properties file first to see if it's utilized elsewhere

Then, publish the revised port in your docker configuration. Basically, just change the last port mapping down above to 8883 <-> 8883 (or whichever port was assigned in the config file, as long as both are equal), and restart the container.

**Comment by timlitw** [comment]
Thanks for that.  I will see what I can figure out.  since it is all done in the Plesk web interface I'll have to see if I can find the docker file. and how to edit it etc....   I changed to the 5.7.19 version hoping something would have changed but still the same - at least making a backup from and restoring works.

**Comment by timlitw** [comment]
If I run docker ps I get
docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                       PORTS                                                                                                                                            NAMES
2af97##d5c##        jacobalberty/unifi:5.7.19-sc-5c48d8a0   "/usr/local/bin/do..."   About an hour ago   Up About an hour (healthy)   0.0.0.0:6789->6789/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:3478->3478/udp, 0.0.0.0:8843->8843/tcp, 0.0.0.0:8444->8443/tcp, 0.0.0.0:8883->8880/tcp   unifi

so is the last 0.0.0.0:8883->8880/tcp what is causing the problem?

**Comment by phroggster** [comment]
Are you not able to just click the port number in the Plesk interface and type in a new port to match the 8883 as set in Unifi? I'm not familiar with Plesk, but the quick Google seems to imply that you can manually map ports that were already exposed by the docker image.

**Comment by timlitw** [comment]
I can change the right side as seen in the attachment above - but I can't change the left side and it seems it is still sending what is on the left side

**Comment by phroggster** [comment]
Yeah, I typed too quickly in mobile and retract it. After some further googling, Plesk appears to only allow ports that are already exposed by the docker image which does raise the difficulty. You'll probably need to create a docker hub account, clone this repository, edit the dockerfile to use the new port (maybe also expose the SSL redirect port depending on your requirements), commit to github, then have docker hub build the image, and switch to using that in Plesk. Otherwise, you could create a "simple" derived docker image with a dockerfile like the following:
```
FROM jacobalberty/unifi:latest
EXPOSE 6789/tcp 8080/tcp 8443/tcp 8883/tcp 8843/tcp 3478/udp
WORKDIR /unifi
HEALTHCHECK CMD /usr/local/bin/docker-healthcheck.sh || exit 1
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["unifi"]
```
and publish it to the registry. Harder to keep it up-to-date with any changes that go in upstream, but it is what it is.
