### ISSUE TITLE
stable version - 5.6.26 as of 2017-12-08

### ISSUE THREAD

**Issue by gjs1969** [jacobalberty/unifi-docker#112]
What is going on with the actual versions ? i see the latest stable is 5.6.26 while my docker version of JA is already at 5.6.30.  What has happened ?
I also noticed there has been a 5.7 release today , i can imagine it is not a docker version yet, bu t where has the 5.6.30 version gone ?

**Comment by jacobalberty** [comment]
Seems to be a problem with the docker hub, latest is supposed to be 5.7.30, lts is 5.6.36 :stable does seem to have the correct version i'm trying forcing a rebuild of the :latest tag to see if that fixes it
