### ISSUE TITLE
Update arm32v7-beta branch with same versions as master

### ISSUE THREAD

**Issue by ssoriche** [jacobalberty/unifi-docker#117]
As the title suggest, can the `arm32v7` branch be updated to run the current UniFi versions?

**Comment by jacobalberty** [comment]
The latest unfii release is building now on the arm32v7 branch

**Comment by ssoriche** [comment]
I think the `arm32v7` branch has fallen behind again. Can it be bumped to match the version in master?

**Comment by jacobalberty** [comment]
Went ahead and updated and built it on the hub, it's up now.
