### ISSUE TITLE
Unable to log in with default user and pass

### ISSUE THREAD

**Issue by Taubin** [jacobalberty/unifi-docker#118]
### Host operating system

Windows 10

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Kitematic - Screenshot attached

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

Be able to log in with the default ubnt user and pass

### What actually happens?

Unable to log in with default ubnt user and pass
I've searched the repo for the default user and pass and have come up short. I'm unable to log into the site at all after starting it up. 

![unifi](https://user-images.githubusercontent.com/8891792/39277078-2200bf28-4940-11e8-841c-5c9bba4537bb.png)

**Comment by jacobalberty** [comment]
There isn't a default user and pass with unifi anymore, it gives you a wizard that prompts you to create your admin user on first run.

**Comment by Taubin** [comment]
Unfortunately, there's no first run wizard when run through kitematic, I guess I'll have to do it through the command line instead.

**Comment by jacobalberty** [comment]
I'm not sure why kitematic would interfere with the first run wizard, isn't it just a different ui for docker?

**Comment by Taubin** [comment]
I believe it is, it's Docker's built UI

**Comment by Taubin** [comment]
It has rebound the port for some reason. I deleted the image, and redownloaded it, then was able to log into the rebound port. Thanks for that, I hadn't thought of it.
