### ISSUE TITLE
import_cert script domain name letsencrypt

### ISSUE THREAD

**Issue by m4t7e0** [jacobalberty/unifi-docker#120]
### Host operating system

`Debian 8` 

### What tag are you using

Example: `lts`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

 `docker run --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e RUNAS_UID0='false' -e CERT_IS_CHAIN=true -e BIND_PRIV='false' -e TZ='Europe/Rome' -v /data/unifi:/unifi  --name unifi_controller jacobalberty/unifi:lts'
`

### What do you expect to happen?

on my host /data/unifi/cert another script automatically update the letsencript certificate for my domain (unifi.controller.mydomain.com) and it make the prober file (pem file). So it will be automatically loaded on controller with the correct CN.

### What actually happens?

After  the launch of container the "usr/unifi/init.d/import_cert" make a request for "unifi" CN and the browser dont accept these certificate.

My Fix Was just update it on the CN on import_cert file
           "-keysize 4096 -dname "cn=unifi.controller.mydomain.com""

Is possibile to add it as a variable of container instruction?

**Comment by jacobalberty** [comment]
Are you saying you edited line 21 of import_cert? I'm not sure why that would have an effect, it's generating a temporary certificate that should be thrown out on line 74 of the same file then replaced on line 77, can you give me the output of ls /data/unifi/cert on the host system?

**Comment by m4t7e0** [comment]
Yes i have edited the line 21 of import_cert an then the result is the right certificate 

![cert_ok](https://user-images.githubusercontent.com/2818095/40011350-dfcb32de-57a7-11e8-89c8-6990beb198eb.jpg)

```
user@dkr:/# ls   /data/unifi/cert
cert.pem  cert.pem.md5  chain.pem  fullchain.pem  keystore  privkey.pem  README
```
