### ISSUE TITLE
new beta image fails to install

### ISSUE THREAD

**Issue by blackyellowred** [jacobalberty/unifi-docker#123]
### Host operating system
`Debian stretch`

### What tag are you using
`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker volume create --driver local \
    --opt type=nfs \
    --opt o=addr=10.10.100.15,rw,hard,nolock \
    --opt device=:/mnt/pepper/unifi \
    unifi`

`docker run --init --name unifi -d \
-p 8080:8080 \
-p 3478:3478/udp \
-p 6789:6789 \
--restart=always \
-e TZ='America/Vancouver' \
-e UNIFI_GID=1000 \
-e UNIFI_UID=1000 \
-e RUNAS_UID0=false \
-e BIND_PRIV=false \
-e JVM_MAX_THREAD_STACK_SIZE=1280k \
-e PKGURL='https://dl.ubnt.com/unifi/5.9.4-b647df56b7/unifi_sysvinit_all.deb' \
-v unifi:/unifi \
-l traefik.default.protocol=https \
-l traefik.protocol=https \
-l traefik.frontend.rule=Host:unifi.chee.ma \
-l traefik.port=8443 \
-h unifi \
--net=mynet \
 jacobalberty/unifi:beta`

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

New image to install successfully

### What actually happens?

New image pulled from docker hub fails at
`Executing: /tmp/tmp.Xa1CcC7Qlm/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv
C0A52C50
gpg: requesting key C0A52C50 from hkp server keyserver.ubuntu.com
gpg: key C0A52C50: public key "UniFi Developers <unifi-dev@ubnt.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
E: Unsupported file ./unifi.deb given on commandline
chown: cannot access '/usr/lib/unifi': No such file or directory
ln: failed to create symbolic link '/usr/lib/unifi/data': No such file or directory
ln: failed to create symbolic link '/usr/lib/unifi/run': No such file or directory
ln: failed to create symbolic link '/usr/lib/unifi/logs': No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 136: cd: /usr/lib/unifi: No such file or directory
[2018-05-28 21:36:40,890] <docker-entrypoint> Starting unifi controller service.
[2018-05-28 21:36:40,893] <docker-entrypoint> INFO: Changing 'unifi' UID to '1000' and GID to '1000'
Error: Unable to access jarfile /usr/lib/unifi/lib/ace.jar
[2018-05-28 21:36:40,915] <docker-entrypoint> WARN: unifi service process ended without being singaled? Check for errors in /unifi/log.
`

**Comment by jacobalberty** [comment]
Hmm, I'm able to run a simplified form of that command line without issue:

 docker run --rm -it -e PKGURL=https://dl.ubnt.com/unifi/5.9.4-b647df56b7/unifi_sysvinit_all.deb jacobalberty/unifi:beta

It looks like there was an issue connecting to key server it's possible it was transient error with the key server that has resolved itself, another possibility is some sort of ssl intercepting proxy server on your network.

**Comment by blackyellowred** [comment]
@jacobalberty is it true that docker container is behind a vpn on my router. I noticed it tires to get 
keys with `requesting key A15703C6 from hkp server keyserver.ubuntu.com` and that request works, maybe 2 requests back to back fail for some reason.
But anyway I rebooted by router and tired again and this time it worked.
