### ISSUE TITLE
Synology - Unfi Docker - SMTP Fails

### ISSUE THREAD

**Issue by Sirwill1968** [jacobalberty/unifi-docker#124]
### Host operating system

Synology Docker Hub

### What tag are you using

Latest

### What complete docker command or docker-compose.yml do you use to launch the container
GUI 100%  
Zip has json of the docker container config.  

### What do you expect to happen?
When configuring SMTP I expect it to connect to the smtp.gmail.com or any other smtp service.  

### What actually happens?
Get error message no matter what service I attempt to use.   

[Unifi-Docker.syno.zip](https://github.com/jacobalberty/unifi-docker/files/2076951/Unifi-Docker.syno.zip)

**Comment by Sirwill1968** [comment]
Yes I can connect from my laptop to smtp.gmail.com and other smtp servers
using tls ssl or not.

~Will

**Comment by jacobalberty** [comment]
Can you show me a screenshot of the setup page with the smtp settings? If you can access smtp.gmail.com on port 25 then it sounds like you've got an isp that's interfering with smtp connections somehow.

**Comment by jacobalberty** [comment]
Just emailed you.

**Comment by Sirwill1968** [comment]
Turns out it was a google 2 factor auth issue.  Got app password from security center and it works now.
