### ISSUE TITLE
Is this works with UniFi Controller for this UniFi® AP AC LR?

### ISSUE THREAD

**Issue by omidraha** [jacobalberty/unifi-docker#129]
Hi,
Is this docker file compatible with  UniFi Controller  for  this `UniFi® AP AC LR` model,
That is available for [download](https://dl.ubnt.com/unifi/5.7.23/unifi_sysvinit_all.deb) from this [address](https://www.ubnt.com/download/unifi/)

**Comment by regner** [comment]
Yes

**Comment by omidraha** [comment]
Thank you,

After I launching docker with this command:

```
docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Asia/Tehran' -v ~/ws/unifi/data:/var/lib/unifi -v ~/ws/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:5.7.28-sc
```
And then , When I go to this page for `Configure devices`: 
 https://localhost:8443/manage/wizard/

This show me: 

```
No devices found
When a device is detected on your network it will automatically show up in this list.
```

**Comment by omidraha** [comment]
After I logined to the dashboard, the device detected.
Thank you so much.

**Comment by jury89** [comment]
Hi @omidraha, i'm having the same problem you had. When you say `After I logined to the dashboard, the device detected`, which dashboard are you talking about?

Thanks

**Comment by omidraha** [comment]
@jury89, this one:

![unifi_dashboard](https://user-images.githubusercontent.com/397672/42255505-55256d52-7f61-11e8-9474-c1bd75934271.png)
