### ISSUE TITLE
Allow data, cert, and logdir to be overridden

### ISSUE THREAD

**Issue by oyvindkinsey** [jacobalberty/unifi-docker#132]
With the existing Docker file, it is impossible to control the directory where dynamic data is stored, which prevents use under supervisors such as Hassio, where only /data is actually persisted across restarts.

Can we make it so that environment variables for these three will only be set by the Docker file if not already set, or require that these, or a prefix for them, is set by the user?

**Comment by jacobalberty** [comment]
I will be fixing this, it is almost actually just be a documentation issue. as setting the DATADIR environment variable will almost achieve what you want, though that moves ONLY the unifi data and does not cover ceritficate data or logs. 

There was one hardcoded path under /unifi/data that I have just corrected in the beta branch in the c494af0 commit

**Comment by oyvindkinsey** [comment]
I believe I tried setting DATADIR, but I believe https://github.com/jacobalberty/unifi-docker/blob/master/Dockerfile#L10-L12 will overwrite any env variables already set.
