### ISSUE TITLE
Container does not launch due to exec failure.

### ISSUE THREAD

**Issue by drachul** [jacobalberty/unifi-docker#135]
### Host operating system
`Centos 7.5.1804`

### What tag are you using
I've tried with `stable`, `latest` and `lts`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker run --rm --init --net=host -e TZ='America/Vancouver' -v $PWD/unifi:/unifi --name unifi-test jacobalberty/unifi:stable`

### What do you expect to happen?
Docker container to launch with Unifi controller running.

### What actually happens?
```
# docker run --rm --init --net=host -e TZ='America/Vancouver' -v $PWD/unifi:/unifi --name unifi-test jacobalberty/unifi:stable
exec -- failed: No such file or directory
```
and then the container exits.

I've tried running the example in the README, verbatim (using root, in root's $HOME,) and get the exact same problem.

Have also run the `linuxserver/unifi` image with no issues.

### Docker version
```
# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by jacobalberty** [comment]
Interesting, that feature is a new(well more than a year old at this point)
feature in docker, but even if youre running an older version of docker it
should just warn you that the flag isn't supported. It looks like you have
a newer version of docker but it cant find the init binary

**Comment by drachul** [comment]
`docker info` shows this for docker-init:
```
Init Binary: /usr/libexec/docker/docker-init-current
```

And that file does appear to exist:
```
# ls -l /usr/libexec/docker/docker-init-current
-rwxr-xr-x 1 root root 845128 May 18 08:45 /usr/libexec/docker/docker-init-current
```

So not sure what the issue is, either way running without `--init` works, so I guess this can probably be closed as there's a workaround.
