### ISSUE TITLE
[FATAL tini (7)] exec /usr/local/bin/docker-entrypoint.sh failed: Exec format error

### ISSUE THREAD

**Issue by elliottn** [jacobalberty/unifi-docker#138]
### Host operating system
`Raspbian stretch`

### What tag are you using
`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
`docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='US/Eastern' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:latest`

### What do you expect to happen?
Initial run of container

### What actually happens?
`[FATAL tini (7)] exec /usr/local/bin/docker-entrypoint.sh failed: Exec format error`

**Comment by elliottn** [comment]
I suspect the issue is related to needing an ARM image since i am attempting on a Raspberry Pi

**Comment by elliottn** [comment]
Duplicate of #105 
using arm32v7-beta tag fixed issue

**Comment by elliottn** [comment]
@jacobalberty recommend updating Supported Docker Hub Tags and Respective Dockerfile Links in README.md to include the arm32v7-beta tag

**Comment by CBDFactum-com** [comment]
I have QNAP TS-431P and I get the same error. What can it be? Which container can I use for my QNAP?
Thx
