### ISSUE TITLE
Rewrite compose file in v2.2 format

### ISSUE THREAD

**Issue by dghodgson** [jacobalberty/unifi-docker#139]
I noticed that the compose file is currently using the v2.4 format. It's always nice to use the latest and greatest, but I don't see any technical reason for needing v2.4 over v2.2. As it is, none of the 2.3+ features are being used (other than the long-form volumes declarations, which can currently all be re-written in v2.2 format).

Reverting back to the v2.2 format will allow the compose file to be used on systems which are stuck with Docker Engine 1.13.x (e.g. CentOS 7/RHEL 7).

**Comment by Toasty27** [comment]
#140 is a PR with the proposed changes
