### ISSUE TITLE
Error starting 

### ISSUE THREAD

**Issue by claym** [jacobalberty/unifi-docker#14]
I just ran

~$ docker run --net=host -d jacobalberty/unifi:latest

Got this error:

4acb32b0ea26446bc809008a5b54dd402c5f0296edd2fd616733dd98a6800212
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"apparmor failed to apply profile: no such file or directory\"".

Any ideas what would cause this?

Thanks!

**Comment by chupakabr** [comment]
+1, any solution/workaround?

**Comment by cdrom1028** [comment]
I am doing the same thing with no issues. Do you have the -v path set to an existing folder?

**Comment by jacobalberty** [comment]
What distribution are you guys using @chupakabr and @claym  ?

**Comment by chupakabr** [comment]
@jacobalberty Ubuntu 12.10, 3.13.0-106-generic, x86_64

**Comment by jacobalberty** [comment]
@chupakabr are you sure your host os is 12.10 and not 12.04? 12.10 is officially unsupported by docker and shouldn't have packages in the repository.

**Comment by jacobalberty** [comment]
also it sounds to me like you're trying to run an image other than unifi since these are based on debian:jessie

**Comment by chupakabr** [comment]
@jacobalberty yep.

ubuntu@Ubuntu-1210-quantal-64-minimal:/etc/apparmor.d$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.10
Release:	12.10
Codename:	quantal

I updated linux kernel and then installed docker.
