### ISSUE TITLE
AP connects to Docker IP

### ISSUE THREAD

**Issue by bswinnerton** [jacobalberty/unifi-docker#142]
### Host operating system

Clear Linux

### What tag are you using

`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yaml
version: '2.2'
services:
  mongo:
    image: mongo:3.4
    container_name: unifi_mongo
    restart: always
    volumes:
      - db:/data/db
    networks:
      - unifi
  controller:
    image: jacobalberty/unifi:latest
    container_name: unifi_controller
    restart: always
    depends_on:
      - mongo
    volumes:
      - data:/unifi/data
    networks:
      - unifi
    ports:
      - 8080:8080
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
  exporter:
    image: bswinnerton/unifi_exporter
    container_name: unifi_exporter
    restart: always
    depends_on:
      - controller
    command: -config.file /etc/unifi_exporter/config.yml
    volumes:
      - exporter_config:/etc/unifi_exporter
    ports:
      - 9130:9130

volumes:
  db:
  data:
  exporter_config:

networks:
  unifi:
```

### What do you expect to happen?

The AP to connect to the IP used in `set-inform`:

```
mca-cli
set-inform http://10.70.117.3:8080/inform
```

### What actually happens?

The AP attempts to connect to an internal Docker IP, which it can't route to.

```
Aug 18 22:41:59 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[11] (http://172.26.0.3:8080/inform)
Aug 18 22:41:59 UBNT user.err syslog: ace_reporter.reporter_fail(): initial contact failed #1, url=http://172.26.0.3:8080/inform, rc=11
Aug 18 22:42:14 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[11] (http://172.26.0.3:8080/inform)
Aug 18 22:42:14 UBNT user.err syslog: ace_reporter.reporter_fail(): initial contact failed #2, url=http://172.26.0.3:8080/inform, rc=11
Aug 18 22:42:37 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[11] (http://172.26.0.3:8080/inform)
Aug 18 22:42:37 UBNT user.err syslog: ace_reporter.reporter_fail(): initial contact failed #3, url=http://172.26.0.3:8080/inform, rc=11
Aug 18 22:42:37 UBNT user.err syslog: ace_reporter.reporter_fail(): [STATE] entering SELFRUN!!!!
```

For some reason, this only happens when the Docker container is restarted. If I go through the adoption process again, everything is fine until the AP loses the connection with the container.

**Comment by bswinnerton** [comment]
This is what the AP sees from its perspective before and after connectivity with the container is severed:

```
UniFi# info

Model:       UAP-AC-Pro-Gen2
Version:     3.9.42.9152
MAC Address: 78:8a:20:5c:0a:85
IP Address:  10.70.117.4
Hostname:    UBNT
Uptime:      880 seconds

Status:      Connected (http://10.70.117.3:8080/inform)
UniFi# set-inform http://10.70.117.3:8080/inform

Adoption request sent to 'http://10.70.117.3:8080/inform'.  Use the controller to complete the adopt process.
```

```
UniFi# info

Model:       UAP-AC-Pro-Gen2
Version:     3.9.42.9152
MAC Address: 78:8a:20:5c:0a:85
IP Address:  10.70.117.4
Hostname:    UBNT
Uptime:      1084 seconds

Status:      Unknown[11] (http://172.26.0.3:8080/inform)
```

**Comment by jacobalberty** [comment]
I need to update readme.md to more accurately follow the current directions from unifi,  or at least link to the ssh directions on their website.

You need to run set-inform once, adopt then when the ap comes back run set-inform a second time to permanently save the setting. https://help.ubnt.com/hc/en-us/articles/204909754-UniFi-Layer-3-methods-for-UAP-adoption-and-management#8 has more details. I haven't personally used ssh adoption in a while and it appears the procedure has changed since I last used it.

**Comment by bswinnerton** [comment]
> You need to run set-inform once, adopt then when the ap comes back run set-inform a second time to permanently save the setting.

I had tried that quite a few times to no avail before writing this issue 😕.

I think I was able to find it out, but for the sake of posterity I wanted to write down some notes. TL;DR I think L3 adoption is just incredibly flaky.

Previous to moving Unifi over to a container (with the image from this repository), I was running Unifi in a virtual machine. That virtual machine had its own IP address on the same network as the AP, so there was no problem using L2 adoption. I ended up copying the config off of that old Unifi instance, and once I had the container set up (with [this](https://github.com/bswinnerton/home-lab/blob/5299ed235f239cb225665f5d8129b21ee392a45d/containers/unifi/docker-compose.yml) configuration), I reapplied the old config.

That's when I started running into the problems that are described in this issue. This was the first time that I've attempted L3 adoption, so I'm not sure if this is a problem with the Docker container, or Unifi, but the fact that the AP was automatically pulling a Docker IP seemed to imply that somehow the `set-inform` URL was falling back to something on the Docker network.

After a tip in the ##ubnt IRC channel, I think that I may have figured this out. There are two big changes that I made, but I'm not sure which one ultimately resolved the issue.

First, setting the "Controller Hostname/IP" to the explicit IP, not FQDN, in Unifi under Settings > Controller, as well as checking the Override inform host with controller hostname/IP.

The second thing that I attempted was using the DHCP Option 43 adoption method outlined [here](https://help.ubnt.com/hc/en-us/articles/204909754-UniFi-Layer-3-methods-for-UAP-adoption-and-management#7). This is quite easy to do with an EdgeRouter, you just have to type in the IP here:

<img width="359" alt="screen shot 2018-08-19 at 10 53 01 am" src="https://user-images.githubusercontent.com/934497/44310050-1195f280-a39e-11e8-84ce-5913788e58ab.png">

While I still see these in the AP log:

```
Aug 19 10:51:49 UBNT user.info syslog: ace_reporter.reporter_set_managed(): [STATE] enter MANAGED
Aug 19 10:52:30 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[10] (http://10.70.117.3:8080/inform)
Aug 19 10:52:30 UBNT user.err syslog: ace_reporter.reporter_fail(): inform failed #1 (last inform: 0 seconds ago), rc=10
Aug 19 10:52:45 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[10] (http://10.70.117.3:8080/inform)
Aug 19 10:52:45 UBNT user.err syslog: ace_reporter.reporter_fail(): inform failed #2 (last inform: 15 seconds ago), rc=10
Aug 19 10:53:00 UBNT user.err syslog: ace_reporter.reporter_fail(): Unknown[10] (http://10.70.117.3:8080/inform)
Aug 19 10:53:00 UBNT user.err syslog: ace_reporter.reporter_fail(): inform failed #3 (last inform: 30 seconds ago), rc=10
Aug 19 10:53:00 UBNT user.err syslog: ace_reporter.reporter_fail(): [STATE] entering SELFRUN!!!!
```

The device shows as "Connected" in Unifi (though every time that the controller restarts, the device goes through the "adopting" phase all over again.

**Comment by jacobalberty** [comment]
You may want to consider looking into a macvlan setup. That would allow you
to give the container its own ip on the real network. That's what I've been
doing instead of l3 adoption.

**Comment by malahal** [comment]
Just started unifi controller in a docker image today! I ran into this issue today. Setting unifi controller ip address in my erx edgerouter didn't help though. Starting the container with --net=host did help.

**Comment by mniesiobedzki** [comment]
I have the same issue.
`mcad: ace_reporter.reporter_fail(): [STATE] entering SELFRUN!!!!
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): inform failed #1 (last inform: 990 seconds ago), rc=11
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): inform failed #2 (last inform: 1006 seconds ago), rc=11
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): inform failed #3 (last inform: 1023 seconds ago), rc=11
mcad: ace_reporter.reporter_fail(): [STATE] entering SELFRUN!!!!
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): initial contact failed #4, url=http://IP_UNIFI:PORT/inform, rc=11
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): initial contact failed #5, url=http://IP_UNIFI:PORT/inform, rc=11
mcad: ace_reporter.reporter_fail(): Unknown[11] (http://IP_UNIFI:PORT/inform)
mcad: ace_reporter.reporter_fail(): initial contact failed #6, url=http://IP_UNIFI:PORT/inform, rc=11`
