### ISSUE TITLE
Controller suddenly not starting anymore

### ISSUE THREAD

**Issue by siccovansas** [jacobalberty/unifi-docker#143]
### Host operating system

Ubuntu 14.04

### What tag are you using

5.6.39

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -v ~/unifi:/unifi --name unifi jacobalberty/unifi:5.6.39`

### What do you expect to happen?

I expect it to start the Controller and keep it running, just like it has done for a while now.

### What actually happens?

I get the following warnings and the container stops.

```
[2018-08-22 18:02:47,405] <docker-entrypoint> Starting unifi controller service.
[2018-08-22 18:02:47,406] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
[2018-08-22 18:02:47,690] <docker-entrypoint> WARN: unifi service process ended without being singaled? Check for errors in /unifi/log.
```

**Comment by jacobalberty** [comment]
Do you have any errors in the files in /unifi/log

**Comment by siccovansas** [comment]
The log files contain lines but they are all from earlier on. So no new logs related to running the docker command right now.

**Comment by siccovansas** [comment]
Everything works again after a reboot of my computer :)
