### ISSUE TITLE
SSL certificate chain file, *.p12 files

### ISSUE THREAD

**Issue by fiechr** [jacobalberty/unifi-docker#145]
I had some trouble getting my self-signed certificate to work.

Since I have already some experience with SSL (and Unifi Controller), I thought the chain.pem is supposed to contain the certificate itself and then all certificates of the CAs (only one in my case) - in that order from top to bottom.
Like it is described here: https://www.digicert.com/ssl-support/pem-ssl-creation.htm

But this didn't worked for me - and after looking at the import script, I also understand that the chain.pem is treated as if it only contains the CA's certificates, but not the server's certificate itself(?). Also it seems to be created in reverse order?

I then removed the server certificate itself from chain.pem and now it works.

Maybe I'm getting something wrong here? But if not, it would be nice to update the script or the docs to make this more clear to the user (especially what the chain.pem should contain).  :-)

Also - maybe - you could add the possibility to provide an already created/existing *.p12 file, which would already contain everything needed.

Apart from that everything works fine. Thank you for your work providing this image!

**Comment by jacobalberty** [comment]
the CERT_IS_CHAIN=true environment variable will make cert.pem behave like you describe. chain.pem has just the chain so when you renew cert.pem you're not replacing everything. That's how certbot behaves. It also has the behavior of creating fullchain.pem which would contain cert.pem and chain.pem in a single file. I went with seperate chain.pem and cert.pem files because thats how most of the documentation for getting certificates working with unifi was written. I believe I ran into some issues with the keystore management tools as well when trying to do everything as a single file.

**Comment by jpawlowski** [comment]
Using CERT_IS_CHAIN=true does not work correctly w/o still having a proper chain.pem file presented (there is an awk error that is unable to find that file because it does not exist).
This should not happen as the chain part is then to be part of the cert.pem file itself.

**Comment by jpawlowski** [comment]
No, it's my internal CA.

The solution for me was to not rely in the internal script but put my own script into /usr/local/unifi/init.d/certs:

´´´´
#!/bin/sh

while [ true ]; do
  if [ -s /certs/unifi.req.signed ]; then
    break
  elif [ -s /certs/unifi.req.error ]; then
    echo "CSR signing error:"
    cat /certs/unifi.req.error.txt
    exit 10
  elif [ -f /certs/unifi.req.processing ]; then
    echo "CA is processing CSR: $(cat /certs/unifi.req.processing) ..."
  elif [ -f /certs/unifi.req ]; then
    echo "Waitiung for CA to provide certificate ..."
  fi
  sleep 10
done

cd /certs
cp -f unifi.crt /unifi/cert/cert.pem
cp -f unifi.nopasswd.key /unifi/cert/privkey.pem
cp -f ca-chain.crt /unifi/cert/chain.pem
´´´´

This script will actually also help me to wait until my internal CA had automatically created the required certificate.
