### ISSUE TITLE
Trigger build for newest controller stable release

### ISSUE THREAD

**Issue by ruimarinho** [jacobalberty/unifi-docker#15]
Can you trigger a new build so that the latest tag is updated? Thanks!

**Comment by jacobalberty** [comment]
Building with latest unifi 5 now, thank you for letting me know it's out.

**Comment by jacobalberty** [comment]
Hmm on checking  according to the release post 5.3.8 hasn't been pushed to the repo yet so I can't build this yet.

> Introducing our latest release for UniFi wireless, routing & switching hardware. This is a new post to bring attention to the status change from Stable Candidate to Stable. It will be posted to our downloads page and pushed to the repo on 12.12.16.

**Comment by jacobalberty** [comment]
https://community.ubnt.com/t5/UniFi-Wireless/UniFi-5-3-8-Stable-has-been-released-Yeah-but-has-it-though/td-p/1756106 Some discussion on the issue.

**Comment by ruimarinho** [comment]
Uh, I also got confused about this as I was testing the Stable Candidate and though that the final Stable would be released across all channels simultaneously. Unsure about why another week of public beta test has been proposed. Sorry about the false alarm :/

**Comment by jacobalberty** [comment]
Yeah it doesn't make much sense to me either but I went ahead and added a reminder for me to trigger a build on the 12th. I only posted the links so I can come back and remind myself why I had to wait.

**Comment by jacobalberty** [comment]
Just got home and it looks like repository finally updated (it hadn't before I left work to run errands) I just triggered the build I'll close this issue when its done and tested on my end.

**Comment by ruimarinho** [comment]
Thank you :)
