### ISSUE TITLE
Running behind reverse proxy, question about making ports accessible

### ISSUE THREAD

**Issue by ovizii** [jacobalberty/unifi-docker#150]
### Host operating system

Debian stretch

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
docker run -d --init \
--name unifi \
-p 1900:1900/udo \
-p 3478:3478/udp \
-p 8080:8080 \
-p 6789:6789 \
--expose 8443 \
-p 8843:8843 \
-p 8880:8880 \
-p 10001:10001/udp \
--expose 27117 \
-p 5656-5699:5656-5699 \
-e TZ='Europe/Berlin' \
-e RUNAS_UID0=false \
-v /home/ovi/docker/unifi/unifi-data:/unifi \
--label traefik.port=8443 \
--label traefik.frontend.rule=Host:wifi.mydomain.tld \
--label traefik.backend=unifi \
--label traefik.enable=true \
jacobalberty/unifi:stable
```

this container runs behind traefik as reverse proxy. 
I just wanted to know if this is correct, I am exposing port 27117 locally only as I don't want that port reachable from the internet and traefik is reverse-proxying wifi.mydomain.tld:443 to port 8443 - all other ports seem to have to be reachable from the internet and cannot be secured via https?

or can I change some other ports from their external mapping to run through the reverse-proxy and thus be secured with HTTPS?

**Comment by ovizii** [comment]
Those settings seem OK to me and yet I get a server error 404 when testing it. 
neither mongod.log nor server.log show any errors. 

I reverted to this config to test without the reverse proxy: 

```
docker run -d --init \
--name unifi \
--restart unless-stopped \
-p 1900:1900/udp \
-p 3478:3478/udp \
-p 8080:8080 \
-p 6789:6789 \
-p 8443:8443 \
-p 8843:8843 \
-p 8880:8880 \
-p 10001:10001/udp \
--expose 27117 \
-p 5656-5699:5656-5699 \
-e TZ='Europe/Berlin' \
-e RUNAS_UID0=false \
-v /home/ovi/docker/unifi/unifi-data:/unifi \
--label traefik.port=8443 \
--label traefik.frontend.rule=Host:wifi.mydomain.tld \
--label traefik.backend=unifi \
--label traefik.enable=true \
jacobalberty/unifi:stable

```

and everything works just fine. so it must be me proxying somethign wrong but the same traefik settings work for all my other containers, except none of them has a HTTPS backend but rather HTTP. 
No matter which settings I use, I can always control this unifi container from the universal dashboard via unifi.ubnt.com so basically there is no problem, I just wanted to check if anyone is successfully using traefik as a reverse proxy for this unifi.

oh and bwt. unifi.ubnt.com shows my internal docker IP in their dashboard but since the connection is mage via API it all works - is this the same for everyone else? I would have expected that in the dashboard I would see my external IP of my docker host.

**Comment by phroggster** [comment]
Try adding `--label traefik.protocol=https` to your `docker run` arguments, and verify that the traefik TLS frontend is functional. You may also want to add `insecureSkipVerify = true` to the main (header) section of traefik.toml, at least for testing, or ensure that the unifi container's certificates are appropriate.


> -p 1900:1900/ud**o**

`s/udo/udp/` for good measure.

**Comment by ovizii** [comment]
@phroggster 

Thanks for chiming in. I can try `--label traefik.protocol=https` although none of the other contaienrs needed it as in my traefik.toml I have defined a redirect of HTTP to HTTPS: 

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
```
`insecureSkipVerify = true` is already set and my backends are all HTTP only except for this unifi backend.

`-p 1900:1900/udo` I had caught this typo after posting here, thanks. 

**===>>> Result: works perfectly!** 
it must have been this which fixed it:
`--label traefik.protocol=https`

**The last remaining question is:** Does my port mapping vs exposing make sense? I mapped every port to the outside which seemed necessary and only used the reverse proxy HTTPS termination for the web gui.

Here is the last working run script:
```
docker run -d --init \
--name unifi \
--restart unless-stopped \
-p 1900:1900/udp \
-p 3478:3478/udp \
-p 8080:8080 \
-p 6789:6789 \
--expose 8443 \
-p 8843:8843 \
-p 8880:8880 \
-p 10001:10001/udp \
--expose 27117 \
-p 5656-5699:5656-5699 \
-e TZ='Europe/Berlin' \
-e RUNAS_UID0=false \
-v /home/ovi/docker/unifi/unifi-data:/unifi \
--label traefik.port=8443 \
--label traefik.frontend.rule=Host:wifi.mydomain.tld \
--label traefik.backend=unifi \
--label traefik.enable=true \
--label traefik.protocol=https \
jacobalberty/unifi:stable

```

**Comment by phroggster** [comment]
Not every port is necessary to expose depending on your environment. *Note particularly my edit above about exposing 27117*, but the others are all reasonable if you're actually using the features. If you're *not* using the features, then there's no reason to expose the ports.

Take the 5656-5699 ports for example. If your environment doesn't have any Edu access points installed with their built-in mics and speakers, then there's zero benefit of exposing these ports. Same with 1900/udp: if the controller isn't on the same layer 2 network segment as a device being controlled by it, then there's no need to allow it.

All you're doing is increasing your attack surface by exposing more features to the outside world, but I don't know what features you actually require in your environment.

**Comment by ovizii** [comment]
Thanks for all that help. I got all that. The 27117 was a no-brainer, no idea why I exposed it in the first place since unifi runs on the same container as the DB so not necessary.

Any other ports I can proxy with traefik or are all the other ports/services designed to be used as is and secure enough? 

I'm currently only using traefik this to have a proper HTTPS certificate for the webgui and to be able to use port 443.

**Comment by jacobalberty** [comment]
> I'm currently only using traefik this to have a proper HTTPS certificate for the webgui and to be able to use port 443.

just fyi you can modify the ports in the [system.properties](https://help.ubnt.com/hc/en-us/articles/205202580-UniFi-system-properties-File-Explanation#default%20ports) file (change your `-p 8443:8443` to `-p 443:443` and load [certificates into the docker image](https://github.com/jacobalberty/unifi-docker#certificate-support).

As an aside I use nginx+oauth2_proxy to put my unifi install (and a few other web services) behind my google authentication. As of the recent 5.9.x releases unifi doesn't play well with my reverse proxy anymore, I'm not sure if its something about oauth2_proxy or perhaps it uses something like websockets and they arent being properly proxied. But it looks like the newer betas will break at least some cases of reverse proxying, just something to be on the lookout for if you want to use a reverse proxy.

**Comment by ovizii** [comment]
@jacobalberty thanks, I know that I could manually load my certificates into the uinifi container but I recently discovered traefik and switched from using nginx. its got automated letsencrypt features which are hassle-free to setup and use.

Thanks for all the other pointers. I'm currently only using traefik with basic authentication but I think I read that they also support other authentication providers.

Thanks for all the support and the docker unifi image and the proper documentation which made it possible for me to run my own unifi controller in a few hours :-)
