### ISSUE TITLE
preference changes aren't saved

### ISSUE THREAD

**Issue by Jefronty** [jacobalberty/unifi-docker#151]
I don't know if it's an issue with the Unifi Controller itself, or the Docker image, since Docker is the only way I've used it.  In recent versions, the refresh button is not enabled by default.

![image](https://user-images.githubusercontent.com/4952737/45919043-b3a57080-be5d-11e8-9af4-f2b9e93c6c39.png)

It is easy enough to enable in the preferences, but each time I log in it is gone.  
I'd think because the button in preferences says "Save and Close" that preferences would be persistent.

![image](https://user-images.githubusercontent.com/4952737/45919071-329aa900-be5e-11e8-88e3-c416cff1d557.png)

If preferences are able to be saved it would be great if in future updates this is resolved.

**Comment by spparis91** [comment]
I'm also experiencing this issue even in 5.10.19, as the "dark theme", refresh button, and the "don't show me what's new" preferences aren't saved after i log out of the controller and back in. Any chance there's been a fix not posted here in this thread?

**Comment by x-jokay** [comment]
Using `5.10.21` this seems still to be an issue.

Even tried to reinstall from scratch with restoring configuration.

**Comment by x-jokay** [comment]
Can confirm it for `5.10.26`.

**Comment by ning42** [comment]
What are you running the docker on?
I've been running on QNAP, and I can't reproduce the error you describe.
Is it always or only when deploying a new version of the container - and then it is saved after-wards?

**Comment by x-jokay** [comment]
I run it on [RancherOS](https://github.com/rancher/os).

Always, even if the notification states "controller settings saved".

**Comment by x-jokay** [comment]
Recreated new container and restored backup, still not working.

**Comment by x-jokay** [comment]
Finally, using `5.11.39` it is able to really save the settings again 👍

**Comment by Jefronty** [comment]
By the behavior I think the preferences are saved to cookies.  I haven't updated my controller version for a while, but according to replies from @x-jokay and @ning42 it sounds like current controller version might be storing preferences to the host.

**Comment by x-jokay** [comment]
@Jefronty good point, as my cookies are cleaned on browser exit.
