### ISSUE TITLE
Unifi 5.9.29

### ISSUE THREAD

**Issue by jacobalberty** [jacobalberty/unifi-docker#154]
I am waiting for the [branch layout ](https://help.ubnt.com/hc/en-us/articles/360008240754#1) to be updated on ubiquiti's website before I push 5.9.29 into stable, for now if you want to try 5.9.29 stable, the stable candidate is the same and can be used by pulling jacobalberty/unifi:5.9.29-sc . As soon as the branch layout is updated I will push 5.9.29 to the appropriate branches and update the other releases to match the new layout.

**Comment by jacobalberty** [comment]
5.9.29 is now stable. 5.8.x phased out and 5.6.x left as lts as per the official unifi repos.

**Comment by bootc** [comment]
Hi Jacob - there still isn't a 5.9.29 tag in the Docker Hub. While we can certainly use `5.9` or `stable` it would be handy to be able to lock to a particular version.
