### ISSUE TITLE
IP displayed at Unifi Cloud Access

### ISSUE THREAD

**Issue by buckaroogeek** [jacobalberty/unifi-docker#159]
I have been using unifi-docker for quite some time with few if any issues not of my own making. Thank you for providing the Unifi controller as a docker container.

I have the controller registered with the Unifi Cloud Access, https://unifi.ubnt.com. The IP displayed at Unifi Cloud Access is 172.17.0.2 which almost certainly the docker container IP and not the IP for the fedora system hosting docker and this controller. Is there a setting I can use that will enable the controller to send the correct IP?

thanks

Brad

### Host operating system

Fedora 29 with docker-ce-0.0.0.20181128010312.f9756bf-0.fc29

### What tag are you using

Latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
Note that the :Z postfix on the volume mounts is for correct selinux configuration.

# version 3 - 
uUID=$(id -u)
uGID=$(id -g)
docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 6789:6789/tcp -p 10001:10001/udp -e TZ=America/Pacific -e RUNAS_UID0=false -e UNIFI_UID=$uUID -e UNIFI_GID=$uGID -v $PWD/unifi-vol:/unifi:Z -v $PWD/run:/var/run/unifi:Z --name unifi jacobalberty/unifi:latest

### What do you expect to happen?
Unifi Cloud Access displays the public IP for the controller not the docker IP.

### What actually happens?
Displays docker assigned IP - 172.17.0.2

**Comment by jacobalberty** [comment]
You're using the port forwarding configuration, so yes the ip that unifi knows will be the internal ip address. The best way to fix this is probably to use the macvlan driver (https://docs.docker.com/network/macvlan/ for details) http://collabnix.com/docker-17-06-swarm-mode-now-with-macvlan-support/  is the article I used for setting up my own macvlan setup, there may be newer articles on macvlan support that are more in depth. The one big caveat of using macvlan is the docker host can not  directly access containers running on the macvlan driver, this can be worked around but I can't find the link about it right now, I'm asking in the docker channel where it went I'll try to post the information when I find it.

**Comment by buckaroogeek** [comment]
Thank you. After I posted I found #103 which has a very similar problem and the same solution. I will take a look at macvlan.  In #103 another solution appears to be prepending the IP address for each port forward.  I really appreciate the guidance. Thanks

**Comment by buckaroogeek** [comment]
An update.

Short answer: macvlan is indeed a solution and solved a couple of vexing problems when needed to (re)adopt devices after changing the network subnet the devices are on or adding a USG to the system. Unifi Cloud Access now displays a routable IP on the ranch subnet instead of a private docker IP.

Longer answer: I run the Unifi Controller in Docker using this excellent implementation. Docker is running on my home workstation (fedora 29) at the moment. The steps taken below are set in this context - the unifi controller hosted in docker on a workstation on the same subnet as the USG, Unifi switches, and Access Points. I outline the steps below.

Ranch subnet: 192.168.110.1/24. DHCP in the USG is configured to issue ip addresses in the .110.50 to .110.200 range. I reserved the last 30 hosts in the range for use with the macvlans (yes there are 2).

1. Use macvlan support in Docker to create a network.
`docker network create -d macvlan -o parent=enp8s0  --subnet 192.168.110.0/24     --gateway 192.168.110.1 --ip-range 192.168.110.224/27 --aux-address 'host=192.168.110.225' unifinet'`
This creates the macvlan in the same subnet used for the unifi network here on the ranch. The `ip-range` tells Docker to use IPs in that subnet and the `--aux-address` tells Docker to not use that IP for reasons which will be clear in step 3 below.

2. Start the controller.
`uUID=$(id -u)
uGID=$(id -g)
docker run --rm --init --network unifinet --ip 192.168.110.226 -e TZ=America/Pacific -e RUNAS_UID0=false -e UNIFI_UID=$uUID -e UNIFI_GID=$uGID -v $PWD/unifi-vol
:/unifi:Z -v $PWD/run:/var/run/unifi:Z --name unifi jacobalberty/unifi:latest
`
Pretty much the same as in the initial post in this thread but using the macvlan created by Docker and setting an IP for docker to use for the controller. Otherwise Docker could assign any IP in the subnet which would not work for the controller.

At this point everything works, except that I cannot connect to the controller from the workstation that hosts Docker. This is a known characteristic of Docker macvlans. If Docker was running on a NAS device this would not be an issue but in my case, I use the workstation to access the controller web interface.

3. Set up a second macvlan to enable access to the controller from the workstation. I call this macvlan `unifinet-shim` and use the following linux network commands to set it up. All are executed with sudo.
`ip link add unifinet-shim link enp8s0 type macvlan  mode bridge
ip addr add 192.168.110.225/32 dev unifinet-shim
ip link set unifinet-shim up
ip route add 192.168.110.224/27 dev unifinet-shim
`
The first command creates the macvlan and adds it to the physical network device, enp8s0 (many other OSs use eth0). The second command defines an IP for the subnet (matches `--aux-address` in the Docker run above. The third command brings the macvlan up, and the fourth creates a route so that the workstation will direct all traffic for IPs in the docker subnet to the defined IP (192.168.110.225). 

That is basically it. The Unifi Cloud Access Portal now displays the IP passed to Docker for the controller. Adoption by the controller of devices (since the IP changed) when smoothly.

I will put all this in a simple bash script called unifi and in my ~/bin directory.

A key, indispensable reference was http://blog.oddbit.com/2018/03/12/using-docker-macvlan-networks/ which has a comprehensive discussion in you would like more information.

Hope this helps.
