### ISSUE TITLE
Container fails to launch in portainer due to missing --init 

### ISSUE THREAD

**Issue by nhendin** [jacobalberty/unifi-docker#164]
### Host operating system
Ubuntu 18.04 LTS

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
portainer with all options set the same as:

docker run -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -e RUNAS_UID0='false' -e TZ='US/Pacific' -v /opt/docker/unifi:/unifi --name unifi jacobalberty/unifi:stable
### What do you expect to happen?
container should start --- note that portainer does not support **--init**,as far as I can tell. Is there another entrypoint that can be used as a workaround?

![unif-portainer1](https://user-images.githubusercontent.com/3143787/51160855-b8df5e80-1844-11e9-81ca-4c595eed405e.png)

### What actually happens? Errors like this since portainer is guessing the wrong entry point.

[2019-01-15 05:17:06,684] <docker-entrypoint> Executing: 'unifi'
/usr/local/bin/docker-entrypoint.sh: line 183: exec: 'unifi': not found

Note the command / entry point setting in the screenshot attached. Portainer is trying the command "unifi" and /usr/local/bin/docker-entrypoint.sh  --- I think the container probably starts the unifi controller via a small version of init, or something?  

It's my first use of docker so perhaps I am missing something obvious.

**Comment by nhendin** [comment]
Hmm.  Hi! Thanks for the tip.  What should I set the entrypoint to as portainer is still unhappy.  I think Portainer tries to use the Docker API to do something similar -- but apparently not quite identical --- to "docker run"  running the docker command line works fine, but I can't get it to start within portainer.  I'll keep poking at it.

**Comment by jacobalberty** [comment]
Oh hmm now that is odd. It's supposed to call "/usr/local/bin/docker-entrypoin.sh unifi" on start,  unifi is checked for and if it's the first parameter it launches the controller, otherwise it executes whatever command you passed to allow you to enter the container via run,  try removing the quotes around unifi under "Command & logging".  The fact that it's quoted in 
`[2019-01-15 05:17:06,684] Executing: 'unifi'`

Indicates portainer is doing something funny with quotes.

**Comment by nhendin** [comment]
Tried that -- just now with the error message "Failure no command specified"

**Comment by nhendin** [comment]
Should the entrypoint be 
/usr/local/bin/docker-entrypoint.sh unifi
or 
/usr/local/bin/docker-entrypoint.sh
(with unifi specified on the "Command and Logging" line?

**Comment by jacobalberty** [comment]
I believe the second, just don't put quotes.

**Comment by nhendin** [comment]
I had to re-create the portainer setup from scratch --- for some reason the UI kept putting the quotes back --  I got farther --- the container comes up, but the controller service seems to be having trouble starting, when going to it's url, I just see "UniFi Controller is starting up..."  / "Please wait a moment"  For some time.  That may be me making a settings error in haste. I will check the settings more carefully.

Thanks!

**Comment by nhendin** [comment]
One more question: should the working directory be "/unifi" or "/var/run/unifi"  Right now it's set to /unifi
