### ISSUE TITLE
No data persistence / can't login after docker-compose down && docker-compose up

### ISSUE THREAD

**Issue by dukekautington3rd** [jacobalberty/unifi-docker#165]
### Host operating system

Description:    `Ubuntu 17.04`
Codename:       `zesty`

### What tag are you using

Example: `stable` || `5.9.29`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - vlan2
    restart: always
    volumes:
      - /datastore/unifi_mongodb:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
     vlan2:
      ipv4_address: 172.16.10.117
    restart: always
    links:
      - "mongo"
    volumes:
      - /datastore/unifi:/unifi
    environment:
      TZ: America/Chicago
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  data:
  log:
  cert:
  init:

networks:
  vlan2:
    external:
      name: vlan2`

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
After I `docker-compose down` && `docker-compose up`, I would expect to have all the data persist through /unifi/ being bound to a local volume and mongodb being bound to a local volume.  I'm sure that I just don't understand something about Unifi in this regard.  
Any time I destroy the container and bring it back up for any reason, 
I would expect to be able to login after `docker-compose up` and all my config has survived the destruction and rebuild of the container.

### What actually happens?
All login attempts fail after the container group being brought down / back up.
I have to delete the bound data directory (in my case `/datastore/unifi`). docker-compose up and re-run the wizard.  and reconfigure everything.

Additionally, I would expect that restoring a unifi config will restore full config and admin user creds

**Comment by phillijw** [comment]
This may or may not be related but I've been able to set this same thing set up and then weeks or months later (maybe after a reboot or something?), the entire mongodb is wiped clean. Almost every table is empty. No clue what's going on here.

**Comment by jacobalberty** [comment]
I'm not terribly familiar with doing the external mongodb but it looks like there's something going on where the mongodb container isn't persisting the data.

**Comment by lonkaut** [comment]
@phillijw one common thing, is that we've both deviated from @jacobalberty and configured TZ: America/Chicago and used an  external network I use a macvlan network.  Another point to mention is that I noticed (what looks to be) mongo data in the mounted directory for the controller at /unifi/data/db/ . don't know if that's normal or not.  I found it strange that I would find database info both in the controller container `/unifi/data/db/` and the mongo container via `/data/db` .  The files seem to be named similarly but different.  
![image](https://user-images.githubusercontent.com/33333503/51297974-44452500-19e8-11e9-9e22-fda839ed83f0.png)

**Comment by phillijw** [comment]
I have data in `/opt/unifi/data/data/db` as well. It seems that it WAS using that folder (incorrectly) and no longer is for some reason. I'm going to try copying that data to the new folder it's (properly using) and see if that brings everything back

**Comment by lonkaut** [comment]
After following post from "https://techreally.com/ubiquiti-controller-forgot-password/" to find my actual user information(connected to controller container via SSH tunnel), I realize that the mongodb on the controller container (not the mongodb container) actually has the data.  I still don't know why my data/configs didn't persist through tear down and rebuild since I mounted /unifi/data to host filesystem.

**Comment by lonkaut** [comment]
Gettting closer.  Noticed that even doing a` docker stop [container]` `docker start container` yields the same result "(not able to login)"  seems that local Mongod fails to run and startup
once I start manually with `mongod --dbpath /unifi/data/db --port 27117` the database starts and I can connect to it with Robo 3T but still cannot login to unifi server.

**Comment by acidprime** [comment]
I was able to fix this by simply not overriding the db_name. I just set them both to ace and ace_stat

**Comment by darkpixel** [comment]
I'm hitting this under Kubernetes.  Restarting the container causes all data to disappear even though the data appears to be saving to ```/unifi/data``` which is a persistent volume.

**Comment by darkpixel** [comment]
Stalebot probably shouldn't have closed this one.
