### ISSUE TITLE
Sudo and Wget command

### ISSUE THREAD

**Issue by trendman74** [jacobalberty/unifi-docker#176]
### Host operating system

Docker on DSM 6.2.1-23824 

### What tag are you using

5.10.17 stable

### What do you expect to happen?
On DSM, using /bin/bash to open a terminal on your image
Sudo and Wget are not available
Why ? And how ton obtain it ?

**Comment by regner** [comment]
Most docker images don't ship with utilities like that as you are generally not supposed to go into the running container and the goal is to keep them as small as possible.

This image is based on Ubuntu so you should be able to run `apt update` and then `apt install wget`.

**Comment by trendman74** [comment]
Thank's
It's okay
BR
