### ISSUE TITLE
Qnap problem

### ISSUE THREAD

**Issue by Libik2019** [jacobalberty/unifi-docker#182]
Hello, 

I tried install and run container for last version of Unifi. When I started container in Qnap NAS I see this error: https://cl.ly/c897436ea4bf
https://cl.ly/29a376e3ff26

My Qnap is TS-131P, firmware 4.3.6.0875.

Thanks for help

Libor

**Comment by jacobalberty** [comment]
It looks like your qnap is an arm system, you would need to use the arm32v7-beta tag. the 5.10.19 version is building on the hub now.

**Comment by Libik2019** [comment]
Hello,

yes, I can start container now but I see some error: https://cl.ly/3b3ab09e4bba <https://cl.ly/3b3ab09e4bba>   Is it ok?

Thanks


Best Regards


Libor Tušar

Tel.: +420 603 989 889
Email: libortusar@gmail.com
skype: libortusar
