### ISSUE TITLE
Need to restart container after updating certificates or run import-certs?

### ISSUE THREAD

**Issue by sofakng** [jacobalberty/unifi-docker#185]
I'm using certbot on my host system to generate (wildcard) certificates and the host system also renews them as needed.

When a certificate is renewed/updated, should I have the UniFi docker container restarted or can I execute import-certs inside the container to have them updated?

...or is there another/better method for updating them?

**Comment by jacobalberty** [comment]
I believe unifi itself requires a restart to recognize new certificates in the keystore, so you would need to restart the whole container.

**Comment by sofakng** [comment]
Thanks for the help!

**Comment by anthr76** [comment]
We're you able to get the certificates detected ? My web browser is still showing that UniFi is issuing a UniFi certificate after providing LE certs from linuxserver/letsencrypt

**Comment by nessor** [comment]
Do you use a reverse Proxy or how is your environment build?
