### ISSUE TITLE
Not detecting provided LE certificates

### ISSUE THREAD

**Issue by anthr76** [jacobalberty/unifi-docker#188]
### Host operating system

Example: `Arch Linux`

### What tag are you using

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker create --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/New_York' -e RUNAS_UID0='false' -v ~/unifi:/unifi -v /home/anthony/config/etc/letsencrypt/live/**OMITTED FOR PRIVACY**:/unifi/cert --name unifi jacobalberty/unifi:stable`

### What do you expect to happen?

Unifi to use my LE certificates instead of the self signed Unifi Cert.

I tried manually running 'import_cert' though I get no console output.

### What actually happens?

Unifi issues it's own cert instead of the provided LE certificates in /unifi/cert/

Docker/Unifi logs show no acknowledgement of the certificates

![Cert Issued](https://user-images.githubusercontent.com/25143877/55292306-fb7df500-53b6-11e9-826f-5a08abe1900c.png)

![Untitled](https://user-images.githubusercontent.com/25143877/55292318-3718bf00-53b7-11e9-94f6-1b4b6c8a4e08.png)

![Untitled 2](https://user-images.githubusercontent.com/25143877/55292328-57e11480-53b7-11e9-9c88-d3bff281bccc.png)

![Untitled](https://user-images.githubusercontent.com/25143877/55292339-734c1f80-53b7-11e9-940f-c84a42cbf851.png)

**Comment by jenscski** [comment]
If the files in /home/anthony/config/etc/letsencrypt/live/**OMITTED FOR PRIVACY** is symbolic links it won't work without also addind the original files.

You could look if this could help you; https://stackoverflow.com/a/40322275
