### ISSUE TITLE
Controller refuses connection after a few hours

### ISSUE THREAD

**Issue by OliS76** [jacobalberty/unifi-docker#198]
### Host operating system
Synology

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the 
docker run --ip <SOMELOCAL_IP> --network macvlan1 --init -p 8080:8080 -p 8443:8443 -p 8843:8843 -p 8880:8880 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Amsterdam"' -e BIND_PRIV='false' -e RUNAS_UID0='false' -v /volume1/docker/unifi:/unifi --name unifi -d jacobalberty/unifi:latest

Note that I am running via macvlan.

### What do you expect to happen?
Controller UI Available via https://SOMELOCAL_IP:8443 constantly.

### What actually happens?
The controller starts up perfctly and the UI is reachable as expected. After a few hours ( cannot find a deterministic scheme yet) the web site become unavailable (connection refused). The container is actually still running an I can open a bash in it. The log files contain no Information about an error.

I did not find a way to increase any log levels to further dig into this problem.
Any suggestions?

**Comment by jaronfitz** [comment]
I was having the same issue and its been stable since I changed the process of the logs container to tail -f /unifi/log/* instead of cat /unifi/log/*.   Of course that director is one single directory on my docker host mapped to both of the containers.

**Comment by OliS76** [comment]
> 
> 
> I was having the same issue and its been stable since I changed the process of the logs container to tail -f /unifi/log/* instead of cat /unifi/log/*. Of course that director is one single directory on my docker host mapped to both of the containers.

Not sure if I got this right? Which "logs container" do you refer to? I do only have one single container which is is running the unifi image.

**Comment by Matthewn7** [comment]
Also having this issue.

**Comment by jcanales** [comment]
Also having this issue is running for some time and then I get the connection refuse error
