### ISSUE TITLE
[Question] Why do you advise usage of clean up (--rm)?

### ISSUE THREAD

**Issue by Bccc1** [jacobalberty/unifi-docker#204]
It seems you and everyone using your container is using the clean up flag. Why is that? Only to regularly clean up tmp files? Or does the container run into problems when upgrading and the data is still there?

If `--rm` is necessary, how would you recommend to replicate the `--restart always` behaviour?

**Comment by jacobalberty** [comment]
--rm is in there for the example. It's up to your own individual setup whether you would run --rm. The only thing  I'm advising is the --init flag in that example. My own setup(s) that I run use docker-compose with restart: always.

**Comment by Bccc1** [comment]
Great. That's what I hoped.
