### ISSUE TITLE
Radius server

### ISSUE THREAD

**Issue by cbvictorio** [jacobalberty/unifi-docker#208]
### Host operating system

Ubuntu 18.04.2 x64 

### What tag are you using
latest (5.10.24)

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -d \
  --restart=unless-stopped \
  --net=host \
  --name=unifi_51024 \
  -e TZ='America/Tijuana' \
  -e RUNAS_UID0=false \
  -e UNIFI_UID=1001 \
  -e UNIFI_GID=1001 \
  -v /var/docks/unifi:/unifi \
  jacobalberty/unifi:latest

### What do you expect to happen?
I want to configure radius server

### What actually happens?
As soon as the user types username and password, it loads a few seconds and then an error message pops up saying "Network error connection"; i am a bit confused, i do not know if i have to map the ports used to radius server, which i think is 1812 and 1813 directly on my docker run command.

**Comment by kingfisher77** [comment]
This would be interesting for us too. We have linuxserver/unifi-controller but this Docker does not provide Radius Server. Does  jacobalberty/unifi-docker interates Freeradius in the Container?
