### ISSUE TITLE
Use tags in builds

### ISSUE THREAD

**Issue by jacobalberty** [jacobalberty/unifi-docker#21]
This is just to give a warning of the future, the current build system uses directories, docker hub supports using {sourceref} to create tags based on releases. I'd like to clean up the builds to use sourceref instead.

**Comment by jacobalberty** [comment]
The new dynamic tag names for docker hub is now active. I'll start tagging with each new release of unifi (at least within the 5.x series) Any requests for changes to the tags should go here. 

If there are still old versions of unifi sticking around in the repos I'm happy to pin the package and do a new tag with the pinned old package to let people use old versions just let me know.

**Comment by dalonso22893** [comment]
So what is the difference between Stable, latest, or just picking the last 5.x build?

**Comment by jacobalberty** [comment]
Stable, latest and the last 5.4.x build are all intentionally the same. Stable is the name ubiquiti uses for the latest stable release, which as of right now is the latest in the 5.4.x line, from what I understand this week it will become the latest in the 5.5.x line. 'latest' is a tag docker uses so when you do docker pull jacobalberty/unifi without a tag you get 'latest', the 5.4.x tags are intentionally tagged out for each individual release so if you have an issue that pops up in the newer release you can go back and pin yourself to an older release.

I am specifiying 5.4.x instead of 5.x because the one 5.5.x release was a beta release tagged out. I didnt tag the newer betas out because they are still in stable candidate and should be moving to stable soon superceding the old stable of 5.4.x. I believe 5.4.x will soon be 'lts'
