### ISSUE TITLE
set-inform command once on AP and not after every restart of the container

### ISSUE THREAD

**Issue by mschindl** [jacobalberty/unifi-docker#210]
### Host operating system

Ubuntu 18.04.2 LTS + Docker

### What tag are you using

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run \
--init  \
-d \
-p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \
-e UID=1000 \
-e GID=1000 \
-e TZ='Europe/Berlin' \
-v /DATAINT/Docker-Conf/unifi:/unifi \
--net bridge \
--restart unless-stopped \
--name unifi \
jacobalberty/unifi:stable

### What do you expect to happen?
set-inform command once and not after every restart of the container

### What actually happens?

I have to set after each container/server reboot following command on the access point:
AP-BZ.v4.0.42# set-inform http://10.1.1.1:8080/inform

**Comment by kbeflo** [comment]
Been experiencing this problem on controller/server and AP gets lost and doesn't get adopted again on reboots/power failures. 

Setup ssh keys on your controller or server and add them to SETTINGS>SITE>DEVICE AUTHENTICATION.

I setup a cron job to send set-inform command from the controller/server every 5 minutes to adopt multiple APs.

`crontab -e`

```bash
*/5 * * * * /usr/bin/ssh admin@192.168.1.3 '/usr/bin/mca-cli-op set-inform http://192.168.1.2:8080/inform' > /dev/null 2>&1

*/5 * * * * /usr/bin/ssh admin@192.168.1.4 '/usr/bin/mca-cli-op set-inform http://192.168.1.2:8080/inform' > /dev/null 2>&1
```

**Comment by mschindl** [comment]
Ok thank for the workaround.

Before I used the controller directly on Ubuntu and there were no issues like that.
It would be great to find the root cause of the issue

**Comment by sesshomaru86** [comment]
i have the same issue.Strangely after i had upgraded the controller to a different version the device that needed adoption after a power failure or a reboot, changed! Once there were all the 3 unifi devices (gateway/switch and AP) other times only the switch ..really weird behavior but yes it's quite annoying every time sshing into the device and adopting it.In the raspberry i was using before i hadn't the issue, maybe it's because i was using an older version. I can confirm anyway this behavior in ubuntu server.

**Comment by devdavidkarlsson** [comment]
could it be related to the db persistance problems in: https://github.com/jacobalberty/unifi-docker/issues/165#issuecomment-465359567

**Comment by FerronN** [comment]
I've set this up a described, but it doesn't work.
![image](https://user-images.githubusercontent.com/16306688/227480699-ebd52646-a4b7-4f5b-b1b1-a6131bd32472.png)

If I restart the AP or controller the connection is lost and not established until I manually execute the `set-inform` command again.
