### ISSUE TITLE
5.10.26 PKGURL is wrong & breaks build

### ISSUE THREAD

**Issue by EricReiche** [jacobalberty/unifi-docker#217]
The update in https://github.com/jacobalberty/unifi-docker/commit/361f8bc187f39222ef407a3b251d80e3f587f4af breaks the container, as 5.10.26 is only RC and the URL should be https://dl.ui.com/unifi/5.10.26-7fbb9ab8c4/unifi_sysvinit_all.deb

**Comment by jay-to-the-dee** [comment]
Can confirm this URL works and can build my own image from it successfully.

**Comment by jacobalberty** [comment]
Dont know how i missed this issue getting opened, yeah I'm not use to the new ubiquiti releases listing, I fixed it today when I noticed the builds broken and put it into rc instead.
