### ISSUE TITLE
"We do not support upgrading from 5.10.25."

### ISSUE THREAD

**Issue by ginkel** [jacobalberty/unifi-docker#219]
### Host operating system

Ubuntu 18.04

### What tag are you using

`5.10`

### What actually happens?

Currently, UniFi controller displays the following error page:

> We do not support upgrading from 5.10.25.

Ouroboros logs show that the container has been auto-updated just recently as a new image has been pushed:

```
2019-08-05 18:25:15 : INFO : dockerclient : unifi will be updated
```

Has the image available under the `5.10` tag been downgraded?

**Comment by nicx** [comment]
same here, container was auto updated via watchtower.

**Comment by nathanclayton** [comment]
Ditto. Looks like after the prior issue with the PKGSRC for 5.10.26 being wrong it was reverted to 5.10.24.

**Comment by dennisboris** [comment]
Had the same issue so i forced the version to 5.10.25 in the image tag for now until 5.10.26 is out again.

**Comment by nathanclayton** [comment]
I just created  PR #220 to fix this for the time being until 10.5.26 comes out.

**Comment by jay-to-the-dee** [comment]
Also just came across this :(

**Comment by jacobalberty** [comment]
That's weird, it should have only revered the 5.10.26 version, i'm not sure how that revert brought it all the way back to 5.10.24, pushing 5.10.25 now. Sorry for the downtime

**Comment by sofakng** [comment]
I have the same issue.  Do I need to update my docker with the 5.10.25 tag or what is the solution?

**Comment by jacobalberty** [comment]
@sofakng  you should just be able to pull the latest tag and it work now, the new build just finished 4 minutes ago

**Comment by sofakng** [comment]
@jacobalberty - I'm back up and running.  The latest build works great.  Thank you so much for your hard work on this container!

**Comment by jay-to-the-dee** [comment]
> That's weird, it should have only revered the 5.10.26 version, i'm not sure how that revert brought it all the way back to 5.10.24, pushing 5.10.25 now. Sorry for the downtime

That's alright, that's the power of open source to spot these things :)! Thanks for maintaining such a great container!
