### ISSUE TITLE
latest tag still downloading 5.10.25 (instead of 5.10.26)

### ISSUE THREAD

**Issue by rgogada** [jacobalberty/unifi-docker#221]
### Host operating system: synology 918+

Example: `Debian stretch` or `Open Media Vault 3`

### What tag are you using: latest

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5`

Note: A screenshot of your configuration page if using a gui is acceptable

**Comment by rgogada** [comment]
looks like it is fixed now. thanks.

**Comment by zorgzerg** [comment]
I comfirm this: latest tag still downloading 5.10.25 instead of 5.10.26. 
How to fix it?
