### ISSUE TITLE
add ARM64 docker image

### ISSUE THREAD

**Issue by vchrisb** [jacobalberty/unifi-docker#223]
### What do you expect to happen?

It would be great to have multi arch supported docker images which include arm64 support

### What actually happens?

only arm32v7 tags

**Comment by naphta** [comment]
I've done a little work my side to try and support this for myself. I've commented on the ARM support issue but just to give you a point in the right direction the comment is at:

https://github.com/jacobalberty/unifi-docker/issues/54#issuecomment-549434910

**Comment by jacobalberty** [comment]
This is now implemented in `multiarch`, `multiarch-5`, `beta` and `rc` via #360 and will be bubbling out to the rest of the builds as soon as we get a new stable 6.0.x
