### ISSUE TITLE
manifest for tag 5.9 missing in repository jacobalberty/unifi

### ISSUE THREAD

**Issue by runningman84** [jacobalberty/unifi-docker#227]
I use flux to deploy my kubernetes resources. I get this error message every minute:

ts=2019-09-03T12:48:11.458193761Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/jacobalberty/unifi auth={map[]} warn="manifest for tag 5.9 missing in repository jacobalberty/unifi" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"

Maybe you can add a manifest for the tag 5.9?

**Comment by bootc** [comment]
I'm also running into this. Either pushing a new valid manifest or deleting the tag would be helpful here. One of:

```sh
$ docker pull jacobalberty/unifi:5.9.29
$ docker tag jacobalberty/unifi:5.9.29 jacobalberty/unifi:5.9
$ docker push jacobalberty/unifi:5.9
```

Or just delete the tag from the Docker Hub web UI.

Currently the `5.9` tag is just broken:

```sh
$ docker pull jacobalberty/unifi:5.9
Error response from daemon: manifest for jacobalberty/unifi:5.9 not found: manifest unknown: manifest unknown
```

**Comment by jacobalberty** [comment]
If I remember correctly the 5.9 tag was deleted when Ubiquiti ended support for it which would have been some time ago as there hasnt been a release of 5.9 in over a year now and there won't be any more 5.9.x releases going forward. If you need 5.9 you're better off tagging directly to 5.9.29, the only older LTS release that should see continuing updates ( and in fact it looks like I forgot to update the README.md last time one was released) is 5.6.x for the EOL'd gen 2 stuff.

**Comment by jacobalberty** [comment]
Where are you seeing a `5.9` tag? I assume you mean on the docker hub but doing a search for 5.9 on https://hub.docker.com/r/jacobalberty/unifi/tags just gives me the four 5.9.29 tags and no `5.9`

**Comment by jacobalberty** [comment]
Well according to fluxcd/flux#2517 the docker ui wont show the corrupted  tags in the UI, I've pushed a temporary 5.9 I'll be deleting it shortly please let me know if the issue is still there.

**Comment by bootc** [comment]
Thanks, pushing the temporary 5.9 tag now allows Flux to work correctly.

**Comment by jacobalberty** [comment]
Ok, I deleted the temporary 5.9 tag, can you confirm Flux is still working correctly?
