### ISSUE TITLE
Change default ports

### ISSUE THREAD

**Issue by efiten** [jacobalberty/unifi-docker#228]
### Host operating system

Docker on PLESK

### What tag are you using

unifi:5.11.39-sc

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
I use the PLESK Docker environment to start this version.
![unifi](https://user-images.githubusercontent.com/11015082/64254610-074e8400-cf20-11e9-8735-43df295c801e.png)
It somehow auto-discovers the used ports, and even if I change the port in the file <unifi_base>/data/system.properties
it keeps on using the default ports in the left pane of the grapic view inside PLESK.

Is this adjustable ? is there a 'startup-file' where all these ports are listed?

**Comment by efiten** [comment]
I found exactly the same problem :
https://github.com/jacobalberty/unifi-docker/issues/106
isn't it possible to create an image with alternative ports that follows current build ? or make i configurable ?

**Comment by jacobalberty** [comment]
The ports are set at build time and aren't influenced by any of unifi's settings. you would need to simply change the ports in plesk to match your system.properties . You would need to see the plesk documentation for how to do that

**Comment by mniesiobedzki** [comment]
But when I changes ports today (before I saw your comment @jacobalberty ) in  system.properties, Web UI stopped working :/
