### ISSUE TITLE
5.11.39 tag missing from Docker Hub

### ISSUE THREAD

**Issue by jeroenj** [jacobalberty/unifi-docker#229]
It seems that `5.11.39` wans't pushed properly: https://hub.docker.com/r/jacobalberty/unifi/tags?page=1&name=5.11.39

Only a `5.11.39-arm32v7` and `5.11.39-sc` tag are available.

**Comment by jacobalberty** [comment]
the -sc tag should be exactly the same as the final just for future reference. I did push a proper 5.11.39 release tag to the hub this morning and it should be available on the hub as of a few hours ago.

**Comment by jacobalberty** [comment]
ps Thank you for bringing it to my attention

**Comment by jeroenj** [comment]
Great. Thanks! I indeed expected it to be the same but OCD me noticed it. 😜
