### ISSUE TITLE
ENV PKGURL missing for docker container

### ISSUE THREAD

**Issue by vMarkus** [jacobalberty/unifi-docker#238]
On first start error message:
"please pass PKGURL as an environment variable"

PKGURL environment variable is not set for docker image.

Added PKGURL with url to v5.11.46 .deb file solved the issue, it was included in v5.11.39, I had to add it manually to the container. 

Running fine now, love the new small image footprint of just 67MB instead of 748MB - nice job!

**Comment by billimek** [comment]
Seeing the same issue here, @jacobalberty 

The container won't start properly now in tag `5.11.46`,

```shell
➜ mkdir -p unifi/data; mkdir -p unifi/log

➜ docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v $PWD/unifi:/unifi --name unifi jacobalberty/unifi:5.11.46
please pass PKGURL as an environment variable
/usr/local/bin/docker-entrypoint.sh: line 136: cd: /usr/lib/unifi: No such file or directory
[2019-09-17 20:13:00,505] <docker-entrypoint> Starting unifi controller service.
[2019-09-17 20:13:00,507] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
/usr/local/bin/docker-entrypoint.sh: line 155: java: command not found
[2019-09-17 20:13:00,510] <docker-entrypoint> WARN: unifi service process ended without being signaled? Check for errors in /unifi/log.
```

**Comment by jacobalberty** [comment]
Somehow the 5.11.46 tag got done off of  the `beta` branch instead of `master` I have pushed a new 5.11.46 tag to the hub and it is building now
