### ISSUE TITLE
5.11.46 for container station arm32

### ISSUE THREAD

**Issue by Zaiman1906** [jacobalberty/unifi-docker#239]
I would like to have the new controller version 5.11.46 in the container station for arm32-version. "Latest" is not working on my system (QNAP TS-431P)

**Comment by nicedevil007** [comment]
Also I would like to know if you will release a 5.12.xx release for arm32?

**Comment by jacobalberty** [comment]
Yes I will be once it's out of rc.  I don't tag out the release candidates
on arm at this time but once they're in stable I will tag the stables out
on arm

**Comment by nicedevil007** [comment]
Thank you <3
