### ISSUE TITLE
Custom SSLS certificate on Synology hosted Controller

### ISSUE THREAD

**Issue by rwoldberg** [jacobalberty/unifi-docker#249]
I am trying to install a custom ssl cert that I purchased from ssls.com to the unifi controller that is running on my synology nas. I have imported the cert in to the nas and it works perfectly.  When I try to install the cert following the instructions the controller is becomes unresponsive, even when I delete the mount path the controller still remains unresponsive.  Any help would be appreciated.

**Comment by jacobalberty** [comment]
I'd need to see something about your configuration and some data from the logfiles. You should be able to get unifi working again by removing the data/keystore file and leaving the cert folder empty. show me the ouput of `openssl x509 -in cert.pem -noout -text` 


You can leave out the long chain of numbers for modulus and the long chain of numbers after the signature algorithm, but please include the signature algorithm. Your output should look like this

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:bf:26:b6:dd:cb:3c:01:52:fe:e1:e3:b0:7f:3c:62:1d:c2
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Oct 19 17:41:57 2017 GMT
            Not After : Jan 17 17:41:57 2018 GMT
        Subject: CN = unifi.lan.avsbr.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                20:0F:CC:91:B9:9A:73:17:DC:6B:7E:B5:36:03:49:30:F4:7C:10:C8
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:unifi.lan.avsbr.com
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
                  User Notice:
                    Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

    Signature Algorithm: sha256WithRSAEncryption
```

If for some reason you see anything about private key in the output of that command, do not paste it here you're either reading the wrong file or the other container is misconfigured and putting the wrong file in the wrong location.

**Comment by rwoldberg** [comment]
I am not sure how to get to data\keystore I dont see any such folder in the file station.

Here is the output from the cert.pem:
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            d4:51:aa:7c:33:f9:65:e1:80:2e:01:50:8b:95:0d:da
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA
        Validity
            Not Before: Oct 22 00:00:00 2019 GMT
            Not After : Oct 21 23:59:59 2020 GMT
        Subject: OU=Domain Control Validated, OU=PositiveSSL, CN=x.x.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:...:5b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1

            X509v3 Subject Key Identifier: 
                73:3D:CE:EE:28:17:74:D5:EC:21:80:69:A1:FC:89:FB:CF:3C:56:B9
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Certificate Policies: 
                Policy: 1.3.6.1.4.1.6449.1.2.2.7
                  CPS: https://sectigo.com/CPS
                Policy: 2.23.140.1.2.1

            Authority Information Access: 
                CA Issuers - URI:http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt
                OCSP - URI:http://ocsp.sectigo.com

            X509v3 Subject Alternative Name: 
                DNS:x.x, DNS:www.x.x.com
            1.3.6.1.4.1.11129.2.4.2: 
                ......v...\..}h.....#....W|W..j..a:.i......m.........G0E. =-5...D;......!.
ez..\....
MJF.:.!........4}v... .bX.ts*Q........e..w.^.s..V...6H}.I.2z.........u..qEX...m...~.....H0F.!..S*q.D...-.h6,.`e]I./.O..d...hb..!...-<..w.....h.]Q-.............h.
    Signature Algorithm: sha256WithRSAEncryption
         18:...:a9

**Comment by rwoldberg** [comment]
The logs show "No Aliases for private keys found in key store".  So something wrong with the private key.

**Comment by rwoldberg** [comment]
Does the private key need to be encrypted with a specific password?

**Comment by jacobalberty** [comment]
Private key should be unencrypted, there's a password used on keystore but its a default set by ubiquiti (aircontrolenterprise)

**Comment by rwoldberg** [comment]
Could you post an example of what the private key pem file needs to look like?  Obviously without the actual key.  I have tried several different ways but nothing seems to work.

**Comment by jacobalberty** [comment]
````
-----BEGIN RSA PRIVATE KEY-----
<encoded key here>
-----END RSA PRIVATE KEY-----
```

**Comment by rwoldberg** [comment]
I got it figured out.  I was making it way too complicated.  The files provided by ssls.com are PEM files, they just needed to be renamed from key, and cert, and the ca-bundle is the chain file that is needed.  I was trying to import them all in to a pfx file then export them to PEM files, that was not needed.  Thanks for your help.
