### ISSUE TITLE
Build fails due to openjdk-8-jre-headless breaks ca-certificates-java

### ISSUE THREAD

**Issue by wojo** [jacobalberty/unifi-docker#25]
Looks like this is a recent problem on Jessie with openjdk-8-jre-headless: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851667

**Comment by jacobalberty** [comment]
Looks like  the long term solution is to wait for the debian maintainer to fix it, if 5.4.11 beats a fix from debian out then i'll switch over to openjdk:8-jdk for a bit, build is also broken broken because they pulled 5.4.9 packages for some reason.

**Comment by jacobalberty** [comment]
Looks like 5.4.9 is no longer considered a stable release https://community.ubnt.com/t5/UniFi-Wireless/5-4-9-broke-a-lot-of-older-ap-s/td-p/1822772

**Comment by wojo** [comment]
Indeed they pulled it and the reason is unclear (RADIUS profiles, perhaps bricking older devices, etc). I guess we have to play the waiting game for now, but perhaps the -latest should be reverted back to 5.3.11?

**Comment by jacobalberty** [comment]
Yeah working on reverting it, the problem is theres no working build options for a debian base image atm, its gonna grow at least 300mb to use the openjdk bases

**Comment by jacobalberty** [comment]
I'm rebuilding with debian:jessie using the same fix as the openjdk images (see https://github.com/docker-library/openjdk/issues/19#issuecomment-70546872 )

**Comment by jacobalberty** [comment]
Seems there's not an older package available, found the working ca-certificates-java in jessie-backports and installed from there. Uploading new build of 5.3.11 now and I'll tag out the 5.4.11 stable candidate soon to build.
