### ISSUE TITLE
Synology Lets encrypt cert automated import

### ISSUE THREAD

**Issue by stembus** [jacobalberty/unifi-docker#250]
Hello,

is there a way how to import existing and properly working lets encrypt cert from synology host into container/Unifi-Controller?

I know there is a guideline how to import certs by mounting host folder to container folder, but Iwonder how to do this on synology where every 3 months after cert automatic renewal folder name where cert is stored change.

_@NAS:~$ ls -la /usr/syno/etc/certificate/_archive/
total 28
drwx------ 4 root root 4096 Oct 17 21:23 .
drwxr-xr-x 5 root root 4096 May 16  2017 ..
-rw------- 1 root root    7 May 16  2017 DEFAULT
drwx------ 2 root root 4096 Jun 23 23:44 G2MOnW  <-------- previous cert folder
-rw------- 1 root root 1485 Oct 17 21:23 INFO
-rw-r--r-- 1 root root   17 May 16  2017 .syno-ca-cert.srl
drwx------ 2 root root 4096 Sep  2 13:44 XTrIHn  <-------- last cert folder_

Thanks a lot for any advise that can make my life easier every 3 months! :)

**Comment by stembus** [comment]
@jacobalberty dont you have any advicefor me? or do you need any further information so you could support me then?

I am wondering if I do something wrong but ... I would appreciate any advice...

Thanks a lot
J

**Comment by jacobalberty** [comment]
@stembus  I don't personally have a synology device. It looks like you could make a shell script to copy the certificates to where you need them by using the contents of `/usr/syno/etc/certificate/_archive/DEFAULT` to get the current folder

**Comment by stembus** [comment]
@jacobalberty - hmmm, thanks for this "hint" :) Its done, works perfectly :)

**Comment by extric99** [comment]
If someone needs a step by step guide i posted some instructions in this thread
https://community.ui.com/questions/SSL-Certificate-from-Synology-NAS/8fc06b0d-10d9-4805-93c7-e96018c454a7#answer/deff2a4e-68e1-4c61-86ca-ebdea47c239f

**Comment by jimueller** [comment]
@extric99  It looks like the difference between your script and the original author's is

```
rm -f /volume1/docker/Unifi/data/keystore
```
Would you help me understand what happens if the keystore is not deleted?  Is it that the original script wouldn't clean up the expired certificates and just grow larger?  Or is this solving some other issue?

**Comment by extric99** [comment]
The autor of the website made some updates based on feedback i posted. Initially
there were some other. For me the keytool command would prompt me to overwrite i believe without the rm step. This meant i could not fully automate. Maybe there is an argument available for keytool but i didnt find it.
