### ISSUE TITLE
Docker Swarm deployment issue on Raspberry Pi 3 (incompatible architecture)

### ISSUE THREAD

**Issue by hamtaai** [jacobalberty/unifi-docker#252]
### Host operating system

Raspbian Buster Lite on a Raspberry Pi 3. 

### What tag are you using

`5.11.50-arm32v7`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker stack deploy`

### What do you expect to happen?

The unifi controller being deployed to swarm.

### What actually happens?

Swarm errors out with the following: `no suitable node (unsupported platform on 1 node)`.

### Additional info

When inspecting the image, or using `docker run --rm mplatform/mquery jacobalberty/unifi:5.11.50-arm32v7` arch/support list and the docker hub list show "amd64", not "arm".

**Comment by jacobalberty** [comment]
This has to do with how the arm images are built. I'm not sure what the correct solution is. I built the arm images using qemu-user-static. Since they're built on an amd64 host the hub tags them amd64. It's been a few months since I last looked at the issue and decided there wasn't a good solution yet. I'll take a look again this week and see if its solvable yet.

**Comment by hamtaai** [comment]
A saw some guides that are about building multiarch images on travis while looking into solving this, so there might be a good solution out there, but for simplicity, I just cloned this repo to my Pi and re-built the image like that. It works good enough for my use case.. ¯\\_(ツ)_/¯

**Comment by jmb12686** [comment]
@jacobalberty , thanks for your continued support of this project.  With regard to ARM and multiarchitecture based images, publishing a manifest and building via `docker buildx` is the best path forward.  I do this with a number of my public repos, some using Docker Hub automated builds and some using Github Actions.  To be honest, GitHub Actions is the most flexible / clean way to produce multiarch images, but I do have an example repository here where you can view my `hooks` directory and scripts to build on Docker Hub:
https://hub.docker.com/repository/docker/jmb12686/go-loadtest-api

https://github.com/jmb12686/go-loadtest-api/tree/master/hooks


Using GitHub Actions is pretty straightforward, and you can nearly just copy/paste my `.github/workflows` yml files with couple minor tweaks.  Some example repos:
https://github.com/jmb12686/docker-kibana
https://github.com/jmb12686/docker-filebeat
https://github.com/jmb12686/docker-elasticsearch
https://github.com/jmb12686/docker-cadvisor
https://github.com/jmb12686/docker-socat

**Comment by wurmr** [comment]
Until this is fixed you can work around this by adding `--resolve-image=never` to your stack deploy if you want. It will skip that step, but be careful because it will skip that step for every image in your stack.

Something like this:
```
$ docker stack deploy --resolve-image=never -c ./docker-compose.unifi.yml unifi
```

**Comment by jacobalberty** [comment]
This is properly fixed now in the `multiarch` and `multiarch-5` tags. Once we get a new stable unifi 6  (> 6.0.23) out of ubiquiti on https://www.ui.com/download/unifi/ those changes will bubble fully out to the rest of the branches, and all future version tags going forward.
