### ISSUE TITLE
Unifi devices disconnected with Docker controller

### ISSUE THREAD

**Issue by gjs1969** [jacobalberty/unifi-docker#255]
### Host operating system

Synology / Docker

### What tag are you using

Stable

Using the latest controller en Synology OS en Docker version. My configuration and controller work just fine for a few weeks. After that, the controlleer keeps reporting random losses on device connections. The network is functioning normally.  After restarting Docker / Unifi or only Unifi container it is fine again for a couple of weeks. Then it starts all over again. Very annoying.
My Diskstation is a DS916+ with 8 GB, no performance issues at the moment of the issues.

Any suggestions on this ? more people having this issue ?

**Comment by jacobalberty** [comment]
I believe this is a duplicade of #196  I have not been able to reproduce it as of yet. Are you using a remote controller or is the controller local? if local please include your configuration, either docker-compose.yml or the startup line

**Comment by gjs1969** [comment]
Thank you for your reaction

I have a local controller, but also it is managing a remote site, so i guess it is both. The thing is that i do receive disconnects from the local devices. I must say that i have been running the docker container for a few years now as a local only controller. Since a few months i added the remote site, did not have problems for about a month with this, but then it started.  So maybe it is related ?

The startup-line, do you mean : /usr/local/bin/docker-entrypoint.sh unifi  ?

docker-compose.yml i have to look for, i cannot reach that right now. I suppose it is also in /usr/local/bin/ somwhere

**Comment by jacobalberty** [comment]
I missed that you were on synology, you wont have a docker-compose.yml or a startup line. Can you screenshot the configuration page for your unifi container and post it here?

**Comment by gjs1969** [comment]
[Unifi-container1.zip](https://github.com/jacobalberty/unifi-docker/files/3878384/Unifi-container1.zip)

**Comment by gjs1969** [comment]
Any further suggestions ?

**Comment by alexanderharm** [comment]
I have exactly the same issue. Switching to <https://hub.docker.com/r/goofball222/unifi> solved it for us. Not a single disconnect since then. However, we only experienced disconnects from remote sites. On-site it always worked fine. See also #196

**Comment by gjs1969** [comment]
Well, as for there are no other suggestions mentioned after the delivered info, it might be the best solution indeed to make a switch.. thanks alexanderharm
