### ISSUE TITLE
Docker container Unifi-Controller stopped unexpectedly

### ISSUE THREAD

**Issue by sharepointmike** [jacobalberty/unifi-docker#256]
When I start my Unify controller in docker on my Synology 418play immediately this happens: Docker container Unifi-Controller stopped unexpectedly.

I am using the 5.12.22 version. Any idea?

**Comment by lister86** [comment]
I have a similar problem but mine was related to the port 8080 already in use. Maybe you have an application using one of the ports it's trying to bind on the host?

**Comment by pgwilliams** [comment]
Ah!  Thank you so much.   Yes I had my audio station running on 8080.    I bumped the port number in ./docker/Unifi/data/system.properties to 8085 and it's running fine now (initially tried 8081 but have video station running there, doh!).     Would have been helpful if an error had appeared in the log file before it crashed.
