### ISSUE TITLE
unifi controller 15.12.42

### ISSUE THREAD

**Issue by rizlah** [jacobalberty/unifi-docker#260]
I am using the Container station on QNAP and have just downloaded your latest unifi controller container (15.12.35).

I would like to upgrade this controller to the latest beta build which is 15.12.42 and also be in a position to upgrade whenever a new version is released by Ubiquiti

I have tried to SSH to the controller and use the documented method to do this (using the wget <controller url> then installing from there.

This does not appear to be working as the wget command is not available in the container that you have made.
- Is there another way to do this upgrade?
- Do you provide containers with the beta versions?

If there is no easy way to do this I may end up just sticking with the stable releases, assuming that you do create new containers with each stable release?
- On that topic, how soon after the stable versions are released do you publish the new containers?

Sorry for all the questions, I am pretty new to both the unifi equipment and relatively new to using containers as well.

Cheers

**Comment by nicedevil007** [comment]
try to apt update && apt install wget -y inside the container before doing the download of the *deb file.
