### ISSUE TITLE
Find Icon feature for clients does not work

### ISSUE THREAD

**Issue by gamertyke** [jacobalberty/unifi-docker#262]
### Host operating system

Synology

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

defaults

### What do you expect to happen?
A screen should pop up that allows the user to search for a picture for their client devices

### What actually happens?
Error: 
Failed to load
Some data requirements failed to load. Please try again later.

**Comment by dannytsang** [comment]
Are you able to provide the error message or erro log?

**Comment by gamertyke** [comment]
I ended up switching to the LinuxServer image. Sorry to not be of help.

**Comment by MayeulC** [comment]
Hello, I just set up the unifi controller using your docker image, thanks a lot for maintaining it!

I also ran into that issue. Running the following command inside the docker before restarting it fixed it for me:
```
update-ca-certificates -f
```

Error message was as described above. Opening the browser console, I could see a 404 being returned for `https://[ip]:8443/v2/api/fingerprint_devices/0/` with the answer:
```
{"errorCode":404,"message":"Device list could not be found for folder"}
```

This is not a one-off issue with the Unifi controller, it seems:
* https://community.ui.com/questions/UniFi-Controller-Linux/a384c6f8-9a42-4a94-9de0-80c6bfb58a26
* https://community.ui.com/questions/Device-Fingerprint-Feature-information/695b50b5-b2c7-49ac-9537-2356df1da6b9
* https://www.reddit.com/r/Ubiquiti/comments/fpsdg8/problem_with_find_icon/

Incidentally, I am running pihole, but couldn't see any blocked request and could `curl https://static.ubnt.com/fingerprint/0/1671_257x257.png` without issue, so the SSL cert is likely used for something else.

**Comment by mdhom** [comment]
I have got the same problem (Failed to load, Some data requirements failed to load. Please try again later.), here is the log from the server.log file:
```
[2020-11-24T09:33:05,040] <webapi-3794> ERROR api    - fetch fingerprint resources failed: 
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://static.ubnt.com/fingerprint/1/devicelist.json":
 java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: 
the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: java.lang.RuntimeException: 
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
