### ISSUE TITLE
Wy not 5.12.35 after update?

### ISSUE THREAD

**Issue by maestroat** [jacobalberty/unifi-docker#263]
### Host operating system
Synology DS
Example: `Debian stretch` or `Open Media Vault 3`

### What tag are you using

Example: `latest`

hi have done was on this side is:
http://www.bu4.eu/unifi-controller-und-synology-nas-das-docker-dream-team/
download latest version. stop controller, delete files, start controller, restore from backup.
version 5.11.50 again :(

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5`

Note: A screenshot of your configuration page if using a gui is acceptable

**Comment by telenieko** [comment]
The README states that the repository tag is unifi:latest or unifi:stable (among other options. The unifi:unifi5 you wrote in the example does not currently exist on the repository.

So, you command should read `jacobalberty/unifi:stable` where it now says `jacobalberty/unifi:unifi5`
