### ISSUE TITLE
Adoption not working (loop between adopting/pending/adopted) UAP-AC v2

### ISSUE THREAD

**Issue by JHurk** [jacobalberty/unifi-docker#266]
### Host operating system

DSM 6 - docker container

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Sorry, do not know where to get the logs. I used the settings as told in dockerhub.

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
I want to add another AP (UAP-AC an old square one) to my existing setup.
I expect the AP to be added to my devices when I press (of command over ssh) Adopt.

### What actually happens?
The AP gets discovered and I can ssh to it. I can sent the inform command and I can click the Adopt button in the controller. After a few seconds I get a message that the device is adopted, but 2 seconds later it is discovered again. It will not show up on my device list, and stays in the client list.

I have followed all manual around, from using the IOS-app, to the Chrome-extention to SSH, but nothin seems to work.

The device is upgraded to the latest firmware; 3.8.17.6789, the controller is on the latest docker build.

I have on AC-pro connected to the controller, it has been connected for almost a year now. This was added in the same environment (but a lesser version of the controller of course).

**Comment by hayozsoft** [comment]
I'm having the same issue as described by @JHurk  with a Security Gateway.

I will try to use an older Version today.

**Comment by hayozsoft** [comment]
Have you tried to set the "inform-url" on the device you want to adopt properly?
I had the same issue because i had an unmanaged switch between the gateway and the controller, so the gateway did not know where to reply the adoption-inform-message to.

So in my case not a Docker-Related problem!

**Comment by JHurk** [comment]
Thanks for the suggestion. 
I have tried all options I could find. 
Tried in Chrome
Tried in iOS app
Tried with SSH
Tried with Mac App (UniFi Discover)

All have the same result; I can ping/ssh the AP and the AP gets discovered.

Chrome;
I can click the Adopt button, after a few seconds I see a message that the AP is adopted, but 2-3 seconds later the AP shows up again as a device waiting for adoption. 

Mac App
I can set the inform URL in the manage tab (I tried the local ip, I tried unifi:8080, I tried my ddns, etc.). As soon as I click the button to set inform the status of the AP in the Mac App changes to Adopting. After minutes the status changes to pending again. 

iOS app
I can see the AP as a device when I click it to adopt I see it is trying to adopt the AP. After 30 seconds I get a message that I need to check if the AP is in default factory settings and if the controller is reachable. Both things are the case. 

SSH
I can ssh and check the info of the device. I can give the set-inform command and after that I see a list with three items;
1. Go to the controller and adopt the AP
2. Go back to ssh to give the set-inform command for a second time
3. After that the set-inform command will be given after each startup. 
And the prompt is given again. When I go to the controller there is no where (other then the normal adopting proces via Chrome) where I can adopt the AP.
I tried the following order;
1. SSH set-inform
2. Chrome adopt
3. SSH set-inform again
This did not do anything other then described in the separate steps above (chrome results in adopted message but after second the device is discovered again, and SSH set-inform keeps giving the list)

**Comment by JHurk** [comment]
I just downgraded the firmware of the device (UAP-AC) to 3.8.3.
Maybe the firmware was newer than then version of the controller?
No luck, still the same problems. So really looks like a controller or environment/network issue.

**Comment by JHurk** [comment]
Just did a little extra searching, specifically on the UAP-AC v2 not adopting.
The generation 1 devices (UAP-AC v2) are end-of-life and no longer supported and thus no longer able to be adopted when the controller firmware is version 5.6 or lower.
Possible solution is downgrading the controller firmware (which will be set to default so restoring from backup is not possible). After downgrading the firmware you can adopt the UAP-AC v2. As soon as it is adopted you can upgrade the controller firmware, after which you can not make any changes anymore to the UAP-AC v2.

Found answer in multiple posts, all similar to this:
https://community.ui.com/questions/UniFi-Controller-not-discovering-UniFi-AP-AC-v2/6e7365dc-9f96-4213-8c64-146929e382c6

Sorry for posting this as a bug on the docker version of the controller. Thanks for supplying and maintaining the container.
