### ISSUE TITLE
How to connect to the UniFi Controller from outside the network using synology QuickConnect

### ISSUE THREAD

**Issue by cognociente** [jacobalberty/unifi-docker#267]
Synology NAS 218+
Working UniFi Controller inside Docker that can be accessed locally.
I can connect to the NAS interface from a remote location using QuickConnect (synology technology)
I cannot figure out how to access the UniFi Controller page when I am remote
(when I am local I just use/append the port 8443 and all works fine)

**Comment by jpg1961** [comment]
Hi, 
By configuring a reverse proxy in DSM application portal, you should be able to get to your local docker instance from Internet.
I'm using it  on a synology DS918+ and it works fine for me. 
(I don't use quickconnect though). 
Rgds,
