### ISSUE TITLE
Enable HTTP only mode (disable HTTPS redirect)

### ISSUE THREAD

**Issue by Anonymouslemming** [jacobalberty/unifi-docker#268]
### Host operating system
Kubernetes 1.16 on Ubuntu 18.04 worker nodes

### What tag are you using
stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

https://github.com/helm/charts/tree/master/stable/unifi

### What do you expect to happen?

I expect to be able to connect to Unifi webUI in browser

### What actually happens?
I get a message in the browser saying
```
Bad Request
This combination of host and port requires TLS.
```

I believe what is happening is that even though I'm running TLS on my ingress and using https in my browser, the k8s ingress (nginx) is talking http to the connected service in the cluster. 

To confirm this, I want to be able to run the controller on http. However, I get conflicting information from https://github.com/jacobalberty/unifi-docker/blob/master/README.md 
At one point in this doc it states that 8080 is the http port:
```
UNIFI_HTTP_PORT
Default: 8080
```

Later in the doc though, this looks like the controller port:
```
8080/tcp - Device command/control
```

My questions are:

1. How do I force HTTP and disable HTTPS redirect
2. Which port is correct in the README

Thanks,

**Comment by addisaden** [comment]
Is it possible by the Unifi-Software?

In this thread it says no: https://community.ui.com/questions/Controller-how-to-deactivate-http-to-https/c5e247d8-b5b9-4c84-a3bb-28a90fd65668

**Comment by Anonymouslemming** [comment]
It looks like there's an option in the helm chart to add annotations to force the backend to https

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol
