### ISSUE TITLE
Problem with Mongodb running in container

### ISSUE THREAD

**Issue by floppydrive** [jacobalberty/unifi-docker#269]
### Host operating system
Ubuntu 18.04 on ARM odroid N2 hardware

### What tag are you using

`stable` and 'beta

### What complete docker command or docker-compose.yml do you use to launch the container 
sudo docker run -d --init --restart=unless-stopped --name=unifi-controller --volume=/home/odroid/docker/unifi/ --net=host -p 8080:8080/tcp -p 8081:8081/tcp -p 8443:8443/tcp -p 8843:8843/tcp -p 8880:8880/tcp -p 8883:8883/
tcp -p 3478:3478/udp jacobalberty/unifi:arm32v7

### What do you expect to happen?
Can access over odroid:8443 webinterface
### What actually happens?
Webinterface not accessible. When consoling in into running docker container, find this in the mongo logs in container:
2020-01-01T14:19:53.778+0000 ***** SERVER RESTARTED *****
2020-01-01T14:19:53.782+0000 SEVERE: Invalid access at address: 0x484eb4b
2020-01-01T14:19:53.785+0000 SEVERE: Got signal: 7 (Bus error).
Backtrace:0x7639be 0x762f6e 0x76300a 0xf68a7270 0x42bbf6 0x42cf24 0x763c72 0x1c4f80 0xf68988aa
 bin/mongod(_ZN5mongo15printStackTraceERSo+0x25) [0x7639be]
 bin/mongod() [0x762f6e]
 bin/mongod() [0x76300a]
 /lib/arm-linux-gnueabihf/libc.so.6(+0x25270) [0xf68a7270]
 bin/mongod(_ZN5mongo12BsonUnitTest10testboundsEv+0x71) [0x42b^C

**Comment by devdavidkarlsson** [comment]
where is the mongo container?

**Comment by floppydrive** [comment]
It's working now. Thanks. Instead of starting everything manual I now modified the docker-compose to startup the arm container of unifi. After that I see now the webinterface. 
Thanks :)
