### ISSUE TITLE
5.5.6 unstable container

### ISSUE THREAD

**Issue by fflo** [jacobalberty/unifi-docker#27]
Jacob,

can you please provide a docker container for the current "unstable" version 5.5.6?
[https://www.ubnt.com/downloads/unifi/5.5.6-b559495f0c/unifi_sysvinit_all.deb](https://www.ubnt.com/downloads/unifi/5.5.6-b559495f0c/unifi_sysvinit_all.deb)

According to ubnt support it should fix some issues which are not going to be fixed for the 5.4. branch.

**Comment by jacobalberty** [comment]
There's no technical reason it can't be done, its easy enough to just change PKGURL in the dockerfile, though the url to use is https://dl.ubnt.com/unifi/5.5.6-b559495f0c/unifi_sysvinit_all.deb my only concern with it is annoying ubiquiti too much by pushing it someplace you can just pull it without signing up for beta access. they're trying to structure beta to get more bug reports directly.

**Comment by jacobalberty** [comment]
check out the 5.5.7 and unstable tags
