### ISSUE TITLE
Adopting Devices not Ending

### ISSUE THREAD

**Issue by floppydrive** [jacobalberty/unifi-docker#270]
### Host operating system

Ubuntu 18.04

### What tag are you using
stable arm 

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
Used docker compose file to "sudo docker-compose up"

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
Unifi Controller runs and visualizes devices as adopted.

### What actually happens?
After using my backup from my Windows unifi controller instances to restore on the docker unifi controller I can log in. When I log in I see my configuration etc but all devices have a greyed out botton saying Adopt. Also there is some connected/disconnected fluctuation. When I start again my Windows Unifi Controller instances, everything looks normal.

**Comment by PelagicDev** [comment]
Can you post a screenshot of what this looks like on your Ubuntu controller?

**Comment by MarkusLoyen** [comment]
I have the same problem:

**Host operating system**
Debian 10 (Buster)

**What tag are you using**
latest x64

**What complete docker command or docker-compose.yml do you use to launch the container** (omitting sensitive values)?
Used the docker compose file provided to "sudo docker-compose up"

Logged into the AP's and provided via 



**What do you expect to happen?**
Unifi Controller runs and visualizes devices for adoption and starts (as defined in loaded backup-configuration) to automatically to adopt the known APs. 
After having provided via ssh to each controller
set-inform http://new-ip-of-controller:8080/inform 
Adoption should work as expected

**What actually happens?**
After using my backup from my Raspi unifi controller instance to restore on the docker unifi controller I can log in and change settings. I can see my configuration and all 3 devices. 
Pressing adopt from the webfront does not start anything

After having provided via ssh to each controller
set-inform http://new-ip-of-controller:8080/inform 

adoption works seemlessly and all seems works for a few (!!) minutes. 
For one moment during adoption the APs show a sign with a (1) STUN server not reachable, which goes away a moment later. 
Then suddenly adopting starts again and over and over again.
Wifi Works fine without any trouble.

Restart of the container down && up -d ... same as before .. can see the APs send command via ssh adopting starts... like before....

**Comment by drachul** [comment]
My setup is exhibiting this exact same issue.
I have noted that there are a bunch of periodic "<device> was automatically readopted" events, and I have one device (a UniFi Swith 24) doesn't have this problem.

The other devices (Unifi Switch 16XG, 2x Unifi AP-AC-Pro, and a Unifi Security Gateway 4P) all have this adoption issue.

**Comment by MarkusLoyen** [comment]
I found a solution, that ist working for me.

Instead of having a FQDN in the settings in Network as shown below.  Put in the hosts IP-address. Next update will then work smoothly (at least on my side)

![image](https://user-images.githubusercontent.com/58221933/149618313-883f9cdf-e011-41eb-a805-c736667f27e1.png)
