### ISSUE TITLE
config.gateway.json location within docker?

### ISSUE THREAD

**Issue by phoniclynx** [jacobalberty/unifi-docker#274]
This has been driving me up the wall for a few days now. I want to do some advanced configuration of the USG and unifi-docker, but I can not for the life of me figure out where to put this file.

Everything I read tells me that I should put it into a folder called "sites" followed by my site ID. There is no such folder. Or do I need to create the whole directory structure here?

The folder structure is:
/unifi/data:
```
drwxrwxr-x 3 unifi unifi  4096 Nov 23 00:25 backup                                                                            
drwxrwxr-x 4 unifi unifi 24576 Jan 11 16:31 db                                                                                
-rwxrwxr-x 1 unifi unifi 23147 Jan 11 08:20 firmware.json                                                                     
-rwxrwxr-x 1 unifi unifi  2747 Nov 30 13:21 keystore                                                                          
-rwxrwxr-x 1 unifi unifi  1339 Jan 10 08:19 system.properties                                                                 
-rwxrwxr-x 1 unifi unifi  1339 Jan 10 08:19 system.properties.bk                                                              
drwxrwxr-x 3 unifi unifi  4096 Nov 12 11:25 webrtc
```
Do I need to create a folder here called "sites/<site_ID>/config.gateway.json

**Comment by vlm---** [comment]
Try to upload a floorplan for the site. It creates sites folder with subfolder for the selected site. At least it worked for my container running on Synology.

**Comment by buckaroogeek** [comment]
My understanding is that uploading any image as a floorplan will work.

Brad

**Comment by DirkWalter77** [comment]
Hello, uploading a map did not work for me. The directories won't be created.
Any suggestions or hints where I can put the config.gateway.json into or do I have to create the folders manually like @phoniclynx mentioned?

Best wishes!
Dirk

Synology 216+
Docker
Unifi

**Comment by jjdegroot83** [comment]
Hi, I've got the same issue. I need to upload a JSON file to be able to configure the Internet and IPTV VLAN's but I don't see a way to get to the right path on the controller.
Anybody got an idea on how to do that?

**Comment by DirkWalter77** [comment]
jjdegroot83, do you use docker for the unifi controller? If yes, please check the mount path in the configuration of the docker container. The mount path must be "/unifi" and not "/Unifi" oder "/UNIFI" or something like that. Linux is case sensitive ;-) for my error this was the reason. I deleted and re-installed the docker container with the correct mount path "/unifi" and I had all the needed folders with the json files.
