### ISSUE TITLE
Unable to finish wizard, stuck in a loop

### ISSUE THREAD

**Issue by Dragnell87** [jacobalberty/unifi-docker#277]
### Host operating system
RKE 1.15.6 on Ubuntu 18.04 worker nodes

### What tag are you using

`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

https://github.com/helm/charts/tree/master/stable/unifi

### What do you expect to happen?

Setup and acces to Unifi Controlller

### What actually happens?

I am able to access to the wizard, but unable to finish it. In the last step, keep sending me in a loop to the same page. So the wizard never load the config provided. 

Also i am using 
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

was the only way i find  to access to the gui

Other consideration:* Using openEBS for storage provicioning.

**Comment by Dragnell87** [comment]
unifi-controller   NodePort    10.43.102.207   <none>        8080:32626/TCP    12m
unifi-discovery    NodePort    10.43.175.81    <none>        10001:32013/UDP   12m
unifi-gui          ClusterIP   10.43.122.202   <none>        8443/TCP          12m
unifi-stun         NodePort    10.43.38.253    <none>        3478:30039/UDP    

This is what a new instance show, if i access through the browser to what rancher thought is exposing over tcp 32626 it redirects me a 8443 and fails to connect. Is this the expected behaviour? A clean telnet connetion does succed. De default ingress L7 that is created  allow me to access to the unifi-gui but does not save the changes made in the initial setup. 

How ever if i expose the unifi-gui with nodeport, then i can access the setup and finisih the process correctly. The only diference lays in the cert error that pops out whent i am using nodeport. Error that otherways does not pop up using the ingress controller.

Any thought?

**Comment by wojciechwroblewski** [comment]
I've run into this issue today and it seems to be an issue related to ingress/reverse proxy setup. When controller instance is initialized, exact same setup results in login failures (403 when accessing `/api/login`). I've seen multiple reports on ubiquiti community forums reporting this behavior, almost all of them suggest manipulating headers (Origin and/or Referer). Unfortunately I wasn't able to determine correct combination of headers to make this work with nginx ingress.  

Anyway, the issue for sure is not related to the docker image.
