### ISSUE TITLE
Custom SSL Certificate quick config

### ISSUE THREAD

**Issue by jacobalberty** [jacobalberty/unifi-docker#28]
I'm working on building in custom ssl certificates. My thinking is add a new volume say /config/ for image specific configuration (to allow expansion of more quick configuration options)
then put your entire keychain in say /config/ssl.pfx. Then to trigger a new certificate you would delete /usr/lib/unifi/data/keystore and restart your container.

Posting this so if anyone wants to give any input on the feature design ahead of time they can.

**Comment by dannytsang** [comment]
I'd like to see a way of using let's encrypt as an option as well as using your own certificate.

**Comment by jacobalberty** [comment]
That's actually the goal behind it, something easy enough to tie into a lets encrypt client

**Comment by phroggster** [comment]
I found this the other day when i needed to replace a cert, in case it helps: https://github.com/stevejenkins/unifi-linux-utils/blob/master/unifi_ssl_import.sh

I don't use Let's Encrypt, so I didn't test that aspect, but it seems like it would fit right in here (perhaps with some modifications).

**Comment by jacobalberty** [comment]
My thinking on the lets encrypt front is it will be better to have it separate from the image, just make it easy to import lets encrypt certs into it. That way you aren't tied to any specific ACME client and I'm not trying to maintain compatibility with the different update methods ensuring they work with everyone's situation. DNS-01 would be a nightmare to try and support within a docker image due to all the different clients and apis for updating dns records.

**Comment by jcberthon** [comment]
Interesting topic, but using Let's Encrypt also means your UniFi AP uses a public IP address and domain name. You cannot use a CA like Let's Encrypt (and AFAIK other commercial CA) for internal IPs.

**Comment by jacobalberty** [comment]
Lets encrypt works just fine for internal IP addresses, as do other CAs. With letsencrypt probably the easiest way to validate internal ips is using DNS-01 validation. As long as you own the domain you can validate any subdomain under it, public ip or not.

**Comment by vmtyler** [comment]
100%- I use LE with DNS-01 for a domain name that i use for all internal stuff. My client (dehydrated) uses the cloudflare hook to satisfy the DNS challenge. That way all my internal stuff with SSL has legit certs.

I agree with the earlier comment that building the cert mechanism into the dockerfile is a bad idea. What I suggest is adding a directory called certs and on startup it checks the cert to see if its new and then updates the ubiquiti image with it. I actually have a modified version of the script @phroggster linked to that does exactly that. I'll add it in and submit a PR.

**Comment by pho3nixf1re** [comment]
How would that work with something like LetsEncrypt? Those certificates are only good for one month and must be renewed. Typically you use a daemon that automatically renews the certificate every x days. Could you create a dedicated container to renew the certificate and place it in the same location that the UniFi container expects to find it? Would the controller need to be restarted every time the certificate updates?

**Comment by vmtyler** [comment]
LE certs are good for 90 days. There are containers that do exactly that already. I use a cron job that checks all mine and updates them. The controller needs to be restarted anytime you change certs anyway, so I would just have that happen at container startup before starting the controller. I have the code almost done, just testing a few things.

**Comment by vmtyler** [comment]
Ok, I put a PR in for it. Basically if you mount a cert volume, it'll check the certs before starting the controller each time, and if they're changed/new, it'll import them.

**Comment by jcberthon** [comment]
OK good to know! I did not think of exposing internal hosts to the outside DNS resolver. Thanks for the hint!

**Comment by sampl3x** [comment]
@vmtyler Can you help me out how to get a SSL cert (Let'sEncrypt) into the unif docker image?

**Comment by jacobalberty** [comment]
@sampl3x map a volume to /var/cert/unifi and put your le cert in cert.pem under that volume and the private key in privkey.pem under that volume, when you restart (or start) the unifi container it will import the certificate.

**Comment by sampl3x** [comment]
@jacobalberty But how to generate the LetsEncrypt .pem files in your Docker Container?

**Comment by jacobalberty** [comment]
@sampl3x I wouldn't generate them in the unifi container, you would need to decide what challenge to use and then set up certbot to do so. 

You can find examples of people using certbot here
https://community.ubnt.com/t5/UniFi-Wireless/UniFi-Server-HTTPS-Certificate/td-p/338040/page/3 

You would simply need to replace the parts where they import the certificate with you copying the certificate to your mapped volume

**Comment by vmtyler** [comment]
exactly. I use another container to do it- https://github.com/csmith/docker-letsencrypt-lexicon

**Comment by sampl3x** [comment]
I know my way around with certs you buy, convert them with openssl tools but this LetsEncrypt is still strange. I dont want to enable port 443 NAT rule to get a new cert all the time.

@vmtyler maybe you have instructions how you do this with that docker container?

**Comment by vmtyler** [comment]
there are two ways to verify for LE certs, web (as you mentioned) and DNS. I have a tld i bought for a few bucks that i use for all my internal stuff and I have it on cloudflare DNS.
Basically LE asks you to add a DNS entry so they can verify you own the domain. That container can connect to a bunch of diff DNS services (including cloudflare) to do that automatically.
