### ISSUE TITLE
kodi 18 / deployment failed / "exec -- failed: No such file or directory"

### ISSUE THREAD

**Issue by mschindl** [jacobalberty/unifi-docker#288]
### Host operating system

kodi 18
# uname -a
Linux Wohnzimmer 4.19.83 #1 SMP Sat Nov 23 01:55:35 CET 2019 armv7l GNU/Linux

### What tag are you using

arm32v7

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run \
--init  \
-d \
-p 9080:8080 -p 9443:8443 -p 3478:3478/udp -p 10001:10001/udp \
-e TZ='Europe/Berlin' \
-v /storage/docker/unifi:/unifi \
--restart unless-stopped \
--name unifi \
jacobalberty/unifi:arm32v7

### What actually happens?

Restart all time. Without local storage still the same issue.

# docker logs unifi
**exec -- failed: No such file or directory**

Any idea what cause the issue?

**Comment by daveoconnor** [comment]
I'm also seeing this on a libreelec box running on an amd64 machine with a stock docker-compose.yml. Used to work fine.

**Comment by daveoconnor** [comment]
Seems to be related to #135, removing --init from the docker-compose worked for me.

**Comment by mschindl** [comment]
I didn't test it again, but now I tried following deployment:

https://github.com/ryansch/docker-unifi-rpi/issues/71

Thank you and best regards
