### ISSUE TITLE
best upgrade practice

### ISSUE THREAD

**Issue by simonz21** [jacobalberty/unifi-docker#289]
I've been using 5.10.24 (Build: atag_5.10.24_11676) on my QNAP for several months, and it's great, perfectly stable. Managed to do this with my rudimentary skills.

But now I'd like to upgrade, and I'd like to know what the best way to do this is. I can create and download a config backup, create a fresh install with the latest version, and then restore the config from my backup, but I'm guessing I will lose all my data. This is not a deal-breaker, but seems inelegant and clumsy. What's the best practice here?

Thanks

**Comment by simonz21** [comment]
Anyone?

**Comment by vMarkus** [comment]
Hi Simon,

From your example config

> Example: docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5

it looks like you already use volumes for your local filesystem, so your data is not inside of your container.
What I have done from a storage/volume perspective on my NAS is to create directories like
/docker
/docker/unifi_v5_12_22
/docker/unifi_v5_12_22/cert
/docker/unifi_v5_12_22/data
/docker/unifi_v5_12_22/log

When I upgrade I shut down the container 5.12.22. 
I create a new directory with the new controller version like
/docker/unifi_v5_12_35

After shutdown I copy all data and subdirectories from /docker/unifi_v5_12_22 to the new directory.
Download and setup new unifi docker container, use volumes with new path to 5.12.35 and I am naming the container with the version number, too.

Run new container with version 5.12.35 which may convert database to newest version etc.

Why do I copy data? Because if something in the new version is acting up I can just shutdown "new" and go back to "old". Backups for unifi controller do not support downgrading as far as I know and I do not need to fiddle around with backup/restore.

I hope this sheds some light on how you could do it in a fast and convenient way.

**Comment by simonz21** [comment]
Sorry, my original post was confusing. I accententally left the original template, including the command line code, which I absolutely DON'T use...that is way beyond my technical ability, I think.

![image](https://user-images.githubusercontent.com/26865660/76759304-af74bd80-678b-11ea-9615-027faf6b5971.png)
![image](https://user-images.githubusercontent.com/26865660/76759540-2a3dd880-678c-11ea-9154-5b8aaa99877a.png)

As you can see, the actual files are stored somewhere a bit more random. Still, at least I found them!

However, I am smart enough to set up some new folders for the new install:
![image](https://user-images.githubusercontent.com/26865660/76760182-789fa700-678d-11ea-8807-5df60fd1fd50.png)

Now all I need to do is learn how to do a fresh install that points to these folders? Is there something I change in the advanced settings when I create a new Unifi container, or is it some kind of command line thingy, and if so, where do I use it, and how?

Once I have learned and understood this, the rest of your instructions make perfect sense to me, and I can replicate these...I think...!

Thanks for your help.

**Comment by simonz21** [comment]
??

**Comment by PrplHaz4** [comment]
> 
> 
> ??

This is probably more a QNAP question than a docker question at this point, but it sounds like editing "advanced settings" and changing the volume mount locations prior to creating the container might be what you need...

**Comment by Saargebeat** [comment]
I have the same question. How to upgarde properly?

I am using Synology with this docker container. I created a new container, used the same directory, could login and everything was fine - but all devices were offline. They are "managed by another controller" (message was different but this was the meaning).

I could not re-set inform url or even set to factory defaults (login failed).

**Comment by vlm---** [comment]
My steps on Synology using the UI:
1. Download current backup from controller
2. Download new version of image in Docker/Registry
3. Stop running container in Docker/Container
4. Clear container in Docker/Container
5. Start container in Docker/Container

Steps 2-5 can be automated or done manually via ssh.

The way @Saargebeat is doing it, will create a new instance of the controller, therefore the "managed by another controller" error. Importing backup from old instance may help.

**Comment by Saargebeat** [comment]
> My steps on Synology using the UI:
> 
> 1. Download current backup from controller
> 2. Download new version of image in Docker/Registry
> 3. Stop running container in Docker/Container
> 4. Clear container in Docker/Container
> 5. Start container in Docker/Container
> 
> Steps 2-5 can be automated or done manually via ssh.
> 
> The way @Saargebeat is doing it, will create a new instance of the controller, therefore the "managed by another controller" error. Importing backup from old instance may help.

Hello vlm,

thanks for your answer but im not sure what are the differences between your version and mine.

What i did was
1. Download Backup
2. Download new unifi-docker-container (at Synology Docker GUI)
3. Stop "old" unifi-docker-container (at Synology Docker GUI)
4. Changed Ports on the "old" container so they are free for the new one
5. Setting up the new container with correct ports and the "old" directory (so all the settings are still there)
6. Starting new container
7. Devices are offline, so i load the backup
8. Devices are still offline

**Comment by vlm---** [comment]
Luckily, I never had to restore from a backup, so I don’t know why it did not work for you. I do not understand why are you creating new instance of the container but I hope you figure it out eventually. My upgrade steps are better described in this [blog](https://www.sollit.be/ubiquiti-unifi-controller-on-synology-with-letsencrypt-ssl/).

**Comment by Saargebeat** [comment]
Well, the only reason is that i know only this procedure.

I wish you could tell how to update the existing container so i dont have to create a new one...

**Comment by simonz21** [comment]
I did it this way and it worked pretty well. I have a manually set static IP so best to set this before you first run the new container (after you’ve stopped the old one on the same IP), otherwise you end up importing the saved config+data file twice. Apart from that worked totally fine.

**Comment by Saargebeat** [comment]
Not sure if i dont understand correct or if i did not describe properly...

I didnt check yet why, but all my Synology-Docker-Container got the same ip -> the ip from the synology diskstation. Only the ports are different and its actually decided by port, to which docker container i like to connect.

Thats why i changed ports on old unifi-container to have them free for the new, updated one.


But well, as i said i dont know where are the differences between what i did and what you did. I can guarantee that the new container instance has the same ip and ports as the old one had.


Is it possible to get another, maybe more detailed description about how to update the unifi-docker-container without beeing trapped by "managed by another controller" issue?

**Comment by simonz21** [comment]
To get a separate IP, I set the networking to “bridge”, chose the network adapter (physical port) on the NAS, and then specified an IP on the subnet.

**Comment by Saargebeat** [comment]
Thx but on (my) Synology this doesnt work. I cant do anything else than select bridge which means it takes the Synology-NAS-IP and i have to set correct ports to access this container (and not the synology UI or any other container).


But the main issue is to get the unifi controller up to date without having this "managed by another controller" issue

**Comment by lklic** [comment]
I am using docker-compose on an ubuntu box, and I just pulled in the latest image using`docker pull jacobalberty/unifi` and then `docker-compose up -d`

**Comment by dpudia** [comment]
If a restore from previous backup, the unifi backup was restored to the same old version.
If I create new container whit the last registry and I copy the file from the old datastore to the new I have the same result: old version.
I don't understand the correct way to update only the software and migrate only the data.

Any suggestion?
