### ISSUE TITLE
Update Package to 5.4.14

### ISSUE THREAD

**Issue by ahiguero** [jacobalberty/unifi-docker#29]
Hello Jacob
First of all thanks for your great work. Can you please create the new package for version 5.4.14. Another question is there a way to upgrade to the latest version without redoing the container?

**Comment by jacobalberty** [comment]
Is 5.4.14 final yet? I believe it's still release candidate. And you would
need to redo the container to update. If you have your unifi data folder in
some sort of external volume then recreating the container won't lose any
data.

**Comment by ahiguero** [comment]
Hello Jacob
for what i see on the forums it is Stable candidate
[https://community.ubnt.com/t5/UniFi-Wireless/UniFi-5-4-14-Stable-Candidate-has-been-released/m-p/1882072#U1882072](url)

yes the volumnes on my container are mapped to acaul folders on the NAS so i am covered :)

**Comment by jacobalberty** [comment]
I was waiting on these candidates before tagging new releases. Two reasons.
It's apparently not going to be the new stable. It'll be lots and the 5.5
series will be the new stable. Secondly both stable candidates have had fix
releases already extending the stable candidate phase.  I haven't had a
chance to look at what was fixed though maybe it was just minor issues but
between that and the big change I thought it might be better to delay
updating the images till it's final

**Comment by ahiguero** [comment]
Thanks for your reply buddy.

then i would say i can wait :)
