### ISSUE TITLE
MongoDB 3.6 upgrade [5.13.10/Beta]

### ISSUE THREAD

**Issue by Xeroxxx** [jacobalberty/unifi-docker#290]
Can we get an upgrade on the MongoDB to 3.6 in Beta Branch?

Ubiquti starts supporting MongoDB 3.6 with 5.13.10.

3.4 is EOL since January 2020.

https://community.ui.com/releases/UniFi-Network-Controller-5-13-10/345bd4ae-aafc-435d-bd92-0cb3048d38e9

- Add support for MongoDB 3.6.

**Comment by jacobalberty** [comment]
I'm going to make a new branch called `beta-mongo3.6` for this. My only concern is if someone is still using beta to test out  rc's before they make it to "general" 5.12.66 has sat in general rc so long without a final release I'm expecting a new rc for the 5.12 branch to hit beta soon. The build is pending on the docker hub now and should be done shortly.

**Comment by Xeroxxx** [comment]
I agree. Thank you so much!

**Comment by Xeroxxx** [comment]
@jacobalberty Hey, just want to confirm the build works like a charm. No issues so far.

Thanks again.

**Comment by buckaroogeek** [comment]
Would it be prudent to also update the docker-compose.yml file in this branch so the mongo container is also at 3.6?

thanks
