### ISSUE TITLE
Devices not detected in bridge mode

### ISSUE THREAD

**Issue by belliash** [jacobalberty/unifi-docker#297]
Hey,

I am trying to setup UniFi controller in Docker container, but it does not detect any devices. I use the exact command specified in readme and controller itself is working. The docker ps command lists all ports. What is more I specify the same IP in Controller configuration and check 'Override inform host with controller hostname/IP'. Nevertheless, devices are still not seen.

On the other hand, everything works fine, when I use --net=host instead. But unfortunately, it listens on 0.0.0.0 then instead of single interface, what is unacceptable for me.

**Comment by silnice** [comment]
SSH Adoption
The quickest one off method is to ssh into the access point and run the following commands:

mca-cli
set-inform http://<host_ip>:8080/inform

**Comment by belliash** [comment]
SSH adoption should not be necessary.

**Comment by LexxM3** [comment]
Is your port 10001 mapped to container?  Worth a check just in case and https://github.com/jacobalberty/unifi-docker/issues/421 for context.
