### ISSUE TITLE
No mounted volume when using docker-compose

### ISSUE THREAD

**Issue by Spock-to-Kirk** [jacobalberty/unifi-docker#298]
**Host operating system**

Ubuntu 16.04

**What tag are you using**

latest

**What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?**

Let me first thank you for this project. I think Unifi in Docker is a brilliant idea. It is in general more stable and less dependent to dependencies.
I would like to have a local directory mounted to preserve the unifi settings. Your first set up seems to do this and created 2 directories before using docker run:

```
mkdir -p unifi/data
mkdir -p unifi/log
docker run --rm --init ....... -v ~/unifi:/unifi --name unifi jacobalberty/unifi:stable
```

However I use your: docker-compose.yml. With environment RUNAS_UID0=false 
You yml file makes settings for volumes and specifies directories. I want to have my data dir at a different location. I created for instance: /home/user/unify-project/unif/data. Because Im not running it as root I made sure that the entire structure is owned by user "unifi" (id=999). I even set permissions to be writable by everyone.

**What do you expect to happen?**

After starting `docker-compose up`
The unifi web interface started perfectly. I expected that these new directories are mounted to the containers. I expected to see log files in the log dir.

**What actually happens?**

The local directories I created under my home dir are not used.
I reverted the docker-compose.yml to your original file. All is starting as it should.
This log is stored in the "log container" in /unifi/log. I can access it by opening a shell. But Im worried from maintenance point of view. If I want to delete the logs I have to log in. A mounted dir would be better or I could delete the container.
The "Controller container" obviously contains all controller settings and data.

I'm not sure of what to do. The containers will grow in size. I cannot purge the without loosing also my configuration. On the other hand if I have a mounted volume with controller data, db and config, create a new container and put back an older backup of my external data and data and container don't match, then an mounted volume is of no extra user.

I hope you can help me with this.
Any help and instructions are highly apreciated.

**Comment by buckaroogeek** [comment]
Greetings

If the data directory is, for example, /home/user/unify-project/unif/data
then in the dockler-compose file should be something like:

  volumes:
    - /home/user/unify-project/unif/data:/unifi/data

I tend to prefer using a full path instead of ~ just for clarity.

I use the docker-compose file with some modifications. I have unifi
controlled running under docker on a Synology NAS attached to my home
network.;
  unifi:
    image: jacobalberty/unifi:latest
    container_name: SageCreek-Unifi-Controller
    hostname: unifi2
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:ac
    depends_on:
      - mongo
    init: true
    networks:
      macvlan1:
        ipv4_address: 192.168.110.216
    restart: unless-stopped
    volumes:
      - /volume1/docker/unifi/data:/unifi/data
      - /volume1/docker/unifi/log:/unifi/log
      - /volume1/docker/unifi/cert:/unifi/cert
      - /volume1/docker/unifi/init.d:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Pacific
      UNIFI_HTTP_PORT: 80
      UNIFI_HTTPS_PORT: 443
      #RUNAS_UID0: false
      #UNIFI_UID: 1029
      #UNIFI_GID: 65537
    ports:
      - "1900/udp" # L2 discovery
      - "3478/udp" # STUN
      - "6789/tcp" # Speed test
      - "80/tcp" # Device/ controller comm.
      - "443/tcp" # Controller GUI/API as seen in a web browser
      - "8880/tcp" # HTTP portal redirection
      - "8843/tcp" # HTTPS portal redirection
      - "10001/udp" # AP discovery
      - "27117/tcp" # DB communications



Brad

**Comment by Spock-to-Kirk** [comment]
Hi Brad,

Thank you for your update. Meanwhile I solved half of my question. I now know where they are mounted. I assumed that a directory is directly mounted but now I understand that they are docker volumes. They are stored at: /var/lib/docker/volumes.
Use: `docker volumes ls`

I can back up the entire directory or remove logging files. But I still don't know if a container backup (docker load <container>) and a restore of the volume data would work. For instance if there are indexes pointing to certain entries and I replace them I would corrupt the data.
Do you have experience with that?

**Comment by Spock-to-Kirk** [comment]
Issue is closed. Thanks for helping.
