### ISSUE TITLE
Support DHCP server too

### ISSUE THREAD

**Issue by Luzifer** [jacobalberty/unifi-docker#3]
The Unifi controller software supports being the DHCP server for the network settings of a site but when using the container there is no port exposed so DHCP will not work.

> The DHCP employs a connectionless service model, using the User Datagram Protocol (UDP). It is implemented with two UDP port numbers for its operations which are the same as for the BOOTP protocol. UDP port number 67 is the destination port of a server, and UDP port number 68 is used by the client. ([Wikipedia: DHCP](https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol))

So for supporting DHCP please add an `EXPOSE` of `67/udp` to the image.

**Comment by hemsleyk** [comment]
AFAIK Docker can't do layer 2 things like DNS.
