### ISSUE TITLE
Cannot open Mongo shell

### ISSUE THREAD

**Issue by mvaneijken** [jacobalberty/unifi-docker#301]
### Host operating system

Docker on DSM 6.2.2-24922 Update 6

### What tag are you using

'stable' 

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run –d –network host -e TZ='Europe/Amsterdam' -e RUNAS_UID0=false -e BIND_PRIV=false -v /volume1/docker/unifi:/unifi --name unifi jacobalberty/unifi:stable 

### What do you expect to happen?
I would expect that its possible to connect to mongo shell using:
docker exec -ti unifi bash
mongo --host 127.0.0.1:27117

This because Mongo does not start due error:
[initandlisten] Fatal assertion 28579 UnsupportedFormat: Unable to find metadata for table:index-158-2895582586454170724 Index: {name: _id_, ns: ace_stat.stat_archive} - version too new for this mongod. See http://dochub.mongodb.org/core/3.4-index-downgrade for detailed instructions on how to handle this error. at src/mongo/db/storage/wiredtiger/wiredtiger_index.cpp 241

### What actually happens?
I got an error: 
root@unifi:/unifi# mongo --host 127.0.0.1:27117
MongoDB shell version v3.4.24
connecting to: mongodb://127.0.0.1:27117/
2020-04-23T20:42:23.422+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27117, in(checking socket for error after poll), reason: Connection refused
2020-04-23T20:42:23.423+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27117, connection attempt failed :
connect@src/mongo/shell/mongo.js:240:13
@(connect):1:6
exception: connect failed

**Comment by brontide** [comment]
Check `ps auxww` to see if the mongo service is running.  If not you will need to launch mongo as unifi:unifi ( within the container ).  Here is the process line from my instance of the container.  Please confirm the paths are correct for your install.  Note if mongod doesn't start there is no way to use the mongo shell and you should restore a recent backup to a clean installation.

```
mongod --dbpath /usr/lib/unifi/data/db --port 27117 --unixSocketPrefix /usr/lib/unifi/run --logappend --logpath /usr/lib/unifi/logs/mongod.log --wiredTigerCacheSizeGB=1 --bind_ip 127.0.0.1
```

You will want to launch as unifi ( prefix ) `gosu unifi:unifi` and add `&` to put it in the background.
