### ISSUE TITLE
How to use latest 'testing' version?

### ISSUE THREAD

**Issue by Swiftnesses** [jacobalberty/unifi-docker#307]
Hello,

I'd like to use the latest 'testing' version (5.13.27), is there a way to do this?

Many thanks in advance.

**Comment by tsgoff** [comment]
change line 7 to the new version https://github.com/jacobalberty/unifi-docker/blob/master/Dockerfile#L7 and do a docker build

**Comment by jacobalberty** [comment]
Use the :beta tag and provide PKGURL with the correct path to the 5.13.27 debian package.

**Comment by Swiftnesses** [comment]
Awesome, thanks guys!
