### ISSUE TITLE
migrate helm chart to this repo?

### ISSUE THREAD

**Issue by billimek** [jacobalberty/unifi-docker#310]
Hi @jacobalberty!

Myself and @mcronce are maintainers of the [unifi helm chart on the official helm 'stable' repo](https://github.com/helm/charts/tree/master/stable/unifi).  The helm stable repo is slated to be [deprecated in a few months](https://github.com/helm/charts#deprecation-timeline) and all charts hosted there will need to find a new home.

Would you be interested in hosting the unifi helm chart in this repo?  IMO it makes sense to home charts where the Dockerfile is, or at least in a co-located repo within an organization.  I originally discussed the chart in this repo in #136.

I would be happy to submit a pull request to add the necessary github actions to do proper linting and testing of chart changes as well as releases within the repo and 'hosting' on [helm hub](https://hub.helm.sh/).  You can take a look at a [similar PR](https://github.com/munnerz/kube-plex/pull/78) I did for the kube-plex chart to see what it would look like.

Alternatively, I'm happy to host the unifi chart in [my charts repo](https://github.com/billimek/billimek-charts/) once again.  This is where it originally lived in 2018.  I already have a couple dozen charts hosted there already with the proper chart linting/testing/releasing automation in place.

Thanks!

**Comment by buckaroogeek** [comment]
@billimek - so cool to learn about this helm chart.  Would the organization of Jacob's repo need to change? Note I am just an interested observer and not a maintainer.

@jacobalberty - I would think that a k8s implementation of the controller based on your dockerfile would be of special interest to enterprise(y) users of Unifi and for companies that manage multiple unifi networks as a business model. The unifi helm chart seems like a natural extension of your work into that space. 

Best

**Comment by billimek** [comment]
@buckaroogeek thanks!

To host in this particular repo, it would need to have a new `charts/unifi` directory created the repo root.  Ideally the github actions approach would be used to best conduct the helm chart linting, testing, and 'releasing' of new versions, so a couple of new files would need to be created at the repo root under the `.github` directory.  I think it could work with travis, but I don't have recent experience setting up the automation for charts using that.

It would also mean that new github repo 'releases' would be created (with the packaged chart tarball) every time a new version of the chart is released.  I hope that wouldn't make the releases page too cluttered.

Those changes are definitely worth considering.
