### ISSUE TITLE
All arm32v7 images on Docker hub contain MongoDB 2.6

### ISSUE THREAD

**Issue by hrak** [jacobalberty/unifi-docker#313]
### Host operating system

Raspbian GNU/Linux 10 (buster)

### What tag are you using

arm32v7 / 5.12.72-arm32v7 / 5.12.66-arm32v7 / 5.11.50-arm32v7

### What do you expect to happen?

The [repo](https://github.com/jacobalberty/unifi-docker/blob/arm32v7/docker-build.sh) seems to suggest that the ARM image should come with MongoDB 3.4

### What actually happens?

All the tags i tried seem to come with MongoDB 2.6 (that has no WiredTiger support)

```
$ docker run -it jacobalberty/unifi:arm32v7 'dpkg -l'|grep mongo
ii  mongodb-client 1:2.6.10-0ub armhf        object/document-oriented database
ii  mongodb-server 1:2.6.10-0ub armhf        object/document-oriented database

$ docker run -it jacobalberty/unifi:5.11.50-arm32v7 'dpkg -l'|grep mongo
ii  mongodb-client 1:2.6.10-0ub armhf        object/document-oriented database
ii  mongodb-server 1:2.6.10-0ub armhf        object/document-oriented database

$ docker run -it jacobalberty/unifi:5.12.66-arm32v7 'dpkg -l'|grep mongo
ii  mongodb-client 1:2.6.10-0ub armhf        object/document-oriented database
ii  mongodb-server 1:2.6.10-0ub armhf        object/document-oriented database

$ docker run -it jacobalberty/unifi:5.12.72-arm32v7 'dpkg -l'|grep mongo
ii  mongodb-client 1:2.6.10-0ub armhf        object/document-oriented database
ii  mongodb-server 1:2.6.10-0ub armhf        object/document-oriented database
```

The weird thing is that there does seem to be a repo configured for MongoDB 3.4:

```
$ docker run -it jacobalberty/unifi:arm32v7 'cat /etc/apt/sources.list.d/mongo*.list'
[2020-06-04 21:12:33,160] <docker-entrypoint> Executing: cat /etc/apt/sources.list.d/mongo*.list
deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
```

**Comment by hrak** [comment]
Found the cause, the repo at http://repo.mongodb.org/apt/ubuntu only contains arm64 builds, not arm32/armhf

**Comment by jacobalberty** [comment]
The new `multiarch`, `multiarch-5` and `beta` tags now use mongodb 3.4 on arm32/armhf and mongodb 3.6 on arm64 and x86-64, the `arm32v7` tag will be deprecated with the full migration of `latest` to unifi 6 and the `multiarch` branch will be merged into `latest` at that point.
