### ISSUE TITLE
Correct way to pull an arm32v7 image for the latest Unifi version

### ISSUE THREAD

**Issue by hepto** [jacobalberty/unifi-docker#314]
### Host operating system

Raspian/Raspbery Pi OS (kernel 4.19) (Debian 10)

### What tag are you using

`arm32v7` - but this is the crux of the question!`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -d \
  --name unifi \
  --network host \
  --init \
  --restart unless-stopped \
  -e TZ='Europe/London' \
  -e RUNAS_UID0=false \
  --mount source=unifi-data,target=/unifi \
  jacobalberty/unifi:arm32v7

### Question

Would like to know the best way to run this image on `arm` AND keep it up-to-date with periodic `pull`s.

Currently as you see above I'm using the tag `arm32v7` which correctly pulls the arm32v7 version.

However since the update to Unifi `5.12.72` a few weeks ago, that tag is still giving me a `5.12.66` image, but there is another tag, `5.12.72-arm32v7`, that is of course on 5.12.72.

Previously, and what I would like, is to stay on the `arm32v7` tag but have it updated as new versions of Unifi get released.  Then I can simple do a `pull` and get the latest version.  (Actually I use an automated service to do this -- `watchtower`.)

Because it hasn't updated I wonder if I am using the wrong tag, or have the wrong expectations so my question is, for an arm32v7 arch what tag should I use to keep it always pointing at the latest, the same as `latest` is for amd64 please?

I tried to work it out via the available tags on DockerHub, but actually ALL the tags there indicate they are `linux/amd64` which I think is just a hangover from before you could build arm on their servers. 

(Side note - which I think means that they can be updated somehow to show the correct arch, but I don't know how.  Also I think you could now do some kind of multi-arch build where I can use `latest` and it will pull the latest for my arch?)

Anyway, all advice gratefully received - I don't want to switch to the specific 5.12.72 tag as of course I'll just need to change again when the next Unifi is released, and for my purposes I want it to auto-update without me even knowing.

Cheers.

**Comment by psychoticbeef** [comment]
For me it appeared over night (5.13.29). Never saw 5.12.72 though. Running the same setup as you are.

**Comment by hepto** [comment]
Yep - me too.  Maybe the 5.12.72 arm build was just accidentally missed.

I'm sure there is a way on Docker Hub to have multi-arch builds so we could drop the arch specific tags, but I'm not familiar with it.

Will close this as looks like we're moving again ...
