### ISSUE TITLE
Hi Jacobalberty,

### ISSUE THREAD

**Issue by RonaldBlom** [jacobalberty/unifi-docker#318]
This is not really an issue. But normally you are almost as quick as Ubiquity with releasing the new version. And I can mostly see that you are testing with it before the release. But this time no testversions and also no release yet. Hope that you are doing ok?

Regards,
Ronald Blom

**Comment by kwin** [comment]
https://github.com/jacobalberty/unifi-docker/pull/315

**Comment by RonaldBlom** [comment]
Thanks, I will close this one
