### ISSUE TITLE
Update for 5.13.29? - can't seem to get it after updating my container

### ISSUE THREAD

**Issue by L0rdLogan** [jacobalberty/unifi-docker#319]

**Comment by dougle03** [comment]
5.13 has not been released within this repo yet!

**Comment by ericcardenas** [comment]
It's updated now. 👍

**Comment by buckaroogeek** [comment]
5.13.29 now working on a synology docker host with mongo 3.6. All devices adopted without issue.  Normal cpu and ram usage after the initial start period.
