### ISSUE TITLE
First-time setup wizard cannot be completed when connected by port 8080, only by port 8443

### ISSUE THREAD

**Issue by OscarVanL** [jacobalberty/unifi-docker#321]
### Host operating system

Synology DSM 6.2.3

### What tag are you using

`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
sudo docker run -d \
 --net=host \
 -v /volume1/docker/unifi:/unifi \
 -e TZ='Europe/London' \
 --restart=always \
 --name Unifi-Controller \
 jacobalberty/unifi:stable
```

### What do you expect to happen?

I can complete the first-time setup as expected.

### What actually happens?

I've went through all the steps, setting a controller name, logged into my Ubiquiti account, setup a local access login (it's being set up at my parent's house, so don't want them to have to use my Ubiquiti login) and set my WiFi name/password.

Then on the final page I pressed 'Finish' and every time I got an error dialog in the top-right:

```
Cannot configure Controller

Invalid username or password, please try again.
```

I destroyed the container, deleted all the files in `/volume1/docker/unifi` and tried again about 5 times before connecting to port `8443` instead of port `8080`.

After doing this the setup wizard completed first time.

I'm curious if this is reproducible for others or some crazy UniFi bug.

**Comment by jackvanderson** [comment]
EXACTLY the same issue, and I am so happy that you had already figured out a work around because that worked for me too!
I am on a Qnap TS-453Be, version 4.4.2.1320

**Comment by elysiandc** [comment]
Same here too. OMV 5 on a QNAP TS-459 Pro +, linuxserver/unifi-controller:latest deployed via Portainer 1.24
Connecting via port 8443 worked for me as well.

**Comment by P3pit0r** [comment]
Hello, I am having the same issue.
I am running the docker container on a Pi 4 but I do not see at which step I should use port 8443 instead of port 8080. I just recently started using a Pi4 and getting my nose in networking, so please excuse me if my question is silly.

Here is the command I am using to get & run the container :

`sudo docker run -d --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Brussels' -v /home/pi/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7`

Thank you for your help !

**Comment by jackvanderson** [comment]
> Hello, I am having the same issue.
> I am running the docker container on a Pi 4 but I do not see at which step I should use port 8443 instead of port 8080. I just recently started using a Pi4 and getting my nose in networking, so please excuse me if my question is silly.
> 
> Here is the command I am using to get & run the container :
> 
> `sudo docker run -d --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Brussels' -v /home/pi/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7`
> 
> Thank you for your help !

I will be honest, I am not sure about the command to start it, but when I go to access the Unifi page via browser, I just used 8443

**Comment by PrplHaz4** [comment]
I don't believe the WebUI is supposed to be available on 8080 - what makes you think it is?

Per Unifi docs - 8080 is `Port used for device and controller communication.`, and the install docs only mention accessing the controller on 8443.

Install: https://help.ui.com/hc/en-us/articles/360012282453-UniFi-How-to-Set-Up-a-UniFi-Network-Controller
Ports: https://help.ui.com/hc/en-us/articles/218506997-UniFi-Ports-Used

**Comment by BBaoVanC** [comment]
After seeing this, I tried connecting to port 8080, but it just immediately redirects to port 8443.

**Comment by OscarVanL** [comment]
@PrplHaz4 At the time of creating this issue, the latest `stable` release would allow connections on port 8080, which would go to a web configuration page.

I am seeing the behaviour @BBaoVanC describes with the redirection now.

In this case, it looks like the issue is solved. If other people who experienced the issue are also satisfied, I'm happy to close the issue.

**Comment by dawngerpony** [comment]
For the record, I can reproduce this **without** running the Unifi Network Controller in a Docker container. I'm running on a Raspberry Pi. I don't think this is a Docker issue.
