### ISSUE TITLE
5.14.X Build?

### ISSUE THREAD

**Issue by oester** [jacobalberty/unifi-docker#322]
Now that 5.13.29 has been pushed to production, any plans to provide a 5.14.X build? This level is needed for some of the early access devices.

**Comment by jacobalberty** [comment]
Use the beta tag you need to provide the environment variable PKGURL to the relevant package. My understanding of the beta builds is we are not to distribute them so as a workaround I have an image that takes a PKGURL and installs the package from that url on first launch.

**Comment by oester** [comment]
Thanks, that will work.
