### ISSUE TITLE
New arm builds include empty cacerts file - prevents remote connectivity

### ISSUE THREAD

**Issue by dtucny** [jacobalberty/unifi-docker#323]
### Host operating system

CentOS 7

### What tag are you using

arm32v7 and 5.13.29-arm32v7

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -d --init --net=host -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Asia/Manila' -e RUNAS_UID0=false -e UNIFI_UID=1000 -e UNIFI_GID=1000 -v /unifi:/unifi:Z --name unifi --restart unless-stopped jacobalberty/unifi:5.13.29-arm32v7

### What do you expect to happen?
After updating, checks for controller and firmware updates should work, the mobile app should work and remote connectivity should work.

### What actually happens?
Anything that tries to talk to the internet within the controller fails with "java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"

### Notable observations
Image size had grown from 539MB to 715MB.
The file /etc/ssl/certs/java/cacerts is only 32 bytes in the new images.
There are a number of core dumps included in the image, including in /etc/sss/certs/.
./etc/ssl/certs/qemu_java_20200615-205744_8201.core
./etc/ssl/certs/core

### Workaround
Create /unifi/init.d/fixcacerts.sh and make executable with the following:
--- cut ---
#!/bin/bash
rm /etc/ssl/certs/java/cacerts 2> /dev/null; update-ca-certificates -f
--- cut ---

**Comment by jacobalberty** [comment]
I wonder if its related to this bug https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1667263.html

**Comment by tyler611** [comment]
The workaround doesn't work for me on this build.

**Comment by kpine** [comment]
I was successful using the workaround. @tyler611 Make sure you name the script something like `fixcacerts`, **not** `fixcacerts.sh`. The script will never actually be run if the filename has a period.

**Comment by jacobalberty** [comment]
OK I've come up with a clean way to apply a hotfix like fixcacerts and allow it to be removed later when not needed. I'm going to start working on applying it and bubbling it out to the rest then I'll add fixcacerts to the arm32 cross stuff where it's needed,  should be easier to add a fix like that later with what I have planned.

**Comment by jphellemons** [comment]
I've tried this fix with `jacobalberty/unifi:arm32v7-beta` but it's still unhealthy

**Comment by tyler611** [comment]
@kpine thank you! leaving off .sh did the trick. I'm good enough with linux to be dangerous, not good enough to have known that trick. I appreciate the help!

**Comment by wurmr** [comment]
Another workaround is a quick custom Dockerfile to build your own image based on the fix above:

Dockerfile
```
FROM jacobalberty/unifi:5.13.32-arm32v7
RUN rm /etc/ssl/certs/java/cacerts 2> /dev/null; update-ca-certificates -f
```

**Comment by jacobalberty** [comment]
Does this issue still exist in the new `multiarch` or `multiarch-5` tags?

**Comment by jacobalberty** [comment]
I did a bit of digging while fixing my cups builds. I think i need to add a script that runs `c_rehash` to the armhf (i think arm64 does not suffer from this bug) in the new `multiarch` tags. But I would like to get confirmation from someone running a 32 bit arm distro that the issue still exists before I add the script

**Comment by jacobalberty** [comment]
Closed because I confirmed from my raspi it works.
