### ISSUE TITLE
Unraid - Upgrading docker keeps on deleting all my data and keep on loosing all, how can i avoid that ? 

### ISSUE THREAD

**Issue by vdhub** [jacobalberty/unifi-docker#324]
### Host operating system
Unraid 6.8.3
### What tag are you using
stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

_The docker image was taken from apps plugin within unraid , it works perfectly until the update comes, i already lost all on the last update and had to redo all the settings, now it happened the same thing._ actually no , apparently i did it, so what i did wrong here i guess ? 

?xml version="1.0"?>
<Container version="2">
  <Name>unifi</Name>
  <Repository>jacobalberty/unifi</Repository>
  <Registry>https://hub.docker.com/r/jacobalberty/unifi</Registry>
  <Network>br0</Network>
  <MyIP>xxx.xxx.xxx.xxx</MyIP>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://forums.lime-technology.com/topic/60168-support-gitea/</Support>
  <Project/>
  <Overview> Unifi controller, used to manage unifi devices</Overview>
  <Category>Tools: </Category>
  <WebUI>http://[IP]:[PORT:8443]</WebUI>
  <TemplateURL/>
  <Icon>https://test.com/3934889.png</Icon>
  <ExtraParams>--memory=2G</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1587925841</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Description> Unifi controller, used to manage unifi devices</Description>
  <Networking>
    <Mode>br0</Mode>
    <Publish>
      <Port>
	<HostPort>8443</HostPort>
        <ContainerPort>8443</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
      <Port>
	<HostPort>8080</HostPort>
        <ContainerPort>8080</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
      <Port>
	<HostPort>6789</HostPort>
        <ContainerPort>6789</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
      <Port>
	<HostPort>3478</HostPort>
        <ContainerPort>3478</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
      <Port>
	<HostPort>8880</HostPort>
        <ContainerPort>8880</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
    </Publish>
  </Networking>
 <Data>
    <Volume>
      <HostDir>/mnt/user/appdata/unifi</HostDir>
      <ContainerDir>/data</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir>/mnt/user/appdata/unifi</HostDir>
      <ContainerDir>/data</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment/>
  <Labels/>
  <Config Name="Unifi Secure Web Access" Target="8443" Default="8443" Mode="tcp" Description="Container Port: 8443" Type="Port" Display="always" Required="true" Mask="false">8443</Config>
  <Config Name="DEvice Inform HTTP" Target="8080" Default="8080" Mode="tcp" Description="Container Port: 8080" Type="Port" Display="always" Required="true" Mask="false">8080</Config>
  <Config Name="Speedtest Unifi" Target="6789" Default="6789" Mode="tcp" Description="Container Port: 6789" Type="Port" Display="always" Required="true" Mask="false">6789</Config>
  <Config Name="STUN Service" Target="3478" Default="3478" Mode="tcp" Description="Container Port: 3478" Type="Port" Display="always" Required="true" Mask="false">3478</Config>
  <Config Name="Unifi HTTP Access" Target="8880" Default="8880" Mode="tcp" Description="Container Port: 8880" Type="Port" Display="always" Required="true" Mask="false">8880</Config>
  <Config Name="Host Path 1" Target="/data" Default="/mnt/user/appdata/unifi" Mode="rw" Description="Container Path: /data" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/unifi</Config>
  <Config Name="Data Storage Path" Target="/data" Default="/mnt/user/appdata/unifi" Mode="rw" Description="Container Path: /data" Type="Path" Display="advanced" Required="true" Mask="false">/mnt/user/appdata/unifi</Config>
</Container>

this is the config, the folders were automatically created when the container was created but no data inside , so no idea where the data is and why it keeps on resetting every time i do an upgrade 

### What do you expect to happen?
To do the proper update same like the other containers

### What actually happens?

It keep on deleting all my configs and starts as a new container with completely new setup like it was installed for the first time.

**Comment by MushyMiddle** [comment]
I just upgraded to the latest image, and had no issues with data loss.  I'm using Container Station on QTS (QNAP), so can't comment on how that maps to Unraid, but in my case, I map the /unifi volume to a share on my NAS.  According to the docs, I could alternatively map just /unifi/data, but this allows me to also include my Let's Encrypt cert in the same volume and maintain it as well.

That said, I do wonder how Unifi handles things like schema upgrades in this scenario.  But I think if you map your volumes properly, it should work for you.

**Comment by vdhub** [comment]
> I just upgraded to the latest image, and had no issues with data loss. I'm using Container Station on QTS (QNAP), so can't comment on how that maps to Unraid, but in my case, I map the /unifi volume to a share on my NAS. According to the docs, I could alternatively map just /unifi/data, but this allows me to also include my Let's Encrypt cert in the same volume and maintain it as well.
> 
> That said, I do wonder how Unifi handles things like schema upgrades in this scenario. But I think if you map your volumes properly, it should work for you.
> 
> P.S. Also, just in case, anytime I upgrade the controller, I first download the latest DB backup, as you can always just restore your backup on a fresh install and that should recover things. This also makes it easy to transition from a VM or real machine into Docker.

Well apparently you are right , I just did a backup, deleted the container and moved instead of /data  I let the whole /unifi there and miracle the whole folders start to appear so I guess hopefully next upgrade nothing will be deleted anymore . Thanks.
