### ISSUE TITLE
Ubuntu 20.04 on a Raspberry PI 4 gives issues?

### ISSUE THREAD

**Issue by jphellemons** [jacobalberty/unifi-docker#325]
### Host operating system

Ubuntu 20.04 LTS on a Raspberry PI 4
`uname -srm` gives Linux 5.4.0-1011-raspi aarch64

### What tag are you using

`stable` but also tried `arm32v7`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

stable: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Amsterdam' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:stable`

arm32v7: 
`docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Amsterdam' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7`

### What do you expect to happen?
total (wifi) world domination

### What actually happens?
*with stable:*
`[FATAL tini (7)] exec /usr/local/bin/docker-entrypoint.sh failed: Exec format error`
*with arm32:*
```
[2020-06-21 07:57:42,511] <docker-entrypoint> Starting unifi controller service.
[2020-06-21 07:57:42,517] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
Unable to load '/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
^C[2020-06-21 08:01:04,957] <docker-entrypoint> Exit signal received, shutting down
```
this one took so long, I thought it had crashed. So I closed it.
I probably messed something up. I made a unifi folder in my home dir and in there a data and log folder.

**Comment by jphellemons** [comment]
Never mind, seems that I created my unifi folder in /home/username instead of /usr/lib

**Comment by jphellemons** [comment]
docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Amsterdam' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7

gives unhealthy and a webinterface on 8080 is unavailable. please let me know what logs to look at

**Comment by jphellemons** [comment]
I have tried 3 tags: 
- latest
- stable
- arm32v7

started with this:
`docker run -d --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Amsterdam' -v /home/ubuntu/unifi:/unifi --name unifi jacobalberty/unifi:latest`

**Comment by jphellemons** [comment]
`docker exec unifi ps` gives me
```
    PID TTY          TIME CMD
      1 ?        00:00:00 docker-init
      6 ?        00:00:00 bash
     17 ?        00:00:24 java
   1230 ?        00:00:00 ps
```

docker ps shows that the container is unhealty

**Comment by jphellemons** [comment]
Also tried tag `arm32v7-beta` but that also says: unhealthy.

**Comment by jacobalberty** [comment]
What happens now with `latest` or `6.0`?
