### ISSUE TITLE
Update Controller software on QNAP NAS

### ISSUE THREAD

**Issue by barbatrukko** [jacobalberty/unifi-docker#329]
### Host operating system

QNAP TS-853A, Firmware 4.4.2.1320

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Standard Container station, just mapped volumes

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

After pull have latest software version

### What actually happens?

When i log on i read this message:
"Controller software update 5.13.29 is now available."
and i can download a >120MB xxx.deb file: how I must use?
What is the correct way to upgrade controller software?

**Comment by ning42** [comment]
Try looking at this post
https://github.com/jacobalberty/unifi-docker/issues/100
