### ISSUE TITLE
raspi Zero W - container endless restarting

### ISSUE THREAD

**Issue by bonobo15566** [jacobalberty/unifi-docker#333]
### Host operating system

Example: Raspbian GNU/Linux 10 (buster)`

### What tag are you using

Example: `arm32v7`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

sudo docker run -d --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Berlin' -v /home/pi/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7

Installed docker with:
curl -fsSL https://get.docker.com -o docker.sh
sh docker.sh
sudo usermod -aG docker pi

### What do you expect to happen?
container should work :)

### What actually happens?
container is restarting permanently and logs are complete empty.

**Comment by johanneskonst** [comment]
Same here, container keeps restarting, no information in logs...

Ubuntu 20.04 on x86_64

`unifi      | [2020-07-08 00:54:22,501] <docker-entrypoint> Cert directory found. Checking Certs
unifi      | [2020-07-08 00:54:22,515] <docker-entrypoint> Cert has not changed, not updating controller.
unifi      | [2020-07-08 00:54:22,534] <docker-entrypoint> Starting unifi controller service.
unifi      | [2020-07-08 00:54:22,540] <docker-entrypoint> WARN: unifi service process ended without being signaled? Check for errors in /unifi/log.
unifi      | [2020-07-08 00:55:26,500] <docker-entrypoint> Cert directory found. Checking Certs
unifi      | [2020-07-08 00:55:26,515] <docker-entrypoint> Cert has not changed, not updating controller.
unifi      | [2020-07-08 00:55:26,532] <docker-entrypoint> Starting unifi controller service.
unifi      | [2020-07-08 00:55:26,538] <docker-entrypoint> WARN: unifi service process ended without being signaled? Check for errors in /unifi/log.
`

**Comment by jacobalberty** [comment]
Can yo give this a try now with the `latest` tag  now instead of the old `arm32v7` tag there were quite a few changes that directly affect arm devices and should make things more reliable on devices like the raspi zero w
