### ISSUE TITLE
Device Fingerprint > Find Icon not working anymore

### ISSUE THREAD

**Issue by jtreml** [jacobalberty/unifi-docker#335]
When opening the GUI and clicking on 'Device Fingerprint' of any of the network devices with a generic icon, one is able to click on 'Action - Find Icon' to manually select an icon for the device.

This used to work properly but since a few versions ago up until the current version at the time of writing, it throws an error in the form of a dialog box saying:

```
Failed to load
Some data requirements failed to load. Please try again later.
```

### Host operating system

 Debian buster

### What tag are you using

arm32v7

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

-v /xxx/unifi:/unifi

**Comment by BBaoVanC** [comment]
I am not having this issue on my amd64 host.

**Comment by SZanlongo** [comment]
I have this issue as well. Running the same controller (restored using the settings exported from docker) works fine though.
Also, it seems that the docker image can no longer check for firmware updates.

By chance, do you have this set up on a macvlan network only?

**Comment by Faerylnahr** [comment]
Hi,
I experienced the same problem and found following solution. Maybe @jacobalberty could add the command to the docker build file if possible.

The following command which I ran within the docker console solved the issue for me. In addition I restarted the docker container afterwards
`rm /etc/ssl/certs/java/cacerts 2> /dev/null; update-ca-certificates -f`

Source: https://community.ui.com/questions/Device-Fingerprint-Feature-information/695b50b5-b2c7-49ac-9537-2356df1da6b9

Hopefully this solution helps others as well 👍

**Comment by jtreml** [comment]
That does indeed fix the problem. Hopefully @jacobalberty could fix that in the image, though, so this procedure doesn't have to be run on every update.

Regarding earlier posts:
- Can't speak about x86_64, in my case, this happens with arm32v7.
- Not using a macvlan network, indeed I'm running it with `--net=host`
