### ISSUE TITLE
Any chance of a 5.14.x tracking version ? Just added a test wifi6 device to my network and it requires > 5.14.9

### ISSUE THREAD

**Issue by robertcoles** [jacobalberty/unifi-docker#336]
### Host operating system

Synology DSM 6.2.3-25426

**Comment by JakeDEvans** [comment]
Bump, looks like 5.14.22 is GA
https://community.ui.com/releases/UniFi-Network-Controller-5-14-22/65337b17-f6e4-4f91-b78e-a4db05826e41

**Comment by JakeDEvans** [comment]
@robertcoles you can use my fork until his is ready - https://hub.docker.com/r/jacobdevans/unifi
