### ISSUE TITLE
Unable to access Controller Interface

### ISSUE THREAD

**Issue by Blizzardo1** [jacobalberty/unifi-docker#340]
### Host operating system

Debian Buster

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker create \
  --name=unifi-controller \
  -e PUID=1000 \
  -e PGID=1000 \
  -e MEM_LIMIT=1024M \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 1900:1900/udp \
  -p 8843:8843 \
  -p 8880:8880 \
  -p 6789:6789 \
  -p 5514:5514  \
  -v path to data:/config \
  --restart unless-stopped \
  linuxserver/unifi-controller

### What do you expect to happen?
I expect to access the controller at :8443

### What actually happens?
Unable to connect to controller, time out, despite packets being sent to the server. I have access to every other docker container but this one, I don't know why, and it's making me want to throw my server out the window.

**Comment by Blizzardo1** [comment]
So after about an hour including the 5 minutes from this post, I have access again, after dropping my session to the trash and restarting, and then restarting the daemon,  I see the controller, but I have no logs stating what was happening. This is the first time I've ever had an issue, and it looks like it's likely a unique one, because as I said, the firewall was allowing traffic, but the container was not responding to the requests. Unsure if close for now, or leave open for some sort of investigation

**Comment by SaswatPadhi** [comment]
You're using the docker image for another repo: https://github.com/linuxserver/docker-unifi-controller
