### ISSUE TITLE
Does not work with UniFi AP-AC-Mesh

### ISSUE THREAD

**Issue by skelgaard** [jacobalberty/unifi-docker#341]
### Host operating system

Synology docker

### What tag are you using

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -p 8090:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Copenhagen' -v /volume1/docker/unifi:/unifi --name unifi jacobalberty/unifi:stable

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
it doesn't connect proper to UniFi AP-AC-Mesh

I tried making a new controller, adding the UniFi AP-AC-Mesh and it creates, but the wifi newer comes up.

I then installed their windows controller, and works, then did a backup, retored on the docker, and it then goes back to error saying that UniFi AP-AC-Mesh is disconnected.

### What actually happens?

connect proper to UniFi AP-AC-Mesh

**Comment by edeca** [comment]
The current `stable` image (`567b207048513bdc51fbb2a74569d468250917b642c304d4c6f7937b92754669`) works fine for me with an AP-AC-Mesh. I am running in Docker on Linux with the following ports forwarded: 3478/udp, 6789/tcp, 8080/tcp, 8443/tcp, 8843/tcp.
