### ISSUE TITLE
arm beta not using PKGURL?

### ISSUE THREAD

**Issue by deornoth** [jacobalberty/unifi-docker#342]
Debian Stretch on RPi3.

arm32v7-beta

docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/Chicago' -e RUNAS_UID0='false' -e PKGURL='https://dl.ui.com/unifi/5.14.20-bd8311653e/unifi_sysvinit_all.deb' -v /home/pi/docker/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7-beta

Version 5.13.32 is installed, not 5.14.20.  

.20 actually came out this morning, but I was trying 5.14.18 all weekend and getting the same result. I always end up with 5.13.32.

**Comment by jacobalberty** [comment]
The arm beta was beta in that it was testing the cross building, it had been deprecated but the tags were never removed from the docker hub (to avoid breaking existing setups). The main `beta` tag now officially has arm support in it. 

There's one caveat with your command line though RUNAS_UID0 is removed from beta the user flag is the way going forward, however the user flag is not compatible with beta right now. I will be working out a fix soon, likely involving sudo, I need to work out how to get sudo properly locked down for the container though.. But as is your command line would work just fine replacing `jacobalberty/unifi:arm32v7-beta` with `jacobalberty/unifi:beta, RUNAS_UID0 would simply be ignored
