### ISSUE TITLE
Does not work on aarch64 platform?

### ISSUE THREAD

**Issue by pixeltronics** [jacobalberty/unifi-docker#344]
### OS

QNAP TS-328

### What tag are you using

arm32v7

### What do you expect to happen?
I expect to access the controller at :8443

### What actually happens?
Unable to connect to controller, time out (container is running). QNAP supprt tells me, that there isn't a matching version for aarch64 platforms. Is this correct?

**Comment by jacobalberty** [comment]
I believe this is fixed by #369  give `latest` a try, `arm32v7` tag is gone now with the unified multiarch images.

**Comment by pixeltronics** [comment]
Great! Multiarch images matches now wit my QNAP. Thanks a lot !
