### ISSUE TITLE
Repository and releases, community support

### ISSUE THREAD

**Issue by ThomDietrich** [jacobalberty/unifi-docker#347]
Hey @jacobalberty,

hope you are doing great. I do not want to step on anyone's toes or lessen the tremendous work you've done here so far. Thanks for maintaining this image.

It seems like you are not as active as you used to. That is totally understandable. I wanted to ask if you considered giving a second person elevated permissions for the repository. They could help with the day-to-day business like handling trivial Issues or merging PR #346. 

Looking at https://github.com/jacobalberty/unifi-docker/graphs/contributors maybe @rohanrns is a suited candidate?

Just an idea. Of course it is totally acceptable if you prefer to stay the sole manager of the project.
All the best, th

**Comment by codeaholics** [comment]
Don't forget that there's no reason why you can't fork this repo and build your own images while you wait for @jacobalberty to catch up.

**Comment by GnusBjelin** [comment]
Thanks. Gonna update my skills for that.

Med vänliga hälsningar / Best regards

 <https://bjelin.com/>	
Magnus Hallgard
SYSTEM ADMINISTRATOR 
Tel.+46101516719
--------------------------------
Bjelin Sweden AB
 Apelvägen 2, 263 62 Viken - Sweden <>

www.bjelin.se <https://bjelin.se/>

We process your personal data in accordance with the General Data Protection Regulation "GDPR". For more information about this, request for rectification or erasure etc., visit our website: www.bjelin.com/privacy/ <https://n-ywv5ciy2u4ntjhnzmfrwz4yeitj3nruyxrn7dna-0lu-script.googleusercontent.com/www.bjelin.com/privacy/>. This e-mail and any attachments are intended only for the addressees and contains confidential information. If you have received this e-mail in error, please notify us immediately and delete the message from your system.

**Comment by ThomDietrich** [comment]
Old ticket whose claim was unfounded. Great work and thanks @jacobalberty !!!
