### ISSUE TITLE
Check For Updates Failed

### ISSUE THREAD

**Issue by dhunterjacobs** [jacobalberty/unifi-docker#350]
### Host operating system

Debian

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -d \
-p 8080:8080 \
-p 8443:8443 \
-p 3478:3478/udp \
-p 10001:10001/udp \
-e TZ=America/New_York \
-v ~/unifi:/unifi \
--restart=unless-stopped \
--name unifi \
jacobalberty/unifi:stable

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

Firmware updates are checked for successfully.

### What actually happens?

Clicking the "Check for Updates" button under Updates>General fails. The same result happens for both controller and firmware updates. It used to work, from what I can tell the issue began when updating the container to the latest stable release, 5.14.23. 

Anyone else seeing this issue?

**Comment by 3DIRK** [comment]
Might be of #323 - at least that's what my installation shows

**Comment by dhunterjacobs** [comment]
Well, chalk this one up to "have you turned it off and on again?"

I rebooted the Debian server and now check for updates works fine. We had a power outage a few nights ago so I guess something must have gotten out of whack.
