### ISSUE TITLE
Unifi Network Controller Version 6.0

### ISSUE THREAD

**Issue by ThomDietrich** [jacobalberty/unifi-docker#351]
Hey community,
Ubiquiti releases the third release of the new controller version 6. https://community.ui.com/releases
I was wondering when this project will follow to provide an image. Did anyone already look into this?

Let's use this ticket to discuss

Best! Thomas

**Comment by jacobalberty** [comment]
As far as I know 6.0 is in rc status still. It hasn't been released yet

**Comment by sanyer** [comment]
I'm trying to use it with beta tag, but getting this error for some reason: `standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by sanyer** [comment]
oh, right
`beta` is available only for amd64 platform

**Comment by apo-mak** [comment]
It is now the new stable :
 https://community.ui.com/releases/UniFi-Network-Controller-6-0-20/3ddd1684-6747-4a66-a038-5ff0b25f4027

Pull request:
https://github.com/jacobalberty/unifi-docker/pull/353

**Comment by Hardtarget24** [comment]
Yup, was just coming to mention 6.0.20 has hit stable, was wondering if this project was going to be switching to the 6.x release.

**Comment by jacobalberty** [comment]
@Hardtarget24 i will definitely be moving to  6.x just trying to decide the best way to handle that  as 6.0.20 breaks wireless for a lot of people.

**Comment by lukasa1993** [comment]
its out… when will docker image be pushed ?

**Comment by jacobalberty** [comment]
@lukasa1993 although it has been tagged stable there are unfortunately still major bugs in 6.0.x which mean if I push 6.0 to the 'latest' tag on docker it will very likely break production networks for anyone using watchtower,  I have a [proposed solution on the pull request](https://github.com/jacobalberty/unifi-docker/pull/353) I am taking comments on now. I will likely begin the tagging changes to implement that solution within the next hour or so unless someone has a improvements to that solution.

**Comment by lukasa1993** [comment]
> @lukasa1993 although it has been tagged stable there are unfortunately still major bugs in 6.0.x which mean if I push 6.0 to the 'latest' tag on docker it will very likely break production networks for anyone using watchtower, I have a [proposed solution on the pull request](https://github.com/jacobalberty/unifi-docker/pull/353) I am taking comments on now. I will likely begin the tagging changes to implement that solution within the next hour or so unless someone has a improvements to that solution.

uh they messed up so much ?

**Comment by jacobalberty** [comment]
I think they were simplifying the wlan settings code and it exposed ancient bugs around vlan tagging. A lot of people (my home network included) got bit by a bug where 6.0.20 applied vlans to the wlan networks that did not exist under 5.14.x. As far as I know going forward 6.0.20 is stable but that initial provision may kick anyone off, so the jist of it is I will likely be making a new `stable-6` tag to use for a bit and leave `latest` on 5.14.x while also creating a new `stable-5` for 5.14.x at some point  in the near future when enough users have had a chance to manually upgrade and correct any networking issues, `latest` will become `stable-6`.

**Comment by lukasa1993** [comment]
> I think they were simplifying the wlan settings code and it exposed ancient bugs around vlan tagging. A lot of people (my home network included) got bit by a bug where 6.0.20 applied vlans to the wlan networks that did not exist under 5.14.x. As far as I know going forward 6.0.20 is stable but that initial provision may kick anyone off, so the jist of it is I will likely be making a new `stable-6` tag to use for a bit and leave `latest` on 5.14.x while also creating a new `stable-5` for 5.14.x at some point in the near future when enough users have had a chance to manually upgrade and correct any networking issues, `latest` will become `stable-6`.

so if i use RC here its stable of theres 6 version right ?

**Comment by jacobalberty** [comment]
@lukasa1993 `6.0.20-rc` is the exact same build as what the stable will be yes

**Comment by lukasa1993** [comment]
> @lukasa1993 `6.0.20-rc` is the exact same build as what the stable will be yes

okay thank you

**Comment by jacobalberty** [comment]
Controller version 6.0 is now up under the tags `6.0` and `stable-6` as well as the usual `6.0.20`. I will probably wait about a month  before bringing it to `stable` and `latest` so anyone who has a setup that may be broken by the upgrade has a chance to manually fix it without being caught totally off guard. If Ubiquiti releases a version that migrates the old settings to 6 safely I will go ahead and move the tags at that time. README.md has also been updated to reflect the new tags.

**Comment by it-can** [comment]
Will version 6 also work on synology docker? the latest version works great, but when downloading stable-6 the download just fails...

**Comment by jacobalberty** [comment]
Sounds like that was an issue with the docker hub.

Ubiquiti pushed out a fix for one of the biggest holdups with 6.0.x yesterday. It's building on the hub now I highly advise anyone use 6.0.22 instead of 6.0.20, in fact I will be deleting the 6.0.20 tags as soon as 6.0.22 is done building. It is unfortunately not able to safely replace the main stable tag yet.

**Comment by it-can** [comment]
> Sounds like that was an issue with the docker hub.
> 
> Ubiquiti pushed out a fix for one of the biggest holdups with 6.0.x yesterday. It's building on the hub now I highly advise anyone use 6.0.22 instead of 6.0.20, in fact I will be deleting the 6.0.20 tags as soon as 6.0.22 is done building. It is unfortunately not able to safely replace the main stable tag yet.

seems done building, updated stable-6 and got 6.0.22

**Comment by yoyellow** [comment]
updated from stable-5 to stable-6 (6.0.22) without any noticable issues.

**Comment by douklias** [comment]
Just updated to stable-6 (6.0.22). It seems to be working fine. No issues yet.

**Comment by ik234** [comment]
Is there any special update steps? I'm currently on 5.13.32 created by command 
docker create -e TZ='Europe/Moscow' -e RUNAS_UID0=false -v /home/unifi/unifi:/unifi --net=host --restart unless-stopped -e JVM_MAX_HEAP_SIZE=4096M -e JVM_INIT_HEAP_SIZE=2048M --user unifi --name unifi jacobalberty/unifi:latest

when i recreated container, it failed to start
[2020-09-19 18:13:42,065] <docker-entrypoint> Starting unifi controller service.
2020-09-19 18:13:42,686 main ERROR RollingFileManager (logs/server.log) java.io.FileNotFoundException: logs/server.log (Permission denied) java.io.FileNotFoundException: logs/server.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
What i'm doing wrong?

**Comment by nicx** [comment]
tried the update... bad idea, I got the broadcast storm mentioned here: https://community.ui.com/questions/Broadcast-storm-after-Unifi-controller-upgrade-to-6-0-20/0b924047-0632-4304-bada-4158a0a5349e and had to rollback everything :(

Thats not a "stable" in any case ;)

**Comment by gmg1967** [comment]
Just installed the stable-6 version on my Synology. Worked great, so thanks to Jacob! What I don't understand for the life of me is why they dropped MAC address whitelist filtering? I first thought I am crazy as I couldn't find it, but it's a feature that they took out (see https://community.ui.com/questions/Unifi-Controller-6-0-20-Mac-Filtering-Settings/60ab199a-e9b5-4750-a850-5e4d1c66bb91). I will stick to 5 for now...

**Comment by ThomDietrich** [comment]
@gmg1967 there is mentioning of MAC filtering in the changelog for 6.0.23

I'm going to close this issue. Thanks @jacobalberty
