### ISSUE TITLE
PKGURL being ignored in beta?

### ISSUE THREAD

**Issue by fongd** [jacobalberty/unifi-docker#355]
### Host operating system

Ubuntu 20.04.1 LTS

### What tag are you using

`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

<pre>
  unifi:
    image: jacobalberty/unifi:beta
    container_name: unifi
    depends_on:
      - pihole
    volumes:
      - /opt/dockerdata/unifi:/unifi
    ports:
      - 3478:3478/udp  # STUN service
      - 6789:6789/tcp  # speedtest
      - 8080:8080/tcp  # device command/control
      - 8443:8443/tcp  # web interface + API
      - 8843:8843/tcp  # HTTPS portal
      - 8880:8880/tcp  # HTTP portal
      - 10001:10001/udp  # UBNT discovery
    environment:
      - TZ=${TZ}
      - RUNAS_UID0=false
      - UNIFI_UID=1003
      - UNIFI_GID=1003
      - PKGURL=https://dl.ui.com/unifi/5.14.23-70ddb4015a/unifi_sysvinit_all.deb
    restart: unless-stopped
</pre>

### What do you expect to happen?

I should be using UniFi Controller 5.14.23

### What actually happens?

My container was automatically upgraded to 6.0.23

I've been using this configuration for months and was hoping to stay off the 6.x train until Ubiquiti stabilizes it but the update to https://hub.docker.com/layers/jacobalberty/unifi/beta/images/sha256-1047b5c435e0cd83b25036e6255a671c586c33e837803b9a35ad2886875a632e?context=explore seems to be ignoring PKGURL and has upgraded my controller to 6.0.23.

**Comment by jacobalberty** [comment]
Looks like it happened when I merged in #206 into beta to bring it out to master.
I've cleared PKGURL in beta again.
