### ISSUE TITLE
Cannot configure Controller

### ISSUE THREAD

**Issue by Volle83** [jacobalberty/unifi-docker#356]
### Host operating system

Docker on QNAP TS-673

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
Installing with ContainerStation

### What do you expect to happen?
Doing First Setup 

### What actually happens?
When configuring the new container, in Step 6 of 6 appears:
Cannot configure Controller
Invalid username or password, please try again.

The credentials in step 2 are correct

**Comment by martindlarsson** [comment]
Same issue here. Running on a fresh Ubuntu 20.04 install. The host machine is an old Dell laptop and I am connecting to it through SSH and running the setup in Chrome on a Mac book pro.

Ran the following command:
sudo docker run --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Europe/Stockholm' -v ~/unifi:/docker_volumse/unifi --name unifi --restart unless-stopped jacobalberty/unifi:stable

It also does not release the prompt in bash. So when I hit ctrl+c to get control over the promt again, it shuts down the container. How do I get it to run and release the promt?

**Comment by PrplHaz4** [comment]
> 
> 
> Same issue here. Running on a fresh Ubuntu 20.04 install. The host machine is an old Dell laptop and I am connecting to it through SSH and running the setup in Chrome on a Mac book pro.
> 
> Ran the following command:
> sudo docker run --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Europe/Stockholm' -v ~/unifi:/docker_volumse/unifi --name unifi --restart unless-stopped jacobalberty/unifi:stable
> 
> It also does not release the prompt in bash. So when I hit ctrl+c to get control over the promt again, it shuts down the container. How do I get it to run and release the promt?

This does not seem like the same issue as you are not using ContainerStation.

Use `-d` to detach, and it looks like your volume mapping is off (also volumes is spelled wrong) - maybe try:

```
sudo docker run --init -d -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Europe/Stockholm' -v ~/unifi:/unifi --name unifi --restart unless-stopped jacobalberty/unifi:stable
```

**Comment by martindlarsson** [comment]
Tried your command above but no go. I deleted the image and container in Portainer. Also created a volume named unifi and ran your command. It starts up fine and I put in my credentials in set 2 of 6, no devices to setup and skipped step 5 to setup Wifi. And in the last step it starts setting up but only gets to about 40% and then says my username and password is incorrect.

I had a controller set up before and after new install of Ubuntu 20.04 on the same machine I am trying to set up a new controller replacing the old. E.g. I have a working network but I guess I will have to start from scratch because I didn't create a backup.
<img width="895" alt="Screenshot 2020-09-29 at 12 43 53" src="https://user-images.githubusercontent.com/14070530/94549312-4ef22d00-0252-11eb-83c7-7cc254899235.png">

**Comment by PrplHaz4** [comment]
> 
> 
> Tried your command above but no go. I deleted the image and container in Portainer. Also created a volume named unifi and ran your command. It starts up fine and I put in my credentials in set 2 of 6, no devices to setup and skipped step 5 to setup Wifi. And in the last step it starts setting up but only gets to about 40% and then says my username and password is incorrect.
> 
> I had a controller set up before and after new install of Ubuntu 20.04 on the same machine I am trying to set up a new controller replacing the old. E.g. I have a working network but I guess I will have to start from scratch because I didn't create a backup.

It sounds like you created a new (empty) volume and are already configuring the controller from scratch.  Was your previous controller running in docker?  The command that I gave you would have put the Unifi controller data on the local drive at `~/unifi` (or used whatever controller data existed there before).

You may be able to use cloud access (if it was enabled) to log in and create a backup that you can then restore: https://network.unifi.ui.com/

**Comment by martindlarsson** [comment]
I found the solution!!
https://community.ui.com/questions/Getting-Invalid-username-or-password-please-try-again-when-setting-up-unifi-controller/92e619e8-efd8-488b-8dc4-f96cabbd57bc#answer/d4a927ff-451c-4a2f-bf7b-15900ee92f6f

I used http://ip.to.my.controller:8080 and got the error. When I switched to https://ip.to.my.controller:8443, clicked (Chrome) advanced and proceed to page, the setup went through OK. :)
