### ISSUE TITLE
Unable to Update Docker Image or Backup Unifi Controller Setings

### ISSUE THREAD

**Issue by Jonah1970** [jacobalberty/unifi-docker#363]
### Host operating system

Synology 918+ DSM version 6.2.3-2546 Update 2

### What tag are you using

Latest (but am unable to upgrade from 5.14.23 to 6.0.23)

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

![image](https://user-images.githubusercontent.com/53110372/96179186-61de5000-0f28-11eb-856f-be3a371e662f.png)

### What do you expect to happen?

(1) I should be able to upgrade to version 6.0.23 by downloading the "latest" version from the registry and then stopping, clearing, and restarting the container.

(2) Another problem I am having which may be related to the above is that I am unable to backup the Unifi Controller settings using the "Download File" button.

### What actually happens?

(1) From Synology DSM and after downloading the "latest" version from the Registry, I stop the container, clear, then restart the container.  However, upon restart I am still at the previous version 5.14.23.  I have even deleted the container plus the associated image, redownloaded "latest" from the registry and then reconfigured the container but it still comes up as 5.14.23.   

I have generally been following this guide https://lazyadmin.nl/home-network/unifi-controller-on-a-synology-nas-with-docker/ however I had to change port 8080 to another (8099) because originally the container would continually restart and there would be an error in the log to say that port 8080 is already in use.

I currently have /docker/unifi mapped to /var/lib/unifi (which I think I got from another guide) however I noticed that the release notes say that users are urged to move to using the new volumes ASAP.  I did try starting the container with /unifi rather than /var/lib/unifi however it again failed to start due to port 8080 being in use but despite me changing this to 8099 as before.

![image](https://user-images.githubusercontent.com/53110372/96181298-b1724b00-0f2b-11eb-8b0e-87207137a9bb.png)

I have since reverted the mapping to /var/lib/unifi and the Unifi Controller is working but still at version 5.14.23.

(2) The backup does not work and the "Download" button changes to a permanent spinning wheel.

![image](https://user-images.githubusercontent.com/53110372/96180320-2b093980-0f2a-11eb-8f1e-a8f43c1a3944.png)

**Comment by Er-Yas** [comment]
About your problem of updating to the 6.0 version. here is the readme in the first page :

latest tag
For now latest tracks latest-5 which is 5.14.x. This is due to some breaking changes when upgrading from 5.14.x to 6.0.x. At some time in the near future latest will get moved to the 6.0.x branch. This is your grace period to either upgrade to 6.0.x manually and ensure nothing breaks or move yourself to some 5.14.x tag that holds you there instead of continuing to track latest.

**Comment by Jonah1970** [comment]
Thanks for the heads-up ... the main reason I wanted to upgrade was to stop the annoying notification about a new version being available.  

I am happy to stay on 5.14.23 for now howvever it would nice to understand why I am unable to backup my settings.

Cheers Mate!

**Comment by jacobalberty** [comment]
The backup button on unifi is just slow. You have to click it and then just leave the window open for a while, it takes it a bit for it to build the backup. You might want to enable an automatic weekly backup instead and just download from that if you want regular backups.

**Comment by Jonah1970** [comment]
I left it going over 2hrs backup up just the settings and still just get the spinning wheel.  If I try and backup with 7 days worth of data then I immediately get the following error message:
![image](https://user-images.githubusercontent.com/53110372/96304928-e8f8fa00-0ff4-11eb-8683-9f58b959f350.png)

I'm wondering if it could be a file permission error ...
![image](https://user-images.githubusercontent.com/53110372/96305056-23629700-0ff5-11eb-9ffe-098bf626c21e.png)

**Comment by jacobalberty** [comment]
Aha. I see the error now. Backups is owned by root. You need to change the
owner is (and probably group id) to 999

**Comment by Jonah1970** [comment]
That was it, backups are now working fine.
Thank you for your help.
