### ISSUE TITLE
Bug latest "latest" build 

### ISSUE THREAD

**Issue by ChrisGIT1** [jacobalberty/unifi-docker#364]
After deploying the latest "latest" build I can't acces the controller anymore and get the following message: "UniFi Controller startup failed. We do not support upgrading from 6.0.23". I'm not a very experienced IT guy. I have the controller running on a docker instance on my Synology 918+ NAS and I'm using Watchtower for automatic updates. As of today Watchtower updates the new build of "latest" and since then the controller isn't working anymore.

Can someone help me a little bit, how to solve this?

**Comment by jacobalberty** [comment]
Unfortunately I briefly pushed 6 to `latest` while working on #360 . I pulled the tag and rebuilt `latest` from `stable-5` and hoped I did it quick enough to avoid anyone using watchtower from getting it.

You have two choices
1. restore from a recent backup, you may have one under your config folder in `data/backup`, or maybe under `autobackup` in that same folder.
2.  Move to `stable-6`

If you do want to stay on 5 and restore from a backup I would suggest using the `stable-5` tag instead. `latest` will be officially moving to 6 hopefully within the next week.

**Comment by ChrisGIT1** [comment]
I'll try to move to stable-6, thnx for your quick reply. Just to be sure about the steps I need to take:
- stop container latest
- delete container latest
- download stable 6
- install just like described on https://github.com/jacobalberty/unifi-docker/tree/83606ea53aaf5f785fa1c2b3accd8bdee20cb2d2

or don't I have to delete the current one? Should stopping it be enough? 

I'm using a Synology 918+ NAS which supports Docker

**Comment by jacobalberty** [comment]
That should work. Just make sure your `/unifi` volume is the same between the two installs

**Comment by ChrisGIT1** [comment]
Thanks, it works again with stable 6
