### ISSUE TITLE
New stable fails to run

### ISSUE THREAD

**Issue by hypnosis4u2nv** [jacobalberty/unifi-docker#365]
### Host operating system

QNAP NAS

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Watchtower 

### What do you expect to happen?

Should get to Unifi GUI

### What actually happens?

GUI Page:
UniFi Controller startup failed

We do not support upgrading from 6.0.23.

Portainer Images from Watchtower container update:

sha256:66b2b9081db9707abf01d2ff7af54a... Unused | jacobalberty/unifi:<none> | 822.4 MB | 2020-10-16 13:04:47
sha256:094b620effdde8108ecd4de1c95eb6... Unused | jacobalberty/unifi:<none> | 712.4 MB | 2020-10-16 12:45:19
sha256:485d0516d695bae076a0d2b1bec693... Unused | jacobalberty/unifi:<none> | 823.3 MB | 2020-09-15 11:37:51
sha256:c8857e3378155731b2d06df6d4ddf8... | jacobalberty/unifi:latest | 822.4 MB | 2020-10-16 15:50:06

Container Log:

[2020-10-16 15:54:17,862] <docker-entrypoint> Starting unifi controller service.,
[2020-10-16 15:54:17,864] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode

**Comment by jacobalberty** [comment]
It looks like you got bit by the same issue as #364  the solution options are the same.

**Comment by hypnosis4u2nv** [comment]
Sorry, didnt see the post you referred to. 

I had to stop the conatiner, delete the directory, duplicate it and use a backup to restore.

**Comment by jacobalberty** [comment]
It was marked closed so it's hidden from the default issues.
