### ISSUE TITLE
Can you add 6.1.x support?

### ISSUE THREAD

**Issue by arb15** [jacobalberty/unifi-docker#370]
For those of us using a UXG, can you add the 6.1.x branch please?

thanks!

**Comment by jacobalberty** [comment]
To try and maintain compliance with the early access agreement I don't build any images against beta versions. What I do instead is publish a `beta` tag with most of the pre-requisites and the relevant build scripts still in tact. See the [beta directions in README.md](https://github.com/jacobalberty/unifi-docker#beta-users). The one caveat with the beta image is right now --user does not work with the pre-built ones. I am working on getting that fixed as part of #362.
