### ISSUE TITLE
InvalidAlgorithmParameterException when trying to log in

### ISSUE THREAD

**Issue by BennyM** [jacobalberty/unifi-docker#376]
### Host operating system

`Raspberry Pi OS`

### What tag are you using

Example: `arm32v7`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`sudo docker run -d --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Brussels' -v /home/pi/unifi:/unifi --name unifi jacobalberty/unifi:arm32v7`

### What do you expect to happen?

Log into the controller after creating the container.

### What actually happens?

I followed this blog article to set everything up: https://tynick.com/blog/09-08-2019/unifi-controller-with-raspberry-pi-and-docker/

However when I want to log in I get this error in the console `api.err.NotFound`. Looking in the logs yields this exception:
`java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

### How to resolve:

Log into the container and run these commands:
```
dpkg --purge --force-depends ca-certificates-java
apt-get upgrade
apt install ca-certificates-java
reboot
```

### References
https://community.ui.com/releases/USG-4-4-41/4e5ae4f9-76aa-4ccb-8b25-848d6722e353#comment/b0419d32-a908-4f7c-b918-4419a267184d
https://unix.stackexchange.com/questions/296488/e-package-any-package-has-no-installation-candidate

**Comment by jacobalberty** [comment]
Try using c_rehash instead of the dpkg and apt commands see if that works

**Comment by BennyM** [comment]
The commands I referred to solve it. I had expected the image to have the necessary bits to get started right away. 

Do you want me to create a pull request or was I doing something wrong from the start?

**Comment by jacobalberty** [comment]
I had ssl errors with my cups images and I was able to use c_rehash to resolve the issue, its a cleaner fix as it doesn't involve reinstalling the packages, I've been unable so far to reproduce any ssl errors on this image so I can't test c_rehash to see if it fixes it.

If you do a pull request put a shell script to run the commands in `post_build/armhf` that'll ensure it only runs on the relevant architecture

**Comment by jacobalberty** [comment]
@BennyM oh I just realized you're still using the `arm32v7` tag, just use `latest` this should be fixed in `latest` and it now supports multiarch images.
