### ISSUE TITLE
Help with Unifi DB Rapair 

### ISSUE THREAD

**Issue by DannMendis** [jacobalberty/unifi-docker#377]
I need some humble help. I need to repair by Unifi Docker DB (which is mounted to my NAS) and want to follow the Unix steps in below Unifi article (How to Repair a Database on Debian-based Linux) 
https://help.ui.com/hc/en-us/articles/360006634094

When I login to the container and try to stop the service, getting below error:
`unifi@jacobalberty-unifi1:/unifi$ service unifi stop
logger: invalid option -- 'R'
Try 'logger --help' for more information.
unifi cannot start. Please create unifi user, and chown -R unifi /var/lib/unifi /var/log/unifi /var/run/unifi
unifi@jacobalberty-unifi1:/unifi$ `

My request is how to perform above steps?

**Comment by jacobalberty** [comment]
How are you launching the container? through your nas's gui interface? docker run commands or docker-compose?

**Comment by DannMendis** [comment]
I am running the container via NAS GUI. Unfortunately to do the DB Rapair, I need to stop it via the terminal.

I login to the NAS terminal via SSH and then executed docker commands to get in to the bash of the container.

I really can’t afford to blow the DB and start from ground up.

**Comment by jacobalberty** [comment]
The way I would do it is stop the container, back up your unifi volume so you get the database and all, then use a docker run on the cli with the same volumes and settings as the gui but add `-it --entrypoint bash` and maybe `--rm` to remove the container when you exit. If you are using `RUNAS_UID0=false` or `--user` you may or may not need to drop those, i would try with them in place first. from there you will be in a running container without unifi or mongodb launched. you can then launch proceed with your repair.

**Comment by DannMendis** [comment]
Much appreciated. I am not a docker expert and really appreciate if you can give me the docker commands from the NAS shell you want me to execute. I can backup the data as it’s saving to my NAS.

**Comment by DannMendis** [comment]
I did a completely reinstall. For future l
Releases good to give this feature to the users. Problem is UniFi user not available and container is running as root. I will close this issue.
