### ISSUE TITLE
Redirect Failing

### ISSUE THREAD

**Issue by ezekieldas** [jacobalberty/unifi-docker#380]
### Host operating system

CentOS Linux release 7.6.1810 (Core)
### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`/usr/bin/docker run -p 8080:8080 -p 8443:8443 -p 8880:8880 -p 8843:8843 -p 3478:3478/udp -p 10001:10001/udp -v /usr/local/ubnt/unifi/data:/usr/lib/unifi/data -v /usr/local/ubnt/unifi/logs:/usr/lib/unifi/logs -v /usr/local/ubnt/unifi/supervisor:/var/log/supervisor --name unifi jacobalberty/unifi:latest` 

### What do you expect to happen?
I have a transparent proxy redirecting requests like so: 

```
<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName unifi
  ServerAlias unifi unifi.local
  ProxyPass / http://myserver.local:8080/
  ProxyPassReverse / http://myserver.local:8080/
</VirtualHost>
```
This worked fine when I was running 5.10.x and previous. After recently updating to 6.0.28 this no longer works. I think there's a config in the app that has changed. Looking for help identifying this. 

### What actually happens?

```
curl -IL http://unifi.local
HTTP/1.1 302
Date: Tue, 17 Nov 2020 18:25:13 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_perl/2.0.10 Perl/v5.16.3
Location: /manage
Transfer-Encoding: chunked

HTTP/1.1 302
Date: Tue, 17 Nov 2020 18:25:13 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_perl/2.0.10 Perl/v5.16.3
Location: https://unifi.local/manage
Transfer-Encoding: chunked

curl: (7) Failed connect to unifi.local:443; Connection refused
```

**Comment by bcookatpcsd** [comment]
slight OT.. 

*cough* caddy *cough*

80211.x.y.z {
#encode zstd 
encode {
        gzip 1
}
reverse_proxy https://10.20.1.105:8443 {
transport http { 
        tls
        tls_insecure_skip_verify 
        }
        }
}

*   Trying 1.2.3.4:443...
* Connected to 80211.x.y.z (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=80211.x.y.z
*  start date: Nov 17 15:46:54 2020 GMT
*  expire date: Feb 15 15:46:54 2021 GMT
*  subjectAltName: host "80211.x.y.z" matched cert's "80211.x.y.z"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560c07457a80)
> HEAD / HTTP/2
> Host: 80211.x.y.z
> user-agent: curl/7.73.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 302 
HTTP/2 302 
< alt-svc: h3-29=":443"; ma=2592000
alt-svc: h3-29=":443"; ma=2592000
< date: Thu, 19 Nov 2020 21:56:12 GMT
date: Thu, 19 Nov 2020 21:56:12 GMT
< location: /manage
location: /manage
< server: Caddy
server: Caddy

< 
* Connection #0 to host 80211.x.y.z left intact


I would check your server.log, usually I have that problem if there is a mongodb issue..
