### ISSUE TITLE
6.0.28 -> 6.0.36 no problem.. all good; thank you. 

### ISSUE THREAD

**Issue by bcookatpcsd** [jacobalberty/unifi-docker#383]
just updated from 6.0.28 to 6.0.36.. 

docker stop unifi
docker rm unifi 
docker system prune -af
docker run -d \                                                                                                                                                              
    --name unifi \
    --restart unless-stopped \
    -e TZ=America/New_York \
    -p 3478:3478/udp -p 6789:6789/tcp -p 8080:8080/tcp -p 8443:8443/tcp -p 8880:8880/tcp \
    -v /home/docker/unifi:/unifi \
    -v /home/docker/unifivar:/var/run/unifi \
    jacobalberty/unifi:latest

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                   PORTS                                                                                                                              NAMES
432ffe66bbf8        jacobalberty/unifi:latest   "/usr/local/bin/dock…"   7 minutes ago       Up 6 minutes (healthy) 

*thank you sir*

**Comment by jsBlackBelt** [comment]
I tried to upgrade from `stable-6` to `latest` as it now follows 6.x versions.
`stable 6` was at 6.0.28 and when upgraded to latest (6.0.36) I got an error
`"we do not support upgrading from 6.0.28"`

Something wrong with the docker image? Or my upgrade process?

**Comment by bcookatpcsd** [comment]
I created a backup using the past 30 days (mine was like 350M) rm'd the container and all other image layers.. pulled down the latest.. waited for :8080 to respond with a 'welcome to unifi' screen.. restore from downloaded backup.. and came back in 20 minutes.. and my :8080 redirected to :8443/manage and the login page was there..

**Comment by jsBlackBelt** [comment]
@bcookatpcsd rm+prune did the trick for me as well. 
Thanks @jacobalberty for your great work.
