### ISSUE TITLE
6.0.36 tag uses the 5.14.23 software

### ISSUE THREAD

**Issue by matthewprenger** [jacobalberty/unifi-docker#384]
Attempted to upgrade to 6.0.36 and noticed the image actually contains version 5.14.23 of the Unifi software. It appears the 'latest' and 'stable-6' tags correctly use 6.0.36, but the 6.0.36 tag does not.

https://hub.docker.com/layers/jacobalberty/unifi/6.0.36/images/sha256-039f95a0cbca8af21992d6c803492c495b8d3254bd0312151c66165fdaa36f49

**Comment by jacobalberty** [comment]
The corrected 6.0.36 is queued to build now on travis
