### ISSUE TITLE
openwrt docker ce can not restart

### ISSUE THREAD

**Issue by boyu899** [jacobalberty/unifi-docker#387]
why my openwrt docker ce can not restart 

x86 router Intel nuc

docker update --restart=always unifi 

Can not restart 

You need to restart manually every time.

Everything else is fine

docker ce is good

unifi controller is good in docker ce

I'm from China 

English is not very good

**Comment by jacobalberty** [comment]
Is there anything in `docker logs unifi`

**Comment by boyu899** [comment]
[2020-11-29 20:56:58,514] <docker-entrypoint> Starting unifi controller service.,
[2020-11-29 20:56:58,515] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode,
[2020-11-29 20:59:13,107] <docker-entrypoint> Starting unifi controller service.,
[2020-11-29 20:59:13,109] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode,
:0 STUN id:   2; fd: 235 172.17.0.3:37503 -> 54.169.127.141:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 238 0.0.0.0:41935 -> 54.244.51.38:3478 (all_interfaces) DTLS id:  timed out,
:0 STUN id:   2; fd: 236 172.17.0.3:47510 -> 54.169.127.141:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 239 0.0.0.0:59541 -> 54.244.51.38:3478 (all_interfaces) DTLS id:  timed out,
:0 STUN id:   2; fd: 235 172.17.0.3:35920 -> 54.244.51.6:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 238 0.0.0.0:44068 -> 54.169.127.137:3478 (all_interfaces) DTLS id:  timed out,
:0 STUN id:   2; fd: 235 172.17.0.3:52898 -> 54.169.127.146:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 238 0.0.0.0:58570 -> 54.169.127.142:3478 (all_interfaces) DTLS id:  timed out,
:0 STUN id:   2; fd: 236 172.17.0.3:52172 -> 54.169.127.149:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 239 0.0.0.0:45431 -> 54.169.127.133:3478 (all_interfaces) DTLS id:  timed out,
:0 STUN id:   2; fd: 235 172.17.0.3:38590 -> 54.169.127.146:3478 (eth0) DTLS id: 0 ()(NATDISCOVERY) timed out,
:0 TURN id:   3; fd: 238 0.0.0.0:45491 -> 54.169.127.150:3478 (all_interfaces) DTLS id:  timed out,

**Comment by boyu899** [comment]
I tested it dsm nas restart is very ok  

 unifi is no problem in  pve-nas-dsm6.2.x   is good for restart

sorry my English is not very good

**Comment by boyu899** [comment]
The latest version can be started automatically and can be installed without any action.
