### ISSUE TITLE
Controller can not save WAN network settings

### ISSUE THREAD

**Issue by Trumf-dk** [jacobalberty/unifi-docker#388]
### Host operating system

Synology

### What tag are you using

Latest (6.0.28)

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

![Capture](https://user-images.githubusercontent.com/16223645/100608639-fbad6100-330c-11eb-8aa2-5d787be62d29.PNG)

### What do you expect to happen?

save the settings

### What actually happens?

An error as seen in the capture.

I got a new ISP and new IP and new DNS.
The controller can not access internet and can not download latest version because the DNS is not updated.
The Synology NAS is connected to the internet. It is only the UNIFI controller that is not.
I can access the controller webinterface.
I can not save new DNS settings. I can not even save old settings without changes.

Is there a file i can change somewhere. I have looked everywhere in /docker/Unifi through filestation.

Thanks in advance

**Comment by sgtcoder** [comment]
I am having this issue too, but for the LAN network. It simply won't let me change the IP address to the correct IP.
