### ISSUE TITLE
Cannot Ugrade from version 6.0.23 to 6.0.36

### ISSUE THREAD

**Issue by marcolino7** [jacobalberty/unifi-docker#389]
Hi,
trying to upgrade container from 6.0.23 to 6.0.36, downloading image from docker repository, but when 6.0.36 start, I got this error:

![image](https://user-images.githubusercontent.com/11460036/100719188-9618ad80-33bc-11eb-8928-7e03f9c6e0c3.png)

I rolled back to 6.0.23.
Anyone has this issue?

Thanks

**Comment by jacobalberty** [comment]
Try doing a docker image pull for the 6.0.36 tag make sure you have the
latest version of that tag.

**Comment by NK74** [comment]
Hi,

Same issue but from 6.0.28 to 6.0.36

Thanks

**Comment by marcolino7** [comment]
Hi @jacobalberty 
with release tag, it work, I think there is an issue with "latest" tag.

Marco

**Comment by jacobalberty** [comment]
@marcolino7 I'm using `latest` tag with 6.0.36 now I'm not able to identify any reason it wouldn't work. Try the following command and give me the output
`docker run -it --rm jacobalberty/unifi:latest dpkg -l unifi`

**Comment by marcolino7** [comment]
`root@docker3:~# docker run -it --rm jacobalberty/unifi:latest dpkg -l unifi
Unable to find image 'jacobalberty/unifi:latest' locally
latest: Pulling from jacobalberty/unifi
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
f76d80639eae: Pull complete
a327128c1d7d: Pull complete
21a98b379452: Pull complete
20b3816edb85: Pull complete
e130b822986a: Pull complete
f6db4168b476: Pull complete
d98de0ae6a55: Pull complete
15567eedf5fa: Pull complete
6d1f03901534: Pull complete
e750da3bf17a: Pull complete
da8a13103966: Pull complete
d016ffac1504: Pull complete
Digest: sha256:bacf34424f405d3bc16bd6e592a432cff8b051c671c75be3ca6e883d844dc566
Status: Downloaded newer image for jacobalberty/unifi:latest
[2020-12-02 23:24:31,641] <docker-entrypoint> Executing: dpkg -l unifi
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                 Version                         Architecture                    Description
+++-====================================================-===============================-===============================-=============================================================================================================
ii  unifi                                                6.0.36-14304-1                  all                             Ubiquiti UniFi server
root@docker3:~#
`

**Comment by jacobalberty** [comment]
Are you sure you were rushing the latest tag. Because that command just
pulled a new image

**Comment by marcolino7** [comment]
Hi @jacobalberty 
I don't know what happened the time when it did not work. I do same procedure all times, I have a batch to update version.
Thanks for support

Marco

**Comment by BryanWall** [comment]
I have been running on 6.0.23 for several months. I tried going to ":latest" today but got the same error as in #364.

> "UniFi Controller startup failed. We do not support upgrading from 6.0.23"

To upgrade the container I exported the settings from the existing container, deleted the 6.0.23 image and container, downloaded the "latest" image, edited the image setting in the settings file to "image": "jacobalberty/unifi:latest", imported the settings, then started the container. 

I followed the same steps and instead chose stable-6 and it worked. The readme suggests that stable-6 and latest should be the same. If they should be the same, do you have any guess what happened? Should I be able to go to latest now? What's the best tag to be on at this point?
