### ISSUE TITLE
Certificate import script no longer recognizes Let's Encrypt OSCP domain

### ISSUE THREAD

**Issue by alongfield** [jacobalberty/unifi-docker#392]
### Host operating system

Kubernetes 1.18.5+vmware.1

### What tag are you using

6.0.41

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

k8s-at-home/unifi helm chart

### What do you expect to happen?

Let's Encrypt certificates properly read in and added to Unifi keystore

### What actually happens?

/usr/unifi/init.d/import_cert does not recognize that this is a Let's Encrypt certificate and does not add the cert chain.  

```
root@unifi-1607191735-f586c4d8d-7gg9t:/unifi# openssl x509 -noout -ocsp_uri -in cert/tls.crt
http://r3.o.lencr.org
```

On November 24th, 2020, Let's Encrypt started using r3.o.lencr.org for their OSCP FQDN.  The check in the import script looks for "letsencrypt", so doesn't recognize this new domain.

**Comment by jacobalberty** [comment]
So how critical is it nowadays for the lets encrypt chain to be included, most browsers and proxy servers should fetch the chain when its not included and at least in chrome I don't have an issue loading my unifi server with a letsencrypt certificate as is.

For now I'm preparing a pr with a patch to just add additional checking for lencr.org in the ocsp uri though.

**Comment by alongfield** [comment]
That's basically the same as I was doing, except I mounted a ConfigMap on top of the script with a patched one that checked both cases in each block.

```
          if [[ ("${CERTURI}" == *"letsencrypt"* || "${CERTURI}" == *"lencr"*) && "$CERT_IS_CHAIN" == "true" ]]; then
              awk 1 "${CERTTEMPFILE}" "${CERTDIR}/${CERTNAME}" >> "${CHAIN}"
          elif [[ "${CERTURI}" == *"letsencrypt"* || "${CERTURI}" == *"lencr"* ]]; then
              awk 1 "${CERTTEMPFILE}" "${CERTDIR}/chain.pem" "${CERTDIR}/${CERTNAME}" >> "${CHAIN}"
          elif [[ -f "${CERTDIR}/ca.pem" ]]; then
              awk 1 "${CERTDIR}/ca.pem" "${CERTDIR}/chain.pem" "${CERTDIR}/${CERTNAME}" >> "${CHAIN}"
          else
              awk 1 "${CERTDIR}/chain.pem" "${CERTDIR}/${CERTNAME}" >> "${CHAIN}"
          fi

```

**Comment by astavitsky** [comment]
Why do we need to check for letsencrypt issued cert if `CERT_IS_CHAIN="true"` ?
