### ISSUE TITLE
UniFi Network Controller 6.0.43

### ISSUE THREAD

**Issue by ning42** [jacobalberty/unifi-docker#398]
Christmas greetings, with wishes of a happy holiday and thank you for the effort - highly appreciated 👍 
 
[UniFi Network Controller 6.0.43](https://community.ui.com/releases/UniFi-Network-Controller-6-0-43/b28bb453-927a-4dd8-82f7-40af28505510) is release as officiel/stable

**Comment by jacobalberty** [comment]
6.0.43 still appears to be rc according to the blog post, it's building on travis now to be tagged as 6.0.43-rc

**Comment by ning42** [comment]
oh ... sorry about that
