### ISSUE TITLE
Upgrade not working

### ISSUE THREAD

**Issue by mbierman** [jacobalberty/unifi-docker#404]
### Host operating system

Synology NAS I'm upgrading via terminal 

### What tag are you using

Tried `latest` and `6.0`

### What complete docker command or docker-compose.yml do you use to launch the sudo 

```
docker stop unifi
sudo docker pull jacobalberty/unifi:6.0
sudo docker start unifi
```

### What do you expect to happen?
I was running 6.0.36. I expected to be runing 6.0.43

### What actually happens?
I am still running 6.0.36.

**Comment by dennypage** [comment]
Did you reset the container?

**Comment by danielwagn3r** [comment]
Having a permission problem in one of the container volumes when upgrading von 6.0.41 to 6.0.43 - did you see something like this? Couldn't solve it yet myself.

**Comment by danielwagn3r** [comment]
@mbierman Take a look at the permissions of the `backup` folder in the folder where you start the unifi controller. Might be, that the permissions and ownership mismatch between your host and container.

Perhaps an extension to the compose file reflecting on https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e might bring a stable solution. Currently there seems to be an implicit assumption that the uid of the user invoking `docker run` or `docker-compose up` match the uid of the unifi user inside the unifi_controller container.

**Comment by mbierman** [comment]
> Did you reset (clear) the container?

I had not. I ended up removing and starting over and restoring settings from a backup and that did resolve it.

**Comment by mbierman** [comment]
> Perhaps an extension to the compose file reflecting on https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e might bring a stable solution. Currently there seems to be an implicit assumption that the uid of the user invoking `docker run` or `docker-compose up` match the uid of the unifi user inside the unifi_controller container.

other than my old backups weren't recognized by the Controller things are o.k. now. Currently backup permissions are set to root root. What should they be? Currently my settings are `--env=UNIFI_GID=999` and `--env=UNIFI_UID=999`

Also, looks like ui moved backups from 
`/backup/autobackup`
to 
`/data/backup/autobackup`

**Comment by danielwagn3r** [comment]
I've tried to set the UNIFI_GID and UNIFI_UID parameters in the compose file, but it didn't change the uid/gid in the containers passwd and group file, not even when I forced the recreation of the containers.
My workaround is to set permissions to uid=999/gid=999 on the backup directory in the host filesystem, which isn't really nice. On recent Ubuntu systems the uid/gid is already taken by a default system-user.

**Comment by puuuudding** [comment]
> I've not recognized it on 6.0.41 but it's there also. As I tried to upgrade to 6.0.43 the UniFi Controller seem's to try to make a backup before upgrade, which fails. Subsequently the upgrade fails.

Last time after changed the UID to 999, I started a unifi controller from scratch successfully (maybe because controller didn't check the backup folder permission). But this resulted to my controller hadn't auto backed up for over a month. This time I updated the controller and the permission issue of `backup` folder emerged.

**Comment by jvamos** [comment]
I am currently having issues matching these settings up correctly with container-station QNAPs version of Docker.
