### ISSUE TITLE
Embedded mongodb server consumes entire disk within minutes

### ISSUE THREAD

**Issue by thetooth** [jacobalberty/unifi-docker#406]
### Host operating system

Ubuntu 18.04.2 LTS

### What tag are you using

6.0

### What actually happens?

Under /opt/unifi/data/db/journal on the host where I am mounting persistent data, the mongodb server will immediately begin allocating WiredTigerLog files, around one every 3 seconds. This results in server becoming unavailable due to lack of disk space after a few minutes.

This issue is also present in the stable tag, but generally takes a month to consume the entire disk, prior to 5.0 there was never any issues with disk usage.

**Comment by bohmandan** [comment]
I have the same problem.
Started occurring after an upgrade from version 5 to version / tag 6.0.

**Comment by LukasGasp** [comment]
I had the same problem. When I wanted to access the Web-Interface I got the message: Database Migration in progress... 
I deleted the old container with all files and made a new one.
