### ISSUE TITLE
Folder permission for local backup folder

### ISSUE THREAD

**Issue by puuuudding** [jacobalberty/unifi-docker#407]
### Host operating system

Linux sanctuary 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker-compose up` with default docker-compose.yml

### What do you expect to happen?

Start normally.

### What actually happens?

local backup folder permission denied

In the folder running `docker-compose up`, a `backup` folder will be created to save backup files. The folder has permission `root:root`. This causes docker unifi controller permission error. I have to manually change `backup` folder owner to 999. Last time permission is changed for volumes' folder, how to automatically change the `backup` folder?

**Comment by danielwagn3r** [comment]
Seem's to relate to #404

**Comment by puuuudding** [comment]
> Seem's to relate to #404

yes you're right, seems to be same issue
