### ISSUE TITLE
6.0.45 fails to start

### ISSUE THREAD

**Issue by glc650** [jacobalberty/unifi-docker#413]
### Host operating system

Ubuntu 20.04.1 LTS

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

version: '3.7'
services:
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi
    init: true
    restart: unless-stopped
    volumes:
      - /home/server/docker/unifi/config:/unifi
    environment:
      - RUNAS_UID0=false
      - UNIFI_UID=1000
      - UNIFI_GID=1000
      - TZ=America/Los_Angeles
      - JVM_MAX_THREAD_STACK_SIZE=1280k
    # ports:
      # - "10.0.0.4:3478:3478/udp" # STUN
      # - "10.0.0.4:6789:6789/tcp" # Speed test
      # - "10.0.0.4:8080:8080/tcp" # Device/ controller comm.
      # - "10.0.0.4:8443:8443/tcp" # Controller GUI/API as seen in a web browser
      # - "10.0.0.4:10001:10001/udp" # AP discovery
    network_mode: "host"

### What do you expect to happen?

container to start

### What actually happens?

container fails to start

unifi         | [2021-01-28 04:32:36,181] <docker-entrypoint> Cert directory found. Checking Certs
unifi         | [2021-01-28 04:32:36,186] <docker-entrypoint> Cert has not changed, not updating controller.
unifi         | [2021-01-28 04:32:36,189] <docker-entrypoint> Starting unifi controller service.
unifi         | [2021-01-28 04:32:37,196] <docker-entrypoint> INFO: Changing 'unifi' UID to '1000' and GID to '1000'
unifi         | Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
unifi         | 	at com.ubnt.net.B.ö00000(Unknown Source)
unifi         | 	at com.ubnt.service.OoOO.øO0000(Unknown Source)
unifi         | 	at com.ubnt.ace.Launcher.main(Unknown Source)
unifi         | Caused by: java.lang.RuntimeException: Web context failed to initialize
unifi         | 	... 3 more
unifi         | [2021-01-28 04:33:15,416] <docker-entrypoint> Exit signal received, shutting down
unifi exited with code 0

changing tag to image: "jacobalberty/unifi:6.0.43" (i.e. reverting to previous latest) solves the problem

**Comment by DedMsk** [comment]
On Synology works fine
Download latest, clear, run

**Comment by glc650** [comment]
DedMsk, I did that multiple times and it didn't work.

Today I started from scratch (backed up my old folder containing all of my unifi data as is, took the same docker-compose.yml and dockerfile and ran docker-compose up) after downloading a config backup and restoring from that backup.  That of course worked.  So I then used the data from the backed up unifi folder and ran docker-compose up again (this time with latest tag) and that also worked so not sure what was up.

**Comment by srfoster1** [comment]
I have exactly the same issue (On synology NAS).
Currently running 6.0.43

With sudo access
```
docker-compose down
docker-compose pull
docker-compose up -d
```
And the image fails to start, with the same failure as the OP.
With a completely fresh start, it works, although I have not tried a full restore yet (still using 6.0.43).
