### ISSUE TITLE
Will this work on a WIndows host?

### ISSUE THREAD

**Issue by GaTechThomas** [jacobalberty/unifi-docker#414]
### Host operating system

Windows 10

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Nothing yet.

### What do you expect to happen?

I keep trying to turn the unifi controller on a Windows box, spending a lot of time on several paths. Before I go down that road again, please clarify whether the following info from the readme means that it works on Windows or not. Thank you.

"Unifi uses mongo store its data. Mongo uses the fsync() system call on its data files. Because of how docker for windows works you can't bind mount /unifi/db/data on a docker for windows container. Therefore -v ~/unifi:/unifi won't work."

**Comment by Atreidae** [comment]
I tried it on windows ages ago. it wasn't great.

It /can/ work but the important part here is that you cant mount the /unifi/db/data folder outside the container.
So when the container is redeployed, boom, all your config is gone.

You could get around this by backing up your controller before you do anything with the container, but it's too risky for my liking.
I ended up switching to linux, if you have a spare Raspberry Pi, or if your home NAS supports docker, I'd go with that instead.

**Comment by GaTechThomas** [comment]
Thanks for the response. After more reading I did something similar to what you suggest, mounting the storage in a container. Docker compose made it pretty easy. I'll post what I did soon in case it helps others.
