### ISSUE TITLE
Controller does not come up when port 8080 is not bound

### ISSUE THREAD

**Issue by pfried** [jacobalberty/unifi-docker#42]
Is it possible to startup the container without all ports bound on the host?

It seems to me that if i do only bind port 8443 (for testing only) the container does not come up. Is there any reason for this?

I know i need more or all of the ports in production, but i do have other containers running on the same host using these ports already (8080)

**Comment by jacobalberty** [comment]
It runs fine with only specific ports bound, what does docker ps say about the ports for the running container?

**Comment by pfried** [comment]
It does not bind them somehow, usually i get an error if the ports cannot be bound. But this then may be a docker specific error

**Comment by pfried** [comment]
Thank you for the quick responst, i think this issue is not related to this project, binding to the host network and specifying the ports may have some problems, if i do not specify the ports they get bound correctly to a ephemeral port range

**Comment by JohnnyMaccarone** [comment]
I actually have the same problem. Everything works until I try to bind the ports to the non-standard ones. 
While I use the same command as pfried, I also don't see any ports being mapped when I check with 'docker ps'. 
(I would need to run 10 containers on the same box, so changing those ports is required). 

Not sure how to accomplish this.

**Comment by jacobalberty** [comment]
@JohnnyMaccarone  If you need to run 10 containers mapping all of those ports may be a bit heavier than you should be doing. You should look into some of the more advanced docker networking options. Specifically the macvlan networking driver allows you to give containers routable ips.

https://blog.docker.com/2016/12/understanding-docker-networking-drivers-use-cases/

**Comment by JohnnyMaccarone** [comment]
Thanks for your quick response !
I'll have a look into your suggestion. 
Cheers.

**Comment by pfried** [comment]
I did attach the container to a macvlan, a very helpful article on this issue:
http://collabnix.com/docker-17-06-swarm-mode-now-with-macvlan-support/
