### ISSUE TITLE
ENV overrides for UNIFI_UID and UNIFI_GID not taking effect [podman]

### ISSUE THREAD

**Issue by Merlin8000** [jacobalberty/unifi-docker#420]
### Host operating system

Red Hat Enterprise Linux 8

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

# podman run -d --cap-drop ALL -e UNIFI_UID=271 -e UNIFI_GID=271 -e RUNAS_UID0=false -e JVM_MAX_HEAP_SIZE=1024m -e TZ='America/Chicago' -p 3478:3478/udp -p 8080:8080/tcp -p 8443:8443/tcp -p 8843:8843/tcp -p 10001:10001/udp --user unifi -v /opt/unifi:/unifi:Z --name jacobalberty/unifi:stable-6

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
Container to run successfully, writing files as the user 'unifi' having a uid of 271.

### What actually happens?
Permission denied errors as files created with unifi and from console have uid of 999.

Ran a git clone, changed the values of UNIFI_UID and UNIFI_GID, then ran podman build with the modified DockerFile.  container seems to load successfully.

**Comment by zphelj** [comment]
Through some experimentation I and reading of the git source files I realized that using the ENV variables and omitting the option '--user unifi' on the command line appears to achieve what I'd expect.

In this example I have a user 'unifi' defined on the Docker host as UID/GID 1101

sudo docker run --rm \
  -e TZ='America/Chicago' -e BIND_PRIV=false -e RUNAS_UID0=false -e UNIFI_UID=1101 -e UNIFI_GID=1101 \
  -p 8080:8080 -p 8443:8443 -p 3478:3478/udp \
  -v /docker/unifi:/unifi \
  jacobalberty/unifi:latest
[2021-06-02 17:06:19,564] <docker-entrypoint> Starting unifi controller service.
[2021-06-02 17:06:19,571] <docker-entrypoint> INFO: Changing 'unifi' UID to '1101' and GID to '1101'
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)

**Comment by hannibal85** [comment]
Unfortunately for me both options are not working. Omitting the --user unifi leads to the container being executed as root (as expected). The ENV for UNIFI_GID and UNFI_UID are set correctly (checked via config UI) but the user still is created with UID:GID = 999:999 (checked via cat /etc/passwd inside the container)
