### ISSUE TITLE
Hub.Docker Stable/Latest not updated to 6.1.7.1

### ISSUE THREAD

**Issue by opensourcefan** [jacobalberty/unifi-docker#427]
Is there normally a lag in updates?

**Comment by Zamotic** [comment]
While it may say the latest version is 6.0.*, I just pulled down the latest image from https://hub.docker.com/r/jacobalberty/unifi and it was up to date as of a few days ago.

**Comment by opensourcefan** [comment]
When I install via either latest or stable 6 only 6.0.45 installs.

**Comment by Zamotic** [comment]
I'm pulling down on a raspberry pi, so perhaps i'm getting a different result. There does appear to be new images under: jacobalberty/unifi:6.1.71

**Comment by opensourcefan** [comment]
I saw that something was updated days ago in line with 6.1.71. 

I'm trying to keep the install standardized to prevent any issues. Installing via the hub is the safest for me. If I pull it I don't get all the previous applied settings.

**Comment by ecdlguy** [comment]
I use docker on a Synology DS718+ (Intel Celeron J3455).
With the Synology Docker Package, pulling "jacobalberty/unifi:latest"  and starting the container fires up 6.0.45.
How can I debug this? Why isn't it pulling 6.0.71? 

cheers, Thorsten

**Comment by opensourcefan** [comment]
> I use docker on a Synology DS718+ (Intel Celeron J3455).
> With the Synology Docker Package, pulling "jacobalberty/unifi:latest" and starting the container fires up 6.0.45.
> How can I debug this? Why isn't it pulling 6.1.71?
> 
> cheers, Thorsten

I suspect it might be pulling a local image instead of actually retrieving the "latest".

**Comment by ecdlguy** [comment]
> I suspect it might be pulling a local image instead of actually retrieving the "latest".

No, I've removed any local images and I see traffic on the interface while downloading.
Also, the method I use to update worked flawlessly since many versions.

**Comment by opensourcefan** [comment]
> > I suspect it might be pulling a local image instead of actually retrieving the "latest".
> 
> No, I've removed any local images and I see traffic on the interface while downloading.
> Also, the method I use to update worked flawlessly since many versions.

Ya strange, I too never had an issue until this update but clearing my local images helped. Maybe that was a coincidence.

**Comment by ecdlguy** [comment]
Ok @opensourcefan, you were right. I thought I cleaned up all images, but there some with tag "none". For some reason, the container was using one of these. After removing the container and pruning all images, I finally have the right image running.
Thank you for pointing me in the right direction.

**Comment by opensourcefan** [comment]
> Ok @opensourcefan, you were right. I thought I cleaned up all images, but there some with tag "none". For some reason, the container was using one of these. After removing the container and pruning all images, I finally have the right image running.
> Thank you for pointing me in the right direction.

Excellent, glad its fixed. Now you get to see an annoying ad unless you have a Dream Machine.
