### ISSUE TITLE
error when run docker-compose

### ISSUE THREAD

**Issue by wiebereu** [jacobalberty/unifi-docker#429]
I am running Docker on my Synology NAS. 
I am trying to run the latest stable version of unifi controller by running the docker-compose file. 
The creation of the database and the log container went well, but i receive an error when creating the Unifi controller container. 

Below is what the error says: 

**ERROR: for controller  Cannot start service controller: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write sysctl key net.ipv4.ip_unprivileged_port_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.**

What has i done wrong? 

below is the line of the Docker compose file i got the error about 

    sysctls:
       net.ipv4.ip_unprivileged_port_start: 0

**Comment by anthonyloukinas** [comment]
Provide your docker-compose file

**Comment by daftz** [comment]
Did you find a solution to this? I'm running into the same error on my Synology with DSM 7.

**Comment by jacobalberty** [comment]
This looks like an issue with Synology running an old kernel.  You can remove the two sysctl lines and  then either run as root or run as a regular user and just make sure not to use any ports under 1024.

That sysctl requires a kernel newer than 4.4.

**Comment by daftz** [comment]
Removing the sysctl line did the trick, thank you!
