### ISSUE TITLE
Request: Expose port 1900 (MACVLAN)

### ISSUE THREAD

**Issue by 40417256** [jacobalberty/unifi-docker#437]
I use the container in MACVLAN mode, therefore I can use L2 adoption

### What do you expect to happen?
as per [https://help.ui.com/hc/en-us/articles/218506997-UniFi-Ports-Used](https://help.ui.com/hc/en-us/articles/218506997-UniFi-Ports-Used) port 1900 is used to perform L2 adoption.

In controller 6.x It is possible to change management from untagged to VLAN.

### What actually happens?
Have to perform L3 adoption over the same VLAN whilst L2 is possible.

**Comment by jacobalberty** [comment]
The expose directives have no effect on macvlan, they serve only to document typical ports in use.

further I don't believe port 1900 is used to perform L2 adoption. The documentation says it's to make the application discoverable. Unifi devices don't discover  the network application the application discovers them. That port appears to be used by the android and ios applications to discover the network application as per [ui-team](https://community.ui.com/questions/UniFI-undocumented-Port-1900-How-to-deactivate/41d54f41-553d-438a-a90d-82566ad0689a#answer/851de0cd-b57f-4e91-95ca-5758afc51b6b)

They probably should be deprecated and removed to be honest as the only time they are used is if you use the `--publish-all` argument to docker run using the default networking. When you do that it it randomizes the ports they're exposed on ensuring unifi will not work at all.
