### ISSUE TITLE
Request: CRON entry for /usr/unifi/init.d/import_cert

### ISSUE THREAD

**Issue by 40417256** [jacobalberty/unifi-docker#438]
### What do you expect to happen?

I use automation for the web interface SSL certificates, certificates will be updated automatically on the controller. I understand the script import_cert is only run on container startup. A nice feature would be to add to the Dockerfile:

ENV ...\
       CERT_CRON_SCHEDULE=my schedule here (to disable user year > 2300 by default - cron will never execute it)

### What actually happens?
The script can be run only at startup because it is placed in /usr/local/unifi/init.d not an issue by itself but since I do not know when certificates are updated (sometimes in a 90 days span), I never know when it will happen.

**Comment by jacobalberty** [comment]
You wouldn't typically run multiple services inside a single container. cron would be its own seperate service only tangent

**Comment by jacobalberty** [comment]
You wouldn't typically run multiple services inside a single container.

cron would be its own seperate service only tangentally related to unifi. I think a better solution might be to modify the import_ssl script to allow it to properly run when unifi is up including a restart on certificate change. Then use the hosts cron daemon, or an image like go-crond to call import_ssl every 12 hours or so.

**Comment by PrplHaz4** [comment]
> 
> 
> You wouldn't typically run multiple services inside a single container.
> 
> cron would be its own seperate service only tangentally related to unifi. I think a better solution might be to modify the import_ssl script to allow it to properly run when unifi is up including a restart on certificate change. Then use the hosts cron daemon, or an image like go-crond to call import_ssl every 12 hours or so.

Would it be feasible/preferable to change import_ssl to watch the certificate file for changes and import when the provided cert is updated?  I'm not sure how inotify works across the docker volume paradigm...

**Comment by jacobalberty** [comment]
I'd need to add inotify-tools package and use inotifywait but thats probably  doable. I use an inotify based synchronizer in docker to synchronize files from another docker container so it should work. Things like windows hosts probably wont work right though. One way or another i'll need to update import_ssl (and possibly docker-entrypoint.sh) to restart  unifi when the cert changes, at the same time i can add an optional inotifywait parameter to watch the file.

**Comment by jacobalberty** [comment]
Finally  getting around to this.

It looks like the easiest thing to do may be to just run `inotifywait -e modify,create,delete,move /unifi/cert/` and shut down the container when /unifi/cert gets updated, then if you have a restart policy that will restart it unifi will simply restart and import_cert would run on startup.

This could break setups where  a restart policy isnt setup.

The other option is throw supervisord in the container, let it handle starting and restarting unifi

**Comment by PrplHaz4** [comment]
I'm not sure how to evaluate the pros/cons of each approach, but the breaking change could be avoided by putting it behind an env variable to make the new behavior opt-in.

Since there's multiple processes running in the container, a service manager doesn't seem unreasonable either...

**Comment by 40417256** [comment]
Hello,

Has this made it to the image yet ? I would like to test it again in the coming weeks.

Thanks,

Eric
