### ISSUE TITLE
Current stable 6.2.23 fails to start up

### ISSUE THREAD

**Issue by lynix** [jacobalberty/unifi-docker#440]
### Host operating system

`Arch Linux ARM` on RPi 3b+

### What tag are you using

`stable-6`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```version: "3.9"
services:
  controller:
    image: "jacobalberty/unifi:stable-6"
    network_mode: host
    environment:
      TZ: Europe/Berlin
    volumes:
      - /mnt/volumes/unifi:/unifi
    user: unifi
    restart: unless-stopped
```

### What do you expect to happen?

Container starting up properly after pulling 6.2.23.

### What actually happens?

Tomcat fails to start inside container:

```
6f2fdf3109ff[304]: Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
6f2fdf3109ff[304]:         at com.ubnt.net.B.ö00000(Unknown Source)
6f2fdf3109ff[304]:         at com.ubnt.service.C.Óo0000(Unknown Source)
6f2fdf3109ff[304]:         at com.ubnt.ace.Launcher.main(Unknown Source)
6f2fdf3109ff[304]: Caused by: java.lang.RuntimeException: Web context failed to initialize
6f2fdf3109ff[304]:         ... 3 more
```

Web UI then only shows 404 page on port 8443.

**Comment by kickbutts** [comment]
Same with me.
I am running it on a Ubuntu Server.

**Comment by jacobalberty** [comment]
https://community.ui.com/releases/UniFi-Network-Application-6-2-23/df89533b-184a-4fb7-b2c6-9f894b82df27

It looks like its a known issue. I'm not sure why ubiquiti called this stable.

**Comment by jacobalberty** [comment]
To make it weirder, for me it upgraded fine from latest 6.1 to 6.2.23

**Comment by lynix** [comment]
Are you referring to this comment from Ubiquiti?

> We've pulled the release since we've identified a migration issue for those upgrading from 6.1.71 to 6.2.23 ( some cases ). We are working on resolving this issue.

**Comment by jacobalberty** [comment]
Yeah looking at the release blog I need to pull the 6.2 stuff when I get
back to a computer.

**Comment by lynix** [comment]
Okay so this can safely be considered an upstream bug, no issue on your side :)
