### ISSUE TITLE
Latest version (12/05/21) does not start

### ISSUE THREAD

**Issue by RealGandy** [jacobalberty/unifi-docker#441]
### Host operating system
Raspbian

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)
Using DockStarter with no overrides

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
Container to run and unificontroller to be available

### What actually happens

- Error in log:

> 2021-05-13 14:43:59,005 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
> 2021-05-13 14:44:01,177 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"

- Unifi Web Gui shows following:

> UniFi Controller startup failed
> We do not support upgrading from 6.2.23

**Comment by jacobalberty** [comment]
6.2.23 was pulled by ubiquiti because many people could not upgrade to it. So I rolled back `latest` and `stable-6` tags. if you were able to upgrade to 6.2.23 already just move to the 6.2 tag until ubiquiti releases a new 6.2.x release.

**Comment by ilkkaolavas** [comment]
I was able to upgrade to 6.2.23 and pulling latest took me down and I got error. Changed to 6.2 tag and it works again. Thanks!

**Comment by RealGandy** [comment]
Same here, 6.2 tag and all back up.

Thanks for prompt response
