### ISSUE TITLE
"We do not support upgrading from 6.2.23" error

### ISSUE THREAD

**Issue by emanuelem** [jacobalberty/unifi-docker#443]
Recently I started to see this error when I access the UI. I think the issue is the following:

- Unifi Controller auto-updated to the latest version: 6.2.23. Likely updating some conf or DB file too.
- My Docker image, which is is pinned to `latest`, auto-downgraded to 6.1 (`latest` is currently an alias for 6.1). This is because I use Watchtower to keep my images up-to-date.
- Hence the error.

I was able to solve by pinning to [6.2.23](https://hub.docker.com/layers/jacobalberty/unifi/6.2.23/images/sha256-356e0fdc34459386c42c0bfd140c64b1f880d98935a4845e890c501b0fe91484?context=explore), but it would be best if `latest` was an alias of 6.2.23.

Thanks!

**Comment by jacobalberty** [comment]
6.2.23 was pulled by ubiquiti due to migration issues and current official latest from ubiquiti is 6.1.71. the `6.2` tag right now is still an alias for 6.2.23 but as of right now 6.2.23 is no longer stable

**Comment by chenganir** [comment]
Thanks for the update. Whats the best way to recover properly from this ? My docker has a unifi folder on my NAS with the latest autobackup from 5/13 which is 6.1.71. How can I pull back 6.1.71 and avoid updating to the latest (6.2.23)? Do I need to rebuild my controller from scratch and restore from backup ?

Thanks !

**Comment by jacobalberty** [comment]
If  you were able to upgrade from 6.1.71 to 6.2.23 i would just use the `jacobalberty/unifi:6.2` tag for now. The only issue that i'm aware of that lead to them pulling it was the inability for many people to upgrade to it.

**Comment by chenganir** [comment]
Yeah I was able to upgrade and it worked well, I also have a 6.2.23 backup, but watchtower downgraded me to 6.1.71.
Any specific way I can rebuild my container to use the 6.2 label instead of the latest label and still maintain by unifi config ?

**Comment by eldigo** [comment]
> Yeah I was able to upgrade and it worked well, I also have a 6.2.23 backup, but watchtower downgraded me to 6.1.71.
> Any specific way I can rebuild my container to use the 6.2 label instead of the latest label and still maintain by unifi config ?

I suggest to look into using portainer. This makes life much easier.
I just switch from latest to 6.2 tag in breeze. Fixing the issue for now
Thanks!

**Comment by lambu76** [comment]
> Recently I started to see this error when I access the UI. I think the issue is the following:
> 
> * Unifi Controller auto-updated to the latest version: 6.2.23. Likely updating some conf or DB file too.
> * My Docker image, which is is pinned to `latest`, auto-downgraded to 6.1 (`latest` is currently an alias for 6.1). This is because I use Watchtower to keep my images up-to-date.
> * Hence the error.
> 
> I was able to solve by pinning to [6.2.23](https://hub.docker.com/layers/jacobalberty/unifi/6.2.23/images/sha256-356e0fdc34459386c42c0bfd140c64b1f880d98935a4845e890c501b0fe91484?context=explore), but it would be best if `latest` was an alias of 6.2.23.
> 
> Thanks!

I'm experiencing the same problem.

I'm using Doscker on Synology NAS.

How did you solve the problem ?

How did you change the pin of your container from latest to a specific version ?

thx

**Comment by emanuelem** [comment]
> How did you change the pin of your container from latest to a specific version ?

Just specify the image name as `jacobalberty/unifi:6.2.23` rather than `jacobalberty/unifi`

**Comment by lambu76** [comment]
> > How did you change the pin of your container from latest to a specific version ?
> 
> Just specify the image name as `jacobalberty/unifi:6.2.23` rather than `jacobalberty/unifi`

Is it possible to do it by using docker app in Synology?

**Comment by Atreidae** [comment]
> > > How did you change the pin of your container from latest to a specific version ?
> > 
> > 
> > Just specify the image name as `jacobalberty/unifi:6.2.23` rather than `jacobalberty/unifi`
> 
> Is it possible to do it by using docker app in Synology?

Yep couple of ways
* enable the SSH cli on the Synology and update the docker image via the CLI
* delete and recreate the container with an image of `jacobalberty/unifi:6.2.23` instead of `jacobalberty/unifi`
* Install and use Portainer (heaps better than the Docker management on the Syno by default, esp if you get into networking)

Great thread over on the Syno forums about doing it here 
https://community.synology.com/enu/forum/11/post/132066
