### ISSUE TITLE
Unifi Not Starting and is Providing Minimal Reasons to why that is... 

### ISSUE THREAD

**Issue by JohnOmernik** [jacobalberty/unifi-docker#45]
First let me lay out what I had, I had the Unifi:5.4.11 container, setup on a Marathon/Mesos. Now, it should not matter that it was here, I volume mounted data, run, and lib directories as instructed to persistent storage, so that's great, I am also running it in HOST network mode. 

This was working for me, I would run it, do things I need to do , and then I would shut it down as to not waste resources.  When I needed to upgrade/config I'd just start the service and go from there. Today, when I went to start the service, it starts and stays up, however, the actual service isn't running.  

My outputs are this...

From a Mesos perspective, there is nothing in Standard Error, and in Standard Log there only "Starting unifi controller service."

In the log directly, there are only two files unifi.err.log and unifi.out.log.  unifi.out.log is empty (but is created when I start the container).  unifi.err.log has only the string "Service killed by signal 11" it it repeats and grows if I leave things running. 

If I go into the container, these are the only processes running:

    1 ?        Ss     0:00 /usr/bin/dumb-init -- /usr/local/bin/unifi.sh
    7 ?        Ss     0:00 sh /usr/local/bin/unifi.sh
   10 ?        S      0:00 unifi -nodetach -home /usr/lib/jvm/java-8-openjdk-amd64 -classpath /usr/share/java/commons-daemon.jar:/usr/lib/unifi/lib/ace.jar -pidfile /var/run/unifi/unifi.pid -procname unifi -outfile /var/log/unifi/unifi.out.log -errfile /var/log/unifi/unifi.err.lo
g -Dunifi.datadir=/var/lib/unifi -Dunifi.rundir=/var/run/unifi -Dunifi.logdir=/var/log/unifi -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024M com.ubnt.ace.Launcher start
   

If I kill -9 pid 10 the container stops (probably expected) 

Some other things:
- /var/lib/mongodb is empty... is that intended? 
- In /var/log no other log files seem to have any info on what is happening (Any other place to look)
- I tried upgrading to a 5.4.16 image, and then a 5.5.11 image and am getting the same result. 

I typically am competent at troubleshooting, but I am at a loss on how to approach this. Ideally I'd like this to work without having to start from scratch and readopt and setup my network... Anything would be appreciated. 

John

**Comment by jacobalberty** [comment]
I am not familiar with Mesos, does it use a debian base?  If so #44 may be a fix, when I get a little time this evening I was going to integrated it into all of the branches and tag out the most recent releases with it, i'll go ahead and merge it into master now though so give it about 20 minutes then try the `latest` tag

**Comment by JohnOmernik** [comment]
This is likely the issue.  I will apply this tomorrow and try it. Mesos is
OS agnostic, it's an orchestrator sorta like Docker Swarm.  That's said I
am running Ubuntu based oses on the hosts. I will check it and try it
tomorrow and report back!

**Comment by devsr** [comment]
For what it is worth, this issue is also being discussed on the Apache Commons Daemon JIRA under [DAEMON-363](https://issues.apache.org/jira/browse/DAEMON-363).

Seems to affect recent kernel updates for both Debian 8 and RHEL/CentOS 7

**Comment by jacobalberty** [comment]
Really, so centos is affected as well? well shoot. The fix is in the `latest` tag now, you just need to pass the environment variable

**Comment by devsr** [comment]
@jacobalberty I can confirm that setting `JVM_MAX_THREAD_STACK_SIZE="2m"`  on the container solves the issue with the latest image. Thanks.

**Comment by jokajak** [comment]
I can also confirm this. Thanks for the quick fix!

**Comment by jacobalberty** [comment]
that was @joshenders who provided the actual fix, I just merged it in.

**Comment by JohnOmernik** [comment]
Awesome thanks everyone! The fix in #44 fixed my issue too!  What a weird issue.
