### ISSUE TITLE
Can't load my own (officially signed) SSL certificate

### ISSUE THREAD

**Issue by Alex-Bron** [jacobalberty/unifi-docker#450]
### Host operating system

Red Hat Enterprise Linux

### What tag are you using

stable-6

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

podman run --init --conmon-pidfile /%t/%n-pid --cidfile /%t/%n-cid -d \
-e TZ=CET \
-e UNIFI_HTTP_PORT=9080 \
-e UNIFI_HTTPS_PORT=9443 \
--network aragorn_net \
--name unifi \
--user unifi \
--uidmap 0:65536:200 \
--uidmap 999:1002:1 \
-p 9080:9080/tcp \
-p 9443:9443/tcp \
-p 3478:3478/udp \
-v /data/unifi:/unifi:Z \
-v /data/unifi/cert:/unifi/cert:Z \
docker.io/jacobalberty/unifi:stable-6
(started as systemd unit)

### What do you expect to happen?

I installed my SSL certificate as /data/unifi/cert/cert.pem; private key as /data/unifi/cert/privkey.pem and the intermediate certificate as /data/unifi/chain.pem. As shown in my startup command, /data/unifi/cert is mapped to /unifi/cert. I would expect the Unifi container to load my certificate so I have an official valid SSL connection to the Unifi container.

### What actually happens?

Upon starting the container, I see that the md5 sum of the cert.pem file is generated and stored in cert.pem.md5. This md5sum is correct. But other than that nothing happens with the certificate, key and chain, and the server.log file is holds two Java exceptions:
<launcher> ERROR StandardService - Failed to start connector [Connector[HTTP/1.1-9443]]
org.apache.catalina.LifecycleException: Protocol handler start failed
Caused by: java.lang.IllegalArgumentException: No aliases for private keys found in key store
Caused by: java.io.IOException: No aliases for private keys found in key store

Certificate is also used on another application, where it works fine. So the certificate is valid.

**Comment by brianknudsen99** [comment]
I have this cron.daily to update my cert to unifi controller, a littel tricky, but works.

#!/bin/sh

# Have this script to transfer my letcsencrypt Cert to Unifi Controller
# Create pfx file with cert and privkey and chain

openssl pkcs12 -export -inkey /etc/letsencrypt/live/website.com/privkey.pem -in /etc/letsencrypt/live/website.com/cert.pem -c
ertfile /etc/letsencrypt/live/website.com/chain.pem -out /etc/letsencrypt/live/website.com/bal.pfx -name unifi -passin pass:secret -passout pass:secret

# Copy pfx til Unifi Docker Container
/usr/bin/cp /etc/letsencrypt/live/website.com/bal.pfx /location_of_unifi_cert/cert/unifi/certs/.

# Transer Certifict to Unifi Datastore

# Delete old cert
keytool -delete -alias unifi -keystore /location_of_unifi_datastore/cert/unifi/data/keystore -storepass aircontrolenterprise
# Import new Certificat to Unifi
keytool -importkeystore \
-srckeystore /location_of_unifi_cert/cert/unifi/certs/bal.pfx -srcstoretype PKCS12 \
-srcstorepass secret \
-destkeystore /location_of_datastore/cert/unifi/data/keystore \
-deststorepass aircontrolenterprise \
-destkeypass aircontrolenterprise \
-alias unifi \
-trustcacerts
