### ISSUE TITLE
Enhancement Request: Optional mDNS reflector installed

### ISSUE THREAD

**Issue by mbierman** [jacobalberty/unifi-docker#451]
### Host operating system

Synology DSM

### What tag are you using

`stable`

```
 docker run --name=unifi \
        --hostname=unifi \
        --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        --env=BASEDIR=/usr/lib/unifi \
        --env=DATADIR=/unifi/data \
        --env=LOGDIR=/unifi/log \
        --env=CERTDIR=/unifi/cert \
        --env=RUNDIR=/var/run/unifi \
        --env=ODATADIR=/var/lib/unifi \
        --env=OLOGDIR=/var/log/unifi \
        --env=CERTNAME=cert.pem \
        --env=CERT_PRIVATE_NAME=privkey.pem \
        --env=CERT_IS_CHAIN=false \
        --env=GOSU_VERSION=1.10 \
        --env=BIND_PRIV=true \
        --env=RUNAS_UID0=true \
        --env=UNIFI_GID=999 \
        --env=UNIFI_UID=999 \
        --volume=/volume1/docker/UniFi:/unifi:rw \
        --volume=/unifi \
        --volume=/var/run/unifi \
        --network=host \
        --workdir=/unifi \
        --expose=3478/udp \
        --expose=6789/tcp \
        --expose=8080/tcp \
        --expose=8443/tcp \
        --expose=8843/tcp \
        --expose=8880/tcp \
        --restart=always \
        --label='maintainer=Jacob Alberty <jacob.alberty@foundigital.com>' \
        --log-driver=db \
        --detach=true \
        -t jacobalberty/unifi:latest unifi"
```

### What do you expect to happen?
Not a bug, but an enhancement request. I would love to have a DNS reflector included in the docker image as an option so that things like AirPlay and Chromecast work across VLANs. I get that some people won't want this and will want the "pure" ui image so perhaps this could be enabled/disabled in a config option. 

### What actually happens?
Currently it doesn't seem this is supported.

**Comment by dennypage** [comment]
A mDNS reflector to cross VLANS is something appropriate to a firewall distribution. This isn't a firewall distribution.

**Comment by mbierman** [comment]
Since mDNS is something that is part of the UI Controller but requires USG this would be valuable so that things like Chromecast and AirPlay can work across VLANs.

**Comment by dennypage** [comment]
Not sure where you are getting this from. I do not see the Avahi daemon in the docker container. Nor do I see the image designed for multiple interfaces. Routing between network interfaces, whether they be VLAN or native, is a firewall/router activity. This docker package is a provides a configuration management system, not a firewall/routing system.

**Comment by jacobalberty** [comment]
I'm looking at it and I'm not sure that the unifi controller would be well positioned for mdns reflection either. It looks like something like https://hub.docker.com/r/flungo/avahi might be a better fit and it has an example for enabling reflection. But adding a reflector into the unifi mimage adds a random moving part thats almost entirely unrelated to everything else in it.

**Comment by mbierman** [comment]
Avahi is certainly seems to be popular. I'm suggesting an option to easily install a replacement for what unifi provides in USG. It might be that they actually just stick avahi in themselves on USG, I don't know.

**Comment by dennypage** [comment]
Yes, Avahi is what is used on USG. Avahi is also what is used in various open source firewall distributions for mDNS support. Likely what Firewalla uses to implement mDNS reflection as well.  This is where you should look for mDNS routing.
