### ISSUE TITLE
Possible multiarch issue - ":latest" currently pulls down amd64 instead of arm64

### ISSUE THREAD

**Issue by morrisalex** [jacobalberty/unifi-docker#452]
### Host operating system

`Ubuntu 20.04.2 LTS on Raspberry Pi 4B`

### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker run --rm --init -p 1900:1900/udp -p 3478:3478/udp -p 5514:5514/udp -p 6789:6789 -p 8080:8080 -p 8443:8443 -p 8843:8843 -p 8880:8880 -p 10001:10001/udp -e TZ='Etc/UTC' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:latest`

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

`Docker should pull down the arm64 image. It used to, up until today.`

### What actually happens?

`Docker pulls down the amd64 image.`

**Comment by jacobalberty** [comment]
I just moved builds from travis-ci to github actions I forgot to add the additional arch to the workflow I'll check in fix shortly.

**Comment by morrisalex** [comment]
Super, thank you!

**Comment by jacobalberty** [comment]
:latest should be good I'm pushing v6 v6.2 and v6.2.26 now

**Comment by morrisalex** [comment]
Yup, it works. Loaded it now. Thanks for fixing this.
