### ISSUE TITLE
pull of 6.2.26 fail

### ISSUE THREAD

**Issue by ning42** [jacobalberty/unifi-docker#454]
### Host operating system
Qnap 

### What tag are you using
6.2.26

[~] # docker pull jacobalberty/unifi:6.2.26
Error response from daemon: manifest for jacobalberty/unifi:6.2.26 not found: manifest unknown: manifest unknown

works fine with 6.2.5
[~] # docker pull jacobalberty/unifi:6.2.25
6.2.25: Pulling from jacobalberty/unifi
Digest: sha256:bf1fe868ca2ffadc71e4711c6221e2c252e5d94b15994fc46c1d294f2d384d3c
Status: Image is up to date for jacobalberty/unifi:6.2.25
docker.io/jacobalberty/unifi:6.2.25

**Comment by ning42** [comment]
arg never min - figured it out - change of tag syntax :)

**Comment by jacobalberty** [comment]
Sorry busy day today. I meant to reply and explain that. I'll go ahead and push the new readme to docker hub too to try and make it more visible. The change in syntax was caused by the move from travis to github actions.

**Comment by LeehamElectronics** [comment]
I could not find anything in the read me file, I just used the stable-5 branch:
`docker pull jacobalberty/unifi:stable-5`
