### ISSUE TITLE
Stable-6 tag on docker hub seems stale

### ISSUE THREAD

**Issue by buckaroogeek** [jacobalberty/unifi-docker#455]
Good afternoon

I have been using the stable-6 tag in my docker-compose yaml file for the controller. Is stable-6 still tracking the current version 6 release or has stable-6 been replaced by another tag? Stable-6 was last updated over a month ago and does not (yet) pull 6.2.26. I did a brief search in Issues but nothing seemed to jump out.

thanks!

Brad

**Comment by jacobalberty** [comment]
`stable-6` has been effectively replaced with `v6` or `v6.2`. Tagged versions also are now prefixed with `v` from `v6.2.26` going forward. This is due to moving from travis-ci to github actions the new build script changed things.

**Comment by buckaroogeek** [comment]
Thanks Jacob. Much appreciated.
