### ISSUE TITLE
Cannot restore .unf from file upload

### ISSUE THREAD

**Issue by Hraph** [jacobalberty/unifi-docker#471]
### Host operating system

Debian 11
Docker version 20.10.8, build 3967b7d

### What tag are you using

6.4.54

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker-compose up -d

### What do you expect to happen?

On unifi setup select an .unf image from local disk, upload and restore.

### What actually happens?

The restore fails.
In server.log I got :
`java.io.FileNotFoundException: /usr/lib/unifi/data/backup/5.10.20.unf (Permission denied)`

This is due to the docker-compose volume `- ./backup:/unifi/data/backup`.

**Comment by jbouwh** [comment]
Make sure you authorize uid 999/gid 999 in the local file system.

**Comment by drunken-monk3y** [comment]
configuration was working out of the box. somehow my AP was not able to connect anymore... i simply reconfigured it. that might be more of a unifi problem than a THIS project problem i guess
