### ISSUE TITLE
SNMP not working - No response 

### ISSUE THREAD

**Issue by michmoor0725** [jacobalberty/unifi-docker#472]
### Host operating system

Ubuntu 20.04.3 LTS

### What tag are you using

 latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Using GUI - Portainer

Note: A screenshot of your configuration page if using a gui is acceptable
![image](https://user-images.githubusercontent.com/47565104/136488979-81a13a48-930c-4b56-8966-b7b71c437631.png)

### What do you expect to happen?
Exposing UDP port 1161 on the host and map that to port 161 in the container. 
The expectation is that SNMP would work.

### What actually happens?
Nothing. SNMPWalk indicates no response.

From Management station:
sudo snmpwalk -v2c -c #### 192.168.15.2:1161
Timeout: No Response from 192.168.15.2:1161

**Comment by jacobalberty** [comment]
@shk3bq4d snmp does work, you either have to map the ports 1:1 no remapping, or just expose the container directly to the network. I use macvlan and have been running mrtg for years.

**Comment by shk3bq4d** [comment]
Thanks a lot for the feedback.

Maybe I didn't find it in the image myself because I'm still on 6.5.x?

I'll check 7.0 whenever I have a chance!

**Comment by shk3bq4d** [comment]
still no luck on 7.0.25, but I see that latest is now tracking 7.1.61, so I'll schedule another upgrade:
I tried direct mapping and host network.
I also guess there's a setting I have missed somewhere in the GUI
```
$ netstat -lnp | grep -E 'java|mongo'
tcp        0      0 0.0.0.0:8843            0.0.0.0:*               LISTEN      168085/java
tcp        0      0 0.0.0.0:8880            0.0.0.0:*               LISTEN      168085/java
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      168085/java
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      168085/java
tcp        0      0 0.0.0.0:6789            0.0.0.0:*               LISTEN      168085/java
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      161640/mongod
udp        0      0 0.0.0.0:5514            0.0.0.0:*                           168085/java
udp        0      0 0.0.0.0:3478            0.0.0.0:*                           168085/java
udp        0      0 0.0.0.0:10001           0.0.0.0:*                           168085/java
udp        0      0 172.17.0.1:58218        0.0.0.0:*                           168085/java
udp        0      0 10.101.6.80:50252       0.0.0.0:*                           168085/java
unix  2      [ ACC ]     STREAM     LISTENING     50774521 161640/mongod        /tmp/mongodb-27017.sock
```

**Comment by shk3bq4d** [comment]
I now have upgraded to 7.1.61 and still can not figure how to have SNMP working on the controller.

I tried my luck setting:

```
JVM_EXTRA_OPTS: -Dcom.sun.management.snmp.port=161
```

but that must not be it as I think openjdk does not implement the needed classes as it resulted in 

```
 java.lang.UnsupportedOperationException: Unsupported management property: com.sun.management.snmp.port
     Caused by: java.lang.ClassNotFoundException: sun/management/snmp/AdaptorBootstrap
```

@jacobalberty : enabling  SNMP on the controller seems to be non-obvious, while you may consider this out of the scope of your project, is there any chance you recall how it is to be configured?

**Comment by shk3bq4d** [comment]
@OliHall : no, I haven't managed to get it working.

**Comment by OliHall** [comment]
@shk3bq4d Thanks, that's interesting.
I can monitor all my APs with SNMPv3, but I cannot get SNMP monitoring of the controller working.

- I tried controller version 6.0.28 and also the latest 7.4.162.
- I tried both versions in a docker container with macvlan and a dedicated IP address for the controller container.
- I also spun up a dedicated VM and installed 7.4.162 directly on ubuntu 22.04.
- None of these options exposed port 161 for SNMP monitoring of the controller.

@jacobalberty please can you clarify your comment above?
> snmp does work, you either have to map the ports 1:1 no remapping, or just expose the container directly to the network. I use macvlan and have been running mrtg for years.

Are you monitoring the controller with SNMP? or jus monitoring the APs?

Many thanks,
Oli.
