### ISSUE TITLE
Docker still tracking 6.4.54 instead of latest 6.5.51

### ISSUE THREAD

**Issue by richardklam** [jacobalberty/unifi-docker#478]
https://community.ui.com/releases/UniFi-Network-Application-6-5-51/781e3ae2-0f56-42ba-8753-599d4aaa1638?page=8

**Comment by jacobalberty** [comment]
6.5.51 is still in release-candidate status, it hasn't been pushed to stable yet.

**Comment by darkpixel** [comment]
Latest is 6.5.52 as of a few hours ago.

https://community.ui.com/releases/UniFi-Network-Application-6-5-52/b7ca4128-c6f7-4741-9da1-e216db190452

I would love to see beta versions available for those of us who are beta testers, but there's probably some language in the agreement from UniFi about not distributing beta versions to anyone who isn't a member of the beta program...and there's no way to validate that information from the perspective of a docker image, so we're probably out of luck. ;)

**Comment by jacobalberty** [comment]
I've pushed 6.5.52-rc tag, it'll be up on the hub soon.

There is a way to use betas use the `jacobalberty/unifi:beta` tag and pass the environment variable `PKGURL` with the url to the debian package for the beta you want, this would work with using rc's as well. for example the `PKGURL` for 6.5.52 is `https://dl.ui.com/unifi/6.5.52-4b1a918bba/unifi_sysvinit_all.deb`
