### ISSUE TITLE
6.1.61-Arm32 needed

### ISSUE THREAD

**Issue by Zaiman1906** [jacobalberty/unifi-docker#480]
My wife has a new Apple iPhone 13, which uses WPA3 in the security protocol. In my opionion that confuses the connection (the iPhone disconnects from time to time for a few seconds).
But on my QNAP TS-431p it is only possible to install Arm32-Controller versions, the latest one is 6.0.23.
To change the security protocol to WPA2-/WPA-3 I need Controller version Arm32-6.1.61.
Will it come soon?

**Comment by jacobalberty** [comment]
All images are built with amd64, arm32 and arm64 support. Just pull the tag
for the version you want and it will pick what architecture is appropriate
for your system.

**Comment by Zaiman1906** [comment]
Oh, I didn't know that I can use other versions than the called Arm32-Versions. Last year it didn't work for me with other versions, so I used version 5.10.24 for a long time. Now I tried version 6.4.54 without the Arm32-tag and it is working well. Thank You, jacobalberty!

**Comment by jacobalberty** [comment]
It was a relatively recent change, about 5 months ago. to use the docker buildx stuff with github actions to get everything built all together.

Just a heads up though there are some issues with the arm32 versions that may result in arm32 going away eventually unfortunately. MongoDB does not work on arm for anything newer than the version I'm using now (3.2.22). If unifi ever gets a hard dependency on a newer version of MongoDB then arm32 won't be viable to update anymore.

**Comment by GoliathLabs** [comment]
@jacobalberty can be closed I guess
