### ISSUE TITLE
Docker on Synology

### ISSUE THREAD

**Issue by ragnarger** [jacobalberty/unifi-docker#481]
### Host operating system

Example: DiskStation 7

### What tag are you using

Example: `latest`

### What do you expect to happen?
i want to access the web site

### What actually happens?
i get a page with "HTTP Status 404 – Not Found"

pls help me :)

**Comment by Doriangaensslen** [comment]
I've had the same. I think java stuff needs some time, do you have the same message if you try again after 3-4 Minutes?

**Comment by ragnarger** [comment]
Hey @Doriangaensslen 
yes it took its time... after my break to cook some food it was there.

**Comment by GoliathLabs** [comment]
@jacobalberty Can be closed I guess

**Comment by ragnarger** [comment]
Oh yes it can be closed and thank you for your help!
