### ISSUE TITLE
unifi fails to start in v6.5.54

### ISSUE THREAD

**Issue by allenporter** [jacobalberty/unifi-docker#495]
### Operating system

Ubuntu 20.04.2 LTS

### UniFi Tag

v6.5.54

### Docker run

using k8s-at-home helm chart

### Bug description

Unifi controller fails to start.

### Steps to reproduce

I'm currently using the k8s-at-home helm chart to run the unifi image and I upgraded to `v6.5.54` this morning (thanks for being on top of the CVE!)

This chart is currently running `v6.2.26` which I assume is in scope for this CVE:
https://github.com/k8s-at-home/charts/blob/master/charts/stable/unifi/values.yaml

I realize this could be an issue with the chart, but I thought I would start here.

### Relevant log output

```shell
[2021-12-11 16:32:11,151] <docker-entrypoint> Starting unifi controller service.
error: exec: "java -Dunifi.datadir=/unifi/data -Dunifi.logdir=/unifi/log -Dunifi.rundir=/var/run/unifi -Xmx1024M\n -Djava.awt.headless=true\n -Dfile.encoding=UTF-8 -jar /usr/lib/unifi/lib/ace.jar start": stat java -Dunifi.datadir=/unifi/data -Dunifi.logdir=/unifi/log -Dunifi.rundir=/var/run/unifi -Xmx1024M
-Djava.awt.headless=true
-Dfile.encoding=UTF-8 -jar /usr/lib/unifi/lib/ace.jar start: no such file or directory
[2021-12-11 16:32:12,178] <docker-entrypoint> WARN: unifi service process ended without being signaled? Check for errors in /unifi/log.
```
```

**Comment by allenporter** [comment]
Whoops, i see there is a dupe already closed #493

**Comment by jacobalberty** [comment]
This looks like a duplicate of #493 which should have a fixed version on the docker hub right now. However I have been deleting and remaking tags a bit right now as I am backporting the fix to 6.0.45 for EOL hardware support ( #494 ) I need about 30 minutes for the builds on the hub to fully settle and then it should be fixed. I'll reply again when I'm done messing up the tags on the hub.

**Comment by allenporter** [comment]
I'll follow the original report. Thanks for the effort here!

**Comment by jacobalberty** [comment]
Ok, everything on the hub should be fixed. Give it a docker pull and you should have a working version.
