### ISSUE TITLE
Cannot get input stream descriptor for bucket 'sites', directory 'abcdefghi'

### ISSUE THREAD

**Issue by boyke** [jacobalberty/unifi-docker#498]
Hi,

After upgrading one of the (Dockerized) controllers from 5.9.X to 5.14.23 i noticed lots of warnings like below inside server.log

<inform-112> WARN  system - Cannot get input stream descriptor for bucket 'sites', directory '4yiidspk', file 'config.properties'

According to some threads at the UniFi forum i could has something to do with permissions of those folders, but everyone has read access on it. For example

/var/lib/unifi/sites/abcdefghi/map exists and has 755 root permissions

AFAIK this is the only controller with this warnings

**Comment by jacobalberty** [comment]
do yo have a `/unifi/sites/abcdefghi/config.properties`

**Comment by jacobalberty** [comment]
I believe that is just a benign error you should safely be able to ignore it assuming everything else is working fine. It's trying to read config.properties to look for any site wide parameters and erroring when it can't find it. You could probably safely just touch config.properties in those folders if you want to get rid of the error.
