### ISSUE TITLE
Unifi user fixed at UID=999

### ISSUE THREAD

**Issue by basbloemsaat** [jacobalberty/unifi-docker#509]
At my system (debian), the uid 999 is in use by another user (systemd-coredump in debian). The unifi user is fixed at uid 999. In my opinion it would be better if UNIFI_UID and UNIFI_GUID were overridable in env variables.

**Comment by jacobalberty** [comment]
UNIFI_UID and UNIFI_GID do what you want. They are currently undocumented because my goal was to move away from using gosu to drop permissions and instead use --user to set permissions at launch. But I can't find a suitable solution to reliably set permissions for end users.   so for now UNIFI_UID and UNIFI_GID still exist.

**Comment by basbloemsaat** [comment]
Alas, they should, but they don't. If I include them in env, either in a docker-compose.yml or directly on the command line:

    docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Africa/Johannesburg' -e UNIFI_UID=997 --user unifi -v /home/bas/t/unifi:/unifi jacobalberty/unifi:latest

The files and directories (log and data) created all have owner 999.

I think this is because the unifi user is created at build time, at which time UNIFI_UID is 999. At line 183 of docker-entrypoint.sh the condition "${CUID}" != "0" is then true (CUID is 999), thus, 
   
    ${UNIFI_CMD} & 

is ran as the 999 user, never executing the code below which seems to be intended to change to another uid. I tried changing the line 183 condition to "${CUID}" == "0", which I think it should be, but I could not get it to work: it gives a lot of "chown: changing ownership of ... Operation not permitted".

**Comment by basbloemsaat** [comment]
never mind, I had to omit "--user unify", but rather start the container as root. Got it working with

    docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Africa/Johannesburg' -e UNIFI_UID=997 -e UNIFI_GID=996 -e RUNAS_UID0=false -e BIND_PRIV=false -v /home/bas/t/unifi:/unifi test

Thanks

**Comment by GoliathLabs** [comment]
@basbloemsaat this can be closed I guess

**Comment by koitsu** [comment]
#516 addresses this a bit more cleanly, which can let you override the env vars in combination with `--user`.  In other words, after my PR is imported, you should be able to do something like `docker run -e UNIFI_UID=$(id -u) -e UNIFI_GID=$(id -g) --user $(id -u):$(id -g) ...` and achieve a 1:1 mapping of guest-to-host UID/GID for UniFi things.  (MongoDB may still be a problem though, not sure.)

**Comment by koitsu** [comment]
Actually, sorry about this -- it looks like #516 is not correct and not a viable solution. I didn't realise that the useradd/groupadd were being done via RUN (i.e. during image build-time) and not during actual container launch-time.
