### ISSUE TITLE
Self-signed certificates without chain.pem

### ISSUE THREAD

**Issue by alexandresoro** [jacobalberty/unifi-docker#514]
### Operating system

ArchLinux

### UniFi Tag

latest

### Docker run

k3s

### Bug description

I am trying to setup this image with my own self-signed certificate.

Certificate has been generated like this:

`openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout key.pem -out certificate.pem -subj "/CN=<MY_HOST_NAME>" -addext "subjectAltName=DNS:<MY_HOST_NAME>" `

So basically there is no chain PEM.

If I set up the certes out of the box, it does not work because the unit script is looking for a `chain.pem` and `CERT_IS_CHAIN=true` has no effect. I managed to work around this by creating an empty chain file, but this is not something clean in my opinion.

Is this expected and is there a reason why `CERT_IS_CHAIN` could not be applicable to non-LE certificates?

**Comment by matthiaskoerner-ba** [comment]
I'm trying to reopen this issue since I lost quite a lot of time on this.

My suggestion is to resolve this issue either by fixing it or by explicitely mentioning it in the README.md:
> If I set up the certes out of the box, it does not work because the unit script is looking for a chain.pem and CERT_IS_CHAIN=true has no effect. **I managed to work around this by creating an empty chain file, but this is not something clean in my opinion.**
