### ISSUE TITLE
Step by step upgrade from 6.2.25 to latest stable possible?

### ISSUE THREAD

**Issue by Daimonion1980** [jacobalberty/unifi-docker#521]
Hello 

I have the controller installed on a debian (started with buster and made an upgrade to bullseye) bullseye VM and it's working fine on version 6.2.25. I have cloned the github repo and nothing changed inside. Of course i have a complete setup inside the controller (several APs, Switch Security Gateway)
I'm using the controller with an unchanged docker-compose script. Just made a git pull and docker-compose up -d

Now i want to upgrade to a more actual and stable version though 6.2.25 has some bugs that i hope will be solved in more actual version.

Okay, so i started the upgrade with following commands

docker-compose down
git pull (git merged everything fine)
docker-compose pull
docker-compose up -d --force-recreate

After this the controller started up but did stuck at migrating database. 

So I think the versions are not compatible. But maybe a step by step upgrade is a way to go? New Setup is not an option at the moment because for this i have to backup the settings first but this is also a bug in 6.2.25 (i tried also the old interface)

Which tags, instead of "-latest" in docker-compose.yml, are a good way to update from 6.2.25 to the actual stable?

Thanks for your work!

**Comment by buckaroogeek** [comment]
My update process using docker-compose is somewhat different. I started with the docker-compose.yml file from the repository many versions ago, but it has been modified to launch other containers such as pihole in addition to unifi. 

The steps I follow to update are:

1. ssh to the computer running docker (a synology but that is mostly irrelevant)
2.  cd to the directory containing the docker-compose.yml file.
3. run ```sudo docker-compose pull``` to pull the latest images
4. inspect the list of images: ```sudo docker images``` 
5. if there is a new unifi image I run ```sudo docker-compose up -d unifi```. The name unifi is the name set within docker-compose.yml.
6. wait to make sure everything starts properly and check the web interface.
7. inspect the images again ```sudo docker images``` 
8. delete any old images using ```sudo docker rmi XXXX``` where XXX is the image id from the list.

On occasion I visually compare my docker-compose.yml file to the version in the repository to see if there are any changes that might be usefil..

One suggestion to update from 6.2.25 to the current stable release (6.5.55 on my system would be to install at least 1 version of each minor version. The Controller went from 6.2.x to 6.4.x to 6.5.x.  To be safe update to the last version of the 6.2 release (6.2.26), Then 6.4.54 (the only 6.4 release), then 6.5.53, followed by 6.5.55.  But it would probably be better for someone more knowledgeable than I to offer a better process.

**Comment by Daimonion1980** [comment]
Thank you for your detailed answer. First of all i will make a cleaning and remove every container i don't need anymore. 

After this i will try an update to 6.2.26 (edit docker-compose file with -v6.2.26 instead of -latest) and hope there is a chance to get a settings backup from the controller.

**Comment by buckaroogeek** [comment]
I also use the controller to create a back up just in case.  I have not had problems with updates for minor versions such as 6.4.x to 6.5.x but major version changes (5.x to 6.x) can sometimes be a problem.

**Comment by Gamertech** [comment]
> One suggestion to update from 6.2.25 to the current stable release (6.5.55 on my system would be to install at least 1 version of each minor version. The Controller went from 6.2.x to 6.4.x to 6.5.x. To be safe update to the last version of the 6.2 release (6.2.26), Then 6.4.54 (the only 6.4 release), then 6.5.53, followed by 6.5.55.

This should (theoretically) work fine provided your install's intact. Also if you haven't done it, jacobalberty moved to a combined unifi volume for the image. There's info for that under the Volumes section on the front page of the repo. It's not mandatory, but so much neater.
