### ISSUE TITLE
Lack of dnsutils makes it very hard to diagnose network problems

### ISSUE THREAD

**Issue by bimargulies** [jacobalberty/unifi-docker#522]
### Operating system

Synology

### UniFi Tag

latest

### Docker run

The standard cl as best I can tell.

### Bug description

While my Unifi controller is operational, I've got two problems:

1. all ssh logins are refused and there is no log traffic to diagnose even with unifi log level set to debug
2. a variety of log errors about problems resolving host names

It is very hard to make heads or tails of the DNS errors without dig or nslookup (or apt-get to install them).

I could make my own fork and add some more stuff, but  I wondered if you had any suggestions.

Finallly, and I confess unrelatedly, can you suggest an end-to-end tutorial for using real certs? The comments in the readme are tantalizing. I can't use acme.sh directly in the image given the problems with DNS and package installs.

**Comment by jacobalberty** [comment]
What do you mean all ssh logins are refused? there is no ssh server in the image and what log entries? apt-get should let you install anything in the image that you need as well you just need to apt-get update first.

**Comment by TobiasLaving** [comment]
If you have access to the host machine running the container you can enter the network namespace of the container, allowing you to use the container network but host filesystem. 

Example:
```
[tobias@tobias-expertbook ~]$ docker inspect network-unifi-controller-1 | grep -i pid
            "Pid": 12682,
            "PidMode": "",
            "PidsLimit": null,
[tobias@tobias-expertbook ~]$ sudo nsenter -t 12682 -n
[tobias-expertbook tobias]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
12: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Pretty neat trick if the container image lacks any tools, but the host does not
