### ISSUE TITLE
Documentation says latest tracks 6.x but it see,s to be 7.x now. 

### ISSUE THREAD

**Issue by mbierman** [jacobalberty/unifi-docker#530]
### Operating system

N/a

### UniFi Tag

Latest

### Docker run

N/a

### Bug description

[hub.docker ](https://hub.docker.com/r/jacobalberty/unifi/tags) Says “latest” tracks 6.- but as of this release, it is 7.x. The documentation needs updating.

**Comment by jacobalberty** [comment]
This should be fixed as of last night
