### ISSUE TITLE
how to use docker-healthcheck.sh

### ISSUE THREAD

**Issue by bcookatpcsd** [jacobalberty/unifi-docker#542]
### Operating system

Void (rolling) 5.15.32

### UniFi Tag

unifi:v7.0.25

### Docker run

https://codebeautify.org/yaml-validator/y2261ef1f

### Bug description

I keep running out of memory and need to restart the controller.. I'm not sure why.. how do I use the healthcheck? It seems to work inside the container.. but when it runs out of memory and stops responding.. the container needs to be manually restarted.. 

```
~# docker exec -it unifi bash
root@void-10G-hs:/unifi# /usr/local/bin/docker-healthcheck.sh 
HTTP/1.1 302 
Location: /manage
Transfer-Encoding: chunked
Date: Tue, 19 Apr 2022 01:19:25 GMT

HTTP/1.1 302 
Location: /manage/account/login?redirect=%2Fmanage
Transfer-Encoding: chunked
Date: Tue, 19 Apr 2022 01:19:25 GMT

HTTP/1.1 200 
X-Frame-Options: SAMEORIGIN
vary: accept-encoding
Accept-Ranges: bytes
Last-Modified: Fri, 11 Mar 2022 11:47:50 GMT
Cache-Control: max-age=0
Expires: Tue, 19 Apr 2022 01:19:25 GMT
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 1325
Date: Tue, 19 Apr 2022 01:19:25 GMT

```

suggestions? 

Thank you in advance. 

### Steps to reproduce

I am not sure what causes the container to run out of memory.. 

### Relevant log output

```shell
not sure if this relevant.. 

[2022-04-18T18:33:08,365] <inform-33> ERROR Http11NioProtocol - Failed to complete processing of a request
java.lang.OutOfMemoryError: GC overhead limit exceeded
com.ubnt.service.lock.O0OO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.B.super(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.ooOO.super(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.G.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.G.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.G.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.H.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.PA.Object(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.PA.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.B$_OOo.run(Unknown Source) [ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by bcookatpcsd** [comment]
![image](https://user-images.githubusercontent.com/55087301/164034937-05817e75-df93-40b6-9779-66eb9e995c3f.png)

docker logs unifi -f
[2022-04-18 18:33:25,913] <docker-entrypoint> Starting unifi controller service.
[2022-04-18 18:33:25,914] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
[2022-04-18 18:34:17,766] <docker-entrypoint> Exit signal received, shutting down
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[2022-04-18 18:34:23,777] <docker-entrypoint> Starting unifi controller service.
[2022-04-18 18:34:23,778] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
[2022-04-18 18:38:45,004] <docker-entrypoint> Exit signal received, shutting down
[2022-04-18 18:38:55,355] <docker-entrypoint> Starting unifi controller service.
[2022-04-18 18:38:55,356] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
Exception in thread "http-nio-8080-Acceptor" java.lang.OutOfMemoryError: Java heap space

root@void-10G-hs:/unifi# /usr/local/bin/docker-healthcheck.sh
root@void-10G-hs:/unifi# echo $?
28

 docker exec -it unifi /usr/local/bin/docker-healthcheck.sh
[I] root@void-10G-hs ~ [28]#

**Comment by bcookatpcsd** [comment]
sometimes it's quick.. 

docker-compose -f unifi-compose.yml start; docker logs unifi -f

[2022-04-19 11:22:18,900] <docker-entrypoint> Starting unifi controller service.
[2022-04-19 11:22:18,900] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
Exception in thread "https-jsse-nio-8443-Poller" Exception in thread "https-jsse-nio-8843-Poller" Exception in thread "http-nio-8880-Poller" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "WebSocket background processing" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1040)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.timeout(NioEndpoint.java:1025)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:827)
        at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-nio-8080-Acceptor" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-5-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by bcookatpcsd** [comment]
Apparently I had environment listed twice in my compose file.. and that was why none of the env variables set were working.. 

:/

**Comment by Gamertech** [comment]
7.0.25 introduces a significant memory leak that continues in every official and EA release after it.

Ubiquiti seems to be refusing to acknowledge it again. They're happy to reply to every other comment on their forums but keep skipping any mentioning the leak.

If you have a backup, you can change tags to downgrade the docker image to an older one. `jacobalberty/unifi:v7.0.23` was the previous one.

**Comment by bcookatpcsd** [comment]
Mine seems to be doing much better since finding the Dup environment line.. 

CONTAINER ID   IMAGE                       COMMAND                  CREATED        STATUS                  PORTS     NAMES
06ff49c8e87a   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   47 hours ago   Up 46 hours (healthy)             unifi

        environment:
          - TZ=America/New_York
          - JVM_INIT_HEAP_SIZE=2048M
          - JVM_MAX_HEAP_SIZE=2048M
          - LOTSOFDEVICES=true


I have about 150 (+/-) switches and 350+ APs.. One controller across 10 networks.. mgmt interface for the unifi equipment, and 2 vlan'd ssids per AP.. 

Void linux controller (void is incredible; I run Void btw..) 

![image](https://user-images.githubusercontent.com/55087301/164704805-0d6292c3-1fb9-4f72-a83c-c32b4102b23f.png)

**Comment by bcookatpcsd** [comment]
This is the problem I have when I have a problem.. 

![image](https://user-images.githubusercontent.com/55087301/165105814-31aad483-5089-401a-b6ba-4f7b94a09c1c.png)

And then this is how I know it's happening.. 

![image](https://user-images.githubusercontent.com/55087301/165106075-8ef5c802-9229-4e02-9e3d-84c232abb78c.png)

docker restart unifi and then everything is fine.. 

I've not had this problem since I worked out the env in my compose file..

**Comment by bcookatpcsd** [comment]
root@void-d51d87:/usr/local/bin# /usr/local/bin/docker-healthcheck.sh
root@void-d51d87:/usr/local/bin# echo $?
28

And so this is my original bug.. how do I use the docker healthcheck.. 

Is there something I need to put in my compose to then do something when this 'unresponsive' situation occurs? 

Thank you in advance. 

@jacobalberty

**Comment by koitsu** [comment]
If you look at the health check script itself, you'll see that exit code 28 comes from `curl` (since it's the last command run).  If you examine the man page for curl, you'll see:
```
EXIT CODES
       28     Operation timeout. The specified time-out period was reached according to the conditions.
```
The healthcheck script is running, within the container itself, `curl --max-time 5 -kILs --fail https://localhost:${PORT}`.

The flags in question do the following:

* --max-time 5 = if the entire request and payload response takes longer than 5 seconds, treat the request as failed
* -k = do not do SSL certificate verification
* -I = issue a HEAD request, not a GET
* -L = follow HTTP 301 or 302 redirects / Location: headers
* -s = disables curl's progress metre and any error messages; **successful messages are still output** (as you found when running the HC script directly)

The ${PORT} variable is dynamically determined by the script prior to running `curl`.  It looks in your /unifi/data/system.properties file (within the container) and tries to extract the port number from any line that starts with `unifi.https.port` (not commented-out lines!).  If there is a match, it pulls the port number out from that directive.  If there isn't a match, it assumes port 8443.

You should be able to reproduce the problem with that knowledge.

My guess is that this begins to return 28 for you either because --max-time 5 is kicking in due to extreme CPU load (your previous screenshots show what looks like Java and Mongo running many, many times (there should only be 1 of each running in a single container!) and the request takes too long.  I don't know why that's happening to you.  I can, however, tell you that it is NOT NORMAL for a super basic Unifi Controller installation's Java process to be taking up 2.4GBytes of RES/RSS.  Mine takes up around 700MBytes (Java is bloated).   If there is a memory leak as reported by another user, I have not seen it, even when my container runs for months (but I certainly believe Ubiquiti software could cause this; they don't have a great track record of analysing resource usage effectively).  There might be a particular feature/thing people are using in it that causes the problem.  Likewise, my mongod process takes up around 100MBytes of RES/RSS, not 500MB+.

**Comment by bcookatpcsd** [comment]
@koitsu 

Thank you for this detailed breakdown.. 

I understand return values and what they imply, I guess my bigger question is.. 

Um, ok it timed out, um it failed.. now what? Soo.. starting with what we know.. should it restart the container? (this is what I do not know..) 

I'm looking for a solution to "when there is a problem"..

I would like the container to take care of itself and restart itself..

That seems to be what my question is.. 

My largest network I have close to 120 (2:1 AP to switch) and around 200 phones, which the lldp is spamming the server.log as well (but that is a different problem..) I have 9 Sites maybe a little over 500 unifi pieces (and then those 750+ phones)

So
 
```
 time /usr/local/bin/docker-healthcheck.sh
8< snip >8
Date: Mon, 02 May 2022 12:06:55 GMT


real    0m0.020s
user    0m0.011s
sys     0m0.001s
root@void-d51d87:~# echo $?
0
```

When it isn't this, I would like to restart the container.. 

or this

```
 time docker exec -it unifi /usr/local/bin/docker-healthcheck.sh


________________________________________________________
Executed in  222.28 millis    fish           external
   usr time   14.14 millis  102.00 micros   14.04 millis
   sys time    4.43 millis   34.00 micros    4.40 millis
```

I was assuming that possibly I could get docker to understand that this container was not responding, AND, do something about it.. 

But I cannot find anything in the dockerfile healthcheck (https://docs.docker.com/engine/reference/builder/#healthcheck) that speaks to dealing with containers once marked as unhealthy.. 

It would seem that the line referenced in the dockerfile for HEALTHCHECK never marks the container as unhealthy.. 

Do you see an unhealthy status in your 'ps -a'?

**Comment by bcookatpcsd** [comment]
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                      PORTS     NAMES
1629469d86ae   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   27 minutes ago   Up 27 minutes (unhealthy)             unifi

Looks as if it moves to unhealthy..

**Comment by bcookatpcsd** [comment]
Applied the docker run for that autoheal image.. 

Waiting and seeing.. 

switching between old and new if.. seems to make it happen sooner than later in my case..

**Comment by bcookatpcsd** [comment]
![image](https://user-images.githubusercontent.com/55087301/167187326-c1e361ae-e386-48e5-994a-40f8a254b288.png)

autoheal 

For. The. Win.

I never even knew things were down..

**Comment by wortkrieg** [comment]
@bcookatpcsd how did you manage to run it with autoheal? Mine keeps being restarted by autoheal=true during startup of the unifi container.

**Comment by bcookatpcsd** [comment]
I did start autoheal after unifi.. 

Just restarted docker as a whole.. (which restarted autoheal and unifi) 

```
[I] root@void-d51d87 ~# docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED      STATUS                           PORTS     NAMES
efb4828ecc1e   willfarrell/autoheal        "/docker-entrypoint …"   7 days ago   Up 1 second (health: starting)             autoheal
1629469d86ae   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   7 days ago   Up 1 second (health: starting)             unifi
```

Waited a few seconds.. and checked again.. and again.. 

```
[I] root@void-d51d87 ~ [SIGINT]# docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED      STATUS                             PORTS     NAMES
efb4828ecc1e   willfarrell/autoheal        "/docker-entrypoint …"   7 days ago   Up 21 seconds (healthy)                      autoheal
1629469d86ae   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   7 days ago   Up 21 seconds (health: starting)             unifi
[I] root@void-d51d87 ~# docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED      STATUS                        PORTS     NAMES
efb4828ecc1e   willfarrell/autoheal        "/docker-entrypoint …"   7 days ago   Up About a minute (healthy)             autoheal
1629469d86ae   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   7 days ago   Up About a minute (healthy)             unifi
```

Looks good.. 

According to my history:

```
docker run -d \
    --name autoheal \
    --restart=always \
    -e AUTOHEAL_CONTAINER_LABEL=all \
    -v /var/run/docker.sock:/var/run/docker.sock \
    willfarrell/autoheal
```

Didn't check this before.. 

```
 docker logs autoheal -f
06-05-2022 15:55:45 Container /unifi (1629469d86ae) found to be unhealthy - Restarting container now with 10s timeout
```

and checked unifi logs:

```
[2022-05-06 11:55:45,182] <docker-entrypoint> Exit signal received, shutting down
[2022-05-06 11:55:55,555] <docker-entrypoint> Starting unifi controller service.
[2022-05-06 11:55:55,569] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
[2022-05-10 08:46:44,130] <docker-entrypoint> Exit signal received, shutting down
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[2022-05-10 08:46:49,441] <docker-entrypoint> Starting unifi controller service.
[2022-05-10 08:46:49,455] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
```

Auto heal looks to be UTC and Unifi is America/New_York.. 

but the minutes line up.. 

just stopped autoheal, rm'd it.. and added the TZ env.. 

Nothing in the logs atm.. but does that help? 

```
 docker exec -it autoheal env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bd2e8a30d7cc
TERM=xterm
AUTOHEAL_CONTAINER_LABEL=all
TZ=America/New_York
AUTOHEAL_START_PERIOD=0
AUTOHEAL_INTERVAL=5
AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
DOCKER_SOCK=/var/run/docker.sock
CURL_TIMEOUT=30
WEBHOOK_URL=
HOME=/root
```
