### ISSUE TITLE
can we get a v7.1.61 tag please?

### ISSUE THREAD

**Issue by DolmensDude** [jacobalberty/unifi-docker#545]
release candidate as of 2 days ago. in the general release section and out of EA.

many, many, many thanks for all you're doing!

**Comment by niloofr** [comment]
It's here : https://github.com/jacobalberty/unifi-docker/releases/tag/v7.1.61

**Comment by jacobalberty** [comment]
Yep sorry meant to go back and close this since it's done

**Comment by DolmensDude** [comment]
Great. Thanks. (Again)

I use these via Container Station on QNAP which is nagging about end of support for LXC for LXD. Easy to use than pulling and a run command, but that ease of use creates a dependency on tags which is unfair on you..

Also, I probably should get my head around using the beta tag so that I can just self-determine a unifi version number?  Ubiquity has been pushing release candidates in general release which is getting out in front of rc tagging. Is using the beta tag the way to go?
