### ISSUE TITLE
restart controller == lose connectivity?

### ISSUE THREAD

**Issue by bcookatpcsd** [jacobalberty/unifi-docker#552]
### Operating system

void 5.15 -> 5.10 

### UniFi Tag

v7.1.61

### Docker run

unifi-compose.yml (local version)

### Bug description

I've been updating to the 7.1.61 and testing different docker env commands.. 

People are telling me the network has been going up and down all day.. 

I used to be able to reboot/restart the controller and devices would stay connected.. 

Is this happening to anyone else? 

### Steps to reproduce

Ping one of your core switches.. restart the controller.. do you drop packets? 

When the controller comes up.. verify the switch did not reboot..

**Comment by niloofr** [comment]
Hello,

I just did the following test :
  - launch of the ping command on my unifi equipment: gateway, switch and access point
  - restarting the unifi controller

Results :
  - no ping loss to unifi devices
  - no loss of ping to google

Context :
  - I use the all in one version, mongo is included in the same container
  - it runs on a Synology DS218+ NAS

Issues :
  - what is your version of docker?
  - what is the content of your docker compose file?
