### ISSUE TITLE
For level 3 adoption, 'settings->controller' instructions do not work. 

### ISSUE THREAD

**Issue by rekcodocker** [jacobalberty/unifi-docker#553]
### Operating system

Raspberry pi

### UniFi Tag

7.1.61

### Docker run

not relevant it's about the Unifiy controller

### Bug description

There is no "settings -> controller' in the Unify controller version 7.1.61 

### Steps to reproduce

Install the container and (according to instructions) try to access "settings -> controller".  
There are not 'controller'  settings.   See screenshot as proof.
![Screenshot_20220506_120513](https://user-images.githubusercontent.com/16322196/167111674-db55a24d-59c1-4151-adf7-8ee769eecf70.png)

**Comment by Gamertech** [comment]
Ubiquiti pump out new UI layouts frequently, so just needs to be updated. If you're using an old version tag, or have swapped to the 'classic' UI (an option in the UI settings) then those instructions would still apply.
