### ISSUE TITLE
Help text in "Force adoption IP" is outdated

### ISSUE THREAD

**Issue by tiesmaster** [jacobalberty/unifi-docker#557]
The help text [here](https://github.com/jacobalberty/unifi-docker#force-adoption-ip) talks about the `Settings -> Controller`, but there is no section for Controller. Next, I don't see `Controller Hostname/IP`, but rather `Other Configuration` (see screenshot below). I suspect that the settings screen has changed, and that this is a bit outdated. I had a bit of trouble finding that, so I think it might help other people finding the proper place in the Settings. Are your interested in a PR to update the text?

![afbeelding](https://user-images.githubusercontent.com/460904/171064731-2e4e428e-8cda-49f2-bf2c-16df82ea1abe.png)

**Comment by tiesmaster** [comment]
@jacobalberty I don't know if you saw this issue. Are you interested in a possible docs contribution?

**Comment by richb-hanover** [comment]
@tiesmaster - About the same time you posted, I also offered to update documentation in #558. Perhaps we could collaborate on this - I could use verification about forcing adoption (I got stuck on that as well).

I started on the README, but figured I'd ask if @jacobalberty was interested. I haven't heard back - I imagine he's busy. Perhaps it'll be simplest for you and me to work on a PR... Thanks.

**Comment by richb-hanover** [comment]
@tiesmaster I just posted a draft README to a gist at https://gist.github.com/richb-hanover/ba6d86e40879eaec1cf19407b09dedef

I would be pleased to get your comments, both on the overall document plus any thoughts about adoption. Thank you

**Comment by jacobalberty** [comment]
Hey, yes a documentation update would be welcome.

I've been busy with a project that will hopefully be a welcome surprise for Unifi users in the next few months.

**Comment by richb-hanover** [comment]
Great! Comments welcome [on my gist](https://gist.github.com/richb-hanover/ba6d86e40879eaec1cf19407b09dedef)

I have asserted a lot of things about running the container - please check that I've retained the truth of what was there before (and that I haven't introduced any false info.) Thanks!

**Comment by tiesmaster** [comment]
> I started on the README, but figured I'd ask if @jacobalberty was interested. I haven't heard back - I imagine he's busy. Perhaps it'll be simplest for you and me to work on a PR... Thanks.

@richb-hanover Absolutely! Glad to pair up. Awesome to see that you also opened an issue, and already put in a lot of work on a draft. I need to read up on this again, and check my notes, as it's been a while that I was working on this 😅

I gonna dive in, and post back here, when I have something.

> I've been busy with a project that will hopefully be a welcome surprise for Unifi users in the next few months.
@jacobalberty 😮 That's quite a cliffhanger 😅 Any chance, you can give us a little glimpse of that ^_^

**Comment by tiesmaster** [comment]
@richb-hanover It's a bit difficult to see what you're proposing to change to the `README.md` file. It might help if you'd fork the repo, and modify that file and either post a [diff link](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits), or even already create a draft PR to address your issue.

Next, I see that you've had quite a bit of trouble to get things up and running with Docker, which I can definitely understand, as Docker, and containers and such can be quite daunting at first. Though, I'm not sure if this repo should have all those details on operating Docker. I can imagine that this repo would require some level of experience with using Docker, but I think @jacobalberty should give his feedback on that.

---

Looking at what I was running into, I see that my issue is solely about the mismatching documentation on the "Force adoption IP" section, and I think we can tackle that in an isolated manner, to fix the confusion there.

@richb-hanover Looking at your issue, you wrote:

> I would make a big deal about setting the "Override inform host with controller hostname/IP" in the Unifi Controller, describing the different appearance in multiple versions of the Controller

I'd argue that we don't really need to handle multiple versions, but rather update the docs with the latest version of the controller, as that's what the Docker image gives you.

If I don't get any good reasons why not to approach it like that, then I'll put in a PR somewhere later this week.

**Comment by jacobalberty** [comment]
@tiesmaster https://github.com/jacobalberty/unifi-docker/compare/master...richb-hanover-readme I've committed the gist to another branch here's the compare link for them

**Comment by richb-hanover** [comment]
@jacobalberty That's a terrific plan. (I had planned to make my own branch, but you beat me to it. :-) I will stop making changes for the moment (I'm pretty happy with what I had written).

My goal in updating the README is mostly to serve newcomers, while being useful to people who know about Docker and/or Unifi:

- Give confidence that this will make their life easier. (That's why I threw in a little "marketing speak" - "No more hassling with ... upgrades" and concise version/hardware info into the first section.)
- Give simple, but accurate steps for getting the container working - both for initial setup, for stopping/restarting, and for making updates
- Collect all the command-line options into one place
- Collect some useful tips (particularly about AP adoption) so others don't have to stumble over them as I did

BUT... I'm not in love with my words. Please feel free to make further changes to what I've written. (I sort of know how this stuff works, but I sometimes don't get it all correct.) If I overstate something, please pull me back from the precipice :-) Thanks.

**Comment by richb-hanover** [comment]
@tiesmaster I know that Docker sometimes feels daunting. Part of the concern for newcomers is, "Can it really be this simple?" (I think so. Or at least simpler than installing Unifi Controller on some random OS with some random JDK version...)

I am hopeful that I have encapsulated everything a newcomer needs in a "Just Do This..." document. Feel free to update if I have "glossed over" important stuff. Thanks again.

**Comment by jacobalberty** [comment]
I will say I think @richb-hanover's thoughts on docker being daunting are good points. A lot of the issues opened are people not understanding docker itself. Upgrading is a very common question and adding that to the README.md is a good idea, it's a bit more scope than just updating the "force adoption ip" text but it does seem like a good idea to me.

**Comment by tiesmaster** [comment]
@jacobalberty @richb-hanover I've added a bit of feedback to [the commit](https://github.com/jacobalberty/unifi-docker/commit/16aabb480b23eb11999f4075c920bdb1738ff2ac#) created by @jacobalberty, I hope you'll find that useful.

@richb-hanover It might be good to move this to the next stage, and that you make a PR out of this. That also helps a little bit in the process of tracking the feedback, such as resolving discussion.

**Comment by richb-hanover** [comment]
@tiesmaster - Please re-open if the current "Force Adoption" description needs improvement. Thanks.

**Comment by tiesmaster** [comment]
@richb-hanover Thanks for the improved docs!!
