### ISSUE TITLE
can we get a 7.2.x tag?

### ISSUE THREAD

**Issue by DolmensDude** [jacobalberty/unifi-docker#573]
it's RC now (7.2.92).

many thanks for all of the great work!

**Comment by jacobalberty** [comment]
It's building on github actions now

**Comment by WSemeniuk** [comment]
Any ETA for this?

**Comment by DolmensDude** [comment]
It’s already available.

**Comment by WSemeniuk** [comment]
Oops. Missed that. Thanks for the response.

**Comment by mkocaks** [comment]
However I just tried to upgrade my docker image from 7.1.68 to 7.2.92 and it failed - moaning that the db upgrade cannot be performed from this version ?
Any ideas ?

**Comment by DolmensDude** [comment]
the 7.2.92-rc tag shows up as running v7.2.91 in my docker image...  

so we will need an actual 7.2.92 build and tag? (please) ;-)

**Comment by DolmensDude** [comment]
close this one too?

**Comment by joseal** [comment]
Hi, sorry if I'm on the wrong place, but I'm looking for a tag that give me version 7.2.64 for ARMv7 (raspberry), because I've it all configured on the windows version (currently 7.2.64) and I'm trying to migrate the backup to my docker installation...
Any ETA?
