### ISSUE TITLE
`latest` tag still gives 7.1.66; 7.1.68 cannot be found

### ISSUE THREAD

**Issue by richb-hanover** [jacobalberty/unifi-docker#576]
### Operating system

Ubuntu 20.04 LTS on Raspberry Pi

### UniFi Tag

latest

### Docker run

docker run  -d    --restart=unless-stopped    --init --user unifi    -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp    -e TZ='America/New_York'    -v /home/deploy/unifi:/unifi  --name unifi   jacobalberty/unifi:latest

### Bug description

As of 30Jul2022, I expected `latest` to give 7.1.68. but I stopped my 7.1.66 container (using the commands on the updated README.md page) and running this command, I still see 7.1.66 running.

```
docker run  -d   \
   --restart=unless-stopped \
   --init --user unifi \
   -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \
   -e TZ='America/New_York' \
   -v /home/deploy/unifi:/unifi \
 --name unifi \
  jacobalberty/unifi:latest
```

I tried to force the 7.1.68 tag, with the following command, but got this response:

```
deploy@ubuntu-on-RPi:~$ docker run  -d    --restart=unless-stopped \
   --init --user unifi    -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \
   -e TZ='America/New_York' \
   -v /home/deploy/unifi:/unifi \
 --name unifi \
  jacobalberty/unifi:7.1.68

Unable to find image 'jacobalberty/unifi:7.1.68' locally
docker: Error response from daemon: manifest for jacobalberty/unifi:7.1.68 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

### Steps to reproduce

See the description of the problem above

### Relevant log output

```shell
See the description above
```

**Comment by richb-hanover** [comment]
But the good news is that my 7.1.66 container still exists and it "just works" - no angst about whether I hosed my computer with some mistake in the upgrade process. I LOVE DOCKER! (Thanks again.)

**Comment by jacobalberty** [comment]
It would be `jacobalberty/unifi:v7.1.68`  not `jacobalberty/unifi:7.1.68`. but my output for `docker run -it --rm jacobalberty/unifi:latest dpkg -l unifi` to check the version is:
```
[2022-07-30 15:22:33,120] <docker-entrypoint> Executing: dpkg -l unifi
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  unifi          7.1.68-17885 all          Ubiquiti UniFi server
```

Did you make sure to `docker pull jacobalberty/unifi:latest` to make sure you have the latest?

**Comment by richb-hanover** [comment]
Ahah! That was the problem. Perhaps the README.md could be changed to list the tags as`latest` and `v7.1.68`. 

I did _not_ need to `docker pull jacobalberty/unifi:latest` Two minutes after the successful download, 7.1.68 was running without problems. Thanks.

```
deploy@ubuntu-on-RPi:~$ docker stop unifi
unifi

deploy@ubuntu-on-RPi:~$ docker rm unifi
unifi

deploy@ubuntu-on-RPi:~$ docker run  -d    --restart=unless-stopped \
   --init --user unifi    -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \
   -e TZ='America/New_York'  \
  -v /home/deploy/unifi:/unifi \
 --name unifi \
  jacobalberty/unifi:v7.1.68
Unable to find image 'jacobalberty/unifi:v7.1.68' locally
v7.1.68: Pulling from jacobalberty/unifi
8376114ff9b3: Pull complete
f3c0398106ec: Pull complete
694e103ab5fd: Pull complete
2a386c079b04: Pull complete
2c9249d02260: Pull complete
deede6b3fefe: Pull complete
a3835f60fab3: Pull complete
6de06dea5481: Pull complete
76983d5c4702: Pull complete
dd94b32dde3e: Pull complete
19ea6064d339: Pull complete
815342103cfb: Pull complete
698c066480fe: Pull complete
dbf124b4d024: Pull complete
d2ac88c5b172: Pull complete
704fcb3eca85: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:b7471df60d2e0696c9e7589bdce000bc0382c79d080d2028ebba8089c8ca32fa
Status: Downloaded newer image for jacobalberty/unifi:v7.1.68
88963b606b5af7de96c4eec34e3a9ae53de6faf1ce8a73b9cce9211950d5e419
deploy@ubuntu-on-RPi:~$
```

**Comment by richb-hanover** [comment]
Perfect. Thanks!
