### ISSUE TITLE
7.2.92 is released as stable

### ISSUE THREAD

**Issue by ning42** [jacobalberty/unifi-docker#582]
thanks for the great work !

just a info that 7.2.92 is [released](https://community.ui.com/releases/UniFi-Network-Application-7-2-92/f1903cbc-4daa-4695-ac8c-7324bcff529a) as a stable

**Comment by DolmensDude** [comment]
yep... true... the 7.2.92-rc tag is running 7.2.91 in my docker image...  so guessing we need another build and tag?

**Comment by DolmensDude** [comment]
thanks - tag available! close this one?
