### ISSUE TITLE
Switch from java controler to docker - AP are disconnected

### ISSUE THREAD

**Issue by stanthewizzard** [jacobalberty/unifi-docker#584]
### Operating system

docker

### UniFi Tag

stable

### Docker run

docker compose

### Bug description

I have set docker compose

Restored the backup from previous controler

All the app are disconnected.

What am I doing wrong ?
Thanks for help

### Steps to reproduce

---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ./config/:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

Everything is running.
I also did

Find Settings -> System -> Other Configuration -> Override Inform Host: in the Unifi Controller web GUI. (It's near the bottom of that page.)
Check the "Enable" box, and enter the IP address of the Docker host machine.

**Comment by maxirus** [comment]
> image: lscr.io/linuxserver/unifi-controller:latest

You're using the LinuxServer.io Image.... Go ask your question over [there](https://github.com/linuxserver/docker-unifi-controller).

**Comment by vMarkus** [comment]
Hi Stan,
not sure if IP changed etc and the APs ever connected back to the new container. You might have to ssh to your APs and set the inform host manually.  Cluster-ssh may do this for you all at once.

When logged in via ssh type `info` to see current inform-host device configuration

use `set-inform http://a.b.c.d:port/inform` with your needed IP and port configuration to update to your needs
