### ISSUE TITLE
[question] Why is the PKGURL value outdated in build.yml?

### ISSUE THREAD

**Issue by chopeen** [jacobalberty/unifi-docker#588]
Action [build.yml#L9](https://github.com/jacobalberty/unifi-docker/blob/master/.github/workflows/build.yml#L9) still references version `6.5.55`:

```
PKGURL: https://dl.ui.com/unifi/6.5.55/unifi_sysvinit_all.deb
```

Is it in purpose?

**Comment by jacobalberty** [comment]
That's only used for the test execution it ends up only used for the beta tags and isnt part of the version pushed. as long as it's compatible with the healthcheck and available for the build process it's fine, it only becomes outdated if the healthcheck ceases to be compatible with it or if ui pulls it from their servers.
