### ISSUE TITLE
Network update 7.2.94 is now available.

### ISSUE THREAD

**Issue by mo8Zomo0** [jacobalberty/unifi-docker#592]
### Operating system

Docker

### UniFi Tag

${TAG:-latest}

### Docker run

    image: "jacobalberty/unifi:${TAG:-latest}"     container_name: ${COMPOSE_PROJECT_NAME}_controller

### Bug description

Hi! I get the message: "Network update 7.2.94 is now available."

I See it is mentioned in: https://github.com/jacobalberty/unifi-docker/issues/589 
but as this does not seem to be a beta version it does not really fit in there.

https://community.ui.com/releases/UniFi-Network-Application-7-2-94/2ab774d1-0f24-422e-accc-53b8200c10a7

> Debian/Ubuntu specific
> 
> For Debian/Ubuntu users installing via our repo, please update your APT source (see [HERE](https://help.ubnt.com/hc/en-us/articles/220066768-UniFi-How-to-Install-and-Update-via-APT-on-Debian-or-Ubuntu)).
> We support MongoDB 3.6 since 5.13.10, older UniFi Network Application versions only support up to MongoDB 3.4.
>  
> 
> Checksums
> 
> 1f07beafd498ca2067c0ada22c09b310 *UniFi-installer.exe
> fa000379817c03d223589abceca5ec75 *UniFi.pkg
> 53cbbe3353476b4ff29da611213e19e0 *UniFi.unix.zip
> 79289dd4f8745f70739d11d05d0b1135 *unifi_sysvinit_all.deb
> 601df32736f41e40a80a3e472450a3e1 *unifi_sh_api

**Comment by jacobalberty** [comment]
This should be fixed now

**Comment by Nemrissme** [comment]
Thank you @jacobalberty , it's working for me 👍

**Comment by mo8Zomo0** [comment]
Thank you @jacobalberty (also in general for maintaining this)
