### ISSUE TITLE
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

### ISSUE THREAD

**Issue by fiver22** [jacobalberty/unifi-docker#594]
### Operating system

ubuntu 22.04.1

### UniFi Tag

latest

### Docker run

docker run -d     --restart=unless-stopped     --net=host     --name=unifi     -e TZ='America/New_York'     -e RUNAS_UID0=false     -e UNIFI_UID=1001     -e UNIFI_GID=1001     -v /var/docks/unifi:/unifi jacobalberty/unifi:latest

### Bug description

on docker run I get "docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown."

I've found similar issues which suggested manually creating /sys/fs/cgroup/systemd, then mounting cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd 
This works but I bet the issue returns after a reboot. I see people also adding it to fstab so they don't need to manually do it at reboot.

### Steps to reproduce

issue "docker run -d     --restart=unless-stopped     --net=host     --name=unifi     -e TZ='America/New_York'     -e RUNAS_UID0=false     -e UNIFI_UID=1001     -e UNIFI_GID=1001     -v /var/docks/unifi:/unifi jacobalberty/unifi:latest"

**Comment by EugeneKallis** [comment]
any solution to this? i just updated
