### ISSUE TITLE
What to do with `/unifi/run` volume

### ISSUE THREAD

**Issue by ViRb3** [jacobalberty/unifi-docker#610]
### Operating system

Ubuntu 22.04 LTS

### UniFi Tag

v7.2.95

### Docker run

As written in README.md

### Bug description

I noticed that there's an additional volume defined now:

`/unifi/run`
https://github.com/jacobalberty/unifi-docker/blob/f68257c140b303f552c760d2e7cca9ec65c07c2d/Dockerfile#L75

It appears to be the same as `/var/run/unifi`, which I believe was supposed to be named before. Does this really need to be a volume? And if yes, I supposed we need to give it a name now so it doesn't get created on every compose up (I have about 30 of them)?

Thanks!

**Comment by ViRb3** [comment]
Have you had the chance to look at this yet?

**Comment by gctwnl** [comment]
It seems I just ran into the same: [https://github.com/jacobalberty/unifi-docker/issues/610](https://github.com/jacobalberty/unifi-docker/issues/610)

**Comment by gctwnl** [comment]
I have:

1. Added `orun:` to the compose-wide named volumes
2. Changed the volumes in the controller service to:
```
      - run:/unifi/run
      - orun:/var/run/unifi
```
And this fixes the creation of dangling volumes for me.

**Comment by ViRb3** [comment]
Bump
