### ISSUE TITLE
UniFi Network Application 7.3.76 tag?

### ISSUE THREAD

**Issue by DolmensDude** [jacobalberty/unifi-docker#611]
surprise! Unifi auto-updating this on other platforms such as CloudKeys...

will latest pull this or do we need a specific tag?

as always, MANY THANKS for the work on the image - it's beyond awesome.

**Comment by philippgerard** [comment]
Same question here. I'm trying to set up an EA AP (U6+) and need the 7.3.76 or newer for that. Any idea when this will be supported, if ever?

**Comment by dk90103** [comment]
7.3.76 is GA now as pr https://ui.com/download/unifi/unifi-ap-ac-lr
Hopefully we will see a new buld for Docker soon.

**Comment by fussel132** [comment]
After 4 years they've finally upgraded from Java 8 to Java 11, incredible! Looking forward to the new Docker build... and thanks to @jacobalberty for the amazing work :)

**Comment by emilevandeven** [comment]
Tried to move from actual version on Raspberry Pi to docker version. Because on Raspberry it's the actual (7.3.76) version it's not possible to move to docker. Any idea when the docker version is updated to the actual version?

**Comment by jacobalberty** [comment]
the 7.3.76 tag is building now. It won't take over `latest` yet I have a few more systems I'll push it to to confirm it upgrades fine but in about 10 minutes if you want to rush to use it you can use the v7.3.76 tag directly.

**Comment by jacobalberty** [comment]
Thank you @jcostom i went ahead and merged it. Rebuilding 7.3.76 tag now too

**Comment by jcostom** [comment]
Happy to be able to lend a hand. Thanks @jacobalberty for all the work you've put in on this!

**Comment by DolmensDude** [comment]
thanks!
