### ISSUE TITLE
New warning on loading 7.3.76

### ISSUE THREAD

**Issue by Gamertech** [jacobalberty/unifi-docker#615]
### Operating system

Synology DSM 7.1.1

### UniFi Tag

latest

### Docker run

GUI

### Bug description

Doesn't seem to affect anything so far, but now getting this repeatable error in the logs on startup after the update to 7.3.76.

### Steps to reproduce

-Install/update to 7.3.76 on Synology Docker (potentially other systems as well)
-Check the logs for this repeatable warning.

### Relevant log output

```shell
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/usr/lib/unifi/lib/spring-core-5.3.18.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)

WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release
```

**Comment by mikeo999** [comment]
Get the same error today also.

**Comment by DolmensDude** [comment]
confirm seeing this on Container Station on a QNAP as well.

**Comment by gterpstra** [comment]
https://community.ui.com/releases/UniFi-Network-Application-7-3-76/85c75fc7-3e0f-4e99-aa90-7068af4f1141#comment/a6617286-5ded-49e5-8321-78b0078dcf26

Doesn´t seem  container related

**Comment by Hisashi150** [comment]
Same errors on Synology Docer on my DS718+

**Comment by mooglestiltzkin** [comment]
same on qnap. how to fix?

**Comment by lahma0** [comment]
Same error running the container on a Raspberry Pi 3b+ which is running Ubuntu 20.04.5 LTS.

**Comment by Djowie** [comment]
Same container for Ubuntu 20.04

**Comment by halfcyan** [comment]
Also happening on Ubuntu 22.04. For now, is it just better to pin it to an older release?

**Comment by jacobalberty** [comment]
The warning is a [known issue in apache tomcat](https://lists.apache.org/thread/s0xr7tk2kfkkxfjps9n7dhh4cypfdhyy). There's some startup options that could be used to hide them but that would be purely cosmetic, akin to ignoring it.

**Comment by halfcyan** [comment]
It'd be fine if it was just an apache warning, but it prevents the container from starting. Is there some way to bypass it or allow it to continue starting while showing that in the log? Or is this a Ubiquiti issue?

**Comment by jacobalberty** [comment]
The warning won't prevent the container from starting, do you have anything in the  `/unifi/log/mongod.log` or `/unifi/log/server.log` it also looks like there's a new `/unifi/log/migration.log` server.log is most likely to be interesting in terms of torubleshooting.

**Comment by daxm** [comment]
I just rebuilt and loaded my unifi container and saw this message as well.  No response from the devs?
```

**Comment by Trilis29** [comment]
Any info?
I have same error, latest version even got me 404 error

**Comment by Gamertech** [comment]
jacobalberty has responded to this thread and stated it's not an issue. This error is only cosmetic and has nothing to do with any other issues you're having.

**Comment by Trilis29** [comment]
Seems issuse was with new release and DB problem, used tag:7.3.83-ls179 everything works now

**Comment by jacobalberty** [comment]
@Trilis29 whatever the issue there is unlikely to be caused by these warning messages. These warning messages are explicitly saying nothing is broken by the message but it might be in the future. The real root cause is going to be in one of the files in /unifi/log. One of `/unifi/log/mongod.log`, `/unifi/log/server.log` or `/unifi/log/migration.log` is going to contain more information that would be useful in determining the actual cause.

**Comment by sporbox** [comment]
I have that same problem. I get 404 error when I try to access

**Comment by RuudSchellekens** [comment]
I had the same problem. It took the image container much longer to start all services but eventually, the 404 disappeared even with the aforementioned warnings. Used [v7.4.162](https://registry.hub.docker.com/layers/jacobalberty/unifi/v7.4.162/images/sha256-bb0cefe2350d012278c84ddd319835c594e8dff588a939919aba3beb3769bf9b)
