### ISSUE TITLE
WiFiman Speed Tests won't connect to this Docker container.

### ISSUE THREAD

**Issue by wabragg** [jacobalberty/unifi-docker#626]
### Operating system

Debian 4.4.59+ / Synology DSM 6.2.4#25556

### UniFi Tag

latest / 7.3.76

### Docker run

-p 6789:6789/tcp ... yada yada yada, see the image attached below.

### Bug description

Though I pass port 6789/tcp through from my container to the _bridge_ network driver, I've never been able to get WiFiman to recognize my controller on my local network.  If you go into the UNA (Unifi Network App) to Insights/Speed Tests you'll just see a page telling you to go get WiFiman for iOS or Android.  Once loaded on your phone, it's supposed to communicate with the UNA over port 6789 to record speed test information from various places on your local WiFi network.

I've tried this many times, with the current UNA and with older 6.x.x versions and I've never been able to get it to work.  I export all of the normal ports from the Docker container on the Unifi port list excluding those for MongoDB and the UAP-EDU devices.  This includes port 6789/tcp as is listed on your man page and the Unifi site.

The UNA is never seen as being on the local network by the WiFiman program on iOS.

Curiously, your man page shows ...

6789/tcp - Speed Test (unifi5 only) (optional)

which seems to indicate that it only works with UNA 5.x.x or older.  I'm not sure why this would be the case since it's clearly still in all of the recent versions of UNA.

Others I've connected with up on the Unifi community support board also seem to have this same issue with this container.

### Steps to reproduce

Run the container making sure to pass port 6789 through to the network unaltered ... "-p 6789:6789/tcp".  Download Ubiquiti's WiFiman from the app store. While on the local network, Open WiFiman on an iOS device and go to the "Signal" menu item at the bottom.  You'll get a page that reports "Signal Insights Not Available" followed by "Please connect to Unifi Network, or use a WiFiman Wizard to explore Signal Strength insights."

I don't have an Android device with which to further test.

![DockerUnifi](https://user-images.githubusercontent.com/25797889/213320496-5546ec45-85c1-4ac5-8cf0-2a57e5aa86c8.PNG)

**Comment by wabragg** [comment]
Just for clarity, I have gone into UNA's Settings / System / Advanced / WiFiman and enabled connections.  I had neglected to mention this in my original post.

**Comment by wabragg** [comment]
Activity comment.  Not stale.

**Comment by MarcHagen** [comment]
Hi, dont know if you need information. But it seems that in the new 6+ wifiman is only enabled for Dream Machine or Dream Machine Pro running a UniFi Network application.
It also seems the toggle/setting is removed from the UI, but exists in de UniFi control app... confusing yes.

Took me some time to figure this out a while ago, especially because it did work in the 5.x version. 

Please correct me if im wrong! Love too be wrong on this one :)

**Comment by wabragg** [comment]
So you're saying the feature isn't really there in the Network application even though the check-box and the SpeedTest page are there?  Seems antithetical to their making the Network application available outside of their environment.  You'd think they would note or document the neutered features that they are disabling on non-Ubiquiti devices.

**Comment by MarcHagen** [comment]
https://ubntwiki.com/products/software/unifi-controller/6.1_consolidated_change_log
```
Enable WiFiman page. *
* For UDM/UXG platforms only.
```

That's the only note I could find in a while. 
I've just given up, the option is not in the admin section so there is something preventing it from working.

If you source in the UI code you can find:
```
{"group":"system","fieldId":"mgmt_settings.wifiman_enabled","id":"mgmt_settings.wifiman_enabled","isApplicable":"isUbiOS","label":"SETTINGS_COMMON_WIFIMAN","route":"/:site/settings/system","tags":["SETTINGS_SYSTEM_WIFIMAN_DESC"],"type":"FIELD","sortIndex":0,"clickIds":["system-advanced-toggle"]}
```
pretty print:
```json
{
  "group": "system",
  "fieldId": "mgmt_settings.wifiman_enabled",
  "id": "mgmt_settings.wifiman_enabled",
  "isApplicable": "isUbiOS",
  "label": "SETTINGS_COMMON_WIFIMAN",
  "route": "/:site/settings/system",
  "tags": [
    "SETTINGS_SYSTEM_WIFIMAN_DESC"
  ],
  "type": "FIELD",
  "sortIndex": 0,
  "clickIds": [
    "system-advanced-toggle"
  ]
}
```
Somewhere there is a `isUbiOS` function that determs whenever to show it or not.
But the funny thing is the `.../get/setting` api call says : `"wifiman_enabled":true` 

So its enabled, but not working? 
You tell me. And well maybe it is just me! 
But I've not good way to verify and most forums are full with UDM, cloudkeys and unifi switch related wifiman issues.
I've only some access points nothing more, nothing less.

**Comment by wabragg** [comment]
So far it looks like this can be attributed to a cert problem ... which seems to also be affecting Ubiquiti hardware as well like the Cloud Key v2.  It's possible that this is something Ubiquiti protected with a cert and now they are also having trouble keeping it working in their own stuff.

**Comment by boscorelly** [comment]
Not sure it's cert related.

I'm using a traefik as reverse proxy with a valid cert, and it doesn't work too.

**Comment by wabragg** [comment]
I might flip over to the linuxserver.io/unifi-controller Docker image and see if it works properly in that one.
