### ISSUE TITLE
Doesn't seem to run on dedicated IP on ipvlan

### ISSUE THREAD

**Issue by penguinjeff** [jacobalberty/unifi-docker#627]
### Operating system

Fedora 37

### UniFi Tag

rc

### Docker run

docker run -d --init --restart unless-stopped --network vlan10 --ip=192.168.0.223 -p 3478:3478/udp -p 8443:8443 -p 8080:8080 -e TZ='America/Denver' -v /home/unifi:/unifi --user unifi  --name unifi  --name unifi jacobalberty/unifi:rc

### Bug description

I created my network like so
docker network create -d ipvlan --subnet=192.168.0.0/24 --gateway=192.168.0.1 -o ipvlan_mode=l2 -o parent=br0 vlan10

I try hitting https://192.168.0.223:8443 but it times out
Another thing is the --name option doesn't seem to work it just uses a generic number letter combo

### Steps to reproduce

use the info from my description

**Comment by wabragg** [comment]
Interesting.  I've never been able to get the ipvlan driver to work right while the macvlan driver seems to work as expected.  I'll have to watch this one to learn what the solution is for ipvlan.

**Comment by penguinjeff** [comment]
Ugh I had the exact opposite issue. I can start an nginx server and it seems to work perfect on an ipvlan but could not connect to it using a macvlan. I thought my macvlan was broken. I'll give a macvlan a try with your container. Not sure why the --name does not work with your container.

**Comment by buckaroogeek** [comment]
Not sure if this will help or confuse. I used to run unifi on my fedora workstation using a macvlan. Several years ago I moved it to docker-compose and rehosted on a synology.  A shel l script I had to launch unifi on the workstation had the following. Not sure if this would still work. At a high level: 1. create the macvlan; 2. launch unifi on the macvlan; 3. create a shim on the fedora host network so that the network traffic from the workstation can be routed to IPs on the macvlan. As I noted above this is all fairly old and untested.  I also had a variant with podman instead of docker.

```
# create docker macvlan, reserve IP for shim, use defined subnet for docker
docker network rm unifinet
docker network create -d macvlan -o parent=enp8s0  --subnet 192.168.110.0/24 --gateway 192.168.110.1 --ip-range 192.168.110.224/27 --aux-address 'host=192.168.110.225' unifinet

# create macvlan shim on host needed to allow host access to the docker
# hosted applications
#ip link add unifinet-shim link enp8s0 type macvlan  mode bridge
#ip addr add 192.168.110.225/32 dev unifinet-shim
#ip link set unifinet-shim up
#ip route add 192.168.110.224/27 dev unifinet-shim

docker run --rm --init --network unifinet --ip 192.168.110.226 -e TZ=America/Pacific -e RUNAS_UID0=false -e UNIFI_UID=$uUID -e UNIFI_GID=$uGID -v $PWD/unifi-vol:/unifi:Z -v $PWD/run:/var/run/unifi:Z --name unifi jacobalberty/unifi:latest

```

**Comment by penguinjeff** [comment]
Thank you buckaroogeek I'll give that a try I don't know what a shim is and wonder if it will work on my br0 as I needed br0 to properly setup networking in my libvirt environment. I want to move as many machines as I can to docker containers. I am working on pihole and unifi for now then minecraft and maybe freepbx. I still beed libvirt for my gaming vms so I can pass my video card through. Not doing the shim may have been why macvlan did not work for me earlier.

**Comment by penguinjeff** [comment]
Issue was with selinux and volumes.

**Comment by penguinjeff** [comment]
Issue was with selinux and volumes.

**Comment by buckaroogeek** [comment]
> Thank you buckaroogeek I'll give that a try I don't know what a shim is and wonder if it will work on my br0 as I needed br0 to properly setup networking in my libvirt environment. I want to move as many machines as I can to docker containers. I am working on pihole and unifi for now then minecraft and maybe freepbx. I still need libvirt for my gaming vms so I can pass my video card through. Not doing the shim may have been why macvlan did not work for me earlier.

Just to complete the thread. this post - https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/ - provides a useful overview of docker macvlans and the need for a "shim". The shim is basically a way to enable a network connection from the docker host to the IP addresses on the docker macvlan.

**Comment by penguinjeff** [comment]
adding :Z to my volume made it work just FYI ipvlan is so much easier to use.
