### ISSUE TITLE
no redirect from 80

### ISSUE THREAD

**Issue by penguinjeff** [jacobalberty/unifi-docker#628]
### Operating system

Fedora 37

### UniFi Tag

latest

### Docker run

docker run -d --init --restart unless-stopped --network vlan10 --ip=192.168.0.223 -p 3478:3478/udp -p 80:80 -p 8443:8443 -p 8080:8080 -e TZ='America/Denver' -v /home/unifi:/unifi --user unifi  --name unifi  --name unifi jacobalberty/unifi:rc

### Bug description

Not really a bug more of a feature request and not really sure how to implement but it would be nice to have a redirect from port 80.
Note: I changed in my unifi/data/system.properties file
and set
unifi.https.port=443

so that I can go to
https://unifi-ip-or-dns/

but sometimes I forget the 's' and it would be nice to be redirected.

When I had this as a vm instead of a docker container I had lighttpd running and a simple redirect page at /var/www/html/index.html
lighttpd I think was still way overkill maybe a simple java app (since java is already installed anyways for unifi app) to redirect using a page at /var/www/html/index.html then I could map my own volume for /var/www/html with an index.html and have a custom redirect page. I could maybe write a simple java program to do this. I think just about anyone could.

From what I remember java itself has a built in web server that you could probably just load a file as a page.
Maybe also have a variable to pass to run that app so it isn't running by default to slim it up.

Ooh maybe even better just a way for me to start my own command  in the container that I could mount my own volume and run my own java app like I was thinking. I think for now I can connect and start my own java app. I'll try that out. But it would be nice to have a way to automate the starting of my own redirect program.
maybe a way for an rc.local
I could mount a volume in /etc/rc.d/(it doesn't exist in your container) that has my rc.local and have my app in there
like if /etc/rc.d/rc.local exists execute it?
And if I have in my rc.local something like
java -jar /my_mount/redirect.jar

Is there already something in the Docker framework that would already do this(run something like rc.local) I'm kind of new to docker.
I'd like to do something similar to my pihole docker container as well as I have to login and add my own index.html in there as well.
For now when I start that container I then use
docker exec -it pihole bash
and run a script I placed in /etc/pihole/
or is that what the /run directory is for?
Maybe I can create an rc.local in there that does exactly as I want.

### Steps to reproduce

if you assign an ip via macvlan or ipvlan go to http://ip/
you will get a page "This site can’t be reached" making me think the app is down.

**Comment by buckaroogeek** [comment]
Does the Environment Variables section in the readme address this? See https://github.com/jacobalberty/unifi-docker#environment-variables.

I have the following in my docker-compose.yaml file:
```
...
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Los_Angeles
      UNIFI_HTTP_PORT: 80
      UNIFI_HTTPS_PORT: 443
...
```
This seems to work fine with Firefox on my Fedora workstation but Chrome does not pick up the redirect.

**Comment by penguinjeff** [comment]
buckaroogeek you are a miracle worker thank you so much.
