### ISSUE TITLE
Docker image sits at Starting unifi controller service.

### ISSUE THREAD

**Issue by skluthe** [jacobalberty/unifi-docker#63]
<docker-entrypoint> Starting unifi controller service.

Just pulled the latest image and am running it in docker on OMV 3. Log sits at 
`Starting unifi controller service.`

Here is the full log with 1 reboot. Trying the stable tag now.
`[2017-10-12 21:12:20,643] <docker-entrypoint> Starting unifi controller service.`
`[2017-10-12 21:19:51,358] <docker-entrypoint> Exit signal received, shutting down`
`/usr/local/bin/docker-entrypoint.sh: line 1: kill: (15) - No such process`
`[2017-10-12 21:19:58,589] <docker-entrypoint> Exit signal received, shutting down`
`[2017-10-12 21:20:02,184] <docker-entrypoint> Starting unifi controller service.`

**Comment by jacobalberty** [comment]
Which tag is that?

**Comment by skluthe** [comment]
Latest

**Comment by jacobalberty** [comment]
whats the contents of /var/log/unifi look like on the failed start?  I just launched a quick  test with `docker run -t -i -p 8444:8443 jacobalberty/unifi:latest`
and it runs fine.

**Comment by skluthe** [comment]
Looks like it's an empty folder?? Super weird. There's also empty folders for mongodb and apt.

**Comment by skluthe** [comment]
![image](https://user-images.githubusercontent.com/23664304/31530528-06bbf67c-af96-11e7-9aca-a6f18c5f35ab.png)
This is what comes pre-set for variables.

**Comment by skluthe** [comment]
Are there any commands I can run to troubleshoot this?

**Comment by jacobalberty** [comment]
Are you using a new fresh install where it's creating its own data? or importing existing unifi data?

**Comment by skluthe** [comment]
Fresh install.

**Comment by jacobalberty** [comment]
/var/log/apt is completely empty? that's created at install time not execute time, somethings really fishy there. Are you sure you have enough free drive space on the system?

**Comment by jacobalberty** [comment]
What volumes do you have defined for the container?

**Comment by skluthe** [comment]
I have 5gb free in my rootfs and ~2 tb free in my docker share.

**Comment by skluthe** [comment]
![image](https://user-images.githubusercontent.com/23664304/31530985-dcad40d6-af98-11e7-8c1d-4cd415d0e070.png)
![image](https://user-images.githubusercontent.com/23664304/31530992-e770146c-af98-11e7-9acf-393ec294da5f.png)
![image](https://user-images.githubusercontent.com/23664304/31531000-f0e95a3a-af98-11e7-8a5f-541a202f5a4e.png)

**Comment by skluthe** [comment]
I now see I didn't uncheck Read only. Going to the store. When I'm back I'll fix that and try again and report back. Thank you for your help!

**Comment by jacobalberty** [comment]
That would explain quite a bit, still odd that /var/log/apt is empty, it should have the package install information from the setup

**Comment by skluthe** [comment]
Looks like it's still having the same behavior
![image](https://user-images.githubusercontent.com/23664304/31531695-6cbd73ae-af9d-11e7-9907-014d636aa9af.png)
![image](https://user-images.githubusercontent.com/23664304/31531698-750b05d0-af9d-11e7-9233-44a862345cba.png)
![image](https://user-images.githubusercontent.com/23664304/31531702-7b9d7fe0-af9d-11e7-91c6-eef063a10c56.png)
Anything here I need to change?

**Comment by skluthe** [comment]
APT does have some files in it but mongodb and unifi folders are blank still.

**Comment by skluthe** [comment]
[server.log](https://github.com/jacobalberty/unifi-docker/files/1381498/server.log)


[mongod.log](https://github.com/jacobalberty/unifi-docker/files/1381499/mongod.log)
These are the only 2 files with logs in them. I found them on my docker host in /var/logs/unifi

**Comment by jacobalberty** [comment]
Delete and recreat the /var/lib/unifi volume, it appears to be corrupt

**Comment by skluthe** [comment]
Deleted the volume and it still comes back with rc=137 error.

**Comment by jacobalberty** [comment]
not sure how to accomplish it in the omv docker plugin but get the cli inside the container, on the vanilla docker cli this is something like `docker exec -t -i <containerid> bash` then run df, verify that you see the full 2tb of free space in /var/lib/unifi, its possible its for some reason on the rootfs partition and may not have enough space to create the whole volume. Also make sure there are no quotas or anything in effect that may limit storage usage as well.

**Comment by skluthe** [comment]
Just did a fresh install and it's working. Needed to clean omv up anyways. Thank you for the help!
