### ISSUE TITLE
Not working with arm/v7

### ISSUE THREAD

**Issue by zeusilein** [jacobalberty/unifi-docker#632]
As mongodb does currently not support arm/v7 no database is installed.

Please remove arm/v7 from supported platforms.

Working work around / solution: 
Use external database image webhippie/mongodb:latest-arm32v7 with environment variables DB_URI, STATDB_URI, DB_NAME.

Tested on QNAP TS-431XeU with cpu al314.

**Comment by jacobalberty** [comment]
This image uses a legacy version of mongodb (3.6) so it still works on 32 bit armv7 devices. I just tested on a raspi 2 and was able to successfully run the container.

**Comment by adamobrebski** [comment]
I have similar problem, and stop on start connectig on db. Can you explain me how do you configure container, database (what about password to db)?

**Comment by zeusilein** [comment]
On QNAP the installation of mongodb is not working with "latest" and I have not found any version specific for arm/v7. I can not/do not know how to specify the version of the database - latest is choosen for mongodb. As latest mongodb is not available for arm/v7 it does not work.

**Comment by zeusilein** [comment]
> I have similar problem, and stop on start connectig on db. Can you explain me how do you configure container, database (what about password to db)?

My working solution is in detail:

(A) Database "webhippie/mongodb:latest-arm32v7" is configured with bridge networking on http://192.168.xy.ab:27017/

(B) Unifi "jacobalberty/unifi:latest" is configured with bridge networking on http://192.168.xy.cd.
The following environment variables have to be set at creation of the Unifi container in advanced settings:
(B-1) Name: DB_URI 
(B-1) Value: mongodb://192.168.xy.ab:27017/unifi
(B-2) Name: DB_NAME
(B-2) Value: unifi
(B-3) Name: STATDB_URI
(B-3) Value: mongodb://192.168.xy.ab:27017/unifi_stat

**Comment by kwesterl** [comment]
Any chance arm32v7 could still be supported in the future? 
ref: https://hub.docker.com/r/apcheamitru/arm32v7-mongo

**Comment by BobSammers** [comment]
@kwesterl It looks like that image contains MongoDB 3.2, which is the version already used in recent jacobalberty/unifi builds (for armhf - other architectures use later versions), so I don't think that project will help., unfortunately. I've just changed my docker-compose to use "jacobalberty/unifi:v7.4" instead of "latest".
