### ISSUE TITLE
7.3.83 is GA now - Any chance we could get an update pushed ?

### ISSUE THREAD

**Issue by dk90103** [jacobalberty/unifi-docker#633]
### Operating system

7.3.76

### UniFi Tag

stable

### Docker run

Not really used

### Bug description

Not really a bug but Unifi released 7.3.83 to stable/GA. It would be amazing if we could get a new docker build based on this version.

**Comment by jacobalberty** [comment]
Building now I'll mark the tag as release once build completes and i have it deployed here.

**Comment by dk90103** [comment]
Amazing work - Thank you Jacob. Not only for this, but all the great work you are doing on this project. 
    	
    
  

 Fra: Jacob Alberty ***@***.***>Sendt: onsdag, februar 8, 2023 6:27 PMTil: jacobalberty/unifi-docker ***@***.***>Cc: dk90103 ***@***.***>; Author ***@***.***>Emne: Re: [jacobalberty/unifi-docker] 7.3.83 is GA now - Any chance we could get an update pushed ? (Issue #633) 
Building now I'll mark the tag as release once build completes and i have it deployed here.

**Comment by jacobalberty** [comment]
`lastest` is on it now, something broke in the actions for the `v7.3.83` tag, investigating that.

**Comment by DolmensDude** [comment]
tag latest crashing on startup on QNAP Container station right now, rolled back, and will wait until v7.3.83 specific tag is okay. just noting that latest has an issue.

and once again - many thanks for the FAB solution!

**Comment by jacobalberty** [comment]
@DolmensDude The break on the v7.3.83 specific tag has to do with the change in build process, i wouldnt expect it to fix a crash. Might be worth opening another ticket with more details on any crashing.

**Comment by DolmensDude** [comment]
Latest from QNAP’s container station did something really weird.  It tried to do v7.0.25…  Surely that’s what is was… Recreating as 7.3.76 worked again instantly (as usual).

Pulled from logfile server.log

[2023-02-08T18:06:24,799] <launcher> INFO  db     - Version 7.3.76 has changed to 7.0.25, attempting to start migration
[2023-02-08T18:06:25,832] <launcher> INFO  system - ======================================================================
[2023-02-08T18:06:25,834] <launcher> INFO  system - UniFi 7.0.25 (build atag_7.0.25_17292 - release/release) is started
[2023-02-08T18:06:25,834] <launcher> INFO  system - ======================================================================
Have been using specific version number tags for a while now… maybe there was a cached image in CS?  Will have to check later, but I probably can’t look for another 36 hours or so… 

It was probably something I did, or out of sync wat CS pulls… although it’s the usual docker registry. 

Mark as an anomaly for now?  Don’t waste any cycles chasing it down on your end either…  Am up and running, and I’ll do the version specific tag when it’s avail.

Again, many thanks!

**Comment by jacobalberty** [comment]
@DolmensDude version specific tag is up now then, you should be good to go.

**Comment by DolmensDude** [comment]
> @DolmensDude version specific tag is up now then, you should be good to go.

Bravo! up and running!
