### ISSUE TITLE
No aliases for private keys found in key store.  EC private key issue?

### ISSUE THREAD

**Issue by patricegautier** [jacobalberty/unifi-docker#636]
I have a controller running fine inside a container on a rPi.. all good.

I am however running into an issue trying to get SSL going.  I am using ZeroSSL certs and keys that work in many other contexts so unlikely to be the problem.

Tomcat is running into an issue at startup, from /unifi/log/server.log

`Caused by: java.lang.IllegalArgumentException: No aliases for private keys found in key store`

Which I think indicates a problem with the key or key import into the key store

The only thing unusual I see is that it is an EC (elliptic Crypto) key:

/unifi/cert$ cat key.pem
-----BEGIN EC PRIVATE KEY-----
keystuff here..
-----END EC PRIVATE KEY-----

might this be causing an issue?

Spelunking, I can not find any other logs to look at for clues..

**Comment by patricegautier** [comment]
I think I will answer my own question.. independently of this container, another unifi device started complaining with:

`2023-02-14T02:47:44.544Z - error: Failed to load certificate /data/unifi-core/config/unifi-core.crt: Cannot read public key. OID is not RSA.`

So the EC key is likely to problem somehow with Unifi.

**Comment by patricegautier** [comment]
no love - even with a regular RSA 2048 bit key, it's the same error.

For what it's worth:

openssl x509 -in cert.pem -noout -text

unifi@c34605cc7243:/unifi/cert$ openssl x509 -in cert.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            3e:f2:39:62:a8:06:a7:28:c1:75:45:92:76:19:c7:b5
        Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = AT, O = ZeroSSL, CN = ZeroSSL RSA Domain Secure Site CA
        Validity
            Not Before: Feb 14 00:00:00 2023 GMT
            Not After : May 15 23:59:59 2023 GMT
        Subject: CN = testController.gautiers.name
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
<snip>
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier:
                keyid:C8:D9:78:68:A2:D9:19:68:D5:3D:72:DE:5F:0A:3E:DC:B5:86:86:A6

            X509v3 Subject Key Identifier:
                DA:68:CE:B7:5D:29:9D:B9:1B:7D:28:17:1D:2F:84:03:C1:78:A3:F0
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Certificate Policies:
                Policy: 1.3.6.1.4.1.6449.1.2.2.78
                  CPS: https://sectigo.com/CPS
                Policy: 2.23.140.1.2.1

            Authority Information Access:
                CA Issuers - URI:http://zerossl.crt.sectigo.com/ZeroSSLRSADomainSecureSiteCA.crt
                OCSP - URI:http://zerossl.ocsp.sectigo.com

            CT Precertificate SCTs:
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : AD:F7:BE:FA:7C:FF:10:C8:8B:9D:3D:9C:1E:3E:18:6A:
                                B4:67:29:5D:CF:B1:0C:24:CA:85:86:34:EB:DC:82:8A
                    Timestamp : Feb 14 06:27:43.591 2023 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:45:F2:7A:8B:F1:FA:DC:C3:C9:73:C4:2E:
                                C2:D5:DF:16:3E:96:9E:5B:51:4D:CF:8F:97:86:55:C1:
                                6F:EA:A3:BA:02:21:00:A1:24:31:3D:EF:8B:E7:3C:7B:
                                8F:D0:5B:15:E4:15:EE:9D:1A:E5:3B:1C:CD:D9:36:15:
                                EE:44:BE:B3:01:67:C0
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 7A:32:8C:54:D8:B7:2D:B6:20:EA:38:E0:52:1E:E9:84:
                                16:70:32:13:85:4D:3B:D2:2B:C1:3A:57:A3:52:EB:52
                    Timestamp : Feb 14 06:27:43.531 2023 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:18:76:A8:3B:62:3B:09:AF:05:68:F5:7B:
                                A2:85:EB:44:AB:60:45:91:4E:63:70:2C:76:4F:93:E9:
                                C4:19:57:1C:02:21:00:D1:C6:27:1A:DE:4E:D0:7E:A5:
                                48:9F:E0:28:64:76:A5:7E:55:68:81:C0:A3:17:6B:AA:
                                57:1B:A8:4C:67:A7:B9
            X509v3 Subject Alternative Name:
                DNS:testController.gautiers.name
    Signature Algorithm: sha384WithRSAEncryption
<snip>

**Comment by netgitdom** [comment]
> After a lot of digging, it turns out that the keystore was somehow corrupt. Removing it and the cert.pem.md5 caused it to get regenerated and everything is right with the world.
> 
> As a side note, in import_cert, I think this order should be changed, such that if the keystore is missing, then the .md5 should not be taken into account
> 
> if `md5sum -c "${CERTDIR}/${CERTNAME}.md5" &>/dev/null`; then log "Cert has not changed, not updating controller." exit 0 else if [ ! -e "${DATADIR}/keystore" ]; then log "WARN: Missing keystore, creating a new one"

Thanks a lot, this was the solution for my problem with the controller as well 👍
