### ISSUE TITLE
No Such Manifest in latest/v7.3.83 - Unable to deploy in ACI

### ISSUE THREAD

**Issue by adamwhite-tml** [jacobalberty/unifi-docker#637]
### Operating system

Linux

### UniFi Tag

latest

### Docker run

docker manifest inspect jacobalberty/unifi

### Bug description

`no such manifest: docker.io/jacobalberty/unifi:latest`

Due to the above I was unable to deploy to Azure Container Instance. Changing the tag in the docker-compose.yml to v7.3.76 allowed the container to be created and run. 

Appreciate this is specific to Azure and there is a little more configuration I have done to get persistent storage but thought I'd highlight the issue I came across for reference.

### Steps to reproduce

`docker manifest inspect jacobalberty/unifi`

### Relevant log output

```shell
no such manifest: docker.io/jacobalberty/unifi:latest
```

**Comment by ghankins** [comment]
I have a similar issue.

# docker-compose pull
Pulling unifi-controller (jacobalberty/unifi:latest)...
Trying to pull repository docker.io/jacobalberty/unifi ...

**Comment by jacobalberty** [comment]
What architecture is this on?

**Comment by ghankins** [comment]
> What architecture is this on?

It's on x86_64:
Linux misfits.twoguys.org 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.9.2009 (Core)

Docker:
docker-client-1.13.1-209.git7d71120.el7.centos.x86_64
docker-compose-1.18.0-4.el7.noarch
docker-common-1.13.1-209.git7d71120.el7.centos.x86_64
docker-1.13.1-209.git7d71120.el7.centos.x86_64

`docker-compose pull` used to work fine in the past.

**Comment by adamwhite-tml** [comment]
Mine is an Azure Container Instance and reports:

Linux SandboxHost-638127414611802277 5.10.102.2-microsoft-standard #1 SMP Mon Mar 7 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

All other tags work fine so I'm running the 7.3.36 version with no issues (bar the weekly blip where I can't log in to the controller so have to redeploy from a backup).

**Comment by jacobalberty** [comment]
@adamwhite-tml what version of docker?

**Comment by adamwhite-tml** [comment]
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           tmlunificontext
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jacobalberty** [comment]
Tag `hotfix-manifest` just pushed to docker hub and ghcr.io and has the docker manifest media type instead of an oci manifest. If someone with this issue on the `latest` tag could give it a try for me please. Thank you!

**Comment by ghankins** [comment]
I am a docker novice, but this seems to have worked.

```
misfits# docker pull docker.io/jacobalberty/unifi:hotfix-manifest
Trying to pull repository docker.io/jacobalberty/unifi ...
hotfix-manifest: Pulling from docker.io/jacobalberty/unifi
72d9f18d70f3: Pull complete
c1f5da206733: Pull complete
be9f70a5ca98: Pull complete
8223ee9984a0: Pull complete
e0e619912486: Pull complete
9912b028a167: Pull complete
72063233baa3: Pull complete
551c2a3b14f5: Pull complete
330f0c802b1c: Pull complete
fe7d14449f16: Pull complete
0df9b9551e0e: Pull complete
61d205d272cf: Pull complete
cd1d70a50eaf: Pull complete
ea36a350d17a: Pull complete
2644714120a9: Pull complete
36c32fc3bf51: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:70d2fa0cf48cd30f076a5ef9fedd41a7b00f1586e8287af17b22edf7b96dd02d
Status: Downloaded newer image for docker.io/jacobalberty/unifi:hotfix-manifest
```

**Comment by adamwhite-tml** [comment]
I'm not able to quickly deploy at the moment but I still get the below with the latest tag:

`no such manifest: docker.io/jacobalberty/unifi:latest`

**Comment by jacobalberty** [comment]
@adamwhite-tml i havent merged into `latest` yet. With ghankins confirmation that its solved for him I'll go ahead and merge into latest once  the pr finishes it's checks.

**Comment by adamwhite-tml** [comment]
Sorry, wasn't paying full attention.

**Comment by jacobalberty** [comment]
@adamwhite-tml should be fixed in `latest` tag now the version tags are building as well

**Comment by adamwhite-tml** [comment]
Yeah, that looks spot on:

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3627,
         "digest": "sha256:b0660f686234eac1fb1d3ca5df3a4f132486efb21527d145b706b9d20a69230e",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3627,
         "digest": "sha256:96f30011ea8c830be401f639ee331702cf810ae721dcf3400aef4d86b3f0e001",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3627,
         "digest": "sha256:3d243e5d64cb643a34fa8b6c6b505dd873d513208fc2a4b0ce689f75b437d217",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```
