### ISSUE TITLE
L3 inform connection issue

### ISSUE THREAD

**Issue by joechssn** [jacobalberty/unifi-docker#638]
How do I troubleshoot the [RST,ACK]? 

[SYN] TCP 8080 from the public IP of the client site to the controller IP
[RST, ACK] TCP 8080 packet coming from the controller IP back to the public IP of the client site.

SSH into a brand new AP at a remote site, set-inform http://FQDN:8080/inform

Local Site: controller in Docker container
I can see the AP traffic hit the firewall at the local site so I know DNS is resolving properly.

Controller talks to local APs just fine but the controller doesn't appear to be able to receive the Inform packet from the remote APs

Any guidance on how to troubleshoot this is much appreciated!

**Comment by adamwhite-tml** [comment]
What firewalls do you have? We used to have Palo Alto and had to open up all the required ports outbound for the APs and inbound to the controller (at the respective firewalls). The latter was obvious but the outbound was initially confusing as the PA has an allow all out that isn't really all.

**Comment by joechssn** [comment]
my docker-compose.yml looks kinda wimpy compared to some other examples I've seen on here, is anything missing in here?

`
![image](https://user-images.githubusercontent.com/10429188/219441800-d7ae2460-8d3d-44c4-aa19-67bb0e9f9219.png)
`

**Comment by adamwhite-tml** [comment]
Someone else may correct me but to get it up and running you don't need to change the docker-compose.yml. You need at least the mongo service and the unifi controller along with the volumes and the network but best to leave it as is.
