### ISSUE TITLE
any way to update controller version to 7.4.150?

### ISSUE THREAD

**Issue by luckman212** [jacobalberty/unifi-docker#653]
I'm running `latest` (7.3.83 as of this writing) on a DS1515+ and it's working well!

Unfortunately, I have another controller that has a few sites on it that I need to migrate, and it's running 7.4.150 prerelease.

When I try to import the sites, Unifi says I can't because of the version mismatch...

So the question is: is there any way to update the dockerized controller via shelling in with `docker exec -it unifi bash` etc?

**Comment by ai792** [comment]
Clone the project, adjust this line in "Dockerfile" to your preferred version:

```ARG PKGURL=https://dl.ui.com/unifi/7.3.83/unifi_sysvinit_all.deb``` 

Build --> then fingers crossed?

**Comment by luckman212** [comment]
Thank you - I will give that a try!

**Comment by tf1971** [comment]
Hi, I´ve got a similar question:
When will be the new version (right now, it´s 7.1.156) be "officially released" for docker-installations?
On ui.com all the 7.4.xxx-versions are tagged as "early access" so is this a kind of beta-status?
Will it be availiable for docker, when unifiy is releasing it officially?
Thanx!

**Comment by om3rx** [comment]
Hi @stich86 can you provide steps, I am running 7.1.68 right now and want to upgrade to the latest 7.4.156

**Comment by stich86** [comment]
@om3rx you have to clone the @jacobalberty repository on your machine, the edit the `Dockerfile` and change the variable `PKGURL` to `PKGURL=https://dl.ui.com/unifi/7.4.156/unifi_sysvinit_all.deb`

Then you can build up the image with this comand (in my case image tag is unifi-7.4, you can use what you prefer)

`docker build -t unifi-7.4 .`

After it's built, just use it as local image instead the one of Docker HUB images and point to the old volumes so it can upgrade the DB

**MAKE A BACKUP before spin up new container!**

**Comment by jacobalberty** [comment]
I just merged #663 so this should be done now

**Comment by dajappie** [comment]
Thank you!!

**Comment by om3rx** [comment]
Thanks!!! that was easy for me to update!!
