### ISSUE TITLE
INIT and MAX HEAP SIZE always result in 0.00 something. Container cannot start.

### ISSUE THREAD

**Issue by zilexa** [jacobalberty/unifi-docker#657]
### Operating system

Manjaro Gnome

### UniFi Tag

latest

### Docker run

See below

### Bug description
Container exits, does not start properly, because the variables JVM_INIT_HEAP_SIZE and JVM_MAX_HEAP_SIZE are not processed properly, resulting in very small numbers. 

### Steps to reproduce
Created the folders on host: unifi/data and unifi/log. Then compose up: 
```
  unificontroller:
    image: jacobalberty/unifi
    container_name: net-unificontroller
    restart: "no"
    network_mode: host
    volumes:
      - $DOCKERDIR/networking/unifi:/unifi
    environment:
      TZ: $TZ
      LOTSOFDEVICES: 'true'
      JVM_INIT_HEAP_SIZE: '256'
      JVM_MAX_HEAP_SIZE: '1024'
```
Tried with and without the ' ' .
### Relevant log output
```
[2023-05-09 20:31:13,429] <docker-entrypoint> Starting unifi controller service.
[2023-05-09 20:31:13,434] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
Error occurred during initialization of VM
Too small maximum heap
[2023-05-09 20:31:13,507] <docker-entrypoint> WARN: unifi service process ended without being signaled? Check for errors in /unifi/log.
```

`system.properties` shows the environment variables are translated in very tiny numbers: 
```
unifi.db.extraargs=--quiet
unifi.xms=0.000488281
unifi.xmx=0.000976562
unifi.G1GC.enabled=true
unifi.db.nojournal=true
```

**Comment by vernazza** [comment]
I think you are missing the units...
it should be
256M
and
1024M

otherwise, you are setting 256 bytes and 1024 bytes...

**Comment by zilexa** [comment]
Damn! Thanks I will test. I switched to linuxserver image but prefer to switch back :)
