### ISSUE TITLE
"docker-init": executable file not found in $PATH

### ISSUE THREAD

**Issue by nnewc** [jacobalberty/unifi-docker#660]
### Operating system

Ubuntu 23.04

### UniFi Tag

latest

### Docker run

latest docker-compose.yml

### Bug description

Starting the controller container fails on latest master

### Steps to reproduce

```bash
$ docker version
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.20.4
 Git commit:        297e128
 Built:             Thu May 18 10:54:43 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       5d6db84
  Built:            Thu May 18 10:55:20 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:
```

```bash
$ docker-compose version
Docker Compose version v2.17.2

```

### Relevant log output

```shell
$ docker-compose up -d
Error response from daemon: exec: "docker-init": executable file not found in $PATH
```

**Comment by mjlafors** [comment]
Same issue here, after booting Ubuntu, docker unifi controller won't start, with same docker version (20.10.24) and docker-compose version (v2.17.2) and Ubuntu version 20.04.6 LTS. 
Also after docker-compose up -d, docker jacobalberty/unifi:latest won't start: 
Error response from deamon: exec: "docker-init": executable file not found in $PATH

**Comment by nnewc** [comment]
This seems to be caused by: https://github.com/docker-snap/docker-snap/pull/140

This fix is on snap revision 2888, but it is not in the `latest/stable` channel yet. I switched to `latest/edge` by:
```bash
snap switch --channel=edge docker
snap refresh
```
