### ISSUE TITLE
v7.4 went RC - can we get a tag for that one - once again, brilliant, and thanks!

### ISSUE THREAD

**Issue by DolmensDude** [jacobalberty/unifi-docker#661]

**Comment by Kotys** [comment]
+1

**Comment by grego-r-b** [comment]
Thanks!

**Comment by RLinden22** [comment]
+1

**Comment by dajappie** [comment]
No longer RC but officially released!

+1

**Comment by dk90103** [comment]
+1 - Thank you

**Comment by slamp** [comment]
Thanks for the work !

**Comment by TrueMeistro** [comment]
+1 - Thank you!

**Comment by dajappie** [comment]
Hi @scottmac task #663 has been open but not merged, is it possible to do that to create a new build?

**Comment by gitvisual** [comment]
+1

**Comment by TrueMeistro** [comment]
OMG!
https://community.ui.com/releases/Security-Advisory-Bulletin-031-031/8c85fc64-e9a8-4082-9ec4-56b14effd545

**Comment by bchocotoff** [comment]
New tag has been provided yesterday. You can update your configuration now.
Also, it seems that most users won't have that risk.
