### ISSUE TITLE
Issue upgrading

### ISSUE THREAD

**Issue by twils02** [jacobalberty/unifi-docker#666]
### Operating system

Raspberry Pi

### UniFi Tag

latest

### Docker run

docker run jacobalberty/unifi

### Bug description

[2023-06-17 21:10:29,003] <docker-entrypoint> Starting unifi controller service.
[2023-06-17 21:10:29,005] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by kmoens** [comment]
I faced the same issue after an upgrade.

**Comment by CoooWeee** [comment]
same here

**Comment by ffetsred** [comment]
Same for me.
Docker shows that the container is still "starting". It never leaves this state despite that the log files seems to confirm that the upgrade to the new release was successful.

`87cb6a6044da   jacobalberty/unifi:latest   "/usr/local/bin/dock…"   3 minutes ago   Up 3 minutes (health: starting)`

**Comment by mrlexley** [comment]
Same for me, recreating the container doesn't work for me on 2 hosts.

**Comment by marcelomera** [comment]
Estou com o mesmo problema, mesmo apagando a pasta config e recriando a imagem.
Processador Intel.
