### ISSUE TITLE
latest seems not to be latest

### ISSUE THREAD

**Issue by S0uljacker** [jacobalberty/unifi-docker#668]
### Operating system

Synology DSM 7.1.1-42962 Update 6

### UniFi Tag

latest

### Docker run

Not sure where to find it in DSM

### Bug description

At the moment i am running Unifi-Docker with Version 7.3.76 (earlier downloaded with tag "latest").
Version 7.4.156 (tag: 7.4.156) is available on hub.docker.com repository.

Downloading (register) the image with tag "latest" ends up in Version 7.3.76, but should be 7.4.156.

### Steps to reproduce

- Logging in to controller
- Download backup of settings only
- Stopping container
- Reset container
- Download / Register Image with tag "latest"
- Start Container
- Restore backup

**Comment by rchenzheng** [comment]
It is likely pulling from cache, maybe try replacing it with `jacobalberty/unifi:v7.4`
