### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP from browser when attempt to access Unifi web portal

### ISSUE THREAD

**Issue by adamstraube** [jacobalberty/unifi-docker#67]
### Host operating system

Open Media Vault 3.0.80 (Erasmus)

### What tag are you using

Stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

[IMAGE OF CONFIG FOR DOCKER CONTAINER](https://imgur.com/a/9Hzoo)

### What actually happens?

After a recent docker container upgrade I have stopped being able to access the web portal (port: 8443) and get the following browser error: 
_Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP_

I have checked the directory layouts as per the new changes (eg. changed /unifi/lib to /unifi/data) and set the relevant privileges. 
I also tried the solution given [here](https://community.ubnt.com/t5/UniFi-Wireless/Server-has-a-weak-ephemeral-Diffie-Hellman-public-key/td-p/1343026) and restarted but have not had any luck.

The output from _docker-healthcheck.sh_ gives this error:

> curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

I am not sure what else to try here, I have not done anything unusual to this container. Has anybody else experienced this?

**Comment by jacobalberty** [comment]
Yes, two things. Make sure you pull the absolute latest image. Shut down
Disney Then delete the keystore file from your configuration folder. Then
launch with the newest image (it was last updated about twenty hours ago
iirc)

**Comment by adamstraube** [comment]
That worked. Thanks for that and also for the project! It has worked really well and saved me from having to get a separate Cloud Controller Key.
I think you meant docker also, not sure if I can shutdown disney :smiley:

**Comment by jacobalberty** [comment]
lol yeah I meant docker, was replying on my phone and autocucumber changed docker to disney
