### ISSUE TITLE
Update to 7.4.162

### ISSUE THREAD

**Issue by agourisse** [jacobalberty/unifi-docker#670]
New update available 7.4.162
https://community.ui.com/releases/UniFi-Network-Application-7-4-162/50b4b930-631e-4ada-87c4-0b4ea5fb26a7

**Comment by Gamertech** [comment]
7.4.162 is currently Release Candidate, not Stable/Official.

Also it allegedly has some issues with forgetting/corrupting login details. Pass.

**Comment by 00ihsan** [comment]
Any ETA? I need to update because Ubiquity Support asking to.

**Comment by ning42** [comment]
normally it is only when the release is out of RC to stable there is a new version made. 
I can remember that you earlier could make your own build with a --beta parameter, but i cant find it any more

**Comment by Gamertech** [comment]
Heh, UI support usually tells people to update to unreleased versions so they can say they don't support beta software and you should be running Official :P

7.4.162 has been changed to Official now, though they haven't responded to the multiple reports of the update corrupting logins and breaking user perms so I'd be cautious with it. Especially as their backup systems are still borked.

If you want to force the update, you can get the dockerfile from this repo and edit line 13 to the desired version. Can then run it from terminal or a UI like Portainer/Yacht.

**Comment by rvsteiger** [comment]
I ran an USG with unifi-docker on a Synology NAS for years, thanks jacobalberty!
Now I need to replace it with a new UDR that runs 7.4.162. Hence I should appreciate unifi-docker bumped to this version asap for the transfer of the USG settings to work. Thanks!
