### ISSUE TITLE
Captive Portal does not open

### ISSUE THREAD

**Issue by scharrin2** [jacobalberty/unifi-docker#676]
### Operating system

QNAP QTS 5.1.0.2466

### UniFi Tag

latest

### Docker run

docker run -d \ --init \ --restart always \ --user unifi \ --name unifi-1 \ -p 8080:8080 -p 8443:8443 -p 3478:3478/udp \ -e TZ='Europe/Berlin' \ -h unifi-1 \ -v /share/Docker/unifi:/unifi \ jacobalberty/unifi:latest

### Bug description

Hello,

I tried several tutorials to active a Guest network with captive portal.

In my opinion everything is correctly configured.
But when connecting to this Guest W-LAN the page for the captive portal does not open.

Before using this docker image I ran the UNIFI Controller on a Raspberry Pi. There the captive portal worked.

Do you have any ideas how to find the issue?

Best regards,
Christian

![Bildschirmfoto 2023-08-27 um 12 50 32](https://github.com/jacobalberty/unifi-docker/assets/22325491/87500c35-8509-438b-a1c2-c46bbd4c0225)
![Bildschirmfoto 2023-08-27 um 12 50 49](https://github.com/jacobalberty/unifi-docker/assets/22325491/056ec98c-f176-4bad-b94a-87f8cc940b7a)
![Bildschirmfoto 2023-08-27 um 12 51 17](https://github.com/jacobalberty/unifi-docker/assets/22325491/78e94d81-7818-4872-b6b3-b595fcbd1ca3)

**Comment by BlueHairMinerBoy** [comment]
Not sure if you've managed to fix this for yourself but Captive Portal relies on ports 8880 and 8843, you'll need to open them in your launch command.

**Comment by scharrin2** [comment]
> Not sure if you've managed to fix this for yourself but Captive Portal relies on ports 8880 and 8843, you'll need to open them in your launch command.

Thak you - that was the issue!

Now my docker run comand is this:

![image](https://github.com/jacobalberty/unifi-docker/assets/22325491/644f9196-1174-4aea-9849-74f485c7846a)
