### ISSUE TITLE
Setting UNIFI_GID yields an error

### ISSUE THREAD

**Issue by Poquaruse** [jacobalberty/unifi-docker#68]
### Host operating system

Synology NAS

### What tag are you using

Example: `5.6.19-sc`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `sudo docker run -p 8080:8080 -p 8880:8880 -p 8843:8843 -p 6789:6789 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Europe/Berlin' -e RUNAS_UID0='false' -e UNIFI_UID=1036 -e UNIFI_GID=100 -v /volume1/docker/unifi/2017-10-18:/unifi --name 2017-10-18-unifi-5.6.19-sc -d jacobalberty/unifi:5.6.19-sc`

### What do you expect to happen?
Container runs without error.

### What actually happens?
I get an "groupmod: GID '100' already exists" error and the container does not run. 
UID and GID are set in correspondece to the user I created for this container which owns the directory.

Possibly adding option -o (-o, --non-unique) to groupmod would help?!

Best regards

**Comment by jacobalberty** [comment]
Thank you for the report.

I have fixed this and while testing the fix discovered two other issues that were related, all three issues should now be fixed.

**Comment by Poquaruse** [comment]
Hi @jacobalberty,

thank you very much for the quick fix. I updated to the new version and everything worked as expected! 👍 

Best
