### ISSUE TITLE
DNS issue after upgraded to v7.5.174

### ISSUE THREAD

**Issue by rickyjoy** [jacobalberty/unifi-docker#684]
### Operating system

synology DSM 7.1.1-42962 Update 6

### UniFi Tag

latest

### Docker run

docker 

### Bug description

docker run -d --init \
   --restart=unless-stopped \
   -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -p 8843:8843 -p 8880:8880\
   -v ~/docker/unifi:/unifi \
   --user unifi \
   --name unifi \
   jacobalberty/unifi

### Steps to reproduce

My previous unifi version is 7.0.23. When I deleted the container and image in synology, pulled the latest version and launched it, my whole network has DNS issues. Everything is unchanged including the docker folder.

**Comment by rickyjoy** [comment]
> Two potential issues here. One if you have a USG, .174 has a bug that doesn't provision DNS servers to it.
> 
> The other is you skipped 5 major release versions in one go, and Unifi isn't a fan of that.
> 
> If you don't have a USG, I'd downgrade back to your original version or whatever the latest image available in the 7.0 branch is, restore a backup if needed, then stage upgrades through 7.1, 7.2 etc.


Thank you very much. I do have a USG. 
It seems I have to wait for unifi to fix the bug in the future version.
Thanks again.

**Comment by it-can** [comment]
new version is released today https://community.ui.com/releases/UniFi-Network-Application-7-5-185/295de390-ade0-4d83-b297-74b10532138a

**Comment by rickyjoy** [comment]
> new version is released today https://community.ui.com/releases/UniFi-Network-Application-7-5-185/295de390-ade0-4d83-b297-74b10532138a

Thanks
