### ISSUE TITLE
Go back to a previous version?

### ISSUE THREAD

**Issue by tjkcc** [jacobalberty/unifi-docker#687]
It's probably a noob's docker question, but still, wondering if there is a safe way to go back from 7.5.174 to 7.4.162 without losing the settings in the controller (no changes were made in settings between update). I am running docker on a Synology NAS, but I also have portainer installed if that's of any help.
Thanks.

**Comment by Gamertech** [comment]
Unifi software doesn't support smooth downgrading.

Only way is to downgrade then restore a backup from that or an earlier version.
