### ISSUE TITLE
Not able to open guest portal

### ISSUE THREAD

**Issue by truncsphere** [jacobalberty/unifi-docker#691]
### Operating system

Ubuntu 20.04.6 LTS

### UniFi Tag

latest

### Docker run

version: '3.3' services:     unifi:         restart: unless-stopped         ports:             - '8080:8080'             - '8443:8443'             - '3478:3478/udp'             - '8880:8880'             - '8843:8843'         environment:             - TZ=America/Boise         volumes:             - '~/unifi:/unifi'         user: unifi         container_name: unifi_controller         image: 'jacobalberty/unifi:latest'

### Bug description

Migrated controller from a dedicated VM to a docker container. Everything works except for the guest portal. It does not open for users (times out). 

Since migrating the controller to docker the guest portal has not worked. The controller itself and hotspot manager work with no issues. 
I opened ports 8880 and 8843 via docker compose with no luck. 

Not sure where the disconnect might be in this case. 

Note: Guest network is on a VLAN and I changed the IP/port from the old vm controller to the docker IP/port.

**Comment by truncsphere** [comment]
I should add that going to *.*.*.*:8880/guest/s/default/ from my local network works. 
Firewall logs don't show the IP/Port being blocked, and the docker container logs show nothing either for this.

**Comment by truncsphere** [comment]
Moved the controller to an Ubuntu Server vm and the guest portal works now. Closing ticket.

**Comment by pit-mh** [comment]
Not sure if anyone else was having issues with this but I had the same issue. I am using the Secure Portal (Port 8843).

I had the Port 8843 open on my AWS ALB but still couldn't have users successfully connect. 

I had to turn on the Authorization Access in the Unifi Controller for the HotSpot with the Controller URL and the DNS Servers we were handing out to the Guest Network.

This was the only post I could find with a similar issue so hope this helps anyone.
