### ISSUE TITLE
What is the plan for 7.5.176?

### ISSUE THREAD

**Issue by bitdryvr** [jacobalberty/unifi-docker#692]
### Operating system

n/a

### UniFi Tag

n/a

### Docker run

n/a

### Bug description

I may have missed something, but what is the plan to support the official release of 7.5.176 from about 3 weeks ago? After the pullback of the previous Unifi release, I can understand a little caution.

**Comment by mattinglis** [comment]
Second this, whilst I know the reluctance to update too quickly, without this release, those of us with a USG have lost DNS, so it's a critical update for us.

**Comment by iKowex** [comment]
I join the question.

**Comment by Gamertech** [comment]
Don't think it's so much that. jacobalberty seems to take big breaks away from Git for whatever reason. While an update would be good for those affected, real-life comes before unpaid volunteer dev.

If you need something now, then you can download the dockerfile, edit it to .176 and build from it, or you could use Linuxserver's image, but their current version isn't on DockerHub yet and requires you to roll your own database.

**Comment by mattinglis** [comment]
Linuxserver is keeping the old docker up to date till the end of the year, I've had to switch to that to resolve my DNS

**Comment by DKeppi** [comment]
Now you are able to go back to jacobalbertys image - he updated it to 7.5.176 ;)

**Comment by barbatrukko** [comment]
hi,
i did pull on my RaspberryPi4 (where allways runned my network controller) and now i receive a message

```
root@raspi4unifi:/opt# docker pull jacobalberty/unifi:latest
latest: Pulling from jacobalberty/unifi
no matching manifest for linux/arm/v7 in the manifest list entries
root@raspi4unifi:/opt#

```
I did some of wrong?

**Comment by Gamertech** [comment]
Unifi now requires a still hilariously obsolete version of MongoDB to run the controller, however it's new enough that ARM32 devices are no longer supported.

You'd need a RPi 4B or later or to swap to a x86_64 device. If you're on a 4B already, then ensure you install the 64-bit version of Raspian, not the 32-bit.

**Comment by barbatrukko** [comment]
> Unifi now requires a still hilariously obsolete version of MongoDB to run the controller, however it's new enough that ARM32 devices are no longer supported.
> 
> You'd need a RPi 4B or later or to swap to a x86_64 device. If you're on a 4B already, then ensure you install the 64-bit version of Raspian, not the 32-bit.

Hi,
yes I have a 4b and i suppose installed 32bit of ubuntu becouse in teh first time 64bit was not available.
Now I try with new SDCARD, ubuntu 22 64bit and same docker-composer file and we will see.

**Comment by iKowex** [comment]
> Now you are able to go back to jacobalbertys image - he updated it to 7.5.176 ;)

Version already released 7.5.187

**Comment by DKeppi** [comment]
But this is only a Release Candidate

**Comment by iKowex** [comment]
> But this is only a Release Candidate

And what does this change? 7.5.174 too Release Candidate

**Comment by DKeppi** [comment]
7.5.174 was Official first, but than, due to bugs, Unifi switched it back to Release Candidate and 7.5.176 was released! Thats why we asked jacobalberty for an update to 7.5.176!

7.5.187 is still Release Candidate, so no Update to that...

**Comment by swrobel** [comment]
[It has been released](https://github.com/jacobalberty/unifi-docker/releases/tag/v7.5.176). This issue can be closed.

**Comment by DKeppi** [comment]
@iKowex 7.5.187 is Official Released, maybe jacobalberty will update now to it if you open an issue for that!
