### ISSUE TITLE
Please upgrade the beta image

### ISSUE THREAD

**Issue by nibblerrick** [jacobalberty/unifi-docker#693]
### Operating system

Debian

### UniFi Tag

ea

### Docker run

see other issue

### Bug description

Like initially asked in #673 can the beta-image be updated? The fix mentioned in the other issue ended in solving this for the stable builds but not the beta.
Thanks in advance!

**Comment by nibblerrick** [comment]
Still an issue

**Comment by chkuendig** [comment]
This has been promoted to stable now I think https://community.ui.com/releases/UniFi-Network-Application-8-0-7/7818b9df-4845-4c82-ba3c-1218e61010d4

**Comment by nibblerrick** [comment]
The "normal" image is updated, but the beta image is still nit updated, or am I wrong?
