### ISSUE TITLE
UniFi Network Application 8.0.7 is now out

### ISSUE THREAD

**Issue by jmmartj** [jacobalberty/unifi-docker#702]
Hi Jacob,

     This is merely a request/fyi:

https://community.ui.com/releases/UniFi-Network-Application-8-0-7/7818b9df-4845-4c82-ba3c-1218e61010d4

     Also, how can I buy you a beverage?  Thanks for all you do!

~jm

**Comment by runepiper** [comment]
> Also, how can I buy you a beverage?  Thanks for all you do!

You can sponsor @jacobalberty here: https://github.com/sponsors/jacobalberty

**Comment by Gamertech** [comment]
I've updated my PR to add 8.0.7, keep in mind it seems this update wasn't tested with 3rd party routers and is apparently completely broken with any form of 3rd party authentication/DHCP.

**Comment by Gamertech** [comment]
Only Jacobalberty can approve it, so whenever he comes back from wherever he is atm.

There are instructions in the PR comments that tells you how to build it locally if you're interested.

**Comment by iKowex** [comment]
No more waiting for updates?

> There are instructions in the PR comments that tells you how to build it locally if you're interested.
Can you share the link?

**Comment by iKowex** [comment]
> [#527 (comment)](https://github.com/jacobalberty/unifi-docker/issues/527#issuecomment-1822191627) 😉

Thanks, but it’s easier to switch to goofball222/unifi

**Comment by TristanBrotherton** [comment]
Would anyone care to share the upgrade path they took to migrate to goofball222/unifi ?

**Comment by iKowex** [comment]
> Would anyone care to share the upgrade path they took to migrate to goofball222/unifi ?

There's nothing complicated there. The first thing you do is export the settings from the old one. Install according to the instructions goofball222/unifi, plus you need to install it on synology java 17 and export the settings when you first log in.

**Comment by waja** [comment]
> as [goofball222/unifi](https://github.com/goofball222/unifi) seems to be more of a "one man show"? 🤔

Same as this repository.

**Comment by waja** [comment]
For everybody want to test and don't want to build this on it's own, I created a fork and applied this changes. You can grab it at https://github.com/waja/docker-unifi/pkgs/container/unifi/151917726?tag=8.0.7

**Comment by waja** [comment]
> > > as [goofball222/unifi](https://github.com/goofball222/unifi) seems to be more of a "one man show"? 🤔
> > 
> > 
> > Same as this repository.
> 
> Not exactly, if you compare the Git commits of both repos 😉

Okay ... to be more exact: Both have just one single maintainer.

**Comment by iKowex** [comment]
> > > > as [goofball222/unifi](https://github.com/goofball222/unifi) seems to be more of a "one man show"? 🤔
> > > 
> > > 
> > > Same as this repository.
> > 
> > 
> > Not exactly, if you compare the Git commits of both repos 😉
> 
> Okay ... to be more exact: Both have just one single maintainer.

I don't see any problems. You can always switch to another one, this is done very quickly.

**Comment by stefan01220** [comment]
when it's planned to update to 8.0.7?

**Comment by DissonanceTK** [comment]
> In this case, 8.0.7 is incompatible with non-UI routers and authentication.

Sorry if this is a dumb question, but what exactly isn't compatible? I'm using pfSense as my router and UI Network 8.0.7 to run my UI switches and APs. It all works great! I'm guessing this isn't the use case you mean... ?

**Comment by Gamertech** [comment]
That's the use case I mean. 8.0.7 has major compatibility issues with networks running a non-UI router/gateway and/or 3rd party RADIUS/DHCP.

**Comment by kennetharethun** [comment]
> > Linuxserver container broke everything by bumping automatically to 8.x.
> 
> @kennetharethun I wonder if you are using the tag `:latest`, because this is what can happen?
> 
> Personally I use explicit container versions and handle updates independently using [renovate](https://github.com/renovatebot/renovate) 😉
> 
> ![image](https://private-user-images.githubusercontent.com/18613935/287521373-5b7d613b-86bc-4fd8-8dcf-7a1f88d0ec80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDI0MTAsIm5iZiI6MTcwMTc0MjExMCwicGF0aCI6Ii8xODYxMzkzNS8yODc1MjEzNzMtNWI3ZDYxM2ItODZiYy00ZmQ4LThkY2YtN2ExZjg4ZDBlYzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAyMDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZmQ4OGJmMjI2ZTZkOGY0OTc3YmU4NTNmNTQ3ODllNWZhNzljYzg5OTljMjRmYTY3NmNlOTRiMjg2YTk4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GsMwzAkk1B0It-DfgEwFxce0LNDv-y-TcaRbeyxYyO0)
> 
> Anyway, this is what are backups for. Very easy using the automatic backups of the UniFi network application.
> 
> And as @iKowex wrote _"You can always switch to another one, this is done very quickly."_

It happened because linuxserver doesn’t test anything. I have backups. And I do not have the time to babysit each and every single network application update, so I’m yoloing the latest tags and it’s been working fine until I switched from Jacob’s to linuxserver and now I’m back. I don’t mind the delays in updates as much as you guys apparently do.

**Comment by Gamertech** [comment]
Keep in mind, UI's 'Lite' devices don't support spanning tree STP/RSTP, so if you ever have a network loop it'll storm and take down your network. They don't mention that little tidbit in their advertising.

**Comment by joseluislucio** [comment]
Why I cannot see more vpn options?
![image](https://github.com/jacobalberty/unifi-docker/assets/1066785/7fb12f67-6875-4851-be35-eeeb158fe422)

**Comment by joseluislucio** [comment]
> > Why I cannot see more vpn options? ![image](https://private-user-images.githubusercontent.com/1066785/288582724-7fb12f67-6875-4851-be35-eeeb158fe422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDg0NjQsIm5iZiI6MTcwMTkwODE2NCwicGF0aCI6Ii8xMDY2Nzg1LzI4ODU4MjcyNC03ZmIxMmY2Ny02ODc1LTQ4NTEtYmUzNS1lZWViMTU4ZmU0MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDAxNjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNlZDM0NWU5YmU0ODRjZTY3YTE0Yjg1ZDZkMGI2NDY0ZmEyMzZkOWJlZWVkMmZkNzk2ZWMzODc2NjRjMGRlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i2ASxMHEfkADp8D1NNAT_EfI7bnCTIr9Fgz7iffAi6E)
> 
> What router do you have? If you don’t have UDM PRO, then no way.

I have USG-Pro-4. Is not planned to be available to this router?

**Comment by wurmr** [comment]
> > I've updated my PR to add 8.0.7, keep in mind it seems this update wasn't tested with 3rd party routers and is apparently completely broken with any form of 3rd party authentication/DHCP.
> 
> Is this still true? im only running only switches and APs from Unifi, with x86 firewall/routing.

I'm running `nexusforge/unifi-docker:v8.0.7` with a 3rd party router (mikrotik) that handles all the routing/DHCP without any issues.

I only have Unifi Switches and APs and have never had a Unifi gateway product.

**Comment by maisun** [comment]
Anybody have a tutorial on how to migrate from this image to Linuxserver image? Would like to switch however not sure best way to migrate all my settings. Many thanks in advance!

**Comment by maisun** [comment]
> > I don’t mind the delays in updates as much as you guys apparently do.
> 
> I do, because the [Gateway Lite](https://eu.store.ui.com/eu/en/products/uxg-lite) _(UXG-Lite)_ requires **8.x**, so at least my use case seems to be indeed different 😉

How is uxg-lite? Read somewhere the vpn speed is even worse than usg, very surprised

**Comment by elchupoopacabra** [comment]
> > I don’t mind the delays in updates as much as you guys apparently do.
> 
> I do, because the [Gateway Lite](https://eu.store.ui.com/eu/en/products/uxg-lite) _(UXG-Lite)_ requires **8.x**, so at least my use case seems to be indeed different 😉

I am using jacobalberty's latest, 7.5.176, with a brand new uxg-lite with no issues, fwiw.

**Comment by huub99** [comment]
Hello all,

I'm also tgrying to update to 8.0.7 in order to install the latest UXG.
My setup:

- Controller hosted on Synology (jacobalberty version 7.4.156
- USG-3P
- USW-Lite-16-PoE
- USW-Flex-Mini
- U6-Lite (3x)
- UAP-AC-IW 

What I did.
Created a backup file for the settings only.
Stopped the jacob alberty docker container.

created the docker image with goofball22, (807) I had to do some tricks. 
For JVM_EXTRA_OPTS I had to add a space because container manager needs a value to proceed, removing the option resulted in a error. JVM_INIT_HEAP_SIZE I also had to add a value, I added 512M. 
After booting I restored the backup. This took ages so after a 30mins I restarted the image.
I could log in and all the hardware was in the list.

However some kept going offline adopting offline etc. 
Two out of AP's and the 16p switch adopted fine the others did not.

With a lot of effort I managed to get the old version working again. All devices adopted fine accept the USG.

What am I doing wrong

**Comment by iKowex** [comment]
> Hello all,
> 
> I'm also tgrying to update to 8.0.7 in order to install the latest UXG. My setup:
> 
> * Controller hosted on Synology (jacobalberty version 7.4.156
> * USG-3P
> * USW-Lite-16-PoE
> * USW-Flex-Mini
> * U6-Lite (3x)
> * UAP-AC-IW
> 
> What I did. Created a backup file for the settings only. Stopped the jacob alberty docker container.
> 
> created the docker image with goofball22, (807) I had to do some tricks. For JVM_EXTRA_OPTS I had to add a space because container manager needs a value to proceed, removing the option resulted in an error. JVM_INIT_HEAP_SIZE I also had to add a value, I added 512M. After booting I restored the backup. This took ages so after a 30mins I restarted the image. I could log in and all the hardware was in the list.
> 
> However some kept going offline adopting offline etc. Two out of four AP's and the 16p switch adopted fine the others did not.
> 
> With a lot of effort I managed to get the old version working again. All devices adopted fine except the USG.
> 
> What am I doing wrong?
> 
> Many thanks in advance

Java 17 installed on synology?

**Comment by maisun** [comment]
Managed to get Linuxserver 8.07 running, so far so good :)

**Comment by jrothlis** [comment]
> Hello all,
> 
> I'm also tgrying to update to 8.0.7 in order to install the latest UXG. My setup:
> 
> * Controller hosted on Synology (jacobalberty version 7.4.156
> * USG-3P
> * USW-Lite-16-PoE
> * USW-Flex-Mini
> * U6-Lite (3x)
> * UAP-AC-IW
> 
> What I did. Created a backup file for the settings only. Stopped the jacob alberty docker container.
> 
> created the docker image with goofball22, (807) I had to do some tricks. For JVM_EXTRA_OPTS I had to add a space because container manager needs a value to proceed, removing the option resulted in an error. JVM_INIT_HEAP_SIZE I also had to add a value, I added 512M. After booting I restored the backup. This took ages so after a 30mins I restarted the image. I could log in and all the hardware was in the list.
> 
> However some kept going offline adopting offline etc. Two out of four AP's and the 16p switch adopted fine the others did not.
> 
> With a lot of effort I managed to get the old version working again. All devices adopted fine except the USG.
> 
> What am I doing wrong?
> 
> Many thanks in advance

Use https://github.com/nexusforge/unifi-docker/ in the meantime -- a single line change in your docker-compose.yml:

`  controller:
    #image: "jacobalberty/unifi:${TAG:-latest}"
    image: "nexusforge/unifi-docker:${TAG:-latest}"
`

**Comment by trustno1foxm** [comment]
> Or if you prefer to run it on a virtual machine or a RaspberryPi you can use docker-compose and the sample from [here](https://github.com/jacobalberty/unifi-docker/issues/527#issuecomment-1822191627) _(you wouldn't need to take care of the Java version)_ 😉
> 
> Backup (and restore) can be done as follows:
> 
> ![image](https://private-user-images.githubusercontent.com/18613935/286379116-43a2f9b0-693d-4716-8a21-86cbf4b64b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTY5NTcsIm5iZiI6MTcwMjM5NjY1NywicGF0aCI6Ii8xODYxMzkzNS8yODYzNzkxMTYtNDNhMmY5YjAtNjkzZC00NzE2LThhMjEtODZjYmY0YjY0YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1NTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZGUyZTE0NDcwNTkzYWNiYzg3YjQ2MmM2MWFhMGQ0YWJiZmRmY2IyODc3MWM0OWY3ZTdkZmM4MjMyYWEwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nphl8a78jYfSkB6x7AHSqa_MIJr6GLk_zbDr7OLsJN4)
> 
> @iKowex I decided to use the Docker image from [linuxserver/unifi-network-application](https://github.com/linuxserver/docker-unifi-network-application) for now as [goofball222/unifi](https://github.com/goofball222/unifi) seems to be more of a "one man show"? 🤔

how did you get it work? I always get an SRAM Authentication error when using [linuxserver/unifi-network-application] thx!

so long

**Comment by DaveMcCloud** [comment]
I have a regular old broadband supplier provided router and use DHCP via my QNAP NAS.  Is it fair to say that I should swerve 8.0.7 for now based on comments above?

**Comment by jrothlis** [comment]
> I have a regular old broadband supplier provided router and use DHCP via my QNAP NAS. Is it fair to say that I should swerve 8.0.7 for now based on comments above?

Works completely fine for me, I don't understand what the issue could be. I have 3 Unifi switches and 3 U6-Pro with a Mikrotik router, everything works as expected.

**Comment by chopeen** [comment]
[v8.0.24](https://github.com/jacobalberty/unifi-docker/releases/tag/v8.0.24) was released.

**Comment by jmmartj** [comment]
Ran settings backup of latest 7.x version.  
Restored to 8.0.24.
Flawless victory & thanks!
