### ISSUE TITLE
No OpenVPN nor Wireguard VPN Server options

### ISSUE THREAD

**Issue by Memes11** [jacobalberty/unifi-docker#704]
### Operating system

Unraid

### UniFi Tag

latest

### Docker run

docker run through Unraid interface

### Bug description

In the VPN Server section, I do not have the option to use OpenVPN nor Wireguard, only L2TP and PPTP.

The Unifi Network is the 7.5.176

**Comment by johnreitan** [comment]
Such features requires you to run a UniFi gateway, do you have/use that?

**Comment by Memes11** [comment]
yes, I have USG gateway (this one : https://store.ui.com/us/en/products/usg )

**Comment by johnreitan** [comment]
And you have upgraded the USG to match?

**Comment by Memes11** [comment]
USG Device version 4.4.57, appears as Up to date on the interface

**Comment by johnreitan** [comment]
Not officially supported on the USG: https://community.ui.com/questions/Wireguard-on-Unifi-USG/e423de38-1a44-4f15-af70-0c93a55e1600

**Comment by Memes11** [comment]
Ohh, too bad then... Anyway, thanks for your response, that will save me some time trying :)

**Comment by Gitoffomalawn** [comment]
@Memes11: what works for me is running a separate Wireguard server in my LAN, alongside a script that syncs with a DDNS service periodically. Configure port forwarding in the Controller to go along with that, and you're golden.
