### ISSUE TITLE
project still alive

### ISSUE THREAD

**Issue by ruben-herold** [jacobalberty/unifi-docker#707]
@jacobalberty is the project still alive? Or is it dead?

**Comment by xblitz** [comment]
I think he is asking if the maintainer is still alive, because it's been 2 months without any github activity :/ hope everything is okay

**Comment by ruben-herold** [comment]
@xblitz yes and as far as I can see he is the only one with write access.

**Comment by thorstenheinz** [comment]
Seems to be dead! Which alternatives of Unifi Docker Images are available?

**Comment by xblitz** [comment]
> Seems to be dead! Which alternatives of Unifi Docker Images are available?

Honestly, the [linuxserver/docker-unifi-network-application](https://github.com/linuxserver/docker-unifi-network-application) container seems like a good contender, they just don't provide it batteries included (mongo setup), so you need to create your own docker-compose.yml config to set up mongodb alongside unifi.

**Comment by thorstenheinz** [comment]
Thank you!

**Comment by Charlys2112** [comment]
@jacobalberty seems to have create another github project for another scope yesterday. So he is alive maybe he will update Unifi controler project

**Comment by waja** [comment]
> @jacobalberty seems to have create another github project for another scope yesterday. So he is alive maybe he will update Unifi controler project

did he? how do you come to this conclusion?

**Comment by Charlys2112** [comment]
@waja https://github.com/jacobalberty

**Comment by timreuscher** [comment]
> Seems to be dead! Which alternatives of Unifi Docker Images are available?

https://github.com/goofball222/unifi seems to be another option with Mongo built-in.

**Comment by waja** [comment]
> @waja https://github.com/jacobalberty

Ah ... you are talking about the fork of https://github.com/jacobalberty/Links-Awakening-DX-HD. 👍

**Comment by MichiFr** [comment]
New release available [https://github.com/jacobalberty/unifi-docker/releases/tag/v8.0.24](url)

**Comment by jmmartj** [comment]
Ran settings backup of latest 7.x version.  
Restored to 8.0.24.
Flawless victory & thanks!
