### ISSUE TITLE
UniFi Network Application 8.0.24 is now out

### ISSUE THREAD

**Issue by jmmartj** [jacobalberty/unifi-docker#708]
:)  Merely an fyi:

https://community.ui.com/releases/UniFi-Network-Application-8-0-24/43b24781-aea8-48dc-85b2-3fca42f758c9

**Comment by runepiper** [comment]
Hey @jmmartj, check #708 for getting the latest version running.

**Comment by xblitz** [comment]
> Hey @jmmartj, check #708 for getting the latest version running.

Probably meant #707 😄

**Comment by runepiper** [comment]
Dang it, I meant #702 but #707 looks good too.

**Comment by jrothlis** [comment]
Thank you all! Working well here.

**Comment by chopeen** [comment]
[v8.0.24](https://github.com/jacobalberty/unifi-docker/releases/tag/v8.0.24)  was released.

**Comment by jmmartj** [comment]
Ran settings backup of latest 7.x version.  
Restored to 8.0.24.
Flawless victory & thanks!

**Comment by wabragg** [comment]
Yes, thanks for bringing this up to date.  I really didn't mind skipping some of the in betweens.  I get tired of the Ubiquiti software testing that we're subject to at times.

**Comment by varac** [comment]
Btw, the docker image is updated to 8.0.26 already: https://hub.docker.com/r/jacobalberty/unifi/tags (5 days ago)

**Comment by wabragg** [comment]
Man, he's on the ball lately.
