### ISSUE TITLE
Timezone not setting correctly

### ISSUE THREAD

**Issue by rojaxthegreat** [jacobalberty/unifi-docker#71]
### Host operating system
Ubuntu 16.04 4.4.0-97-generic

### What tag are you using
latest; 5.6.19 stable, but was happening on all 5.6.xx-sc

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
version: '2.2'
services:
  unifi:
    image:  jacobalberty/unifi
    init: true
    ports:
      - 8080:8080
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 3478:3478/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
    volumes:
      - /apps/unifi/config:/var/lib/unifi
      - /apps/unifi/logs:/var/log/unifi
      - /apps/unifi/run:/var/run/unifi

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?
Graph times set to America/Denver timezone
### What actually happens?
The time in all graphs in the controller are off by +6 hours, not sure if it is my config or a bug in unifi

**Comment by phroggster** [comment]
Does your controller show the correct timezone at https://your.ip.here:8443/manage/site/default/settings/site ?

**Comment by phroggster** [comment]
Also, be sure to click on a graph to show the local time, if you haven't already:
![screenshot_2017-10-23-18-26-19](https://user-images.githubusercontent.com/14035789/31917995-08893f9a-b820-11e7-8c23-14836f0989a3.png)

**Comment by rojaxthegreat** [comment]
Yes I have the correct time in the controller, it looks like it shows UTC time but not my local controller time
![screenshot 2017-10-23 18 33 40](https://user-images.githubusercontent.com/29667189/31919701-8bdbdfd2-b821-11e7-8a66-01a1446203b8.png)

**Comment by jacobalberty** [comment]
If you run `docker-compose exec unifi date` do you get the correct time? and are log entries under docker-compose logs the correct time?

**Comment by rojaxthegreat** [comment]
Yes both exec and logs show correct time.

**Comment by rojaxthegreat** [comment]
Nevermind, I just figured it out.  I am a scrub and had the user preferences, statistics display set to UTC instead of site timezone.  Thanks anyways guys
