### ISSUE TITLE
Huge LOAD after starting container

### ISSUE THREAD

**Issue by pcjogi** [jacobalberty/unifi-docker#718]
Staring the fresh (latest) installed Container without any Unifi config on a fresh isnstalled PI 4 (2GB) results in a huge Load (up to 100) and ad the end with a non operating system.

Is the PI too small in Memory?

**Comment by johnreitan** [comment]
I run this on my k8s cluster and I just checked the pod, it uses 1.1GiB. 
I have 4GB and 8GB RPI4's in my cluster, never had any resources issues.

**Comment by johnreitan** [comment]
I also see the pod peaked at 1.32GiB

**Comment by pcjogi** [comment]
Seems that the 2 GB PI4 is too small. I added 2 GB Swap, which made a more stable but not performant system. I will change the PI with a 4GB System in the next days and come back with information.

**Comment by dcarbone** [comment]
This is expected.  At boot, the Java app's bootup process can take a few minutes and does consume a large amount of CPU.

It calms down quite a bit after initial boot, however.
