### ISSUE TITLE
Update image to controller version v8.0.28

### ISSUE THREAD

**Issue by dcarbone** [jacobalberty/unifi-docker#719]
Unifi Controller v8.0.28 has been released, and we should make it available: https://community.ui.com/releases/UniFi-Network-Application-8-0-28/f7492865-778d-4539-aaf8-3fb09c4279b0

**Comment by waja** [comment]
v8.0.28 is still RC, isn't it?

**Comment by dcarbone** [comment]
Ah, you're right!  I jumped the gun a bit there. Can close, or I can turn this into a PR for the RC tag series.

**Comment by Gamertech** [comment]
Keep it imo, though you will need to update the links if it's released as the rc and 'official' urls are different.

**Comment by progamer562** [comment]
not rc now

**Comment by Gamertech** [comment]
Still RC.

**Comment by progamer562** [comment]
wydm

**Comment by progamer562** [comment]
nvm cant see that green at all

**Comment by Gamertech** [comment]
Now it's official.
https://dl.ui.com/unifi/8.0.28/unifi_sysvinit_all.deb

**Comment by progamer562** [comment]
yes

**Comment by progamer562** [comment]
how about i cloned this rep and the community updates the rep i will make the rep 100 active with me and others

**Comment by dcarbone** [comment]
If you want, but in the interim I did publish multiarch image of v8.0.28 to https://hub.docker.com/repository/docker/dancarbone/jacobalberty-unifi/general.

**Comment by progamer562** [comment]
https://github.com/progamer562/unifi/pulls make a pull then i will check. tomorrow

**Comment by arkste** [comment]
you can use https://github.com/nexusforge/unifi-docker / https://hub.docker.com/r/nexusforge/unifi-docker
