### ISSUE TITLE
Cannot connect to the Cloud when RUNAS_UID0 is set to false

### ISSUE THREAD

**Issue by ahiguero** [jacobalberty/unifi-docker#72]
### Host operating system

QNAP TS-453A

### What tag are you using

5.6.19

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5`

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

after setting the owner of the folder to the right user group i proceeded to create the container. i should be able to connect to the cloud service. 

### What actually happens?
there is no possibility to connect to the cloud service unless the RUNAS_UID0 is set to true

**Comment by jacobalberty** [comment]
Hmm, I'm unable to reproduce this. I launched with the command line `docker run -t -i --rm -p 8443:8443 -e RUNAS_UID0=false --init jacobalberty/unifi:5.6.19` and after completing the wizard I was able to enable cloud connectivity just fine. Can you provide any details? maybe some log files showing an error?

**Comment by ahiguero** [comment]
For some reason the docker containers on the QNAP do not like the user being different that the root even though I have gone to the command prompt and  the chown so that the user has the proper ownership do the folders. I had other issues with other containers too so I need to check what else I need to configure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jacobalberty** [comment]
Hmm i wonder if it drops capabilities. Do you see any place with something
like cap_add or cap_drop?

**Comment by ahiguero** [comment]
reconfigured the permission on the folders where the image is downloaded and where the docker settings are and it is working now with the non root user. sorry for the trouble Jacob and once again thanks fro your help
