### ISSUE TITLE
Improvement for readme part Adoption

### ISSUE THREAD

**Issue by Gamogamer** [jacobalberty/unifi-docker#727]
### Operating system

Ubuntu Server LTS 22.04.3

### UniFi Tag

latest

### Docker run

docker run -d --init \    --restart=unless-stopped \    -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \    -e TZ='Europe/Germany' \    -v ~/unifi:/unifi \    --user unifi \    --name unifi \    jacobalberty/unifi

### Bug description

Adopting new devices requires port 10001 UDP, this is not reflected in the section in the readme, nor in the side project link.
 -p 10001:10001/udp
after adding this to the run command the device immediately poppep up (I already did what stood there)

**Comment by TheAceMan** [comment]
I assume you are referencing discovering a new AP, not actually adopting it. IE a new AP showing in the device screen as ready to adopt.

I recently worked through adding a new AP. Migrated to k3s recently and wanted to get the discovery working automatically vs having to ssh in to add to the controller. What I found is the AP needs to be able to resolve the unifi controller. I had to make _unifi_ resolve in DNS, I added it to my DNS in pfsense. Port 10001 I believe allows the controller to publish it's hostname to the network (in my scenario this did not solve the problem). But if you can _nslookup unifi_ the AP should discover correctly.

The need for unifi to resolve is not well documented for sure as it took me a while to get this working.
