### ISSUE TITLE
Update image to controller version v8.1.113

### ISSUE THREAD

**Issue by Vest** [jacobalberty/unifi-docker#730]
Unifi Controller v8.1.113 has been released. Can we make it available?
https://community.ui.com/releases/r/network/8.1.113

**Comment by bigjohns97** [comment]
Looks like they finally support MongoDB 7.0 with this release!

**Comment by waja** [comment]
> Version 8.1 and newer supports up to MongoDB 7.0.

**Comment by Gamertech** [comment]
However updating existing Mongo installs to 7.0 is a right prick unfortunately.

**Comment by bigjohns97** [comment]
> However updating existing Mongo installs to 7.0 is a right prick unfortunately.

Honestly I am probably just going to backup from within the UI and start fresh.

**Comment by esand** [comment]
> > However updating existing Mongo installs to 7.0 is a right prick unfortunately.
> 
> Honestly I am probably just going to backup from within the UI and start fresh.

As long as full (and settings only) backups are reliable, I would almost consider this a viable, official, migration path choice. Otherwise, you're supporting all sorts of possible scenarios where the db upgrade could fail (I say this having zero MongoDB experience, just seeing that people seem to have issues upgrading between major releases of it).

If it's a risk to upgrade the latest tag with a release using MongoDB 7, perhaps a mongo7 tag could be created for builds with that where we know that you have to start with a fresh db on first install, then over time (as people read info telling them how to migrate over), you eventually move it to latest so as to at least not hose people that are unaware.

**Comment by Gamertech** [comment]
Mongo requires manual intervention with almost every single x.1 increase, and requires Mongo's version be incremented to match for each step.

Doing them all at once, ie. going from 4.x to 7.x will destroy every install out there :P

Pretty much reinstalling and restoring a backup is the only viable way to get this done.

**Comment by trucktire** [comment]
Hi. I'm not tech savvy but doing my best. I don't know if I'm doing something wrong? When I try updating I get 8.0.28. I tried "docker pull jacobalberty/unifi", "docker pull jacobalberty/unifi:latest" and "docker pull jacobalberty/unifi:v8.1.113" which doesn't work. Am I supposed to do something else?

**Comment by bigjohns97** [comment]
> Hi. I'm not tech savvy but doing my best. I don't know if I'm doing something wrong? When I try updating I get 8.0.28. I tried "docker pull jacobalberty/unifi", "docker pull jacobalberty/unifi:latest" and "docker pull jacobalberty/unifi:v8.1.113" which doesn't work. Am I supposed to do something else?

It hasn't been implemented yet. Watch the task in the OP to complete before trying the specific version.

**Comment by trucktire** [comment]
Thank you. Not really got the hang of github yet. I'll wait for completion. Thanks!

**Comment by buckaroogeek** [comment]
Long (long) time user of this image. I have been using mongodb 3.6 stand alone container for quite a while. With unifi 8.1.113 out and added support for mongodb 7, I decided to try a mongo update process. I have very draft notes of the steps I took to get to mongodb 4.4 at https://github.com/buckaroogeek/unifi-pihole-doh-docker/blob/master/mongo-update.md. It seems to be working ok (i.e. unifi web ui works, no errors in log files). This is Jacob's image along with mongo image hosted in docker on a Synology NAS. I am running 8.1.113 using a clone of Jacob's repository that I bumped up.

**Comment by swrobel** [comment]
Is there any significant benefit of updating the Mongo version if all it's used for is the Unifi controller?

**Comment by buckaroogeek** [comment]
My primary motivation was updating to a supported version like 4.4 for any security, performance and bug related updates.

**Comment by esand** [comment]
> Is there any significant benefit of updating the Mongo version if all it's used for is the Unifi controller?

Support, and by that I mean you're using something relatively current so other software can be expected to function with it (think OS and all its components). The Unifi controller is just a small piece of the puzzle, and having it rely on severely outdated (3.x is EOL, and I believe 4.x is coming soon) makes maintaining a viable container for it very difficult.

If Mongo is updated to v7, it brings the database component to the current community release which also means any other legacy pieces (old Ubuntu distros, etc...) are also hopefully no longer needed. Obviously as you update everything else, you benefit from everything @buckaroogeek mentioned as well.
