### ISSUE TITLE
Backup is still fetching. 

### ISSUE THREAD

**Issue by jslegers73** [jacobalberty/unifi-docker#735]
### Operating system

Raspberry Pi Bookworm

### UniFi Tag

latest

### Docker run

  unifi:     image: jacobalberty/unifi:latest     container_name: Unifi-Controller     restart: always     network_mode: host     hostname: unifi     ports:       - '7080:7080'       - '7443:7443'     environment:       - TZ=${TZ}     volumes:       - /etc/localtime:/etc/localtime:ro       - ./unifi:/unifi

### Bug description

I'm am unable to make a manual backup. It is still showing Preparing and Fetching. This was unfortunately also the case with version 8.0.28.

### Steps to reproduce

Go to Settings -> System -> Backups -> Download -> Settings Only - Download. 
It is possible to download an available backup.

**Comment by esand** [comment]
Are you trying a full backup or settings only? If it's a full backup and you have a very large database of historical data, it could take a while (maybe fail?). Try a settings only backup first to see if that works. If it does, that rules out a lot of possible issues and just means the issue is with backing up your historical data.

**Comment by jslegers73** [comment]
I have tried settings only. There are only two devices in my environment. One AP and one switch.

What I also find strange is the file size of \data\backup\unf files.
Version 8.0.28 is 19Kb
Version 8.1.113 is 4Mb

Is this ok?

**Comment by esand** [comment]
Small files are likely settings only. Larger files include history. I have 4 devices and 30+ clients and a lot of them have custom settings of some sort; my settings only backup is about 500kb.

If you have any backups at all, that means that the process to create the backup is likely working, so it's just downloading that could be the issue.

I did notice that on your docker line you're not specifying a user/group. I believe it's recommended to use unifi:unifi (user/group is defined in the container). You could try that and also check the file permissions of the backups in /unifi on your host system to see what their permissions are.

**Comment by jslegers73** [comment]
I have found it. It was my Nginx Proxy Manager. I use that for https. I forgot to put on the websockets option and after I did it then works.  Sorry for my mistake.
