### ISSUE TITLE
No new Device Update in Controller

### ISSUE THREAD

**Issue by anton-v** [jacobalberty/unifi-docker#736]
### Operating system

Rasbian Wormbook

### UniFi Tag

stable; Network 8.1.113

### Docker run

 docker run -d --init --restart=unless-stopped -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Europe/Amsterdam' -v ~/unifi:/unifi --user unifi --name unifi jacobalberty/unifi

### Bug description

No new firmware images appear under updates. Stig on UAP AC LR | 6.6.55.15189
Device Version 6.6.65 (minor plus ten) is available. Manually installed on one.
When I use 'Check for Updates' nothing seems to happen. 
At Network Application 'Check for Updates' says No update available.

### Steps to reproduce

What is blocking?

### Relevant log output

```shell
-
```

**Comment by esand** [comment]
6.6.65 is only official for gen 6 devices. The UAP AC LR is a gen 2 device, so the latest firmware would be 6.6.55 which is why you haven't seen an update from the controller being pushed to it.

**Comment by anton-v** [comment]
Thanks for sorting this out.
The odd thing is remarkably well that there is a download link for UAP AC LR [https://dl.ui.com/unifi/firmware/U7PG2/6.6.65.15248/BZ.qca956x_6.6.65+15248.240130.2327.bin]
Rereading the page I noticed the remark _This release is now available on the Official release channel for the models/generations listed below, it's still a Release Candidate for all other models_.
Clear that it is a RC for the UAP AC LR. That explains why I can add firmware manually.
