### ISSUE TITLE
Support for Early Access

### ISSUE THREAD

**Issue by Sysadminfromhell** [jacobalberty/unifi-docker#739]
Hey there,

I would like to have the support (Build for label) early access because I have a unifiy Site which uses Early Access Firmware so I need the Network Appliance also to be able to set early access.

Kind regards,

**Comment by Gamertech** [comment]
Problem there is, the EA controller releases that don't make it to RC/'Stable' are usually so broken there's no way we could in good faith suggest anyone use them and are often pulled. The existing EA 8.1.124 is a good example of that with many problems.

In counterpoint, the releases that do make it to 'Official' are usually rushed through EA so fast there's no time/point adding them to a separate branch.

**Comment by Sysadminfromhell** [comment]
Thanks for your replay, what about the RC channel then? Kind regards

**Comment by Sysadminfromhell** [comment]
Hey there, 2 Weeks no update here and a new RC is available. Did you consider adding a Tag for RC or should I generate my own Dockerfile of yours and allow this tag myself?
