### ISSUE TITLE
UniFi Network Application 8.1.127

### ISSUE THREAD

**Issue by rmayergfx** [jacobalberty/unifi-docker#744]
### Operating system

Docker

### UniFi Tag

latest

### Docker run

docker pull jacobalberty/unifi

### Bug description

Please Update Docker to actual Version.

**Comment by rmayergfx** [comment]
See https://community.ui.com/releases/UniFi-Network-Application-8-1-127/571d2218-216c-4769-a292-796cff379561

**Comment by patswayze** [comment]
following - im new to this, does the unifi-docker normally get updated to the latest version?

**Comment by drwtsn32x** [comment]
> following - im new to this, does the unifi-docker normally get updated to the latest version?

Yeah, this is the first time I've seen it take so long.
