### ISSUE TITLE
Update to 8.2.93

### ISSUE THREAD

**Issue by kusznir** [jacobalberty/unifi-docker#751]
### Operating system

Debian Docker

### UniFi Tag

stable

### Docker run

Using compose file and portainer

### Bug description

Hello:

I'm having a unifi issue, and unifi support is refusing to support me until the controller is running on their current version.  Can you please upgrade to the current unifi stable, which is 8.2.93 as of this writing?

### Steps to reproduce

Install...note that version is behind Ubnt's current.

**Comment by kusznir** [comment]
FYI: I looked at the linuxserver build before selecting this one.  The linuxserver build is more complex to set up and appears less flexible to me.  It requires a separate container with mogodb in it, and is harder to handle a variety of networking setups.  It also appears to not handle custom certificates for ssl.  So I very much prefer this one!  I am just looking to get it updated.  Its not far out of date.

**Comment by Viss** [comment]
I'm using this inside of a synology rackstation, and I can't see @dcarbone's image on dockerhub. Is there a walkthrough somewhere for how to switch to the new, maintained image, or any instruction surrounding how to do this in a synology array?

**Comment by e3eli3h** [comment]
@Viss, it is there.
I'm also on syno and couldn't find it.
The mistake I made was to search for "dcarbone" instead of "dancarbone".
Good luck.

**Comment by dcarbone** [comment]
Indeed, dcarbone was taken by the time I got around to making a dockerhub account.

**Comment by drwtsn32x** [comment]
> If it will not be continued I think I am not alone in wanting to know if I need to look elsewhere.

Agreed... If we could get confirmation from @jacobalberty whether or not this has been abandoned, that'd be appreciated.

I'll probably switch to @dcarbone's image if there are no updates for a couple more weeks.  (Thanks for doing that, by the way!)

**Comment by dcarbone** [comment]
I prefer the way Jacob set up his image vs the Linuxserver folk's approach, so I may end up maintaining and pushing a full fork of this for newer versions.

**Comment by drwtsn32x** [comment]
@dcarbone  that would be fantastic!

**Comment by richb-hanover** [comment]
> I prefer the way Jacob set up his image...

I also agree. I revised the README with an eye toward minimizing the required steps. Having everything all in one Docker container makes it a simple process to setup and run. (The people using Unifi want to know about their radios, not fuss with multiple Docker containers, etc.)

@dcarbone - It sounds as if you have set up a separate container on DockerHub. Where can we review its files? I don't find a README or link at: https://hub.docker.com/r/dancarbone/jacobalberty-unifi Thanks

**Comment by mrartw** [comment]
Hello, 
I'm trying to install the dancarbone/jacobalberty-unifi on my QNAP (ContainerStation v2.0.957) but I'm getting "missing signature key" errors. I'm not sure what that means. Any ideas?

**Comment by dcarbone** [comment]
> > I prefer the way Jacob set up his image...
> 
> I also agree. I revised the README with an eye toward minimizing the required steps. Having everything all in one Docker container makes it a simple process to setup and run. (The people using Unifi want to know about their radios, not fuss with multiple Docker containers, etc.)
> 
> @dcarbone - It sounds as if you have already set up a separate container on DockerHub. Where can we review its files? I don't find a README or link at: https://hub.docker.com/r/dancarbone/jacobalberty-unifi Thanks

Its built from my fork here: https://github.com/dcarbone/unifi-docker.  Currently I simply build and push locally, but if Jacob is MIA for the next release, I'll move to a more transparent build system in GHA in that repo.

**Comment by BestBackwards** [comment]
@dcarbone If you intend to continue supporting this going forward, please advise how we can best support you. 
Legend!

**Comment by GoliathLabs** [comment]
It would also be worth trying to contact @jacobalberty for push rights to this repository. That way, all existing users would benefit from timely updates.

**Comment by drwtsn32x** [comment]
Looks like jacobalberty just updated the image!

**Comment by drwtsn32x** [comment]
8.3.32 was released last week.

**Comment by Viss** [comment]
@dcarbone did you ever chuck this into the registry? I just went looking for it and i found a couple of other things that arent unifi related. I don't suppose theres a guide for how to deploy this container you've setup on a synology array? I'm currently using the 'container manager' app on my rackstation to manage this image - but if i can use yours and its mostly painless im happy to switch to get more frequent updates

**Comment by richb-hanover** [comment]
Let's not get ahead of ourselves. @jacobalberty probably has many things to do in addition to keeping up with Ubiquiti's latest version.

Even if the newest release were perfect, it takes a little bit of time to package it, then test it locally before rolling it into "production" for the rest of us.

And more important, I'd much rather stay a week or two behind the bleeding edge of a release. I'm happy to let others find and report the bugs: that means I can simply keep running my network without worrying so much about the Unifi application.

**Comment by drwtsn32x** [comment]
of course, I can appreciate that he's busy.  But even if he opted to publish the latest version soon after its release, we can choose when to upgrade our local installs. I agree that we don't necessarily want to upgrade right away.

I just hope we don't have to wait 30+ days again to have the option of upgrading.

**Comment by dcarbone** [comment]
I don't have the permissions to push to @jacobalberty's dockerhub account, but I did publish v8.3.32 the other day: https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags

I haven't opened a PR as #755 has already been opened.

**Comment by drwtsn32x** [comment]
Thanks, @dcarbone - I may just end up switching to yours!

**Comment by dcarbone** [comment]
> Thanks, @dcarbone - I may just end up switching to yours!

To be clear, "my" version is just me building @jacobalberty's Dockerfile and pushing to my dockerhub account.  The credit remains with the respective authors.

**Comment by Viss** [comment]
ah, i figured it out. the synology array prepopulates registry.docker.com as its place to look for images, i had to go add hub.docker.com and then it found yours. rad! thanks!
