### ISSUE TITLE
Dockerhub images don't support RaspberryPi anymore

### ISSUE THREAD

**Issue by Tibovandenberk** [jacobalberty/unifi-docker#754]
Hi i just wanted to ask why the images on dockerhub are not build for linux/arm/v7? In my setup a Raspberry Pi 4 runs this docker image (for years), is plenty fast for me and doesn't break the bank on powerconsumption. Would you like to build an image for armv7 once in a while?

**Comment by drwtsn32x** [comment]
See:  https://github.com/jacobalberty/unifi-docker/issues/734

**Comment by Tibovandenberk** [comment]
This issue seems to be reduntant
