### ISSUE TITLE
Run fails with "no matching manifest for linux/arm/v8" on Raspberry Pi 4

### ISSUE THREAD

**Issue by rbauman70** [jacobalberty/unifi-docker#756]
### Operating system

Debian GNU/Linux 12 (bookworm)

### UniFi Tag

latest

### Docker run

docker run --name unifi -d --restart=unless-stopped --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ="America/New_York" -v ~/unifi:/unifi jacobalberty/unifi

### Bug description

Attempting to run the latest version on a Raspberry Pi 4 with Bookworm fails.  Works great on my other Debian 12 server but that's x86_64.
```
Unable to find image 'jacobalberty/unifi:latest' locally
latest: Pulling from jacobalberty/unifi
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
```
More info:
```
pi@rpi4:~/unifi $ uname -a
Linux rpi4 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
pi@rpi4:~/unifi $ docker version
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:03:07 2024
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:03:07 2024
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
pi@rpi4:~/unifi $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by jacobalberty** [comment]
It looks like you're using a 32 bit arm version of docker, are you by chance running 32 bit raspbian? unfortunately unifi will no longer run on non 64 bit platforms even though the cpu is 64 bit the os itself needs to be as well.

**Comment by rbauman70** [comment]
No, it's 64-bit.  But it turns out that the current repositories for Raspbian only have the 32-bit (armhf) versions of Docker.  I had to go to https://docs.docker.com/engine/install/debian/ to install the 64-bit version of Docker from their repository.  Unifi is running nicely now on the Pi.  Thanks for your help.
