### ISSUE TITLE
Document how to limit Mongo memory

### ISSUE THREAD

**Issue by deviantintegral** [jacobalberty/unifi-docker#758]
It took me a bit of time to find exactly how to limit Mongo memory in docker, since the docs at https://help.ui.com/hc/en-us/articles/115005159588-UniFi-Tuning-the-Network-Application-for-a-High-Number-of-UniFi-Devices don't explain how. Also, the mongo docs don't explain specifically how to do this with compose (just with docker run).

Could we add something like this to the docker-compose template?

https://github.com/jacobalberty/unifi-docker/compare/master...deviantintegral:unifi-docker:patch-1

Aside, would it make sense to also upgrade the template to compose v3?

**Comment by deviantintegral** [comment]
The PR template asked me to file an issue before opening a PR. I'm glad to open one if the above changes look good.

**Comment by deviantintegral** [comment]
@dobrac sorry to ping, but I see you have the most recent commit and the stale bot keeps poking me 😁 . Any thoughts on my questions above?

**Comment by dobrac** [comment]
> @dobrac sorry to ping, but I see you have the most recent commit and the stale bot keeps poking me 😁 . Any thoughts on my questions above?

Hi, sorry, but I'm no maintainer. I think you will have to wait for @jacobalberty to answer.
