### ISSUE TITLE
/unifi/cert/chain.pem does not work for me with Let's Encrypt

### ISSUE THREAD

**Issue by funked00** [jacobalberty/unifi-docker#76]
with the chain in chain.pem it does not work but if I put the cert and the chain together in cert.pem it's ok. Maybe you should change the doc?

### Host operating system

CentOS Linux release 7.3.1611 (Core)

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run --net=host -d \
-e TZ='Europe/Berlin' \
-v /opt/unifi:/unifi \
--name unifi \
jacobalberty/unifi:latest

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen? chain and cert in cert.pem (real domain masked)
openssl s_client -servername unifi.xxx.net -connect unifi.xxx.net:8443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = unifi.xxx.net
verify return:1
---
Certificate chain
 0 s:/CN=unifi.xxx.net
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3

### What actually happens? (chain in chain.pem)
openssl s_client -servername unifi.xxx.net -connect unifi.xxx.net:8443
CONNECTED(00000003)
depth=0 CN = unifi.xxx.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = unifi.xxx.net
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = unifi.xxx.net
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=unifi.xxx.net
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

**Comment by jacobalberty** [comment]
This should be fixed in beta, are you able to build beta and verify it corrects the issue for you? If you don't know how/don't have the capability to build a docker image at this time then  just let me know and I'll bring it over to the latest tag instead. I just want to make sure it's properly fixed before I start trying to push it to the hub.

**Comment by funked00** [comment]
Sorry, but I'm not so experienced with docker to build the beta image. I'm happy to run your great work in my production server to manage the wlans of some customers. As I said before it works well if I put the cert chain to the cert.pem file. If I should test a new stable version with this issue please let me know.

**Comment by jacobalberty** [comment]
Alright I'm away from my computer for a bit so I can't push to hub right
now but when I get back I'll push it and let you know when the fix is on
the hub

**Comment by jacobalberty** [comment]
Alright, :latest should have the fix now, let me know if it works for you.

**Comment by funked00** [comment]
Yeah, now it works with seperate cert and chain file like in the doc. great work! thank you!
