### ISSUE TITLE
Looses Configuration on upgrade

### ISSUE THREAD

**Issue by penguinjeff** [jacobalberty/unifi-docker#760]
### Operating system

Fedora release 40 (Forty)

### UniFi Tag

latest

### Docker run

nohup podman-compose up -d --remove-orphans 2>nohup.err &

### Bug description

The last two updates I had to completely rebuild my unfi controller. Luckily my network is easy but I had to recreate my wifi network and reset my access points and rejoin then as if it was a new unifi contoller

### Steps to reproduce

`
# grep -v "^#" docker-compose.yml 
version: "3"
networks:
  vlan10:
    external: true

services:
  unifi:
    container_name: unifi
    hostname: unifi.${SUBDOMAIN}.${DOMAIN}
    image: jacobalberty/unifi:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    networks:
      vlan10:
        ipv4_address: 192.168.0.97
    ports:
      - "3478:3478/udp"
      - "8443:8433"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:8080"
    environment:
      TZ: 'America/Denver'
      UNIFI_HTTP_PORT: 80
      UNIFI_HTTPS_PORT: 443
    shm_size: '2gb' # Maximum memory usage
    cpus: .5
    # Volumes store your data between container upgrades
    volumes:
      - '/home/unifi:/unifi:Z'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: always
`

**Comment by pcdewolff** [comment]
Not really a bug, you made your containers without any volumes so there is no persistence at all.
