### ISSUE TITLE
UniFi Network Application 8.4.59

### ISSUE THREAD

**Issue by jpvj** [jacobalberty/unifi-docker#761]
Hi!

8.4.59 is out. Has anybody felt encouraged to start building the docker image for it?

Thank you :-)

**Comment by arkste** [comment]
you can use `nexusforge/unifi-docker` until jacob pushes the new version: 
https://github.com/nexusforge/unifi-docker
https://hub.docker.com/repository/docker/nexusforge/unifi-docker/general

**Comment by jpvj** [comment]
Great - thank you very much.
It's up and running with no issues so far :-)

**Comment by mac8686** [comment]
Great work !!!
Thank you !!

Saludos desde Argentina!
