### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by stembus** [jacobalberty/unifi-docker#766]
Hello @jacobalberty 

Would it be possible to also add "docker-compose.yml" example into your "readme" on Github for unifi-docker?

I am trying to convert my container into project but I do not understand it  enough to be able to create full docker-compose 

Would be good if you could provide an example for let say "standard" deployment that can be then "easily" adjusted based on ENV I use/need to add etc that deviates from the "standard"

Thanks a lot,
Jiri

**Comment by Chewwy420** [comment]
Here is mine for an example...


version: "2.3"

services:
  unifi:
    user: unifi
    image: jacobalberty/unifi
    container_name: unifi-controller
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
    environment:
      TZ: "America/New_York"
    volumes:
      - ~/unifi:/unifi

**Comment by stembus** [comment]
> Here is mine for an example...
> 
> version: "2.3"
> 
> services: unifi: user: unifi image: jacobalberty/unifi container_name: unifi-controller restart: unless-stopped ports: - "8080:8080" - "8443:8443" - "3478:3478/udp" environment: TZ: "America/New_York" volumes: - ~/unifi:/unifi

thanks a lot ;)

**Comment by pcdewolff** [comment]
Kind of late but the github seems to contain and compose.yml for already some time. Seems a good start to me.
