### ISSUE TITLE
Routing features from 8.3.32 not available

### ISSUE THREAD

**Issue by djaymango** [jacobalberty/unifi-docker#770]
**Operating system**
Synology DSM 7.2.1-69057 Update 5

**UniFi Tag**
8.4 stable

**Description**
Since v8.3.32 it has been possible to create NAT routing and policy-based routing via the UI. However, I don't see these features at all. I have even updated to latest build 8.4.59. Other new features are available.

![367761621-513f655a-ee5b-40bb-b4ca-e946dc0ed8eb](https://github.com/user-attachments/assets/92f982bd-a129-4d1b-b438-4be1d9ef84ee)
[https://github.com/jacobalberty/unifi-docker/issues/url](url)

I have an USG 3P, but I couldn't find anything about hardware limitations.
My UI looks like this:
![367763069-7951d42e-9712-49a1-85c5-b209449992c7](https://github.com/user-attachments/assets/46077a20-cbf9-4c3c-b2f1-bcf96775a49d)

Are any of you able to use these features?

**Comment by esplor** [comment]
@djaymango
Just tried it with 2 sites, one with USG-3P, the other with UXG-Lite.
UXG shows nat routing, USG-3P shows the same as your screenshot.

**Comment by djaymango** [comment]
> @djaymango Just tried it with 2 sites, one with USG-3P, the other with UXG-Lite. UXG shows nat routing, USG-3P shows the same as your screenshot.

Huh okay so could be a hardware limitation. Guess I need to read the fine print again.
Thanks for checking and letting me know! 👌🏽
