### ISSUE TITLE
Change standard ports to any other

### ISSUE THREAD

**Issue by gruzzy** [jacobalberty/unifi-docker#82]
Standard ports used by Unifi controller are very well-known and I had quite huge numbers of attempts to break in.
Now I am using non-standard ports and there are no connections from unknown locations.

Unifi Controller has a simple way to change it in the system.properties file
```
## device inform
# unifi.http.port=8080
## controller UI / API
# unifi.https.port=8443
```
Would you be able to add Environment Variables to manage it as you already have support to change settings for MongoDB?

It could be some code before confSet
```
if [ -z "$UNIFI_HTTP_PORT" ]; then
  settings["unifi.http.port"]="8080"
elif
  settings["unifi.http.port"]="UNIFI_HTTP_PORT"
fi

if [ -z "$UNIFI_HTTPS_PORT" ]; then
  settings["unifi.https.port"]="8443"
elif
  settings["unifi.https.port"]="UNIFI_HTTPS_PORT"
fi
```

**Comment by mniesiobedzki** [comment]
Is it possible to implement this improvement?
