### ISSUE TITLE
AP being constantly readopted

### ISSUE THREAD

**Issue by tazmad** [jacobalberty/unifi-docker#83]
### Host operating system

Example: Fedora 26 with Docker version 17.09.0-ce, build afdb6d4

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
```bash
docker run -d --rm --init -p 8081:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -e TZ='Europe/London' --mount source=unifi,target=/unifi --name unifi jacobalberty/unifi:latest
```
Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

Access point adopted and remains that way

### What actually happens?

I see this in the server logs for a given day:

```bash
[root@tazmadlx log]# grep 2017-12-04 server.log | grep adopted | head
[2017-12-04 04:11:30,263] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:12:39,574] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:13:39,627] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:14:39,676] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:15:39,693] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:16:39,731] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:17:39,774] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:18:39,830] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:19:39,870] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[2017-12-04 04:20:39,914] <ssh> INFO  event  - [event] AP[80:2a:a8:16:cb:af] was automatically readopted
[root@tazmadlx log]# grep 2017-12-04 server.log | grep adopted | wc -l
1091
[root@tazmadlx log]# 
```
There also seems to be some sort of memory leak caused by I suspect the java process, but then I am new to all the docker stuff so not 100% sure.  I had seen a post about this issue somewhere but I can't seem to find it now so apologies if this was already resolved and I am doing something dumb.

In case it helps, am running:

```bash
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

Thanks
![73f2d133-266c-4d4d-ae78-a61ceaaee0db](https://user-images.githubusercontent.com/4682808/33591575-2858dc70-d97e-11e7-9732-e37b023a3a36.png)
![60f81b10-f0be-4d08-a1c5-1e94a70f7ddd](https://user-images.githubusercontent.com/4682808/33591576-2882e218-d97e-11e7-9d43-bba5b8158ef9.png)

**Comment by jacobalberty** [comment]
I believe the memory issue you are seeing is related to [this](https://community.ubnt.com/t5/UniFi-Wireless/NOTICE-UniFi-Controller-Memory-Usage-5-6-20/td-p/2137209/jump-to/first-unread-message). 

The adopting issue is going to be an issue with unifi, you would be better off asking them on their forums directly. but I was speaking with someone on IRC about this earlier, he said they recommended he do a reinstall. You could try backing up and trying the latest stable candidate. The latest publicly posted is 5.6.24 but theres a 5.6.26 stable candidate on the beta forums. You can build it with the following

`docker build -t unifi-beta --build-arg PKGURL=https://dl.ubnt.com/unifi/5.6.26-f6a8a26e43/unifi_sysvinit_all.deb "https://github.com/jacobalberty/unifi-docker.git#beta"`

Then launch your container like
`docker run -d --rm --init -p 8081:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -e TZ='Europe/London' --mount source=unifi,target=/unifi --name unifi unifi-beta`

Note, this will take you off the main image and any updates will rely on you re building that local unifi-beta image, but you could use it until next week when (hopefully) 5.6.26 hits stable then move back to the latest tag, assuming it works.

**Comment by tazmad** [comment]
Thanks for the quick response - I'll try both those things out tonight when I get home and feed back.  Much appreciated!

**Comment by jacobalberty** [comment]
They just publicly posted the 5.6.26 stable candidate, so now you can eliminate the entire docker build line and just use 

`docker run -d --rm --init -p 8081:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -e TZ='Europe/London' --mount source=unifi,target=/unifi --name unifi jacobalberty/unifi:5.6.26-sc`

You'll still be off the latest tag so you should move back to it when 5.6.26 hits stable, but at least it saves you having to build it yourself. If you try and find it wont pull that tag, wait ~10 minutes and try again. I just started the build on docker hub now.

**Comment by jacobalberty** [comment]
Let me know if 5.6.26 fixes it, if it doesn't it looks like it may be a java bug, I can try downgrading the java package if 5.6.26 doesn't get it.

**Comment by jacobalberty** [comment]
You can try hotfixing with the older openjdk with:

`docker exec unifi apt-get update`
followed by
`docker exec unifi apt-get install openjdk-8-jre-headless=8u141-b15-1~deb9u1`

you'd need to restart the container after that though.
Sorry for the comment spam, just managed to find the relevant thread on the forums and talk with some  other guys facing the same issue.
Thread is https://community.ubnt.com/t5/UniFi-Wireless/5-6-22-shows-adopting-on-all-devices/m-p/2152181#M264414

**Comment by tazmad** [comment]
Thanks for the “spam” - it was much appreciated and I do believe that 5.6.26-sc has resolved the issues. I still see a few lines of java when running htop, but the memory leak is definitely resolved and logs are no longer showing the readoption happening all the time (although I think this did take a while to manifest). I’ll keep an eye on it. 

Many thanks again and will keep my eyes out for when 5.6.26 goes into the “latest”.

**Comment by jacobalberty** [comment]
Just wanted to update, 5.6.26 went into 'latest' a few days ago so you can get back on that tag to stay current. I've been talking with someone else with the same issue and hes been stable on 5.6.26 since it went stable where he previously had adopting all the time, so it does seem 5.6.26 is the correct fix.

**Comment by tazmad** [comment]
Thank you!
