### ISSUE TITLE
arm32v7-beta image's architecure is amd64 in image metadata

### ISSUE THREAD

**Issue by kniskala** [jacobalberty/unifi-docker#84]
At least the current unifi:arm32v7-beta image's architecture is amd64 in the image metadata.
It works fine when run on stand-alone container (with docker run or docker-compose up) but noticed that when I tried to setup a swarm and run it as a service it got stuck in pending state as there were no amd64 machines in my swarm.

**Comment by jacobalberty** [comment]
Yes, I believe that is the manifest stuff discussed in https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

I need to figure out how I am going to integrate the builds of non x86 architectures, the docker hub doesn't directly support them at this time and I'm having to do a cross build using qemu. Does swarm allow you to use a build from repository instead of using an image?

**Comment by kniskala** [comment]
Ok, so this is a known issue.

An image built from repository gets deployed successfully.
I of course need to push it to another registry for all the swarm participants to be able to find it.
It would just have been nice to be able to skip the building part myself. :)

Thanks for all your work and effort in getting the unifi stuff dockerized.
Much easier to get that up and running than trying to install it on a fresh raspberry pi, especially after the dropped mongodb support in stretch...

**Comment by jacobalberty** [comment]
I'm working on setting up a build server on a raspberry pi 3 now to push images to the hub, hopefully that will fix the metadata issue for you. I'll close this issue when it gets done (hopefully within the week)

**Comment by jpawlowski** [comment]
I could help to use Travis for all platforms.
You may take this as a working example: https://github.com/docker-home-automation-stack/fhem-docker

**Comment by samriley** [comment]
Hi, was there any update on this? Just starting a project using a multi-arch k8s cluster. I have an issue at the moment that I'm unable to allow the unifi controller to run on any node and instead have to target it to a specific architecture even though it should work on any node.
