### ISSUE TITLE
[Feature Proposal] Handle existing chain.pem during import

### ISSUE THREAD

**Issue by ffittschen** [jacobalberty/unifi-docker#86]
### What tag are you using

`none` (yet)

### What do you expect to happen?
By specifying my `CERTDIR` I expect that `import_cert` imports my certificate into the container.

### What actually happens?
`import_cert` won't find my certificate, because it is already chained and named `fullchain.pem` instead of `cert.pem`.

## Proposal

I'd like to propose to add an option to specify if there are two files `chain.pem` and `cert.pem`, or if they are already chained. I'm happy to implement it and create a PR, but I created this issue to discuss the format of how we want to handle it.

I would say we could add an ENV variable `CERTNAME` that defaults to `cert.pem` and additionally add an ENV variable `CHAINPROVIDED` that defaults to `false`. If `CHAINPROVIDED` is set to `true`, we consider the file at `"$CERTDIR/$CERTNAME"` to be the chain and directly use it instead of concatenating a chain and a cert.

What do you think?

**Comment by jacobalberty** [comment]
Easy enough to add the CERTNAME part, just use something like
CERTNAME="${CERTNAME:-cert.pem}" to the top then replace the rest of the references to cert.pem with ${CERTNAME} 

as far as the CHAINPROVIDED bit it's easy enough to add an if statement just need to be sure the TMPLIST stuff doesn't get too buggered and end up leaving a bunch of temp files every time the cert changes.

There is one other change that needs to be accounted for if you want filenames to be changed modified easily. The privkey.pem will still be hardcoded.

**Comment by ffittschen** [comment]
I just created a PR as you can see. I went with an IMO clearer name `CERT_IS_CHAIN` instead of `CHAINPROVIDED`. I hope this is ok
