### ISSUE TITLE
How do I an upgrade to latest docker container? 

### ISSUE THREAD

**Issue by amcsSH** [jacobalberty/unifi-docker#89]
### Host operating system

same

### What tag are you using

`latest` for now

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker on synology nas.

### What do you expect to happen?

a documentation  section about upgrade to new container version.

### What actually happens?

I don't know.

**Comment by jcostom** [comment]
```
docker pull jacobalberty/unifi:stable
docker stop unifi (assuming your container is named "unifi")
docker rename unifi unifi.save
docker run ...... (however you created the original container)
```

If you're using the Synology web ui for Docker, pull latest stable, stop, rename, create new

Happy with the new version? Delete the prior container version.  Done.  The longest part (for me) of doing a container upgrade is pulling & unpacking the updated container image.

**Comment by StefaanD** [comment]
Wouldn't watchtower be of any help here? It does work rather well with other containers, i use v2tec/watchtower docker container to automatically pull new image if they are changed, stopping container, updating container with new images and restarting them.

Bu onnly jacobalberty can confirm if there might be some drawbacks of using watchtower of not.

**Comment by jacobalberty** [comment]
Watchtower should work just fine actually. I use it myself. If your unifi container is named `unifi` then try the following:
```
docker run -d \
  --name unifi-updater \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower unifi
```

This will launch a container named `unifi-updater` to update `unifi` see the [v2tec/watchtower](https://github.com/v2tec/watchtower) page for more advanced configurations.

I'll see about putting together a few update options on the wiki and readme in a bit.

**Comment by tophe75** [comment]
The easiest way I have found is:

- Log in to the controller
- Download the backup
- Stop the UniFi container
- Re-download the Image (latest)
- Start the new container
- Once on the "wizard" page, restore from backup

That is the way I do it.

**Comment by jhelmink** [comment]
This is how I update my containers on Synology Docker;

Open the Docker package.
Go to the Registry, and search for the image.
Click download, and choose the 'latest' tag
This will download the latest image and overwrite the existing older image.
Stop the container that was built on the old image.
Highlight it and select the Clear action.
Restart the container and it will be built from the new image.

This assumes that you've correctly mapped your container /config directory to the local volume, so all the config will be used by the updated image.

**Comment by onmomo** [comment]
@jhelmink thanks, worked like a charm! :-)

**Comment by DannMendis** [comment]
@jhelmink Thanks million. Easy process

**Comment by mszoernyi** [comment]
Does anyone had an issue with the login (`Invalid username and/or password.`) after updating the container? I reinstalled my container (used the same version just changed it from `latest` to `5.9.29` which was the same at that point) and bound the same volume. 

Same happens if I remove the volume and use the unify backup.

**Comment by phillijw** [comment]
@mszoernyi Yes! I believe it's an issue with automatic backups or something like that. I ended up just having to start over unfortunately and lose my backup.

**Comment by coalfield** [comment]
@jhelmink thank you easy to follow and worked great!

**Comment by mayhew132** [comment]
> This is how I update my containers on Synology Docker;
> 
> Open the Docker package. Go to the Registry, and search for the image. Click download, and choose the 'latest' tag This will download the latest image and overwrite the existing older image. Stop the container that was built on the old image. Highlight it and select the Clear action. Restart the container and it will be built from the new image.
> 
> This assumes that you've correctly mapped your container /config directory to the local volume, so all the config will be used by the updated image.

Just a minor update to this (in case anyone else arrives here after a Google Search) - the 'Clear' option is now 'Reset' on the Synology Docker application:
<img width="752" alt="Screenshot 2021-12-30 at 11 38 42" src="https://user-images.githubusercontent.com/25966969/147748681-7ebbaffb-4bfe-4fff-8d5f-8860b57abaf1.png">
