### ISSUE TITLE
Unable to load certificates from jrcs/letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by mjlongfl** [jacobalberty/unifi-docker#90]
### Host operating system

MacOS (actually Alpine Linux on HyperKit)

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/Chicago' -v ~/Documents/Docker/unifi/data:/unifi/data -v ~/Documents/Docker/unifi/log:/unifi/log -v ~/Documents/Docker/nginx-proxy/certs/unifi.`<my domain>`:/unifi/cert --name unifi jacobalberty/unifi:stable

### What do you expect to happen?

Let's Encrypt certificate (obtained using [jrcs/letsencrypt-nginx-proxy-companion](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/) container) is successfully imported and used by Unifi Controller.

### What actually happens?
```
[2017-12-30 14:55:20,894] <docker-entrypoint> Using openssl to prepare certificate...
unable to load certificates
140010480190720:error:0906D066:PEM routines:PEM_read_bio:bad end line:../crypto/pem/pem_lib.c:799:
```
I was able to trace this down to a missing end-of-line (EOL) at the end-of-file (EOF) of chain.pem, which results in the first line of the cert.pem to be concatenated to the last line of chain.pem (i.e.
```
...
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
...
```
).

### Potential solution
The following patch to import_cert fixes the issue (to insert a linefeed between the contents from the two files):
```
60c60,61
<         cat "${CERTTEMPFILE}" "${CERTDIR}/chain.pem" "${CERTDIR}/cert.pem"  >> "${CHAIN}"
---
>         (cat "${CERTTEMPFILE}" "${CERTDIR}/chain.pem"; echo) >> "${CHAIN}"
>         cat "${CERTDIR}/cert.pem"  >> "${CHAIN}"
```

Thanks for all of your hard work in creating (and maintaining) such a great Docker image!

**Comment by jacobalberty** [comment]
I just pushed a patch to the beta branch using `awk 1` instead of `cat`. This automatically adds a newline at the end and is a little cleaner than your proposed solution. Do you know how to build and use the beta  branch to test and make sure it fixes your issue?

**Comment by mjlongfl** [comment]
I have confirmed that the fix you provided (in the beta branch) fixes the issue. What is the expected release date for this functionality?

Thanks

**Comment by jacobalberty** [comment]
It's building on the hub now.

**Comment by mjlongfl** [comment]
Awesome! Thank you for your diligent work and quick responses.
