### ISSUE TITLE
Beta Build Fails w/ ENV Instead of ARG

### ISSUE THREAD

**Issue by iwoloschin** [jacobalberty/unifi-docker#92]
This commit broke beta builds:

https://github.com/jacobalberty/unifi-docker/commit/9604326835cb8942404723932b6e563829d2f919

I'm not sure if there is a way to pass Environmental Variables as part of a docker build, though I think you can as part of a docker run command?

**Comment by jacobalberty** [comment]
That's weird, that was supposed to go only on master, not sure how I accidentally applied it to beta, fixing now
