### ISSUE TITLE
How to upgrade UniFi

### ISSUE THREAD

**Issue by WorldOfMaze** [jacobalberty/unifi-docker#94]
I have UniFi running on my Synology NAS and it works great!  I would not like to upgrade to the latest version.  I was unable to find instruction on how to do the upgrade without starting from scratch.

Is there a way to upgrade UniFi or do I need to backup, remove the old Docker container and install the new one and them import the backup?

Thanks.

**Comment by jacobalberty** [comment]
I'm not familiar with the exact procedure on synology, but as long as you preserve the /unifi volume and reuse the same volume you can just pull the new container and recreate it with that volume. To be on the safe side you might want to make a backup just in case something goes wrong though.

**Comment by tophe75** [comment]
The easiest way I have found is:

- Log in to the controller
- Download the backup
- Stop the UniFi container
- Re-download the Image (latest)
- Start the new container
- Once on the "wizard" page, restore from backup

That is  the way I do it.

**Comment by WorldOfMaze** [comment]
Thanks, trophe75.

**Comment by dagelf** [comment]
That's not the best way to do it, of course - as this dumps all your history - if you would like to preserve that:

`docker ps  # to get your unifi image id
docker pull jacobalberty/unifi # this pulls an updated image
docker stop old_unifi # if you used the command in the readme to start it the first time, this will remove the image but not its "unifi" data volume
docker run -v unifi:/unifi --restart unless-stopped -p 8880:8880 -p 8843:8843 -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp --init -e TZ='Africa/Johannesburg'  jacobalberty/unifi:stable
`

The other nice thing about docker is that you can test the updated image before discarding the old image - but to properly do that you need to make sure you have at least double as much free space as your volume occupies - so you can clone the volume first, and then replace `--volumes-from old_unifi` with `-v new_unifi:/unifi` above. 

`docker run --rm -i -t -v old_unifi:/from -v new_unifi:/to busybox sh -c "cd /from ; cp -av . /to"`

Is the command to clone a volume. Then you can skip the `-p 8880:8880 -p 8843:8843 -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp` above, and if you have a VPN to your docker host, just test it with its 172.17.x.x address, or you can forward another port to it manually `iptables -t nat -I PREROUTING -j DNAT -p tcp --dport 8444 --to 172.17.0.3` or whatever the containers' IP address is. `docker inspect new_unifi|grep 172` is a quick way to get it.

**Comment by buckaroogeek** [comment]
A third alternative to managing a unifi controller is via docker-compose.  The steps are similar to those outlined by @dagelf and also require command line and admin level access to the Synology host. Jacob and team provide an example docker-compose file in the repository that is a decent starting point. Assuming you have a valid docker-compose.yml file then as admin from the directory where the docker-compose.yml file is stored:
`docker-compose pull
docker-compose up -d`

An alternative to using a VPN is to use a macvlan for the unifi controller. There are trade-offs of course. Using docker or docker-compose from the command line as well as options such as a VPN or macvlan depend on some knowledge and skill using linux from a command line and some risks given the admin level access needed. If curiouhttps://github.com/buckaroogeek/unifi-pihole-doh-docker. This is what I use on my home Synology.

Best

**Comment by FlorianHeigl** [comment]
+1 for docker-compose approach, since that really is using a docker functionality as intended.

**Comment by dagelf** [comment]
Problem with docker-compose is - if the updated image corrupts your data you have to do tedious data recovery. Also "docker functionality as intended" is an oxymoron - the docker team has changed the rules multiple times, they are incapable of thinking ahead. Granted, docker is now relatively mature, but they just do not get the Linux philosophy of keeping and reusing what works and insist on reinventing everything and keeping up with their changes is just too time consuming - especially when you can use a method that has worked for 30+ years, and that will keep working.

**Comment by dimkasta** [comment]
I am a bit sceptical about upgrading the image/container and keeping the existing volume. It suggests that unifi upgrades never touch or convert the data in any way, which seems unlikely.

**Comment by dagelf** [comment]
Rightly so. Upgrades have corrupted my data in the past. A bind mount to a
copy-on-write snapshot would be ideal, which could be committed if the
upgrade works and passes tests. If the data wasn't in a volume or bind
mount you would get that automatically. Just running it without, and making
an image and running and updating the image the old fashioned way might be
the best way to do Unifi images, after all. Ironically. If you don't want
to snapshot the data yourself, or duplicate it... which would be a problem
if space is at a premium.
