### ISSUE TITLE
curl error building beta image using "docker build": curl: (3) <url> malformed

### ISSUE THREAD

**Issue by ddribin** [jacobalberty/unifi-docker#96]
### Host operating system

Synology Linux
```
$ uname -a
Linux light 4.4.15+ #15217 SMP PREEMPT Wed Dec 20 18:19:46 CST 2017 x86_64 GNU/Linux synology_apollolake_218+
```

### What tag are you using

`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

    sudo docker build -t unifi-beta --build-arg PKGURL=https://dl.ubnt.com/.../unifi_sysvinit_all.deb "https://github.com/jacobalberty/unifi-docker.git#beta"

### What do you expect to happen?

Install a Beta image.

### What actually happens?

I get this error:

```
curl: (3) <url> malformed
The command '/bin/sh -c mkdir -p /usr/share/man/man1/  && groupadd -r unifi -g $UNIFI_GID  && useradd --no-log-init -r -u $UNIFI_UID -g $UNIFI_GID unifi  && apt-get update  && apt-get install -qy --no-install-recommends     curl     openjdk-8-jre-headless     procps     libcap2-bin  && echo "deb http://www.ubnt.com/downloads/unifi/debian unifi5 ubiquiti" > /etc/apt/sources.list.d/20ubiquiti.list  && apt-key adv --keyserver keyserver.ubuntu.com --recv C0A52C50  && curl -L -o ./unifi.deb "${PKGURL}"  && apt -qy install ./unifi.deb  && rm -f ./unifi.deb  && chown -R unifi:unifi /usr/lib/unifi  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 3
```

**Comment by jacobalberty** [comment]
Try rerunning with the latest beta from github, I added set -ex so it'll show you the expanded command before its run.

**Comment by ddribin** [comment]
Here's the output of the last few commands:

```
+ echo deb http://www.ubnt.com/downloads/unifi/debian unifi5 ubiquiti
+ apt-key adv --keyserver keyserver.ubuntu.com --recv C0A52C50
Executing: /tmp/tmp.AMtJuePKbH/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv
C0A52C50
gpg: requesting key C0A52C50 from hkp server keyserver.ubuntu.com
gpg: key C0A52C50: public key "UniFi Developers <unifi-dev@ubnt.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
+ curl -L -o ./unifi.deb 
curl: (3) <url> malformed
```

So `PKGURL` is empty then the `curl` command is run, for some reason. I'm not very familiar with Docker. Is there a way to dump the arguments set via `--build-arg` ?

**Comment by ddribin** [comment]
FWIW, it looks like the Docker version installed by Synology is pretty old:

```
$ docker --version
Docker version 17.05.0-ce, build 9f07f0e-synology
```

Not sure if that has anything to do with it. Unfortunately, I don't see a way to update the Docker version.

In the meantime, as a workaround, I've copied the `Dockerfile`, updated `PKGURL`, and built an image from this file.

**Comment by jacobalberty** [comment]
It's possible, I asked in the docker channel when build-args came about but didn't get an answer.

**Comment by jacobalberty** [comment]
Oh hey, There's an update to this. jacobalberty/unifi:beta is a valid tag on the hub. Just pass PKGURL as an environment variable now instead of dealing with buildargs.

**Comment by ddribin** [comment]
Oh, nice! I'll try that out for the next beta release and report back.

**Comment by ddribin** [comment]
Alright, just upgraded to a new beta, and that worked!

    sudo docker run -e PKGURL=https://... ... --name unifi-beta jacobalberty/unifi:beta

Since the URL is given at runtime, does it re-download and/or rebuild every time I run `docker run`, even if PKGURL is same as it was previously?

**Comment by jacobalberty** [comment]
Yes, every docker run would re download and reinstall, you can docker stop and docker start and it wont redownload though.

**Comment by ddribin** [comment]
Cool! This seems to be working great! And by making this an environment variable, I can setup the container using Synology's Docker GUI. Thanks much! I think we can close this as fixed, now?
